import { translatedMetadata } from '../../lib/localization/metadata';
import LocalizedContent from "../components/localization/server";
import Link from 'next/link';import {redirect,notFound} from 'next/navigation';
import {workspaceEnabled} from '../../lib/workspace-sandbox';import {workspaceUser} from '../../lib/workspace-server';import {hasCustomerSuccessCourse} from '../../lib/customer-success-course';
export async function generateMetadata() { return translatedMetadata({title:'Kit de empleabilidad',robots:{index:false,follow:false}}); }
const templates=[
 ['CV con evidencia','Perfil profesional: [puesto objetivo, experiencia relevante, herramientas].\nExperiencia: [problema] → [acción propia] → [resultado medido y periodo].\nProyecto: [contexto ficticio], [entregable], [cómo comprobaste el resultado].\nCompetencias: [habilidad] + [evidencia].\nFormación e idiomas: [nivel y respaldo].','Coordiné el onboarding de 12 cuentas en un trimestre; documenté bloqueos y acordé responsables. Si no tienes una métrica verificada, explica el alcance sin inventar porcentajes.'],
 ['Entrevista STAR','Situación: contexto y limitaciones.\nTarea: resultado esperado y tu responsabilidad.\nAcción: decisiones propias, alternativas y por qué.\nResultado: evidencia, límites y aprendizaje.\nSeguimiento: qué comprobarías hoy.','En un caso ficticio, un reporte tardaba 5 días. El objetivo era 2. Organicé validación de fuente, responsables y prueba de CSV. El caso terminó en 3 días: hubo mejora, pero la meta seguía pendiente. Distingue práctica de experiencia laboral real.'],
 ['Portafolio de un proyecto','Nombre y objetivo:\nDataset ficticio:\nProblema y supuestos:\nDecisión y alternativas:\nEntregables:\nPrueba exitosa, fallo y recuperación:\nResultado y límites:\nQué haría distinto:\nEnlace sin secretos:','Cuenta Faro: muestra el plan de éxito, la conciliación de reportes y un mensaje al sponsor. Incluye fórmulas reproducibles. No publiques datos, nombres ni documentación interna de empleadores.'],
 ['Seguimiento de candidaturas','Empresa | puesto | fecha | enlace | ajuste con evidencia | etapa | siguiente acción | fecha de seguimiento.\nRegistra la fuente de cada dato; no guardes credenciales ni información privada de entrevistadores.','Tras una entrevista, anota qué requisitos pudiste demostrar y cuáles quedaron sin evidencia. La evaluación sirve para preparar el siguiente paso, no para calcular una probabilidad garantizada de contratación.'],
 ['Presentación profesional','Soy [nombre], trabajo o me estoy formando en [área]. Me interesa resolver [problema]. En [ejemplo real o proyecto identificado como práctica] hice [acción] y comprobé [resultado]. Busco [tipo de oportunidad] donde pueda aportar [capacidad con evidencia].','Si comienzas desde cero, presenta un proyecto de aprendizaje como proyecto; no lo conviertas en un puesto que no desempeñaste.'],
] as const;
export default async function EmploymentKit(){if(!workspaceEnabled())notFound();const session=await workspaceUser();if(!session)redirect('/login');if(!hasCustomerSuccessCourse(session.profile))return <LocalizedContent><main className="wrap"><h1>Kit de empleabilidad</h1><p>Incluido en Pro y Enterprise. Plantillas, ejemplos y criterios para mostrar tus habilidades con honestidad.</p><Link href="/pricing" className="btn">Ver planes</Link></main></LocalizedContent>;
 return <LocalizedContent><main className="wrap"><span className="pill">INCLUIDO EN PRO Y ENTERPRISE</span><h1>Prepara tu siguiente oportunidad</h1><p>Copia las plantillas a tu editor y usa únicamente datos propios que puedas respaldar. Este recurso no envía candidaturas ni garantiza empleo.</p><section className="card"><h2>Guía de salida laboral</h2><p>1. Define tu puesto objetivo y dos capacidades que puedas demostrar con evidencia revisada. Consulta requisitos reales y separa lo que ya dominas de lo que debes practicar.</p><p>2. Elige una entrega revisada de Faro. Prepara problema, decisión, datos ficticios, pruebas y límites. Identifícala como proyecto formativo; solicita permiso antes de compartir trabajo real.</p><p>3. Ajusta CV y presentación al puesto sin inventar experiencia. Prepara dos respuestas STAR: un logro y una corrección. Practica explicar una decisión técnica a una persona no técnica.</p><p>4. Compara ofertas con fecha, ubicación, moneda, periodo, salario bruto o neto, modalidad, horario, prestaciones y responsabilidades. Si un dato falta, pregunta; no conviertas un promedio general en salario garantizado para tu puesto.</p><p>5. Lleva un registro de candidaturas y acuerda el siguiente paso. Revisa cada semana qué requisitos carecen de evidencia y asigna una práctica concreta. Mantén datos de contacto privados y respeta los canales de cada proceso.</p><p><Link href="/role-training/reinforcements">Atención, trabajo remoto e integraciones</Link></p><h3>Referencias para investigar puestos y remuneración</h3><p>Consulta la fecha y la población de cada estadística. Los promedios profesionales agregados no describen una oferta concreta de Customer Success ni tu experiencia.</p><ul><li><a href="https://www.observatoriolaboral.gob.mx/static/estudios-publicaciones/Tendencias_empleo.html" target="_blank" rel="noreferrer">Observatorio Laboral · México</a></li><li><a href="https://www.economia.gob.mx/datamexico/" target="_blank" rel="noreferrer">Data México</a></li></ul></section>{templates.map(([title,template,example])=><section className="card" key={title} style={{marginBottom:20}}><h2>{title}</h2><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{template}</pre><h3>Ejemplo y criterio</h3><p>{example}</p></section>)}<section className="card"><h2>Revisión antes de compartir</h2><ul><li>El puesto objetivo es claro y cada competencia tiene evidencia.</li><li>Las cifras son verificables; la práctica está identificada como práctica.</li><li>El documento no contiene secretos ni información personal de terceros.</li><li>Los enlaces funcionan y los archivos pueden leerse en móvil.</li><li>Has preparado un caso de éxito y uno que requirió corregir tu enfoque.</li></ul></section><Link href="/dashboard" className="btn secondary">Volver a Mi Garciloga</Link></main></LocalizedContent>;
}


