export type ScenarioText={title:string;context:string;choices:readonly string[]};
export const ADVANCED_KEYS=["intake","diagnosis","stakeholders","tradeoff","finance","crisis","evidence","renewal","transfer"] as const;
export const advancedWords={
es:{heading:"Decisiones profesionales · Faro",intro:"Ocho retos con restricciones reales, alternativas defendibles y consecuencias. Debes fundamentar con datos, reconocer costos y definir cómo verificar el resultado.",facts:"¿Qué hechos y supuestos sustentan esta decisión? ¿Qué información falta?",tradeoff:"¿Qué otra alternativa sería defendible, qué costo asumes y a quién afecta?",verification:"¿Qué indicador, responsable, fecha y evidencia demostrarían si funcionó?",choices:"¿Qué estrategia elegirías y por qué?",sceneConsequence:"Las condiciones resultantes del caso son:",critical:"errores críticos",next:"Confirmar decisión",move:"Continuar al siguiente reto",restart:"Reiniciar caso",stage:"Reto",of:"de",level:"Nivel de exigencia",metric:{trust:"Confianza",adoption:"Adopción",risk:"Riesgo",budget:"Presupuesto USD",days:"Días restantes"},result:"Resultado de decisiones",review:"Requiere revisión humana",submit:"Guardar entrega para revisión",notice:"La puntuación de opciones no califica el razonamiento escrito. Un manager o supervisor autorizado debe validar las competencias; no se otorgan certificados automáticamente.",privacy:"Caso sintético. No escribas datos de clientes reales.",back:"Volver a los cursos",saved:"Entrega registrada para revisión",error:"No fue posible guardar la entrega. Verifica el acceso a tu compañía e inténtalo de nuevo.",optional:"Prueba privada sin guardar evidencia",more:"Puedes seguir en el piloto sin guardar; tu progreso académico no se modifica.",focus:"Próximas competencias para reforzar",skills:{diagnosis:"Diagnóstico",data:"Datos y métricas",planning:"Planeación y riesgos"},
scenes:[
["Una cuenta a punto de irse","Faro tiene 42% de adopción frente a una meta de 75%, una renovación en 45 días, un proceso que tarda cinco días y USD 12,000 para recuperar valor. Ventas quiere una respuesta antes de conocer las causas.",["Invertir en un diagnóstico corto, contrastar métricas e identificar responsables.","Convocar al sponsor y a líderes internos para pactar medidas, aunque aún no haya diagnóstico completo.","Probar una mejora visible con un equipo y medir la adopción durante una semana.","Reservar todo el presupuesto hasta aclarar cada variable y detener cambios durante dos semanas."]],
["Información que se contradice","De 80 usuarios habilitados, 34 usaron el flujo, pero solo 19 validaron informes. Los tickets bajan y el trabajo manual sube. Compras cree que el acceso equivale a retorno financiero.",["Separar cohortes y auditar diez informes con datos anonimizados.","Entrevistar primero al operador, al sponsor y a soporte para identificar contradicciones.","Entregar un resumen con el indicador de tickets y advertir que requiere validación.","Ajustar permisos de los usuarios afectados e investigar los resultados en paralelo."]],
["Tres líderes, tres objetivos","El sponsor exige reducir el proceso de cinco a dos días, Finanzas solicita descuento y Seguridad impide compartir datos de clientes. Hay una reunión decisiva en 30 minutos.",["Definir criterios de aceptación, roles y restricciones que permitan medir valor.","Acordar con el sponsor una primera hipótesis y convocar después a los demás decisores.","Cerrar primero una negociación económica para obtener patrocinio del proyecto.","Dejar que cada equipo ejecute su solución y consolidar la información más adelante."]],
["Tecnología frente a operaciones","Automatizar costaría USD 4,800 y no tiene fecha confirmada. Un proceso manual validado cuesta USD 1,800 y depende de Operaciones. Un piloto limitado cuesta USD 800 y deja equipos sin solución.",["Aprobar un proceso manual acotado con controles, responsables y criterio de abandono.","Seleccionar el piloto barato, evaluar resultados y después ampliar a otros equipos.","Financiar la automatización sin fecha firme y preparar una contingencia incompleta.","Incluir la integración como compromiso contractual y confirmar la fecha más tarde."]],
["La negociación del ROI","Comercial quiere justificar un aumento de 20% por 34 accesos. El reporte tardó tres días en lugar de cinco, pero solo 19 entregas se validaron y no hay costos por hora comprobados.",["Presentar la mejora real, limitaciones y una hipótesis de ROI condicionada a datos faltantes.","Negociar una extensión provisional atada a adopción y calidad de reportes.","Ofrecer descuento general anual a cambio de renovar antes de revisar resultados.","Extrapolar ahorro económico de cada acceso y llamarlo retorno comprobado."]],
["Escalación bajo presión","El riesgo ha crecido. Compras exige una fecha que Ingeniería no confirma y Seguridad investiga un posible acceso inadecuado. No está claro si se trata de un incidente.",["Activar una mesa de recuperación, documentar compromisos y separar la investigación de seguridad.","Pausar temporalmente el flujo bajo sospecha mientras Seguridad investiga y se informa al sponsor.","Conceder una rebaja para ganar tiempo antes de revisar los controles de acceso.","Limitar el mensaje ejecutivo a lo positivo hasta saber si el incidente existió."]],
["Los datos parecían mejores","La confianza se recuperó, pero BI descubre eventos de acceso duplicados. Hay presión por presentar un resultado y el presupuesto para auditoría está limitado.",["Conciliar eventos, validar tareas terminadas y dejar trazabilidad de cada corrección.","Auditar una muestra representativa, explicar incertidumbre y ampliar después el control.","Utilizar agregados con advertencias metodológicas y auditar tras la renovación.","Excluir los datos problemáticos del informe sin explicar cómo se trataron."]],
["La renovación imperfecta","Aún existe una brecha entre uso y valor. Compras pide condiciones definitivas; el sponsor desea continuidad y Operaciones requiere formación.",["Negociar continuidad con resultados comprobables, responsables y fechas de seguimiento.","Proponer una renovación más corta con puntos de control mutuos.","Ofrecer una rebaja permanente y comprometerse a resolver la adopción después.","Presionar con cláusulas de salida para asegurar la firma esta semana."]],
["El último dato cambia todo","Justo antes de presentar a dirección se descubre que cuatro reportes válidos se contabilizaron dos veces. Debes responder con el contrato aún en juego.",["Corregir la base, informar el impacto y revisar los criterios de éxito.","Solicitar una auditoría adicional, declarar incertidumbre y aplazar la conclusión.","Corregir las cifras internamente y avisar al cliente después de la presentación.","Omitir los registros duplicados del anexo y conservar la conclusión optimista."]]
] as const},
en:{heading:"Professional decisions · Faro",intro:"Eight challenges with real constraints, defensible alternatives and consequences. Use evidence, weigh trade-offs and define how you would verify success.",facts:"What facts and assumptions support your choice? What is unknown?",tradeoff:"What other option is reasonable, what cost are you accepting and whom does it affect?",verification:"Which metric, owner, date and evidence would verify the outcome?",choices:"Which strategy would you choose and why?",sceneConsequence:"The new case circumstances are:",critical:"critical errors",next:"Confirm decision",move:"Continue to next challenge",restart:"Restart case",stage:"Challenge",of:"of",level:"Difficulty level",metric:{trust:"Trust",adoption:"Adoption",risk:"Risk",budget:"Budget USD",days:"Days left"},result:"Decision result",review:"Human review required",submit:"Submit evidence for review",notice:"The option score does not grade your written reasoning. An authorized manager or supervisor must validate competencies; no certificates are awarded automatically.",privacy:"Synthetic case. Do not include real customer data.",back:"Back to courses",saved:"Submission saved for review",error:"Could not save submission. Verify organization access and try again.",optional:"Private practice without saving",more:"You can practice without saving; your academic progress remains unchanged.",focus:"Competencies to strengthen next",skills:{diagnosis:"Diagnosis",data:"Data and metrics",planning:"Planning and risk"},
scenes:[
["A customer about to leave","Faro has 42% adoption against a 75% target, renewal in 45 days, reporting takes five days and there is USD 12,000 to recover value. Sales demands answers before the cause is known.",["Fund a quick diagnosis and compare evidence from several owners.","Convene stakeholders now to agree action without a full diagnosis.","Trial a visible fix with one team and track adoption for a week.","Reserve all funding while investigating everything for two weeks."]],
["Conflicting signals","Of 80 enabled users, 34 ran the workflow, but only 19 validated reports. Tickets declined while manual effort rose. Procurement mistakes access for financial return.",["Segment cohorts and audit ten anonymized reports.","Interview operators, sponsor and Support to challenge assumptions first.","Use fewer tickets in an early report but flag uncertainty.","Change affected user permissions while measuring what happens."]],
["Three leaders and three goals","The sponsor wants two-day reporting, Finance wants a discount, and Security forbids customer data sharing. A decision meeting starts in 30 minutes.",["Define success criteria, owners and boundaries before agreeing scope.","Prioritize a hypothesis with the sponsor and bring other stakeholders later.","Negotiate commercial terms first to secure project support.","Allow each department to move separately and combine results later."]],
["Automation versus operations","Automation costs USD 4,800 with an unconfirmed date. A validated manual process costs USD 1,800 but burdens Operations. A small pilot costs USD 800.",["Choose a bounded manual process with controls and stopping rules.","Choose the cheap pilot and scale only after evidence supports it.","Build automation despite uncertainty, with incomplete contingency.","Commit the integration in the contract before confirming delivery."]],
["The ROI conversation","Sales wants a 20% increase based on 34 logins. Reporting dropped from five to three days, but only 19 reports passed verification and hourly costs are unknown.",["Explain measured value, limitations and an ROI hypothesis awaiting evidence.","Offer conditional commercial terms tied to verified outcomes.","Grant an annual blanket discount and address adoption later.","Extrapolate savings from logins and claim they are verified ROI."]],
["Escalation under pressure","Risk is elevated. Procurement wants an unconfirmed delivery date while Security investigates a possible access issue. It is unclear whether a breach occurred.",["Start a recovery group and separate security investigation from delivery promises.","Pause the potentially affected workflow and inform the sponsor.","Offer a discount to buy time before examining access controls.","Only report positive progress to executives until the facts are settled."]],
["The figures were optimistic","BI finds duplicate access events. Trust is improving, but the budget for a full audit is constrained and leaders expect a clear answer.",["Reconcile events and verify completed work against agreed criteria.","Audit a representative sample, disclose uncertainty and plan further checks.","Use aggregate totals with methodology caveats and audit later.","Remove dubious events without disclosing the filtering method."]],
["An imperfect renewal","There is still a gap between logins and value. Procurement demands firm terms, the sponsor wants continuity, and Operations needs training.",["Negotiate continuity with verifiable milestones and responsible owners.","Offer a shorter renewal with shared checkpoints.","Grant a permanent discount and tackle adoption after renewal.","Pressure Procurement using exit clauses to close this week."]],
["The final data surprise","Four validated reports were counted twice. A board presentation starts tomorrow and the contract remains at stake.",["Correct the baseline, disclose impact and revisit acceptance criteria.","Request another audit, disclose uncertainty and delay the conclusion.","Correct the internal numbers and inform the customer after the meeting.","Hide duplicates from the appendix to keep the positive narrative."]]
] as const},
pt:{heading:"Decisões profissionais · Faro",intro:"Oito desafios com restrições reais, alternativas justificáveis e consequências. Use evidências, avalie concessões e planeje a verificação.",facts:"Quais fatos e hipóteses sustentam a decisão? O que falta?",tradeoff:"Que alternativa seria viável, que custo assume e quem é afetado?",verification:"Qual indicador, responsável, data e evidência comprovariam o resultado?",choices:"Qual estratégia escolheria e por quê?",sceneConsequence:"As condições atuais do caso são:",critical:"erros críticos",next:"Confirmar decisão",move:"Continuar para o próximo desafio",restart:"Reiniciar caso",stage:"Desafio",of:"de",level:"Nível de dificuldade",metric:{trust:"Confiança",adoption:"Adoção",risk:"Risco",budget:"Orçamento USD",days:"Dias restantes"},result:"Resultado das decisões",review:"Revisão humana necessária",submit:"Enviar evidências para revisão",notice:"A nota das opções não avalia os textos. Um gerente ou supervisor autorizado deve validar competências; nenhum certificado é emitido automaticamente.",privacy:"Caso fictício. Não inclua dados reais de clientes.",back:"Voltar aos cursos",saved:"Entrega salva para revisão",error:"Não foi possível salvar a entrega. Verifique o acesso à organização.",optional:"Prática privada sem registro",more:"Você pode praticar sem salvar; o progresso acadêmico não muda.",focus:"Competências a reforçar",skills:{diagnosis:"Diagnóstico",data:"Dados e métricas",planning:"Planejamento e riscos"},
scenes:[
["Cliente em risco","Faro tem adoção de 42% contra meta de 75%; renovação em 45 dias; relatórios em cinco dias e USD 12.000 para recuperar valor. Comercial exige decisão.",["Investir em diagnóstico rápido e comparar evidências.","Reunir decisores sem diagnóstico completo para agir logo.","Testar melhoria em uma equipe e medir por uma semana.","Guardar todo o orçamento até investigar tudo."]],
["Indicadores em conflito","De 80 usuários habilitados, 34 executaram o fluxo e somente 19 validaram relatórios. Tickets caem, mas esforço manual aumenta.",["Separar grupos e auditar dez relatórios anônimos.","Entrevistar operação, patrocinador e Suporte antes de agir.","Usar a queda de tickets como indicador inicial com ressalvas.","Alterar permissões dos afetados e medir resultados."]],
["Três líderes, três objetivos","Patrocinador pede dois dias, Finanças quer desconto e Segurança impede compartilhar dados de clientes. Há reunião em 30 minutos.",["Definir critérios de sucesso, responsáveis e limites.","Acordar hipótese com patrocinador e envolver outros depois.","Negociar condições comerciais antes de definir o piloto.","Deixar departamentos agir isoladamente e consolidar depois."]],
["Automação ou operação manual","Automação custa USD 4.800, sem prazo. Processo manual validado custa USD 1.800 e pesa em Operações; piloto custa USD 800.",["Processo manual limitado com controles e prazo para abandonar.","Piloto barato, ampliando somente após evidências.","Criar automação com prazo incerto e contingência parcial.","Prometer integração em contrato antes de confirmar entrega."]],
["A armadilha do ROI","Comercial propõe aumento de 20% com base em 34 acessos. Relatórios caíram de cinco para três dias, mas só 19 foram validados.",["Apresentar valor mensurado e hipótese de ROI condicionada a dados.","Oferecer condições temporárias vinculadas a resultados comprovados.","Dar desconto anual e deixar adoção para depois.","Calcular ROI a partir de acessos e chamá-lo comprovado."]],
["Escalada sob pressão","Compras exige data que Engenharia não confirma. Segurança investiga possível acesso inadequado; o cliente pode escalar.",["Criar equipe de recuperação e separar investigação de promessas.","Pausar fluxo suspeito enquanto Segurança investiga e informar cliente.","Dar desconto para ganhar tempo e investigar depois.","Divulgar apenas boas notícias até confirmar os fatos."]],
["Dados melhores do que pareciam","BI encontra acessos duplicados. Há pressão por um resultado e orçamento limitado para auditar tudo.",["Conciliar duplicados e verificar tarefas concluídas.","Auditar amostra representativa e explicar a incerteza.","Usar números agregados com ressalvas e auditar depois.","Excluir dados problemáticos sem explicar o critério."]],
["Renovação imperfeita","O sponsor quer continuidade, Compras exige termos e Operação precisa treinamento; ainda faltam provas de valor.",["Renovar com metas verificáveis, responsáveis e datas.","Propor renovação curta com pontos de controle.","Conceder desconto permanente e resolver adoção depois.","Pressionar com cláusulas de saída para fechar agora."]],
["Nova informação inesperada","Quatro relatórios válidos foram registrados duas vezes antes da apresentação à direção amanhã.",["Corrigir base, comunicar impacto e atualizar critérios.","Pedir auditoria e comunicar incerteza, adiando conclusão.","Corrigir internamente e avisar cliente depois da reunião.","Ocultar duplicados do anexo para manter relato favorável."]]
] as const},
fr:{heading:"Décisions professionnelles · Faro",intro:"Huit défis avec contraintes réelles, alternatives défendables et conséquences. Justifiez preuves, compromis et vérification.",facts:"Quels faits et hypothèses justifient ce choix ? Que manque-t-il ?",tradeoff:"Quelle autre option reste défendable ? Quel coût et pour qui ?",verification:"Quel indicateur, responsable, échéance et preuve valideraient le résultat ?",choices:"Quelle stratégie choisiriez-vous et pourquoi ?",sceneConsequence:"Les nouvelles conditions du dossier sont :",critical:"erreurs critiques",next:"Valider la décision",move:"Passer au défi suivant",restart:"Recommencer",stage:"Défi",of:"sur",level:"Niveau de difficulté",metric:{trust:"Confiance",adoption:"Adoption",risk:"Risque",budget:"Budget USD",days:"Jours restants"},result:"Résultat des décisions",review:"Évaluation humaine nécessaire",submit:"Soumettre les preuves à évaluer",notice:"Le score des choix ne note pas les justifications. Un responsable autorisé doit valider les compétences; aucun certificat automatique.",privacy:"Cas fictif. Ne saisissez aucune donnée réelle de client.",back:"Retour aux cours",saved:"Travail enregistré pour examen",error:"Impossible d'enregistrer. Vérifiez l'accès à votre organisation.",optional:"Entraînement privé sans sauvegarde",more:"Vous pouvez pratiquer sans enregistrer; la progression académique reste inchangée.",focus:"Compétences à approfondir",skills:{diagnosis:"Diagnostic",data:"Données et indicateurs",planning:"Planification et risques"},
scenes:[
["Compte menacé","Faro atteint 42% d'adoption contre 75% visés, renouvellement sous 45 jours, rapports en cinq jours et budget de 12 000 USD.",["Financer un diagnostic court et recouper plusieurs sources.","Convoquer les décideurs sans diagnostic complet pour agir vite.","Tester une amélioration dans une équipe pendant une semaine.","Préserver tout le budget en suspendant les changements deux semaines."]],
["Indices contradictoires","Sur 80 utilisateurs, 34 ont utilisé le flux, mais 19 rapports seulement sont validés. Les tickets baissent alors que l'effort manuel augmente.",["Séparer les groupes et auditer dix rapports anonymisés.","Interroger les parties prenantes et comparer leurs hypothèses.","Utiliser les tickets comme signal initial avec réserves.","Modifier les autorisations et mesurer l'effet en parallèle."]],
["Trois décideurs, trois objectifs","Le sponsor exige deux jours, Finance une remise, et Sécurité interdit le partage de données. Réunion dans 30 minutes.",["Définir critères d'acceptation, responsables et limites.","Convenir d'une hypothèse avec le sponsor avant les autres.","Négocier les termes financiers avant de choisir le pilote.","Laisser chaque service agir séparément, puis agréger."]],
["Automatisation ou solution manuelle","L'automatisation coûterait 4 800 USD sans date confirmée. Procédure manuelle validée : 1 800 USD. Petit pilote : 800 USD.",["Choisir la procédure manuelle limitée, avec contrôles et arrêt.","Faire un pilote modeste avant de déployer davantage.","Construire malgré le délai incertain et la couverture incomplète.","Promettre contractuellement l'intégration sans date confirmée."]],
["Dilemme sur le retour financier","Commercial veut majorer le tarif de 20% pour 34 connexions. Le rapport passe de cinq à trois jours, mais 19 sont validés.",["Présenter l'amélioration mesurée et une hypothèse de ROI à vérifier.","Proposer des conditions provisoires liées à la valeur prouvée.","Accorder une remise annuelle et repousser l'adoption.","Extrapoler la rentabilité des connexions en la déclarant prouvée."]],
["Escalade de crise","Achats demande une date non confirmée; Sécurité enquête sur un accès possiblement abusif. La confiance diminue.",["Activer une cellule de reprise séparant sécurité et engagements.","Suspendre le flux suspect et communiquer avec le sponsor.","Accorder une remise avant d'enquêter sur les droits d'accès.","Ne communiquer que les progrès jusqu'à la confirmation."]],
["Les données trompent","BI découvre des connexions comptées deux fois. Les ressources pour auditer sont rares, la direction attend des résultats.",["Réconcilier les doublons et valider les tâches achevées.","Auditer un échantillon représentatif et déclarer l'incertitude.","Utiliser les agrégats avec réserve et auditer plus tard.","Écarter les entrées ambiguës sans expliquer la méthode."]],
["Renouvellement imparfait","Le sponsor veut continuer, Achats exige des clauses fermes, Opérations demande une formation. La valeur n'est pas entièrement prouvée.",["Négocier des résultats vérifiables avec responsables et dates.","Proposer une reconduction courte avec points de contrôle.","Accorder une remise durable et corriger l'adoption ensuite.","Utiliser les clauses de résiliation pour forcer la signature."]],
["Révélation finale","Quatre rapports ont été comptés deux fois; présentation au comité demain, contrat toujours en jeu.",["Corriger les chiffres, avertir le sponsor et réviser les critères.","Demander un audit et signaler l'incertitude en différant le constat.","Corriger en interne et avertir le client après la réunion.","Masquer les doublons dans l'annexe pour préserver le récit favorable."]]
] as const}};
export function advancedCopyFor(locale:string){
 const lang=Object.hasOwn(advancedWords,locale)?locale:"es";
 return advancedWords[lang as keyof typeof advancedWords] as typeof advancedWords["es"];
}
export function advancedScenarioText(locale:string,key:string):ScenarioText{
 const index=ADVANCED_KEYS.indexOf(key as typeof ADVANCED_KEYS[number]);
 if(index<0)throw Error("UNKNOWN_SCENE");
 const row=advancedCopyFor(locale).scenes[index];
 return {title:row[0],context:row[1],choices:row[2]};
}
