export const ownerDemoStrings = {
 es:{
  title:"Laboratorio del propietario",subtitle:"Reiniciar mi aprendizaje y preparar una demostración comercial",
  private:"Estas herramientas son exclusivas del propietario. No cambian planes, pagos, compañías, invitados ni datos de clientes.",
  resetTitle:"Reiniciar mi progreso personal desde cero",resetIntro:"Borra tus intentos, avances y entregas personales para repetir los cursos desde el inicio, tantas veces como necesites. No elimina tu cuenta, rol de propietario, contratos, uso de planes, certificados ya emitidos ni evidencias de compañías.",
  resetWarning:"Acción irreversible para tu progreso académico personal. Las certificaciones emitidas permanecen como historial y no se modifican los datos de alumnos o empresas. Sin cargo para el propietario.",
  email:"Escribe el correo de tu cuenta para confirmar",phrase:"Escribe exactamente REINICIAR MI PROGRESO",confirm:"Acepto reiniciar solo mi progreso académico personal, no mi cuenta ni mis clientes.",
  resetButton:"Confirmar reinicio de aprendizaje",resetBusy:"Reiniciando...",resetDone:"Tu progreso académico personal se reinició. Puedes empezar los cursos otra vez.",
  resetError:"No se pudo reiniciar. Comprueba el correo y la frase. No repitas si hubo un error de conexión sin actualizar antes.",
  demoTitle:"Demostración comercial al 100%",demoIntro:"Genera una empresa ficticia con ocho colaboradores, dos equipos, quince niveles completos, competencias 4/4 y reportes listos para mostrar al cliente.",
  generate:"Generar datos simulados al 100%",regenerate:"Regenerar demostración",resetDemo:"Reiniciar simulación al 0%",
  fictitious:"DEMOSTRACIÓN · 100% SIMULADA · NO SON CLIENTES REALES",empty:"Sin datos de demostración generados. Pulsa el botón para crear la vista comercial al 100%.",
  noStorage:"Los datos son temporales y se generan en tu navegador. No se guardan en Supabase, no modifican usuarios reales y no aparecen en la analítica ni en los reportes auténticos.",
  employees:"Colaboradores ficticios",complete:"Niveles aprobados (simulados)",competencies:"Competencias demostradas (simuladas)",teams:"Equipos ficticios",
  viewMap:"Mapa de competencias",viewOrg:"Organigrama",viewCourses:"Cursos y niveles",manager:"Vista de manager / supervisor",
  coursesIntro:"Se simula que los ocho colaboradores completaron los 15 niveles con proyectos y evaluaciones. No se otorgaron certificados reales.",
  orgHead:"Organigrama de ejemplo",teamOne:"Customer Success",teamTwo:"Soporte",captions:"Muestra ficticia para ventas; los niveles 4/4 reflejan resultados inventados, no evidencias verificadas.",
  back:"Volver a Administración",notice:"El reinicio de tu aprendizaje real y la demostración ficticia son acciones independientes."
 },
 en:{
  title:"Owner lab",subtitle:"Reset my learning and prepare a sales demonstration",
  private:"Owner-only tools. Do not change plans, payments, organizations, invitations or customer data.",
  resetTitle:"Reset my personal learning progress",resetIntro:"Clear your own attempts, learning progress and personal submissions, as often as needed. Your account, owner role, contracts, usage limits, issued certificates and company evidence stay untouched.",
  resetWarning:"Irreversible for personal learning progress. Issued certificates remain as history and customer data is not touched. No owner fee.",
  email:"Enter your account email to confirm",phrase:"Type exactly REINICIAR MI PROGRESO",confirm:"I consent to resetting only my own learning progress, not my account or customer data.",
  resetButton:"Confirm learning reset",resetBusy:"Resetting...",resetDone:"Your personal learning progress has been reset; you may take courses again.",
  resetError:"Reset failed. Verify email and phrase. If there was a connection failure, refresh before trying again.",
  demoTitle:"100% complete sales demonstration",demoIntro:"Generate a fictional company with eight employees, two teams, all 15 levels complete, 4/4 competencies and ready-to-share dashboards.",
  generate:"Generate 100% simulated data",regenerate:"Regenerate demonstration",resetDemo:"Reset demo to 0%",
  fictitious:"DEMONSTRATION · 100% SIMULATED · NO REAL CUSTOMERS",empty:"No simulated data yet. Press Generate to create the fully completed sales demo.",
  noStorage:"All data is temporary and generated in your browser. Nothing is saved to Supabase or real users, analytics, or customer dashboards.",
  employees:"Fictional employees",complete:"Levels passed (simulated)",competencies:"Demonstrated skills (simulated)",teams:"Fictional teams",
  viewMap:"Competency map",viewOrg:"Org chart",viewCourses:"Courses and levels",manager:"Manager / supervisor view",
  coursesIntro:"All eight fictional employees show 15 completed levels, projects and assessments. No real certificates were issued.",
  orgHead:"Sample organization",teamOne:"Customer Success",teamTwo:"Support",captions:"Synthetic sales presentation; scores of 4/4 are invented, not verified achievement.",
  back:"Back to administration",notice:"Resetting your real learning and generating fictional demonstrations are independent actions."
 },
 pt:{
  title:"Laboratório do proprietário",subtitle:"Reiniciar o aprendizado e preparar uma demonstração comercial",
  private:"Ferramentas exclusivas do proprietário, sem alterar planos, cobranças, empresas ou clientes.",
  resetTitle:"Reiniciar meu progresso pessoal",resetIntro:"Apaga suas tentativas e entregas pessoais quantas vezes desejar. Conta, função, contratos, limites, certificados emitidos e evidências de empresas permanecem.",
  resetWarning:"Ação irreversível para o aprendizado pessoal. Certificados e dados de empresas não são alterados. Sem cobrança.",
  email:"Digite o e-mail da conta para confirmar",phrase:"Digite exatamente REINICIAR MI PROGRESO",confirm:"Confirmo a reinicialização apenas do meu aprendizado pessoal.",
  resetButton:"Confirmar reinicialização",resetBusy:"Reiniciando...",resetDone:"Seu progresso pessoal foi reiniciado.",resetError:"Não foi possível reiniciar. Verifique e-mail e frase; atualize a página após erros de conexão.",
  demoTitle:"Demonstração comercial 100%",demoIntro:"Gere empresa fictícia com oito colaboradores, duas equipes, 15 níveis concluídos, competências 4/4 e painéis completos.",
  generate:"Gerar dados 100% simulados",regenerate:"Gerar novamente",resetDemo:"Reiniciar demonstração em 0%",fictitious:"DEMONSTRAÇÃO · 100% SIMULADA · NÃO SÃO CLIENTES REAIS",
  empty:"Sem dados fictícios. Clique para gerar a demonstração completa.",noStorage:"Os dados são temporários e existem apenas no navegador. Nada é gravado no Supabase ou nas contas reais.",
  employees:"Colaboradores fictícios",complete:"Níveis concluídos (simulados)",competencies:"Competências simuladas",teams:"Equipes fictícias",
  viewMap:"Mapa de competências",viewOrg:"Organograma",viewCourses:"Cursos e níveis",manager:"Visão de gerente / supervisor",
  coursesIntro:"Oito colaboradores fictícios concluíram 15 níveis, projetos e avaliações. Sem emissão de certificados reais.",
  orgHead:"Organização fictícia",teamOne:"Customer Success",teamTwo:"Suporte",captions:"Exemplo comercial fictício; notas 4/4 não representam competências comprovadas.",
  back:"Voltar à administração",notice:"Reinicialização pessoal e demonstração fictícia são ações independentes."
 },
 fr:{
  title:"Atelier du propriétaire",subtitle:"Réinitialiser mon apprentissage et préparer une démonstration commerciale",
  private:"Outils réservés au propriétaire. Aucun changement de forfait, paiement, entreprise ou client.",
  resetTitle:"Réinitialiser ma progression personnelle",resetIntro:"Efface vos tentatives, progrès et remises personnels autant de fois que nécessaire. Compte, rôle, contrats, limites, certificats et données d'entreprises sont préservés.",
  resetWarning:"Action irréversible pour l'apprentissage personnel. Certificats et données des clients restent inchangés. Aucun frais.",
  email:"Saisissez votre e-mail pour confirmer",phrase:"Saisissez exactement REINICIAR MI PROGRESO",confirm:"Je confirme la réinitialisation de mon seul apprentissage personnel.",
  resetButton:"Confirmer la réinitialisation",resetBusy:"Réinitialisation...",resetDone:"Votre progression personnelle a été réinitialisée.",resetError:"Échec. Vérifiez l'e-mail et la phrase; actualisez après une erreur de connexion.",
  demoTitle:"Démonstration commerciale à 100%",demoIntro:"Créez une entreprise fictive avec huit salariés, deux équipes, 15 niveaux achevés, compétences à 4/4 et tableaux de bord.",
  generate:"Générer des données simulées à 100%",regenerate:"Régénérer",resetDemo:"Remettre la démo à 0%",fictitious:"DÉMONSTRATION · 100% SIMULÉE · AUCUN CLIENT RÉEL",
  empty:"Aucune donnée simulée. Cliquez pour préparer la démonstration complète.",noStorage:"Les données ne vivent que dans votre navigateur. Rien n'est enregistré dans Supabase ou les comptes réels.",
  employees:"Salariés fictifs",complete:"Niveaux réussis (simulés)",competencies:"Compétences simulées",teams:"Équipes fictives",
  viewMap:"Carte des compétences",viewOrg:"Organigramme",viewCourses:"Cours et niveaux",manager:"Vue manager / superviseur",
  coursesIntro:"Huit salariés fictifs ont achevé les 15 niveaux, projets et évaluations. Aucun certificat réel n'a été émis.",
  orgHead:"Organisation fictive",teamOne:"Customer Success",teamTwo:"Support",captions:"Exemple commercial fictif : scores 4/4 inventés, sans preuve validée.",
  back:"Retour à l'administration",notice:"La réinitialisation personnelle et la démo fictive sont deux actions indépendantes."
 }
} as const;
export const ownerDemoCopy=(locale:string)=>ownerDemoStrings[(Object.hasOwn(ownerDemoStrings,locale)?locale:"es") as keyof typeof ownerDemoStrings] as typeof ownerDemoStrings.es;
