// Owner-only course inspector. Kept separate from the learner's localization catalog,
// because its answer keys and editorial labels must never be shipped to public clients.
export const ownerInspectorCopy = {
  es: {
    owner:"SOLO PROPIETARIO · VISTA DE INSPECCIÓN",title:"Revisión de los cursos",
    intro:"Acceso de lectura a los 15 niveles, lecciones, exámenes, rúbricas y respuestas. No altera el progreso de ningún alumno ni consume intentos.",
    back:"Volver a administración",programs:"Programas",choose:"Elige un programa",
    technical:"Programación e integraciones",editorialApproved:"REVISADO",editorialPending:"REVISIÓN EDITORIAL PENDIENTE",
    levels15:"· 15 niveles",level:"Nivel",elements:"elementos: lecciones, evaluación y proyectos. No se exige haber aprobado niveles previos en esta vista.",
    lesson:"Lección",exam:"Examen",project:"Proyecto",levelTag:"· NIVEL",key:"Clave interna:",
    context:"Objetivo, contexto y contenido",work:"Trabajo solicitado",rubric:"Rúbrica:",evidence:"Evidencia solicitada:",
    template:"Plantilla del alumno",example:"Ejemplo de solución",projectCriteria:"Criterios del proyecto",
    decisions:"Decisiones y clave de revisión (solo propietario)",expected:"· Respuesta esperada",
    competencies:"Competencias trabajadas",readOnly:"Inspección segura: no hay formularios de envío ni cambios en aprobaciones, cuotas, certificados o historial.",
    techIntro:"Contenido completo de los niveles, incluidas lecciones no desbloqueadas; consulta sin escrituras.",
    backPrograms:"Ver nueve programas por puesto",chooseLevel:"Selecciona un nivel",editorialState:"Estado editorial:",
    examPrefix:"Examen:",passScore:"Puntuación mínima:",answerKey:"Clave de revisión:",notRegistered:"No registrada",
    projectPrefix:"Proyecto:",technicalFoot:"Esta vista no crea intentos de examen ni aprueba proyectos. Solo la cuenta propietaria activa puede utilizarla.",
    adminLink:"Inspeccionar todos los cursos",exercise:"Ejercicios",
  },
  en: {
    owner:"OWNER ONLY · CURRICULUM INSPECTOR",title:"Review courses",
    intro:"Read-only access to all 15 levels, lessons, exams, rubrics and answers. Does not change any learner progress or consume attempts.",
    back:"Back to administration",programs:"Programs",choose:"Choose a program",
    technical:"Programming and integrations",editorialApproved:"REVIEWED",editorialPending:"EDITORIAL REVIEW PENDING",
    levels15:"· 15 levels",level:"Level",elements:"items: lessons, assessments and projects. Previous levels do not need to be passed in this view.",
    lesson:"Lesson",exam:"Exam",project:"Project",levelTag:"· LEVEL",key:"Internal key:",
    context:"Objective, context and content",work:"Required work",rubric:"Rubric:",evidence:"Required evidence:",
    template:"Learner template",example:"Example solution",projectCriteria:"Project criteria",
    decisions:"Decisions and review key (owner only)",expected:"· Expected answer",
    competencies:"Competencies covered",readOnly:"Safe inspection: no submission forms and no changes to approvals, quotas, certificates or history.",
    techIntro:"Full level content, including lessons not yet unlocked; read-only inspection.",
    backPrograms:"View nine role-based programs",chooseLevel:"Choose a level",editorialState:"Editorial status:",
    examPrefix:"Exam:",passScore:"Passing score:",answerKey:"Review key:",notRegistered:"Not recorded",
    projectPrefix:"Project:",technicalFoot:"This view does not create exam attempts or approve projects. Only the active account owner can use it.",
    adminLink:"Inspect all courses",exercise:"Exercises",
  },
  pt: {
    owner:"SOMENTE PROPRIETÁRIO · INSPEÇÃO DE CURSOS",title:"Revisão dos cursos",
    intro:"Acesso somente de leitura aos 15 níveis, aulas, exames, rubricas e respostas. Não altera o progresso dos alunos nem consome tentativas.",
    back:"Voltar à administração",programs:"Programas",choose:"Escolha um programa",
    technical:"Programação e integrações",editorialApproved:"REVISADO",editorialPending:"REVISÃO EDITORIAL PENDENTE",
    levels15:"· 15 níveis",level:"Nível",elements:"itens: aulas, avaliações e projetos. Não é necessário concluir os níveis anteriores nesta visualização.",
    lesson:"Aula",exam:"Exame",project:"Projeto",levelTag:"· NÍVEL",key:"Chave interna:",
    context:"Objetivo, contexto e conteúdo",work:"Trabalho solicitado",rubric:"Rubrica:",evidence:"Evidência solicitada:",
    template:"Modelo do aluno",example:"Exemplo de solução",projectCriteria:"Critérios do projeto",
    decisions:"Decisões e gabarito de revisão (somente proprietário)",expected:"· Resposta esperada",
    competencies:"Competências abordadas",readOnly:"Inspeção segura: sem formulários de envio nem alterações de aprovações, cotas, certificados ou histórico.",
    techIntro:"Conteúdo completo dos níveis, incluindo aulas ainda bloqueadas; consulta somente de leitura.",
    backPrograms:"Ver nove programas por função",chooseLevel:"Escolha um nível",editorialState:"Estado editorial:",
    examPrefix:"Exame:",passScore:"Nota mínima:",answerKey:"Gabarito:",notRegistered:"Não registrado",
    projectPrefix:"Projeto:",technicalFoot:"Esta visualização não cria tentativas de exames nem aprova projetos. Somente o proprietário ativo pode usá-la.",
    adminLink:"Inspecionar todos os cursos",exercise:"Exercícios",
  },
  fr: {
    owner:"PROPRIÉTAIRE UNIQUEMENT · INSPECTION DES COURS",title:"Examiner les cours",
    intro:"Accès en lecture seule aux 15 niveaux, leçons, examens, grilles d’évaluation et réponses. Aucun changement de progression ni tentative consommée.",
    back:"Retour à l’administration",programs:"Programmes",choose:"Choisir un programme",
    technical:"Programmation et intégrations",editorialApproved:"RÉVISÉ",editorialPending:"RÉVISION ÉDITORIALE EN ATTENTE",
    levels15:"· 15 niveaux",level:"Niveau",elements:"éléments : leçons, évaluations et projets. Il n’est pas nécessaire d’avoir validé les niveaux précédents ici.",
    lesson:"Leçon",exam:"Examen",project:"Projet",levelTag:"· NIVEAU",key:"Identifiant interne :",
    context:"Objectif, contexte et contenu",work:"Travail demandé",rubric:"Grille :",evidence:"Preuve demandée :",
    template:"Modèle de réponse",example:"Exemple de solution",projectCriteria:"Critères du projet",
    decisions:"Décisions et corrigé (propriétaire uniquement)",expected:"· Réponse attendue",
    competencies:"Compétences travaillées",readOnly:"Inspection sécurisée : aucun formulaire ni modification des validations, quotas, certificats ou de l’historique.",
    techIntro:"Contenu complet des niveaux, y compris les leçons verrouillées ; consultation en lecture seule.",
    backPrograms:"Voir les neuf programmes métiers",chooseLevel:"Choisir un niveau",editorialState:"État éditorial :",
    examPrefix:"Examen :",passScore:"Note minimale :",answerKey:"Corrigé :",notRegistered:"Non enregistré",
    projectPrefix:"Projet :",technicalFoot:"Cette vue ne crée aucune tentative d’examen et n’approuve aucun projet. Seul le propriétaire actif peut l’utiliser.",
    adminLink:"Inspecter tous les cours",exercise:"Exercices",
  },
} as const;

export function ownerCopy(locale: string) {
  return ownerInspectorCopy[(locale in ownerInspectorCopy ? locale : "es") as keyof typeof ownerInspectorCopy];
}
