import {translatedMetadata} from '../../lib/localization/metadata';
import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import LocalizedContent from '../components/localization/server';
import CommunityPostCard from '../components/community-post';
import {isUuid} from '../../lib/workspace-sandbox';
import {socialSession,workflowMessage,type CommunityPost} from '../../lib/social-server';
export async function generateMetadata(){return translatedMetadata({title:'Comunidad',robots:{index:false,follow:false}});}
export default async function Community({searchParams}:{searchParams:Promise<{result?:string;before?:string;cursor?:string}>}){
 const s=await socialSession();const query=await searchParams;const {data:member,error}=await s.admin.from('community_members').select('alias,blocked').eq('user_id',s.user.id).maybeSingle();
 const before=query.before&&Number.isFinite(Date.parse(query.before))?new Date(query.before).toISOString():null;
 const feed=member&&!member.blocked||s.moderator?await s.admin.rpc('community_feed',{p_actor:s.user.id,p_before:before,p_cursor:isUuid(query.cursor)?query.cursor:null}):null;
 const posts=(feed?.data??[]) as CommunityPost[];const message=workflowMessage(query.result);
 return <LocalizedContent><main className="wrap"><h1>Comunidad de alumnos</h1><p>Comparte dudas, avances y experiencias de aprendizaje.</p>{message&&<p role="status">{message}</p>}
 <section className="card"><h2>Reglas de participación</h2><p>Usa un alias. Tu correo, perfil y compañía no se comparten automáticamente. Este espacio reúne alumnos de distintas compañías; publica solo información que puedas compartir.</p><p>Respeta a las personas. No publiques contraseñas, datos de clientes, información confidencial, publicidad ni contenido ofensivo. Las publicaciones se revisan antes de ser visibles.</p><p>Puedes reportar contenido o retirar tus publicaciones. Al salir se retiran tu alias y tus publicaciones, incluidas las respuestas asociadas a tus conversaciones.</p></section>
 {error?<p role="alert">No pudimos cargar la comunidad. Intenta nuevamente.</p>:member?.blocked?<section className="card"><p role="alert">Tu participación está suspendida. Contacta a soporte.</p><form method="post" action="/api/community"><input type="hidden" name="action" value="leave"/><button className="btn secondary">Retirar mi participación</button></form></section>:!member&&s.profile.role!=='owner'?<form className="card" method="post" action="/api/community"><h2>Participar en la comunidad</h2><input type="hidden" name="action" value="join"/><label>Alias de comunidad<input name="alias" minLength={3} maxLength={40} required autoComplete="off"/></label><label><input type="checkbox" name="consent" value="1" required/>Acepto las reglas y compartir mi alias y publicaciones con la comunidad.</label><button className="btn">Unirme</button></form>:null}
 {member&&!member.blocked&&<section className="card"><p>Tu alias: <span translate="no">{member.alias}</span></p><form method="post" action="/api/community"><h2>Nueva conversación</h2><input type="hidden" name="action" value="post"/><input type="hidden" name="request_id" value={randomUUID()}/><label>Categoría<select name="category"><option value="help">Dudas</option><option value="progress">Avances</option><option value="discussion">Experiencias</option></select></label><label>Título<input name="title" maxLength={120} required/></label><label>Publicación<textarea name="body" maxLength={4000} required/></label><button className="btn">Enviar a revisión</button></form><details><summary>Salir de la comunidad</summary><p>Esta acción retira tus publicaciones y las respuestas asociadas a tus conversaciones.</p><form method="post" action="/api/community"><input type="hidden" name="action" value="leave"/><button className="btn secondary">Retirar mi participación</button></form></details></section>}
 {feed?.error?<p role="alert">No pudimos cargar la comunidad. Intenta nuevamente.</p>:feed&&<section className="social-stack" aria-label="Conversaciones">{posts.length===0&&<p>Todavía no hay conversaciones.</p>}{posts.slice(0,30).map(post=><CommunityPostCard key={post.id} post={post}/>)}{posts.length>30&&<Link className="btn secondary" href={'/community?before='+encodeURIComponent(posts[29].created_at)+'&cursor='+posts[29].id}>Ver anteriores</Link>}</section>}
 {s.moderator&&<Link className="btn secondary" href="/admin/social">Administrar comunidad y mentorías</Link>}
 </main></LocalizedContent>;
}
