"use client";
import {useState,type FormEvent} from 'react';
import LocalizedContent from '../../components/localization/client';
export default function SeatPurchase({requestId,prices,existingSubscription,initial}:{requestId:string;prices:{name:'starter'|'pro';cents:number}[];existingSubscription:boolean;initial?:{company_name:string;plan_name:string;requested_seats:number;status:string}}){
 const [plan,setPlan]=useState(initial?.plan_name??'starter'),[seats,setSeats]=useState(initial?.requested_seats??5),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const price=prices.find(p=>p.name===plan);const currency=(c:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(c/100);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');try{
  const response=await fetch('/api/stripe/seats',{method:'POST',body:new FormData(event.currentTarget)}),result=await response.json();
  if(!response.ok){setMessage(result.error==='EMAIL_UNVERIFIED'?'Verifica tu correo antes de crear una compañía.':result.error==='SEATS_BELOW_USAGE'?'No puedes contratar menos usuarios que los miembros e invitaciones vigentes.':result.error==='OWNER_PRIVATE'?'El propietario usa la administración de acceso directo.':result.error==='PENDING_PAYMENT'?'Hay un pago o cambio pendiente. Resuélvelo antes de volver a cambiar los seats.':'No pudimos iniciar el cambio. No se habilitaron seats nuevos; revisa tu facturación antes de reintentar.');return;}
  if(result.url){window.location.assign(result.url);return;}
  setMessage('El cambio fue recibido. La organización y el cupo se habilitan después de confirmar el pago. Consulta Mis equipos.');
 }catch{setMessage('No pudimos confirmar el resultado. Revisa tu facturación antes de volver a intentar.');}finally{setBusy(false);}}
 return <LocalizedContent><section className="card"><h2>{initial?'Administrar seats contratados':'Crear plan por seats'}</h2><form className="seat-form" onSubmit={submit}><input type="hidden" name="request_id" value={requestId}/><label>Nombre de organización<input name="company_name" defaultValue={initial?.company_name??''} minLength={2} maxLength={120} required/></label><label>Plan por persona<select name="plan" value={plan} onChange={e=>setPlan(e.target.value)}>{prices.map(p=><option key={p.name} value={p.name}>{p.name==='starter'?'Starter':'Pro'}</option>)}</select><small>{price&&currency(price.cents)} MXN / usuario / mes</small></label><label>Usuarios totales, incluida tu cuenta<input name="seats" type="number" min={5} max={100000} step={1} value={seats} onChange={e=>setSeats(Number(e.target.value))} required/></label><div className="seat-summary" aria-live="polite"><strong>{price&&Number.isSafeInteger(seats)&&seats>=5?currency(price.cents*seats):'Elige al menos cinco usuarios'} MXN / mes</strong><p>{seats} usuarios en total: tu cuenta y {Math.max(0,seats-1)} seats adicionales.</p></div>
 {existingSubscription&&<p>El cambio se aplica a tu suscripción actual y puede generar un cargo proporcional inmediato. Stripe mostrará la factura si el pago requiere tu intervención. El nuevo cupo solo se concede cuando el pago queda confirmado.</p>}
 <label className="consent"><input name="payment_authorization" value="1" type="checkbox" required/>Autorizo el cobro mensual de los usuarios indicados y el cargo proporcional del cambio, cuando corresponda.</label><label className="consent"><input name="permissions_acknowledged" value="1" type="checkbox" required/>Entiendo que debo asignar roles y configurar permisos de visibilidad en mi organización.</label><button className="btn" disabled={busy||!price||seats<5}>{busy?'Procesando…':existingSubscription?'Migrar o actualizar seats':'Continuar al pago'}</button></form><p role="status">{message}</p></section></LocalizedContent>;
}
