import {redirect} from 'next/navigation';
import Link from 'next/link';
import {createAdminSupabase,requireAdmin} from '../../../lib/admin';
import {getServerUser} from '../../../lib/supabase-server';
import LocalizedContent from '../../components/localization/server';
export default async function CompanyAdmin({searchParams}:{searchParams:Promise<{result?:string}>}){
 const {data:{user}}=await getServerUser();if(!user)redirect('/login');try{await requireAdmin(user.id);}catch{redirect('/dashboard');}
 const {data:companies,error}=await createAdminSupabase().from('organizations').select('id,name,organization_contracts(reference,seat_limit,plan_name,valid_until,active)').order('name');
 if(error)throw Error('COMPANY_DATA_UNAVAILABLE');
 const fields=(contract?:any)=><><label>Referencia del contrato o compra confirmada<input name="reference" defaultValue={contract?.reference??''} minLength={3} maxLength={200} required/></label><label>Asientos contratados<input name="seats" type="number" min={1} max={100000} defaultValue={contract?.seat_limit??1} required/></label><label>Plan<select name="plan" defaultValue={contract?.plan_name??'enterprise'}><option value="starter">Starter</option><option value="pro">Pro</option><option value="enterprise">Enterprise</option></select></label><label>Vigencia<input name="valid_until" type="date" defaultValue={contract?.valid_until?.slice(0,10)} required/></label></>;
 return <LocalizedContent><main className="wrap"><h1>Compañías y contratos</h1><Link href="/admin">Administración</Link><p>Registra únicamente asientos de una compra o contrato confirmado. Esta pantalla no realiza cobros ni cambia precios. El responsable debe tener una cuenta con correo verificado. El operador no se añade a la compañía.</p>{(await searchParams).result&&<p role="status">{(await searchParams).result==='saved'?'Cambios guardados.':'No se pudo guardar. Comprueba el correo verificado, la referencia, la vigencia y que el cupo cubra los miembros e invitaciones vigentes.'}</p>}
 <section className="card"><h2>Dar de alta una compañía contratada</h2><form action="/api/company/manage" method="post"><input type="hidden" name="action" value="contract_create"/><label>Nombre de compañía<input name="name" minLength={2} maxLength={120} required/></label><label>Correo del responsable<input name="owner_email" type="email" required maxLength={200}/></label>{fields()}<button className="btn">Crear compañía y contrato</button></form></section>
 {companies?.map(c=>{const contract=Array.isArray(c.organization_contracts)?c.organization_contracts[0]:c.organization_contracts;return <section className="card" key={c.id}><h2 translate="no">{c.name}</h2><form action="/api/company/manage" method="post"><input type="hidden" name="action" value="contract_update"/><input type="hidden" name="organization_id" value={c.id}/>{fields(contract)}<label><input name="active" type="checkbox" value="1" defaultChecked={contract?.active??true}/>Contrato activo</label><button className="btn">Actualizar contrato</button></form><Link href={'/admin/companies/'+c.id+'/invite'}>Invitar como administrador de plataforma</Link></section>;})}
 </main></LocalizedContent>;
}
