import {notFound,redirect} from 'next/navigation';
import {roleTrainingEnabled,roleTrainingSession} from '../../../lib/role-training-server';
import {createAdminSupabase} from '../../../lib/admin';
import {readWorkspacePages} from '../../../lib/workspace-pages';
import {findTrainingActivity,TRAINING_NOTICE} from '../../../lib/role-training-content';
import {COMPETENCIES} from '../../../lib/competency-matrix';
import type {ReviewRun,ReviewVote} from '../../../lib/project-review-flow';
import {isUuid} from '../../../lib/workspace-sandbox';
import Link from 'next/link';
type Submission={id:string;user_id:string;organization_id:string|null;activity_id:number;draft:string;assistance:string;created_at:string};
export default async function TrainingReview({searchParams}:{searchParams:Promise<{organization_id?:string}>}){
 if(!roleTrainingEnabled())notFound();const session=await roleTrainingSession();if(!session)redirect('/login');
 const org=(await searchParams).organization_id??null,privileged=['owner','admin'].includes(session.profile.role);
 if(org&&!isUuid(org))notFound();let leader=privileged;
 if(!privileged){if(!org)notFound();const {data:m}=await session.supabase.from('organization_memberships').select('role').eq('organization_id',org).eq('user_id',session.user.id).eq('active',true).single();if(!m)notFound();leader=['owner','admin','manager','supervisor'].includes(m.role);}
 const reader=privileged?createAdminSupabase():session.supabase;
 const [r,history,runs,votes,catalogResult]=await Promise.all([
 readWorkspacePages<Submission>((a,b)=>{let q=reader.from('learning_practice_submissions').select('id,user_id,organization_id,activity_id,draft,assistance,created_at');if(org)q=q.eq('organization_id',org);return q.order('created_at').order('id').range(a,b);}),
 readWorkspacePages<{id:string;submission_id:string;feedback?:string}>((a,b)=>{let q=reader.from('learning_evidence_history').select('id,submission_id').in('review_source',['admin','manager']);if(org)q=q.eq('organization_id',org);return q.order('observed_at',{ascending:false}).order('id',{ascending:false}).range(a,b);}),
 readWorkspacePages<ReviewRun>((a,b)=>{let q=reader.from('learning_project_review_runs').select('*');if(org)q=q.eq('organization_id',org);return q.order('created_at').order('submission_id').range(a,b);}),
 readWorkspacePages<ReviewVote>((a,b)=>{let q=reader.from('learning_project_review_votes').select('id,submission_id,stage_index,user_id,decision,feedback,observed_at').eq('user_id',session.user.id);if(org)q=q.eq('organization_id',org);return q.order('observed_at',{ascending:false}).order('id',{ascending:false}).range(a,b);}),
 reader.from('learning_activity_catalog').select('id,content_key')]);
 if(r.error||catalogResult.error||history.error||runs.error||votes.error)throw Error('REVIEW_DATA_UNAVAILABLE');
 const eligible=(r.data??[]).flatMap(s=>{const activity=findTrainingActivity(catalogResult.data?.find(c=>c.id===s.activity_id)?.content_key??''),run=runs.data?.find(x=>x.submission_id===s.id);if(!activity||activity.kind==='exercise'||s.user_id===session.user.id||!run&&(!leader||!privileged&&activity.kind==='capstone'))return [];return [{s,activity,run}];});
 return <main className="wrap" lang="es-MX" translate="no"><h1>Revisión humana · formación por puesto</h1><p>{TRAINING_NOTICE}</p><p>Supervisores y managers califican entregables y proyectos dentro de su alcance. Si el proyecto tiene flujo, únicamente revisan las personas elegidas en el paso activo. Capstones: Administración.</p><Link href={'/role-training'+(org?'?organization_id='+org:'')}>Volver al aprendizaje</Link>{org&&leader&&<> · <Link href={`/role-training/approval-flow?organization_id=${org}`}>Configurar flujo opcional</Link></>}
 {eligible.map(({s,activity,run})=>{const latest=run?votes.data?.find(e=>e.submission_id===s.id&&e.stage_index===run.current_stage):history.data?.find(e=>e.submission_id===s.id);const canReview=!run||run.state!=='approved'&&run.snapshot[run.current_stage]?.reviewers.some(p=>p.id===session.user.id);return <section className="card" key={s.id} style={{marginTop:20}}><h2>{activity.title}</h2><p>Entrega {s.id} · {latest?'Ya revisada; cualquier corrección agrega historial':'Pendiente de revisión'}</p>{run&&<><p>{run.state==='approved'?'Flujo aprobado':run.state==='changes_requested'?'Cambios solicitados':'En revisión'}</p><ol>{run.snapshot.map((step,i)=><li key={i}>{step.name} · {run.progress[String(i)]?.approved??0}/{step.required} aprobaciones · {i===run.current_stage&&run.state!=='approved'?'paso activo':i<run.current_stage||run.state==='approved'?'completado':'en espera'} · {step.reviewers.map(p=>p.name||p.id).join(', ')}</li>)}</ol></>}<p style={{whiteSpace:'pre-wrap'}} translate="no">{s.draft}</p>{activity.sourceRubric&&<ul>{activity.sourceRubric.map(r=><li key={r}>{r}</li>)}</ul>}<ul>{activity.rubric.map(t=><li key={t}>{t}</li>)}</ul>{canReview?<form action="/api/role-training/review" method="post"><input type="hidden" name="submission_id" value={s.id}/><input type="hidden" name="expected" value={latest?.id??''}/>{run&&<input type="hidden" name="stage" value={run.current_stage}/>} {activity.competencies.map(k=><label key={k}>{COMPETENCIES[k]}<select name={'score_'+k} required defaultValue=""><option value="" disabled>Valora la evidencia</option>{[0,1,2,3,4].map(v=><option key={v} value={v}>{v}/4</option>)}</select></label>)}<label>Autonomía comprobada<select name="assistance" defaultValue="guided"><option value="guided">Aplicó con guía o autonomía sin comprobar</option><option value="independent">Aplicó sin guía; evidencia suficiente</option></select></label><fieldset><legend>Errores críticos observados</legend>{[['data_exposure','Exposición de datos o credenciales'],['unauthorized_change','Cambio sin autorización'],['invented_commitment','Hecho o compromiso inventado'],['unverified_closure','Cierre sin verificar']].map(([key,label])=><label key={key} style={{display:'block'}}><input type="checkbox" name="errors" value={key}/>{label}</label>)}</fieldset>{run&&<label>Decisión<select name="decision" defaultValue="request_changes"><option value="request_changes">Solicitar cambios</option><option value="approve">Aprobar: todas las competencias ≥3/4 y sin errores críticos</option></select></label>}<label>Feedback con evidencia y siguiente paso<textarea name="feedback" rows={5} minLength={40} maxLength={6000} required defaultValue={run?(latest?.feedback??''):''}/></label><button className="btn">Guardar revisión humana</button></form>:<p>La revisión está cerrada o corresponde a otro paso del flujo.</p>}</section>;})}
 {!eligible.length&&<p>No hay entregas para revisar.</p>}</main>;
}
