'use client';
import {useState} from 'react';
import CompetencyMap from './enterprise/competency-map';
import {COMPETENCIES,competencyProfile,type CompetencyEvidence} from '../../lib/competency-matrix';
import LocalizedContent from './localization/client';
const names=['Ana · Dirección','Luis · Gerente CS','María · Supervisión Soporte','Elena · Customer Success','Julián · Customer Success','Sofía · Onboarding','Diego · Soporte','Paula · Soporte'];
const position=['manager_team_lead','manager_team_lead','tech_support_l2','customer_success','customer_success','onboarding','customer_support','customer_support'];
const date='2026-10-08T12:00:00Z';
function demoHistory(i:number):CompetencyEvidence[]{return Object.keys(COMPETENCIES).flatMap((key,k)=>{
 const base:CompetencyEvidence[]=Array.from({length:i===7&&k===2?1:3},(_,n)=>({id:`demo-${i}-${k}-${n}`,user_id:String(i),organization_id:'demo',activity_key:'demo-'+key,independent_key:`demo-${k}-${n}`,kind:'deliverable',competency_scores:{[key]:key==='data'&&i>=3?1:(k+i)%4===0?2:3},assistance:'independent',review_source:'manager',observed_at:date,critical_errors:[]}));
 if(i<2&&k%3===0){base[0].observed_at='2026-09-01T12:00:00Z';base[0].competency_scores={[key]:3};base.push({...base[0],id:`cap-${i}-${k}`,independent_key:`cap-${k}`,kind:'capstone',review_source:'admin',observed_at:date});base.push({...base[0],id:`recheck-${i}-${k}`,independent_key:`recheck-${k}`,reevaluation_of:base[0].id,observed_at:date});}return base;});}
const rows=names.map((name,i)=>({user_id:String(i),display_name:name,position:position[i],job_title:name,teams:[{id:i<6?'cs':'support',name:i<6?'Éxito del cliente':'Soporte'}],summary:competencyProfile(demoHistory(i),null,new Date(date))}));
export default function CompanyDemo({compact=false}:{compact?:boolean}){const [view,setView]=useState('map');return <LocalizedContent><section className="card"><span className="pill">Demostración · datos ficticios</span><h2>Cuenta Faro</h2><p>Ocho personas, dos equipos y tres niveles de reporte. Ejemplo de solo lectura; no son resultados de clientes reales.</p>{!compact&&<div className="grid grid3">{[['map','Competencias'],['organization','Organigrama'],['person','Antes y después']].map(([k,label])=><button className="btn secondary" key={k} aria-pressed={view===k} onClick={()=>setView(k)}>{label}</button>)}</div>}{view==='map'?<CompetencyMap org="demo" rows={compact?rows.slice(3,6):rows} units={[]} readOnly/>:view==='organization'?<ul><li>Ana · Dirección<ul><li>Luis · Gerente CS<ul><li>Elena · Customer Success</li><li>Julián · Customer Success</li><li>Sofía · Onboarding</li></ul></li><li>María · Supervisión Soporte<ul><li>Diego · Soporte</li><li>Paula · Soporte</li></ul></li></ul></li></ul>:<article><h3>Elena · Customer Success</h3><p>Datos y métricas: antes 1/4, después 3/4.</p><p>Tras tres entregas independientes revisadas por un manager, el nivel pasa de reconocimiento a aplicación autónoma. La práctica no acredita desempeño laboral real.</p></article>}</section></LocalizedContent>;}
