import {randomUUID} from 'node:crypto';
import {createServerSupabase} from '../../lib/supabase-server';
import {goalProgress,type DevelopmentPlan} from '../../lib/development-plan';
import {COMPETENCIES,type competencyProfile} from '../../lib/competency-matrix';
import {TRAINING_ACTIVITIES} from '../../lib/role-training-content';
import {PROFESSIONAL_ACTIVITIES} from '../../lib/professional-route-content';
import LocalizedContent from './localization/server';
export default async function DevelopmentPlans({org,userId,summary,canPropose=false}:{org:string;userId:string;summary:ReturnType<typeof competencyProfile>;canPropose?:boolean}){
 const supabase=await createServerSupabase();const {data,error}=await supabase.from('learning_development_plans').select('*').eq('organization_id',org).eq('user_id',userId).order('created_at',{ascending:false}).limit(10);if(error)throw Error('DEVELOPMENT_PLAN_UNAVAILABLE');
 return <LocalizedContent><section className="card"><h2>Plan de desarrollo</h2><p>Acuerdo de aprendizaje; no es evaluación de desempeño ni se vincula a compensación. Un objetivo no cambia tu calificación: solo la evidencia revisada permite avanzar.</p>{(data as DevelopmentPlan[]??[]).map(plan=><article key={plan.id}><h3>{plan.state==='accepted'?'Plan aceptado':plan.state==='commented'?'Plan comentado':'Propuesta de plan'}</h3><p><time dateTime={plan.due_at}>{plan.due_at.slice(0,10)}</time></p>{plan.goals.map(g=>{const progress=goalProgress(g,summary);return <p key={g.key}>{COMPETENCIES[g.key]} · {progress.level}/4 → {g.target}/4 · {progress.met?'Objetivo cumplido':'En progreso'}</p>;})}<details><summary>Historial del acuerdo</summary><ul>{plan.history.map((e,i)=><li key={i}>{e.at.slice(0,10)} · {({proposed:'Propuesta de plan',accept:'Plan aceptado',comment:'Plan comentado'})[e.action]??e.action}<span translate="no"> {e.comment}</span></li>)}</ul></details>{!canPropose&&<form action="/api/development-plan" method="post"><input type="hidden" name="plan_id" value={plan.id}/><input type="hidden" name="revision" value={plan.revision}/><label>Comentario<textarea name="comment" maxLength={2000}/></label><button className="btn" name="action" value="accept">Aceptar plan</button> <button className="btn secondary" name="action" value="comment">Comentar plan</button></form>}</article>)}{!data?.length&&<p>Aún no hay un acuerdo de aprendizaje.</p>}{canPropose&&<details><summary>Proponer hasta tres objetivos</summary><form action="/api/development-plan" method="post"><input type="hidden" name="action" value="propose"/><input type="hidden" name="plan_id" value={randomUUID()}/><input type="hidden" name="organization_id" value={org}/><input type="hidden" name="user_id" value={userId}/>{[0,1,2].map(i=><fieldset key={i}><legend>Objetivo {i+1}</legend><label>Competencia<select name={'key_'+i} defaultValue=""><option value="">Sin objetivo</option>{Object.entries(COMPETENCIES).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>Nivel objetivo<select name={'target_'+i} defaultValue="3">{[1,2,3,4].map(n=><option key={n} value={n}>{n}/4</option>)}</select></label><label>Actividad asignada<select name={'activity_'+i} defaultValue=""><option value="">Elige una actividad</option>{[...TRAINING_ACTIVITIES,...PROFESSIONAL_ACTIVITIES].filter(a=>a.kind==='deliverable'&&!a.reevaluationOf).map(a=><option key={a.key} value={a.key}>{a.title}</option>)}</select></label></fieldset>)}<label>Fecha objetivo<input type="date" name="due_at" required/></label><button className="btn">Proponer plan</button></form></details>}</section></LocalizedContent>;
}
