"use client";
import {useState} from "react";
import {AI_COST_REFERENCE,estimateAiMonthlyCost} from "../../lib/tutor-cost-estimate";
export default function TutorCostEstimate(){
 const [fx,setFx]=useState("20");const rate=Number(fx);const valid=fx.trim()!=="" && Number.isFinite(rate)&&rate>=0.01&&rate<=1000;
 const scenarios=[{label:"Tutor · 100 consultas",sessions:100,callsPerSession:1,inputTokensPerCall:2500,outputTokensPerCall:768},{label:"Simulador · 20 sesiones de 8 turnos",sessions:20,callsPerSession:8,inputTokensPerCall:3500,outputTokensPerCall:1000},{label:"Simulador · escenario amplio, 20 turnos",sessions:20,callsPerSession:20,inputTokensPerCall:10000,outputTokensPerCall:1500}];
 return <section className="card" style={{marginTop:24}}><h2>Estimación de costo de IA por usuario</h2><p>Escenarios de referencia con {AI_COST_REFERENCE.model}, tarifa Standard sin caché. Son supuestos de consumo, no mediciones ni cargos. Tarifas consultadas el {AI_COST_REFERENCE.checkedOn}.</p>
 <label htmlFor="tutor-estimate-fx">Supuesto editable: MXN por USD</label><input id="tutor-estimate-fx" type="number" min="0.01" max="1000" step="0.01" value={fx} onChange={event=>setFx(event.target.value)}/><p>20 es un ejemplo; no se consultó el tipo de cambio actual.</p>
 {valid?<div style={{overflowX:"auto"}}><table><caption>Costo mensual de tokens por usuario con tus supuestos</caption><thead><tr><th scope="col">Escenario</th><th scope="col">Llamadas</th><th scope="col">Entrada/salida por llamada</th><th scope="col">USD</th><th scope="col">MXN estimados</th></tr></thead><tbody>{scenarios.map(item=>{const cost=estimateAiMonthlyCost({...item,mxnPerUsd:rate});return <tr key={item.label}><td>{item.label}</td><td>{cost.calls}</td><td>{item.inputTokensPerCall}/{item.outputTokensPerCall}</td><td>${cost.usd.toFixed(4)}</td><td>${cost.mxn.toFixed(2)}</td></tr>;})}</tbody></table></div>:<p role="status">Introduce un supuesto de conversión positivo entre 0.01 y 1000.</p>}
 <p>Los tokens de entrada deben incluir instrucciones e historial; la salida incluye razonamiento facturable cuando aplique. No incluye impuestos, cambio/comisiones, reintentos, herramientas ni infraestructura. Una sesión no equivale a una sola llamada; el historial puede crecer. El presupuesto real requiere medición y límites atómicos antes de habilitar IA.</p><p><a href={AI_COST_REFERENCE.source} target="_blank" rel="noreferrer">Tarifas oficiales del modelo de referencia</a></p></section>;
}
