import {test} from 'node:test';import assert from 'node:assert/strict';
import {validDevelopmentGoals,goalProgress} from '../lib/development-plan.ts';
import {competencyProfile} from '../lib/competency-matrix.ts';
import {PUBLIC_JOB_CASES} from '../lib/public-job-cases.ts';import {MIXED_UNITS} from '../lib/mixed-role-content.ts';
import {PROFESSIONAL_ACTIVITIES} from '../lib/professional-route-content.ts';
test('public case summaries match the guarded learning catalog',()=>assert.deepEqual(PUBLIC_JOB_CASES,MIXED_UNITS.map(({key,title,caseTitle})=>({key,title,caseTitle}))));
test('development goals reject duplicate, oversized and unknown targets',()=>{const goal={key:'data',target:3,baseline:1,activity:'common-data'};assert.equal(validDevelopmentGoals([goal]),true);for(const value of [[],[goal,goal],[{...goal,key:'private'}],[{...goal,target:5}],[{...goal,baseline:-1}],[{...goal,activity:'x'.repeat(121)}]])assert.equal(validDevelopmentGoals(value),false);});
test('development goals do not grant competency without reviewed independent evidence',()=>{const goal={key:'data',target:3,baseline:1,activity:'common-data'},e={user_id:'u',organization_id:null,activity_key:'case',kind:'deliverable',competency_scores:{data:3},assistance:'independent',review_source:'manager',observed_at:'2026-10-08T12:00:00Z',critical_errors:[]};const summary=h=>competencyProfile(h,null,new Date(e.observed_at));assert.equal(goalProgress(goal,summary([])).met,false);assert.equal(goalProgress(goal,summary([{...e,id:'1',independent_key:'one'}])).met,false);const records=Array.from({length:3},(_,i)=>({...e,id:String(i),independent_key:String(i)}));assert.equal(goalProgress(goal,summary(records)).met,true);assert.equal(goalProgress(goal,summary(records.map(r=>({...r,review_source:'self'})))).met,false);});
test('GRC includes six subjects at every stage, examinations, capstone and primary sources',()=>{const activities=PROFESSIONAL_ACTIVITIES.filter(a=>a.route==='grc');assert.equal(activities.length,48);for(const level of [1,2,3,4]){assert.equal(activities.filter(a=>a.level===level&&a.key.includes('-unit-')).length,6);assert.equal(activities.find(a=>a.key==='grc-exam-'+level).decisions.length,6);}assert.equal(activities.filter(a=>a.kind==='capstone').length,1);assert.ok(activities.every(a=>a.sourceUrls.some(u=>u.startsWith('https://www.nist.gov/')||u.startsWith('https://www.theiia.org/'))));});
