import test from 'node:test';import assert from 'node:assert/strict';
import {ROLE_CASES,CASE_RUBRIC,roleReviewGuide,nextPracticeChoices} from '../lib/role-practice-cases.ts';
import {ROLE_WORKFLOWS} from '../lib/career-role-workflows.ts';
import {PRACTICE_ACTIVITIES,API_LABS,TARGET_ROLES} from '../lib/practice-learning.ts';
import {RUNTIME_CHALLENGES} from '../lib/runtime-challenges.ts';
import {parsePracticeEvidence} from '../lib/assessment-evidence.ts';
import {createAssessmentVariant,publicAssessmentVariant} from '../lib/assessment-variants.ts';
import {reserveTutor,transitionTutor,tutorBudgetUsage} from '../lib/tutor-budget-policy.ts';
import {extractTutorAnswer} from '../lib/tutor-context.ts';
import {planMonthlyAddonChange,newTutorIntroIntent,ownedLaunchAddons,reviewJointInvoiceFailure} from '../lib/modular-billing-policy.ts';
import {certificateIssuanceDecision,certificatePublicView} from '../lib/certificate-policy.ts';
import {runControlledTutor} from '../lib/tutor-controlled-run.ts';
import {setTimeout as pause} from 'node:timers/promises';

test('every existing position has process, activities, acceptance, deliverable checklist and review rubric',()=>{
 for(const key of Object.keys(ROLE_WORKFLOWS)){const x=roleReviewGuide(key);assert.ok(x.activities.length>=3);assert.ok(x.checklist.length>=6);assert.ok(x.acceptance.length>20);assert.equal(x.rubric.length,4);assert.match(x.source,/^https:/);}
});
test('each current exploration role has three lifecycle cases, choices, evidence and failure variants',()=>{
 assert.equal(new Set(ROLE_CASES.map(x=>x.id)).size,9);for(const role of TARGET_ROLES){const cases=ROLE_CASES.filter(x=>x.role===role.id);assert.equal(cases.length,3);assert.equal(new Set(cases.map(x=>x.stage)).size,3);for(const x of cases){assert.ok(x.options[x.recommended]);assert.ok(x.deliverables.length>=3);assert.ok(x.failure.length>20);}}
 assert.equal(CASE_RUBRIC.length,4);
});
test('personalized choices remain known persisted samples and omit resolved samples',()=>{
 const known=new Set([...PRACTICE_ACTIVITIES,...API_LABS].map(x=>x.id));for(const role of TARGET_ROLES)for(const approach of ['process','code','customer']){const first=nextPracticeChoices(role.id,[],approach);assert.ok(first.length>0);assert.ok(first.every(x=>known.has(x.id)&&x.reason.includes(role.label)));const next=nextPracticeChoices(role.id,first.map(x=>x.id),approach);assert.ok(next.every(x=>!first.some(y=>y.id===x.id)));}
 assert.equal(nextPracticeChoices('support',[],'customer')[0].id,'support-note');assert.equal(nextPracticeChoices('integrations',[],'code')[0].id,'sql-filter');assert.deepEqual(nextPracticeChoices('support',[...known],'code'),[]);assert.deepEqual(nextPracticeChoices('unknown',[],'code'),[]);
});
test('runtime challenges cover filter, sum, invalid input and grouping without persisted quota IDs',()=>{assert.equal(RUNTIME_CHALLENGES.length,6);assert.equal(new Set(RUNTIME_CHALLENGES.map(x=>x.id)).size,6);for(const language of ['python','sql'])assert.equal(RUNTIME_CHALLENGES.filter(x=>x.language===language).length,3);});
const evidence={explanation:'Una decisión con evidencia',test:'Una prueba reproducible',expected:'Resultado esperado válido',observed:'Resultado observado real',failure:'Error y recuperación definidos',tools:'Sin herramientas adicionales'};
test('evidence validates structure, bounds and exact fields without claiming correctness',()=>{assert.deepEqual(parsePracticeEvidence(evidence),evidence);for(const x of [null,[],{...evidence,score:100},{...evidence,tools:''},{...evidence,failure:'x'.repeat(1501)},{...evidence,expected:42}])assert.equal(parsePracticeEvidence(x),null);});
test('server variants are stable per attempt, varied across attempts, and public projection excludes answer',()=>{
 const secret='fixture-variant-secret-only-'.repeat(2);const a=createAssessmentVariant(secret,'attempt_01');assert.deepEqual(a,createAssessmentVariant(secret,'attempt_01'));assert.equal(a.answer,a.rows.filter(x=>x.active).reduce((n,x)=>n+x.seats,0));assert.notEqual(a.prompt,createAssessmentVariant(secret,'attempt_02').prompt);assert.deepEqual(Object.keys(publicAssessmentVariant(a)).sort(),['attemptId','prompt','version']);assert.throws(()=>createAssessmentVariant('short','attempt_01'));assert.throws(()=>createAssessmentVariant(secret,'../bad'));
});
const budget=()=>({account:'fixture_account',period:'2026-10',queryLimit:2,budget:1000,entries:[]});
test('Tutor unavailable never reserves queries or cost',()=>{const x=budget();assert.throws(()=>reserveTutor(x,'request_01',100,false),/PROVIDER_UNAVAILABLE/);assert.deepEqual(tutorBudgetUsage(x),{queries:0,committed:0,uncertain:0});});
test('Tutor replay does not dispatch twice and rejects different reservation cost',()=>{const x=reserveTutor(budget(),'request_01',400,true).ledger;const replay=reserveTutor(x,'request_01',400,true);assert.equal(replay.replay,true);assert.equal(replay.dispatchAllowed,false);assert.equal(replay.ledger,x);assert.throws(()=>reserveTutor(x,'request_01',401,true),/IDEMPOTENCY_MISMATCH/);});
test('Tutor query and cost caps include pending calls',()=>{let x=reserveTutor(budget(),'request_01',600,true).ledger;assert.throws(()=>reserveTutor(x,'request_02',500,true),/COST_LIMIT/);x=reserveTutor(x,'request_02',200,true).ledger;assert.throws(()=>reserveTutor(x,'request_03',100,true),/QUERY_LIMIT/);});
test('only never-dispatched reservations can release cost and query capacity',()=>{let x=reserveTutor(budget(),'request_01',600,true).ledger;x=transitionTutor(x,'request_01','released');assert.equal(tutorBudgetUsage(x).queries,0);assert.equal(tutorBudgetUsage(x).committed,0);assert.equal(reserveTutor(x,'request_01',600,true).dispatchAllowed,false);assert.throws(()=>transitionTutor(x,'request_01','dispatched'),/INVALID_TRANSITION/);});
test('timeout after dispatch retains reservation until reconciliation; no free retry assumption',()=>{let x=reserveTutor(budget(),'request_01',600,true).ledger;x=transitionTutor(x,'request_01','dispatched');x=transitionTutor(x,'request_01','uncertain');assert.deepEqual(tutorBudgetUsage(x),{queries:1,committed:600,uncertain:1});assert.throws(()=>transitionTutor(x,'request_01','released'),/INVALID_TRANSITION/);assert.throws(()=>reserveTutor(x,'request_02',100,true),/RECONCILIATION_REQUIRED/);x=transitionTutor(x,'request_01','settled',450);assert.deepEqual(tutorBudgetUsage(x),{queries:1,committed:450,uncertain:0});assert.equal(transitionTutor(x,'request_01','settled',450),x);assert.throws(()=>transitionTutor(x,'request_01','settled',0),/SETTLEMENT_CONFLICT/);});
test('unexpected actual cost is retained and blocks further cost, rather than silently capped',()=>{let x=reserveTutor(budget(),'request_01',600,true).ledger;x=transitionTutor(x,'request_01','dispatched');x=transitionTutor(x,'request_01','settled',1200);assert.equal(tutorBudgetUsage(x).committed,1200);assert.throws(()=>reserveTutor(x,'request_02',100,true),/COST_LIMIT/);});
test('refused, incomplete and malformed provider fixtures never produce a usable answer and still reconcile cost',()=>{
 for(const response of [{status:'incomplete',output:[]},{status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'refusal',refusal:'No'}]}]},{status:'failed',output:[]}]){
  let x=reserveTutor(budget(),'request_01',400,true).ledger;x=transitionTutor(x,'request_01','dispatched');assert.equal(extractTutorAnswer(response).answer,null);x=transitionTutor(x,'request_01','settled',150);assert.equal(tutorBudgetUsage(x).committed,150);
 }
});
test('invalid Tutor ledgers and usage fail closed',()=>{for(const change of [{period:'2026-99'},{queryLimit:1.5},{budget:Infinity},{entries:[{id:'request_01',bound:100,state:'settled'}]},{entries:[{id:'request_01',bound:100,state:'reserved',actual:0}]}])assert.throws(()=>tutorBudgetUsage({...budget(),...change}));let x=reserveTutor(budget(),'request_01',100,true).ledger;assert.throws(()=>transitionTutor(x,'request_01','settled',20),/INVALID_TRANSITION/);assert.throws(()=>transitionTutor(x,'request_01','dispatched',20),/UNEXPECTED_USAGE/);});
const ready={tutor:true,customerSuccess:true,certificate:true};const sub=()=>({id:'sub_fixture',plan:'starter',baseItemId:'si_base',items:[{id:'si_base',key:'base',priceId:'price_base_existing',quantity:1,cents:24900}]});
test('monthly add-ons reuse base subscription and preserve base item; unready and one-time cannot be appended',()=>{const x=sub();const plan=planMonthlyAddonChange(x,'ai_tutor','add',ready);assert.equal(plan.kind,'append_item_at_renewal');assert.equal(plan.subscriptionId,x.id);assert.deepEqual(plan.preserved,x.items);assert.equal(plan.invoiceFailurePolicy,'requires_review');for(const key of ['ai_simulator','verified_certificate','unknown'])assert.throws(()=>planMonthlyAddonChange(x,key,'add',ready));assert.throws(()=>planMonthlyAddonChange(x,'ai_tutor','add',{...ready,tutor:false}));});
test('existing active price is frozen and cancellation removes only the chosen item',()=>{const x=sub();x.items.push({id:'si_tutor',key:'ai_tutor',priceId:'price_grandfather',quantity:1,cents:9000});assert.equal(planMonthlyAddonChange(x,'ai_tutor','add',ready).cents,9000);const remove=planMonthlyAddonChange(x,'ai_tutor','cancel',ready);assert.equal(remove.itemId,'si_tutor');assert.equal(remove.basePlan,'starter');assert.deepEqual(remove.preserved,[x.items[0]]);assert.throws(()=>planMonthlyAddonChange({...x,baseItemId:'si_tutor'},'ai_tutor','cancel',ready),/BASE_ITEM_MISSING/);});
test('new Tutor phase intent contains only existing 50 and 100 IDs and all base items',()=>{const x=sub();const plan=newTutorIntroIntent(x,{first:'price_fixture_50',renewal:'price_fixture_100'},ready);assert.equal(plan.phases.length,2);assert.equal(plan.firstCents,5000);assert.equal(plan.renewalCents,10000);for(const phase of plan.phases)assert.deepEqual(phase.items[0],{priceId:x.items[0].priceId,quantity:1});assert.throws(()=>newTutorIntroIntent({...x,plan:'pro'},{first:'price_fixture_50',renewal:'price_fixture_100'},ready),/NEW_TUTOR_REQUIRED/);});
test('Pro included launch add-ons have no extra item and future modules remain absent',()=>{assert.equal(planMonthlyAddonChange({...sub(),plan:'pro'},'ai_tutor','add',ready).kind,'included_entitlement');assert.deepEqual(ownedLaunchAddons('pro',[],ready).sort(),['ai_tutor','route_customer_success','verified_certificate']);assert.deepEqual(ownedLaunchAddons('pro',[],{tutor:false,customerSuccess:false,certificate:false}),[]);});
test('certificates are a plan benefit independent of legacy payment; monthly and duplicate ownership remain guarded',()=>{const certificate={key:'verified_certificate',kind:'one_time',status:'paid'};assert.deepEqual(ownedLaunchAddons('free',[certificate],ready),['verified_certificate']);assert.deepEqual(ownedLaunchAddons('free',[{key:'ai_tutor',kind:'monthly',status:'paid'}],ready),['verified_certificate']);assert.deepEqual(ownedLaunchAddons('free',[{...certificate,status:'refunded'}],ready),['verified_certificate']);assert.throws(()=>ownedLaunchAddons('free',[certificate,{...certificate,status:'refunded'}],ready),/INVALID_OWNERSHIP/);});
test('joint invoice failure does not guess an add-on or change base plan',()=>{const x=reviewJointInvoiceFailure('sub_fixture');assert.equal(x.requiresReconciliation,true);assert.equal(x.basePlanMutation,null);assert.equal(x.addonToCancel,null);});
const facts={accountId:'fixture-account',route:'route_customer_success',allLessons:true,examPassed:true,projectApproved:true,owned:true,operational:true};
test('certificate needs trusted completion, paid/included ownership and operational readiness',()=>{assert.equal(certificateIssuanceDecision(facts).eligible,true);for(const key of ['allLessons','examPassed','projectApproved','owned','operational'])assert.equal(certificateIssuanceDecision({...facts,[key]:false}).eligible,false);assert.equal(certificateIssuanceDecision({...facts,route:'future_route'}).eligible,false);});
test('public certificate projection omits email, account and private evidence and preserves revocation',()=>{const x={publicId:'fixture_opaque_certificate_id_12345678',displayName:'Persona ficticia',routeTitle:'Customer Success',issuedOn:'2026-10-07',status:'verified',accountId:'private-account',email:'private@example.test',internalEvidence:{score:100}};const view=certificatePublicView(x);assert.deepEqual(Object.keys(view).sort(),['displayName','issuedOn','publicId','routeTitle','status']);assert.doesNotMatch(JSON.stringify(view),/private|score|email/);assert.equal(certificatePublicView({...x,status:'revoked'}).status,'revoked');assert.throws(()=>certificatePublicView({...x,issuedOn:'2026-02-30'}));assert.throws(()=>certificatePublicView({...x,publicId:'guessable'}));});
function atomicFixture(){let ledger=budget();return {get ledger(){return ledger;},async reserve(id,bound){const x=reserveTutor(ledger,id,bound,true);ledger=x.ledger;return x.replay?'replay':'reserved';},async claim(id){if(ledger.entries.find(x=>x.id===id)?.state!=='reserved')return false;ledger=transitionTutor(ledger,id,'dispatched');return true;},async settle(id,actual){ledger=transitionTutor(ledger,id,'settled',actual);},async uncertain(id){if(ledger.entries.find(x=>x.id===id)?.state==='dispatched')ledger=transitionTutor(ledger,id,'uncertain');}};}
const draftFixture={store:false,max_output_tokens:768,instructions:'Fixture',input:[]};
const runInput={id:'request_01',boundMicroUsd:500,providerReady:true,draft:draftFixture,timeoutMs:1000};
const answerFixture={status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'Explica el filtro con tus palabras.'}]}]};
test('controlled Tutor concurrent replay dispatches one mocked provider call and reconciles once',async()=>{const store=atomicFixture();let calls=0;const provider={async complete(){calls++;await pause(10);return {response:answerFixture,actualMicroUsd:150};}};const results=await Promise.all([runControlledTutor(store,provider,runInput),runControlledTutor(store,provider,runInput)]);assert.equal(calls,1);assert.equal(results.filter(x=>x.status==='complete').length,1);assert.equal(tutorBudgetUsage(store.ledger).committed,150);});
test('controlled Tutor blocks disabled provider before store operations',async()=>{let calls=0;const result=await runControlledTutor({reserve:()=>{throw Error('must not reserve');}},{async complete(){calls++;}}, {...runInput,providerReady:false});assert.equal(result.status,'unavailable');assert.equal(calls,0);});
test('controlled Tutor refusal records billed usage without an answer',async()=>{const store=atomicFixture();const response={status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'refusal',refusal:'No'}]}]};const result=await runControlledTutor(store,{async complete(){return {response,actualMicroUsd:50};}},runInput);assert.equal(result.status,'refused');assert.equal(result.answer,null);assert.equal(tutorBudgetUsage(store.ledger).committed,50);});
test('controlled Tutor missing usage or provider failure retains uncertain cost',async()=>{for(const provider of [{async complete(){return {response:answerFixture};}},{async complete(){throw Error('upstream failed');}}]){const store=atomicFixture();const x=await runControlledTutor(store,provider,runInput);assert.equal(x.status,'usage_pending_reconciliation');assert.equal(x.answer,null);assert.deepEqual(tutorBudgetUsage(store.ledger),{queries:1,committed:500,uncertain:1});}});
test('controlled Tutor timeout holds cost, aborts transport, and reconciles late fixture completion',async()=>{const store=atomicFixture();let aborted=false;let resolve;const response=new Promise(r=>{resolve=r;});const result=await runControlledTutor(store,{complete(draft,signal){signal.addEventListener('abort',()=>{aborted=true;});return response;}},{...runInput,timeoutMs:5});assert.equal(result.status,'usage_pending_reconciliation');assert.equal(aborted,true);assert.equal(tutorBudgetUsage(store.ledger).uncertain,1);resolve({response:answerFixture,actualMicroUsd:80});await pause(0);assert.deepEqual(tutorBudgetUsage(store.ledger),{queries:1,committed:80,uncertain:0});});

