import {test} from 'node:test';import assert from 'node:assert/strict';
import {nextLearningStep} from '../lib/next-learning-step.ts';
import {monthlyReport,monthlyBounds,monthlyCsv,monthlyCompletions} from '../lib/monthly-team-report.ts';
import {reportPdf} from '../lib/report-pdf.ts';
import {publishedWeeklyCases,WEEKLY_CASES} from '../lib/weekly-cases.ts';
import {translationGate} from '../scripts/localization-flag-policy.mjs';
test('next step respects dated assignments then partial then path and avoids invalid dates',()=>{const row=(key,due=null)=>({key,href:'/',title:key,due,minutes:20});assert.equal(nextLearningStep([row('later','2026-12-01'),row('overdue','2026-01-01')],[row('partial')],row('route')).key,'overdue');assert.equal(nextLearningStep([row('invalid','bad')],[row('partial')],row('route')).key,'partial');assert.equal(nextLearningStep([],[],row('route')).key,'route');assert.equal(nextLearningStep([],[],null),null);});
test('scheduled cases remain unavailable until CDMX midnight, archive retains published cases',()=>{assert.equal(WEEKLY_CASES.length,8);assert.equal(publishedWeeklyCases(new Date('2026-10-08T05:59:59Z')).length,0);assert.equal(publishedWeeklyCases(new Date('2026-10-08T06:00:00Z')).length,1);assert.equal(publishedWeeklyCases(new Date('2026-11-27')).length,8);assert.ok(WEEKLY_CASES.every(c=>c.kind==='project'&&c.decisions.length===3&&c.hours===1/3));});
test('monthly report excludes future observations, does not fabricate no-evidence grades and CSV formulas are neutralized',()=>{assert.throws(()=>monthlyBounds('2026-13'));const report=monthlyReport('2026-01',[{user_id:'1',display_name:'=SUM(1,1)',profile:null}],[],[]);assert.ok(report.competencies.every(c=>c.average===null&&c.change===null));assert.match(monthlyCsv(report,s=>s),/"'=SUM/);});
test('PDF emits valid cross references and a bounded summary',()=>{const pdf=reportPdf(Array.from({length:70},()=> 'Garciloga · Comunicación y colaboración'));assert.match(pdf.toString('latin1'),/%PDF-1.4/);assert.match(pdf.toString('latin1'),/\/Count 2/);assert.match(pdf.toString('latin1'),/startxref\n\d+\n%%EOF/);});
test('only explicitly disabled exclusive module texts warn; visible shared text remains blocking',()=>{assert.equal(translationGate('lib/mixed-role-content.ts',{CODEZERO_MIXED_ROUTES:'0'}),'warning');assert.equal(translationGate('lib/mixed-role-content.ts',{}),'error');assert.equal(translationGate('lib/mixed-role-content.ts',{CODEZERO_MIXED_ROUTES:'1'}),'error');assert.equal(translationGate('app/components/vivo-shell.tsx',{CODEZERO_MIXED_ROUTES:'0'}),'error');});

test('monthly completion merges legacy and human keys, excludes weak review and respects later changes',()=>{const e={user_id:'u',activity_key:'project',observed_at:'2026-10-08',review_source:'manager',critical_errors:[],competency_scores:{data:3}};const assignment={user_id:'u',activity_key:'route_unit:7',due_at:'2026-10-01'};const legacy={user_id:'u',activity_key:'route_unit:7',observed_at:e.observed_at,completed:true};const run=(h,l)=>monthlyCompletions('u',h,l,[assignment],[{id:7,content_key:'project'}],Date.parse('2026-10-01'),Date.parse('2026-10-31'));assert.deepEqual(run([e],[legacy]),{completed:1,overdue:0});assert.deepEqual(run([{...e,competency_scores:{data:2}}],[]),{completed:0,overdue:1});assert.deepEqual(run([e,{...e,observed_at:'2026-10-09',critical_errors:['unverified_closure']}],[legacy]),{completed:0,overdue:1});});
