import {translatedMetadata} from '../../lib/localization/metadata';
import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {socialSession,workflowMessage} from '../../lib/social-server';
import LocalizedContent from '../components/localization/server';
import {COMMERCIAL_REFERENCES} from '../../lib/product-roadmap';
export async function generateMetadata(){return translatedMetadata({title:'Mentorías',robots:{index:false,follow:false}});}
function when(iso:string){return new Date(iso).toISOString().slice(0,16).replace('T',' ')+' UTC';}
export default async function Mentoring({searchParams}:{searchParams:Promise<{result?:string}>}){
 const s=await socialSession();const query=await searchParams;
 const [catalog,own,slots]=await Promise.all([
 s.admin.from('mentoring_profiles').select('user_id,display_name,bio,languages,profiles!inner(status)').eq('status','approved').eq('profiles.status','active').limit(50),
 s.admin.from('mentoring_profiles').select('display_name,bio,languages,status').eq('user_id',s.user.id).maybeSingle(),
 s.admin.from('mentoring_slots').select('id,mentor_id,starts_at').eq('active',true).gt('starts_at',new Date(Date.now()+86400000).toISOString()).order('starts_at').limit(100)
 ]);
 // Separate participant queries preserve learner and mentor visibility.
 const ownRequests=await s.admin.from('mentoring_requests').select('id,slot_id,topic,status,expires_at,meeting_url,mentoring_slots!inner(mentor_id,starts_at,ends_at)').eq('learner_id',s.user.id).order('created_at',{ascending:false}).limit(50);
 const mentorRequests=own.data?await s.admin.from('mentoring_requests').select('id,slot_id,topic,status,expires_at,meeting_url,mentoring_slots!inner(mentor_id,starts_at,ends_at)').eq('mentoring_slots.mentor_id',s.user.id).order('created_at',{ascending:false}).limit(50):null;
 const bookings=[...(ownRequests.data??[]).map(r=>({...r,mentor:false})),...(mentorRequests?.data??[]).map(r=>({...r,mentor:true}))];
 const visibleSlots=(slots.data??[]).filter(slot=>catalog.data?.some(m=>m.user_id===slot.mentor_id));
 const occupied=visibleSlots.length?await s.admin.from('mentoring_requests').select('slot_id,status,expires_at').in('slot_id',visibleSlots.map(x=>x.id)).in('status',['pending','confirmed']):null;
 const taken=new Set((occupied?.data??[]).filter(r=>r.status==='confirmed'||Date.parse(r.expires_at)>Date.now()).map(r=>r.slot_id));
 const message=workflowMessage(query.result);
 return <LocalizedContent><main className="wrap"><h1>Mentorías</h1><p>Trabaja con una persona mentora sobre puestos, procesos, decisiones y liderazgo.</p><p>Precio previsto: ${COMMERCIAL_REFERENCES.mentoringMxn} MXN por {COMMERCIAL_REFERENCES.mentoringMinutes} minutos.</p><p>Solicitar una sesión no genera un cobro. La confirmación requiere disponibilidad y verificación del pago por administración. Las solicitudes vencen en 24 horas.</p><p>Horarios en UTC.</p>{message&&<p role="status">{message}</p>}
 {catalog.error||slots.error||occupied?.error?<p role="alert">No pudimos cargar las mentorías. Intenta nuevamente.</p>:<section className="social-stack"><h2>Mentores y disponibilidad</h2>{!catalog.data?.length&&<p>Todavía no hay mentores aprobados con disponibilidad.</p>}{catalog.data?.map(m=><article className="card" key={m.user_id}><h3 translate="no">{m.display_name}</h3><p className="social-body" translate="no">{m.bio}</p><p translate="no">{m.languages.join(' / ')}</p>{visibleSlots.filter(x=>x.mentor_id===m.user_id&&!taken.has(x.id)).map(slot=><form method="post" action="/api/mentoring" key={slot.id}><input type="hidden" name="action" value="request"/><input type="hidden" name="target" value={slot.id}/><input type="hidden" name="request_id" value={randomUUID()}/><p><time dateTime={slot.starts_at} translate="no">{when(slot.starts_at)}</time></p><label>Tema y objetivo<textarea name="topic" minLength={10} maxLength={1500} required/></label><button className="btn" disabled={m.user_id===s.user.id}>Solicitar sesión</button></form>)}</article>)}</section>}
 <section className="social-stack"><h2>Mis sesiones</h2>{ownRequests.error||mentorRequests?.error?<p role="alert">No pudimos cargar las mentorías. Intenta nuevamente.</p>:bookings.length===0?<p>No tienes solicitudes de sesión.</p>:bookings.map(r=>{const slot=r.mentoring_slots as unknown as {starts_at:string;ends_at:string};const status=r.status==='pending'&&Date.parse(r.expires_at)<=Date.now()?'expired':r.status;return <article className="card" key={r.id}><p translate="no">{when(slot.starts_at)}</p><p className="social-body" translate="no">{r.topic}</p><p>{status==='pending'?'Pendiente de confirmación':status==='confirmed'?'Confirmada':status==='cancelled'?'Cancelada':status==='declined'?'Rechazada':status==='completed'?'Completada':'Vencida'}</p>{status==='confirmed'&&r.meeting_url&&<a className="btn" href={r.meeting_url} target="_blank" rel="noopener noreferrer">Abrir sesión</a>}{['pending','confirmed'].includes(status)&&<form method="post" action="/api/mentoring"><input type="hidden" name="target" value={r.id}/><button className="btn secondary" name="action" value="cancel">Cancelar solicitud</button>{r.mentor&&status==='pending'&&<button className="btn secondary" name="action" value="decline">Rechazar solicitud</button>}{r.mentor&&status==='confirmed'&&Date.parse(slot.ends_at)<=Date.now()&&<button className="btn" name="action" value="complete">Marcar completada</button>}</form>}</article>;})}</section>
 {own.data?.status==='approved'&&<section className="card"><h2>Publicar disponibilidad</h2><form method="post" action="/api/mentoring"><input type="hidden" name="action" value="slot"/><label>Inicio de sesión en UTC<input type="datetime-local" name="starts_at" required/></label><p>Publica horarios entre 24 horas y 90 días de anticipación.</p><button className="btn">Guardar horario</button></form>{(slots.data??[]).filter(x=>x.mentor_id===s.user.id).map(slot=><form key={slot.id} method="post" action="/api/mentoring"><input type="hidden" name="action" value="close_slot"/><input type="hidden" name="target" value={slot.id}/><p translate="no">{when(slot.starts_at)}</p><button className="btn secondary">Retirar horario</button></form>)}</section>}
 {s.profile.role!=='owner'&&<details className="card"><summary>Postularme como mentor</summary>{own.data&&<p>{own.data.status==='approved'?'Perfil aprobado':own.data.status==='paused'?'Perfil pausado':'Perfil en revisión'}</p>}<form method="post" action="/api/mentoring"><input type="hidden" name="action" value="apply"/><label>Nombre público<input name="display_name" minLength={3} maxLength={60} required defaultValue={own.data?.display_name}/></label><label>Experiencia y especialidad<textarea name="bio" minLength={20} maxLength={1500} required defaultValue={own.data?.bio}/></label><fieldset><legend>Idiomas de la mentoría</legend>{['es','en','pt','fr'].map(l=><label key={l}><input type="checkbox" name="languages" value={l} defaultChecked={own.data?.languages.includes(l)??l==='es'}/><span translate="no">{l.toUpperCase()}</span></label>)}</fieldset><label><input type="checkbox" name="consent" value="1" required/>Acepto publicar este perfil y recibir solicitudes de mentoría si se aprueba.</label><p>Actualizar tu perfil requiere una nueva revisión.</p><button className="btn">Enviar perfil a revisión</button></form></details>}
 {s.moderator&&<Link className="btn secondary" href="/admin/social">Administrar comunidad y mentorías</Link>}
 </main></LocalizedContent>;
}
