'use client';
import LocalizedContent from '../../components/localization/client';
import {useState} from 'react';
import {REVIEW_ROLES,emptyReviewSelector,validReviewSelector,validReviewStages,type ReviewFlow,type ReviewPerson,type ReviewSelector,type ReviewStage} from '../../../lib/project-review-flow';
type Position={key:string;title:string};
function Selector({label,value,onChange,people,positions}:{label:string;value:ReviewSelector;onChange:(s:ReviewSelector)=>void;people:ReviewPerson[];positions:Position[]}){
 const [search,setSearch]=useState('');
 const toggle=(key:'roles'|'positions'|'users',id:string)=>onChange({...value,[key]:value[key].includes(id)?value[key].filter(x=>x!==id):[...value[key],id]});
 return <LocalizedContent><fieldset><legend>{label}</legend><label><input type="checkbox" checked={value.all} onChange={e=>onChange({...value,all:e.target.checked})}/>Todas las personas activas en mi alcance</label><p>Las selecciones se suman: basta coincidir con un rol, puesto o persona. Nunca incluye al autor como revisor.</p><details><summary>Por rol</summary>{Object.entries(REVIEW_ROLES).map(([id,title])=><label key={id} style={{display:'block'}}><input type="checkbox" checked={value.roles.includes(id)} onChange={()=>toggle('roles',id)}/>{title}</label>)}</details><details><summary>Por puesto</summary>{positions.map(p=><label key={p.key} style={{display:'block'}}><input type="checkbox" checked={value.positions.includes(p.key)} onChange={()=>toggle('positions',p.key)}/>{p.title}</label>)}</details><details><summary>Por nombre o usuario</summary><label>Buscar nombre o ID<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{people.filter(p=>(p.display_name+' '+p.user_id).toLowerCase().includes(search.toLowerCase())).map(p=><label key={p.user_id} style={{display:'block'}}><input type="checkbox" checked={value.users.includes(p.user_id)} onChange={()=>toggle('users',p.user_id)}/><span translate="no">{p.display_name}</span> · {REVIEW_ROLES[p.role as keyof typeof REVIEW_ROLES]??p.role} · <small>{p.user_id}</small></label>)}</details></fieldset></LocalizedContent>;
}
export default function FlowEditor({org,flow,people,positions}:{org:string;flow?:ReviewFlow;people:ReviewPerson[];positions:Position[]}){
 const [audience,setAudience]=useState(flow?.audience??{...emptyReviewSelector(),roles:['learner']});
 const [stages,setStages]=useState<ReviewStage[]>(flow?.stages??[{name:'Supervisor',required:1,reviewers:{...emptyReviewSelector(),roles:['supervisor']}},{name:'Manager',required:1,reviewers:{...emptyReviewSelector(),roles:['manager']}}]);
 const update=(index:number,patch:Partial<ReviewStage>)=>setStages(old=>old.map((s,i)=>i===index?{...s,...patch}:s));
 const move=(index:number,direction:number)=>setStages(old=>{const result=[...old];[result[index],result[index+direction]]=[result[index+direction],result[index]];return result;});
 return <LocalizedContent><form action="/api/role-training/approval-flow" method="post"><input type="hidden" name="organization_id" value={org}/><input type="hidden" name="flow_key" value={flow?.flow_key??''}/><input type="hidden" name="version" value={flow?.version??0}/><input type="hidden" name="audience" value={JSON.stringify(audience)}/><input type="hidden" name="stages" value={JSON.stringify(stages)}/><label>Nombre del flujo<input name="name" defaultValue={flow?.name??'Proyecto: supervisor y manager'} minLength={3} maxLength={120} required/></label><label>Estado<select name="enabled" defaultValue={flow?.enabled===false?'false':'true'}><option value="true">Activado para nuevas entregas</option><option value="false">Desactivado para nuevas entregas</option></select></label><label>Prioridad del flujo (1 primero)<input type="number" name="priority" defaultValue={flow?.priority??100} min={1} max={1000} required/></label><p>Si coinciden varios flujos, se aplica el de número menor. Un empate impide enviar hasta corregir la configuración.</p><Selector label="A quién se aplica" value={audience} onChange={setAudience} people={people} positions={positions}/>{stages.map((s,i)=><section className="card" key={i}><h3>Paso {i+1}</h3><label>Nombre del paso<input value={s.name} onChange={e=>update(i,{name:e.target.value})} maxLength={120} required/></label><label>Aprobaciones mínimas de personas distintas<input type="number" value={s.required} onChange={e=>update(i,{required:Number(e.target.value)})} min={1} max={20} required/></label><Selector label="Quién califica y aprueba" value={s.reviewers} onChange={reviewers=>update(i,{reviewers})} people={people} positions={positions}/><div><button type="button" disabled={i===0} onClick={()=>move(i,-1)}>Subir paso {i+1}</button> <button type="button" disabled={i===stages.length-1} onClick={()=>move(i,1)}>Bajar paso {i+1}</button> <button type="button" disabled={stages.length===1} onClick={()=>setStages(old=>old.filter((_,n)=>n!==i))}>Eliminar paso {i+1}</button></div></section>)}<button type="button" disabled={stages.length>=8} onClick={()=>setStages(old=>[...old,{name:'Nueva revisión',required:1,reviewers:emptyReviewSelector()}])}>Agregar paso</button><p>Hasta 8 pasos, en el orden mostrado. Un solo paso con varios revisores sirve para revisión paralela. Una solicitud de cambios detiene el avance; cada persona puede corregir su propia revisión con historial.</p><p>Las entregas existentes conservan su flujo. Los revisores se fijan al enviar; si alguien pierde acceso, no podrá seguir revisando. Una nueva entrega utilizará la configuración vigente.</p><button className="btn" disabled={!validReviewSelector(audience)||!validReviewStages(stages)}>Guardar nueva versión del flujo</button></form></LocalizedContent>;
}
