import type { CareerDimension, CareerPositionKey } from "./career-guidance.ts";
export type LabActivity = { key: string; title: string; scenario: string; options: string[]; lesson: string };
export const LAB_ACTIVITIES: LabActivity[] = [
{ key:"priority", title:"Priorizar bajo presión", scenario:"Un cliente no puede entrar; un informe vence mañana; un colega pide ayuda sin urgencia y hay un error visual menor. ¿Cómo empieza el personaje ficticio?", options:["Verifica impacto y alcance del bloqueo; atiende el acceso y comunica prioridades.","Termina el informe antes de investigar el bloqueo.","Atiende cada solicitud por orden de llegada."], lesson:"Priorizar requiere impacto, urgencia y dependencias. Comunica el orden y revisa si el bloqueo afecta a más usuarios." },
{ key:"diagnose", title:"Diagnosticar un 401", scenario:"Una integración devuelve 401. Internet funciona y otro usuario de la misma empresa puede entrar.", options:["Revisa token, permisos y registros sin compartir credenciales.","Reinicia todos los servicios antes de recopilar evidencia.","Cambia la configuración de todos los usuarios."], lesson:"Un 401 orienta hacia autenticación; comprueba credenciales y alcance antes de intervenir. Redacta registros y reproduce con el mínimo cambio." },
{ key:"customer", title:"Responder a un cliente molesto", scenario:"La exportación lleva una hora fallando. ¿Qué mensaje envía el personaje?", options:["Reconozco el impacto; revisemos error y alcance. Te comunicaré el siguiente avance.","Seguro estará resuelto en cinco minutos.","No es mi área; intenta más tarde."], lesson:"Reconoce el impacto, pide evidencia concreta y acuerda el siguiente contacto. Evita prometer tiempos sin confirmarlos." },
{ key:"project", title:"Preparar una implementación", scenario:"El onboarding vence el viernes; faltan datos y una integración. Participan tres personas.", options:["Aclara responsables y dependencias; prepara capacitación en paralelo y prueba la integración antes del lanzamiento.","Capacita primero y revisa los datos al final.","Asigna todo a una persona para evitar coordinación."], lesson:"Separa tareas independientes de las que bloquean el lanzamiento. Define responsables, criterio de aceptación y una alternativa si falla la integración." },
{ key:"explain", title:"Explicar una API", scenario:"Una persona sin formación técnica necesita entender una API.", options:["Es una forma acordada para que dos programas soliciten e intercambien información, como consultar un pedido.","Es un endpoint REST con serialización JSON y autenticación bearer.","Es una conexión que siempre permite ver todos los datos."], lesson:"Empieza con una tarea conocida y una analogía breve; después aclara permisos y límites. Comprueba la comprensión con una pregunta." },
{ key:"objection", title:"Entender una objeción", scenario:"Un prospecto teme pagar por algo que no va a utilizar.", options:["Pregunta qué resultado busca y qué impediría usarlo; acuerda una prueba con criterio de éxito.","Ofrece un descuento urgente sin conocer el problema.","Insiste en que el plan más caro siempre es mejor."], lesson:"Diagnostica la necesidad antes de recomendar. Una prueba necesita objetivo medible, responsables y fecha de revisión." },
{ key:"anomaly", title:"Investigar una anomalía", scenario:"Acme: Starter $249; Beta: Pro $699; Gamma: Free $699; Delta: Starter $249. ¿Qué revisa el personaje?", options:["Gamma: verifica contrato, extras y origen del dato antes de editar.","Cambia Gamma a cero inmediatamente.","No hay nada que verificar si el número es positivo."], lesson:"Una anomalía es una hipótesis. Contrasta fuentes y documenta el motivo de cualquier corrección; no cambies facturación por una sola fila." },
{ key:"choice", title:"Elegir otra práctica", scenario:"El personaje tiene veinte minutos libres. ¿Qué actividad elige voluntariamente?", options:["Resolver un pequeño bug.","Ayudar a un cliente a adoptar una función.","Organizar el plan de una implementación.","Preparar una conversación con un prospecto."], lesson:"Preferencia y desempeño son señales distintas. Esta elección ficticia aporta preferencia; no demuestra habilidad ni experiencia." }
];
export const BASE_DIMENSIONS: CareerDimension[][] = [
["organization_execution","customer_orientation","analysis_precision","ambiguity_tolerance"],
["technical_problem_solving","analysis_precision","autonomy","troubleshooting"],
["customer_orientation","explanatory_communication","ambiguity_tolerance"],
["organization_execution","project_management","leadership_coordination","stakeholder_management"],
["explanatory_communication","customer_orientation","teaching_adoption"],
["commercial_persuasion","customer_orientation","explanatory_communication"],
["analysis_precision","technical_problem_solving","autonomy"],
["software_building","teaching_adoption","project_management","prospecting"]
];
export const ROLE_PRACTICES: Record<CareerPositionKey, { task:string; deliverable:string; review:string; example:string }> = {
developer:{task:"Construye un validador de formularios sin enviar datos reales.",deliverable:"Código, pruebas de entradas vacías y explicación de decisiones.",review:"Valida límites, mensajes accesibles y ausencia de datos sensibles.",example:"Rechaza un correo inválido y conserva el resto del formulario."},
tech_support_l1:{task:"Clasifica cinco tickets ficticios por impacto y urgencia.",deliverable:"Tabla de prioridad, pregunta inicial y criterio de escalación.",review:"Distingue impacto de tono del mensaje y reúne evidencia mínima.",example:"Un bloqueo general se investiga antes que un error visual aislado."},
tech_support_l2:{task:"Diagnostica una integración que falla solo para un usuario.",deliverable:"Árbol de hipótesis y pruebas reversibles.",review:"Cada prueba descarta una hipótesis y protege credenciales.",example:"Compara permisos y caducidad del token antes de reiniciar."},
tech_support_l3:{task:"Investiga fallos intermitentes después de una nueva versión.",deliverable:"Cronología, hipótesis raíz, mitigación y prevención.",review:"Separa correlación de causa y define observabilidad y rollback.",example:"Relaciona trazas con la versión y contrasta con un grupo de control."},
customer_support:{task:"Responde un reclamo por una exportación fallida.",deliverable:"Respuesta inicial, seguimiento y cierre verificable.",review:"Reconoce impacto, evita promesas y confirma la resolución.",example:"Solicita hora y error; acuerda cuándo volverás a informar."},
onboarding:{task:"Diseña la primera semana de adopción de una cuenta ficticia.",deliverable:"Plan, responsables, capacitación y primer valor medible.",review:"Incluye dependencias, validación técnica y evidencia de adopción.",example:"Completar el primer flujo útil vale más que asistir a una sesión."},
customer_success:{task:"Una cuenta ficticia perdió usuarios activos: prepara un plan de valor.",deliverable:"Hipótesis, preguntas, acciones y medición de adopción.",review:"Conecta uso con resultado del cliente, sin confundirlo con venta.",example:"Valida si cambió el proceso antes de recomendar más capacitación."},
account_manager:{task:"Prepara una renovación con una objeción de precio.",deliverable:"Plan de negociación, alternativas y siguiente compromiso.",review:"Usa evidencia de valor y límites de concesión explícitos.",example:"Intercambia una concesión por un compromiso verificable."},
key_account_manager:{task:"Desarrolla una cuenta con tres áreas y un patrocinador nuevo.",deliverable:"Mapa de actores, riesgos y plan trimestral de cuenta.",review:"Define gobierno, objetivos conjuntos y dependencias políticas.",example:"Valida prioridades con cada área antes de proponer expansión."},
sdr_bdr:{task:"Prepara una secuencia de contacto para una empresa ficticia.",deliverable:"Tres mensajes y preguntas de calificación.",review:"Personaliza por necesidad, respeta rechazo y acuerda siguiente paso.",example:"Pregunta por el problema operativo antes de pedir una demo."},
account_executive:{task:"Una oportunidad está estancada antes de la firma.",deliverable:"Mapa de decisión, riesgos y plan de cierre conjunto.",review:"Confirma comprador, proceso, presupuesto y criterio de decisión.",example:"Acuerda con el cliente quién revisa el contrato y cuándo."},
pre_sales:{task:"Demuestra cómo una integración resolvería un caso ficticio.",deliverable:"Guion de demo, requisitos y límites de viabilidad.",review:"Conecta función con valor y distingue capacidad actual de promesa.",example:"Muestra un flujo concreto e identifica permisos necesarios."},
project_manager:{task:"Recupera un proyecto con una dependencia retrasada.",deliverable:"Plan revisado, riesgos, decisiones y comunicación.",review:"Explicita alcance, responsables y efecto en fecha y recursos.",example:"Presenta alternativas con costo y criterio de aceptación."},
administrative_assistant:{task:"Organiza un registro ficticio con datos duplicados.",deliverable:"Registro limpio y procedimiento de verificación.",review:"Conserva trazabilidad y confirma antes de eliminar.",example:"Marca duplicados potenciales y contrasta el identificador."},
executive_assistant:{task:"Resuelve un choque de agenda con información confidencial.",deliverable:"Opciones de agenda y plan de comunicación.",review:"Anticipa dependencias y comparte solo lo necesario.",example:"Confirma prioridad con el ejecutivo sin reenviar información privada."},
manager_team_lead:{task:"Coordina un equipo ficticio con sobrecarga y prioridades en conflicto.",deliverable:"Plan de delegación, seguimiento y conversación de apoyo.",review:"Evalúa capacidad, desarrolla personas y hace explícitas las decisiones.",example:"Redistribuye trabajo con acuerdos claros y revisa carga semanal."}
};

