import type { CareerPositionKey } from "./career-guidance.ts";

export type LearningGuide = {
  concept: string;
  question: string;
  options: { text: string; explanation: string; correct: boolean }[];
  steps: [string, string, string];
  twist: string;
};

function guide(
  concept: string, question: string, answer: string, why: string,
  distractor: string, correction: string,
  steps: LearningGuide["steps"], twist: string,
): LearningGuide {
  return {
    concept, question, steps, twist,
    options: [
      { text: distractor, explanation: correction, correct: false },
      { text: answer, explanation: why, correct: true },
      { text: "Actuar primero y documentar únicamente si algo falla.", explanation: "Registra la hipótesis y el criterio de éxito antes de intervenir. Así puedes verificar qué cambió y aprender del resultado.", correct: false },
    ],
  };
}

export const LEARNING_GUIDES: Record<CareerPositionKey, LearningGuide> = {
  developer: guide(
    "Validar una entrada significa comprobar las reglas del dato antes de usarlo. Una regla explícita y un mensaje concreto permiten corregir errores. La validación del navegador mejora la experiencia; el servidor también debe validar antes de aceptar datos.",
    "Un formulario acepta un correo vacío. ¿Qué cambio atiende el problema?",
    "Definir que el correo es obligatorio, validar la regla y probar entradas válidas e inválidas.",
    "La regla determina el comportamiento y las pruebas verifican que se mantiene, incluidos casos límite.",
    "Ocultar el botón de enviar cuando el formulario parezca vacío.",
    "Ocultar el botón no verifica datos enviados por otras vías ni explica el error al usuario.",
    ["Escribe reglas para correo vacío, formato inválido y entrada válida.", "Implementa validación y mensajes asociados a cada campo.", "Prueba cada regla y explica por qué el servidor también debe comprobarla."],
    "Una entrada válida en el navegador llega modificada al servidor. Añade una comprobación del lado del servidor y una prueba que reproduzca el caso.",
  ),
  tech_support_l1: guide(
    "El triage reúne información para decidir prioridad, siguiente acción y responsable. Impacto indica a quién y qué afecta; urgencia indica cuánto puede esperar. Una escalación útil incluye síntoma, alcance, pasos de reproducción y evidencia redactada.",
    "Un mensaje es muy molesto pero afecta un detalle visual; otro bloquea a toda una empresa. ¿Cuál requiere atención primero?",
    "El bloqueo general, mientras se reconoce y comunica el seguimiento del otro caso.",
    "El impacto y la urgencia guían la prioridad; ambos clientes necesitan una respuesta clara.",
    "El mensaje más molesto, para que deje de reclamar.",
    "El tono no demuestra impacto. Atenderlo primero puede retrasar una interrupción general.",
    ["Crea cinco tickets ficticios con alcance y urgencia.", "Asigna prioridad y escribe la primera pregunta que falta responder.", "Prepara una escalación con evidencia mínima y criterio para actualizar al cliente."],
    "El bloqueo tiene una alternativa temporal. Reevalúa la urgencia sin perder el seguimiento ni cerrar el incidente antes de verificar.",
  ),
  tech_support_l2: guide(
    "Diagnosticar consiste en contrastar hipótesis con pruebas pequeñas y reversibles. Un 401 orienta a autenticación: revisa credenciales, caducidad y alcance. Evita copiar tokens en tickets y distingue lo observado de lo supuesto.",
    "Solo un usuario recibe 401 y el resto puede entrar. ¿Qué prueba tiene más sentido primero?",
    "Comparar configuración de autenticación y caducidad del token con datos redactados.",
    "Reduce el problema a la diferencia entre usuarios y contrasta una hipótesis sin modificar todo el servicio.",
    "Reiniciar los servicios de toda la empresa.",
    "Una intervención amplia agrega riesgo y no explica por qué solo falla una identidad.",
    ["Registra síntoma, alcance y tres hipótesis ordenadas.", "Diseña una prueba reversible para cada hipótesis y qué resultado la descartaría.", "Escribe diagnóstico, siguiente acción y un resumen comprensible para el cliente."],
    "La primera hipótesis resulta falsa. Actualiza el árbol y elige una segunda prueba sin repetir acciones que ya descartaste.",
  ),
  tech_support_l3: guide(
    "Un análisis de causa raíz distingue síntoma, desencadenante y condición que permitió el fallo. Una mitigación reduce impacto; una corrección atiende la causa. La coincidencia con un despliegue es una pista que necesita evidencia.",
    "Los fallos aparecen después de una versión nueva. ¿Qué conclusión está justificada?",
    "La versión es una hipótesis que debe contrastarse con trazas y una comparación controlada.",
    "La cronología orienta la investigación, pero no demuestra por sí sola una causa.",
    "La versión es la causa definitiva porque los eventos coincidieron.",
    "Una correlación temporal puede esconder cambios de carga, configuración o datos.",
    ["Construye una cronología con cambios y síntomas.", "Compara trazas de casos fallidos y exitosos; define una mitigación reversible.", "Documenta causa confirmada o incertidumbres, corrección y una señal preventiva."],
    "El rollback reduce pero no elimina los errores. Investiga una segunda condición y explica qué evidencia falta antes de cerrar la causa raíz.",
  ),
  customer_support: guide(
    "Una respuesta de soporte reconoce el impacto, delimita lo que se sabe y ofrece un siguiente paso verificable. Una fecha de actualización es distinta de una promesa de resolución. El cierre requiere confirmar que la tarea vuelve a funcionar.",
    "Todavía no conoces la causa de una exportación fallida. ¿Qué puedes comprometer?",
    "Recopilar error y alcance, investigar y comunicar el avance en un momento acordado.",
    "Controlas la siguiente actualización aunque todavía no puedas confirmar cuándo estará resuelto.",
    "Asegurar que estará resuelto en cinco minutos.",
    "Un plazo sin evidencia crea expectativas que pueden incumplirse.",
    ["Redacta una respuesta que reconozca el impacto y pida dos datos concretos.", "Escribe un seguimiento que distinga confirmado, pendiente y siguiente acción.", "Define cómo comprobarás con el cliente que la exportación funciona."],
    "El cliente necesita el archivo para una reunión. Propón una alternativa viable e indica sus límites sin prometer que sustituye la solución definitiva.",
  ),
  onboarding: guide(
    "Onboarding busca que el cliente alcance un primer resultado útil. Completar sesiones o configurar opciones es actividad; lograr que el cliente ejecute su flujo clave es valor. Dependencias, responsables y validación conectan ambos.",
    "Todos asistieron a la capacitación pero nadie puede completar su flujo principal. ¿Terminó el onboarding?",
    "Todavía no: hay que identificar el bloqueo y comprobar el primer resultado útil.",
    "La asistencia no demuestra que el cliente pueda usar el producto para su objetivo.",
    "Sí, porque la sesión programada ya se impartió.",
    "La entrega de una sesión mide trabajo realizado, no adopción ni valor.",
    ["Define el primer resultado del cliente y cómo se comprobará.", "Ordena datos, integración, capacitación y validación por dependencias.", "Asigna responsables y prepara un plan alternativo para el viernes."],
    "La integración se retrasa dos días. Rediseña el primer valor con un flujo permitido temporalmente y acuerda qué queda pendiente.",
  ),
  customer_success: guide(
    "Customer Success conecta adopción del producto con resultados del cliente. Una caída de uso es una señal para investigar; no confirma por sí sola riesgo de cancelación ni necesidad de vender más. Las hipótesis se revisan con contexto y métricas.",
    "Baja el uso semanal de una cuenta. ¿Cuál es el siguiente paso más útil?",
    "Preguntar por cambios del proceso y contrastar uso con el objetivo acordado.",
    "El contexto puede revelar estacionalidad, un bloqueo o un cambio legítimo del trabajo.",
    "Ofrecer de inmediato una expansión para aumentar el compromiso.",
    "Comprar más no resuelve una causa de baja adopción que todavía no entiendes.",
    ["Define el objetivo ficticio y una métrica de resultado junto con una de adopción.", "Formula tres hipótesis y preguntas para confirmarlas.", "Propón acciones con responsables y una revisión del resultado."],
    "El uso subió pero el resultado de negocio sigue igual. Revisa si la métrica de adopción representa la tarea que genera valor.",
  ),
  account_manager: guide(
    "Gestionar una renovación requiere comprender valor, restricciones y alternativas. Una concesión debe tener límite y contrapartida acordada. Negociar no consiste solo en bajar precio: alcance, plazo y compromisos pueden cambiar la propuesta.",
    "El cliente pide un descuento antes de renovar. ¿Cómo preparas la conversación?",
    "Aclaro la causa, el valor obtenido, los límites y qué compromiso recibiríamos a cambio.",
    "Permite negociar con información y conservar una propuesta sostenible para ambas partes.",
    "Ofrezco el descuento máximo de inmediato.",
    "Una concesión sin diagnóstico ni contrapartida puede no resolver la objeción y reduce margen.",
    ["Resume objetivo del cliente, evidencia de valor y objeción.", "Prepara dos alternativas con límites y compromisos.", "Redacta un acuerdo de siguiente paso con responsable y fecha."],
    "El cliente necesita menos alcance, no menor precio unitario. Ajusta la propuesta y explica cómo cambia el valor esperado.",
  ),
  key_account_manager: guide(
    "Una cuenta estratégica involucra objetivos y decisiones de varios actores. El mapa de stakeholders distingue usuarios, patrocinador, decisores y posibles bloqueadores. Un plan de cuenta conecta relaciones con resultados y mecanismos de gobierno.",
    "Llega un patrocinador nuevo a una cuenta con tres áreas. ¿Qué conviene hacer?",
    "Validar prioridades y criterios de decisión con el nuevo patrocinador y las áreas involucradas.",
    "Los objetivos anteriores pueden seguir o cambiar; necesitas comprobarlos antes de proponer expansión.",
    "Reutilizar el plan anterior sin conversar para ahorrar tiempo.",
    "El cambio de patrocinio puede modificar prioridades, apoyo y proceso de decisión.",
    ["Dibuja un mapa ficticio de actores, intereses y capacidad de decisión.", "Define objetivos conjuntos y riesgos para el trimestre.", "Propón reuniones de gobierno y cómo resolver desacuerdos."],
    "Dos áreas quieren resultados incompatibles. Prepara opciones y una decisión conjunta sin asumir que el patrocinador resolverá todo.",
  ),
  sdr_bdr: guide(
    "La prospección intenta identificar si existe una necesidad relevante y acordar una conversación útil. Calificar implica problema, encaje y siguiente paso. Respetar el rechazo protege la relación y evita insistir sin valor.",
    "Un contacto dice que no tiene interés ahora. ¿Qué respuesta respeta su decisión?",
    "Reconocerlo, aclarar si desea un contacto futuro y terminar si no lo autoriza.",
    "El seguimiento debe responder a un interés o acuerdo; la insistencia no demuestra oportunidad.",
    "Mandar el mismo mensaje cada día hasta que responda.",
    "La repetición sin permiso no agrega relevancia y puede deteriorar la relación.",
    ["Define una empresa ficticia y una hipótesis de necesidad.", "Escribe tres mensajes breves con una pregunta relevante.", "Incluye criterios de calificación y una forma respetuosa de cerrar el contacto."],
    "Responde una persona sin capacidad de decisión. Comprueba si puede ayudar a identificar al responsable sin convertirla en una oportunidad confirmada.",
  ),
  account_executive: guide(
    "Una oportunidad requiere un proceso de decisión confirmado, no solo entusiasmo. Un plan de cierre conjunto establece quién decide, qué criterios usa y qué pasos faltan. La fecha se valida con el cliente y sus dependencias.",
    "El contacto dice que le encanta la demo pero el contrato no avanza. ¿Qué falta verificar?",
    "Quién decide, qué revisiones faltan y cuál es el proceso acordado para firmar.",
    "La intención favorable no elimina compras, revisión legal o aprobación de presupuesto.",
    "Considerar la venta ganada porque la demo gustó.",
    "Confundir interés con decisión crea una previsión poco confiable.",
    ["Identifica problema, comprador, criterios y proceso de decisión ficticios.", "Lista riesgos y pasos pendientes del contrato.", "Redacta un plan de cierre conjunto con responsables y fechas confirmables."],
    "La revisión contractual agrega una condición nueva. Actualiza el plan y la previsión antes de prometer una fecha de firma.",
  ),
  pre_sales: guide(
    "Una demo técnica muestra cómo un flujo concreto responde a una necesidad. Debe distinguir capacidades actuales, requisitos y límites. Una prueba de viabilidad necesita criterios de aceptación para evitar confundir demostración con promesa.",
    "El cliente pregunta por una función que no está disponible. ¿Cómo responde el consultor?",
    "Aclara el límite actual y valida si una alternativa existente cumple el objetivo.",
    "La transparencia permite una decisión informada y evita compromisos que la implementación no puede cumplir.",
    "Decir que estará disponible pronto sin confirmación.",
    "Una promesa no respaldada convierte una expectativa en riesgo de implementación.",
    ["Define caso de uso, entradas ficticias y criterio de éxito.", "Prepara una demo del flujo con permisos y requisitos mínimos.", "Documenta límites, alternativas y cuestiones que requieren una prueba."],
    "La demo funciona con datos pequeños, pero el volumen esperado es mayor. Diseña una prueba de viabilidad y evita afirmar que escalará sin medir.",
  ),
  project_manager: guide(
    "Un proyecto coordina alcance, recursos, fecha y riesgos. Una dependencia es algo que debe ocurrir para que otra tarea avance. Cambiar una fecha sin revisar dependencias no resuelve el plan; hay que comparar alternativas y acordar decisiones.",
    "Una dependencia se retrasa. ¿Qué debe actualizar el responsable del proyecto?",
    "Impacto en tareas, alternativas, riesgos y acuerdos con los responsables.",
    "Permite elegir conscientemente entre alcance, recursos y fecha con información compartida.",
    "Solo la fecha final en el calendario.",
    "Mover una fecha no identifica bloqueos ni consigue un acuerdo sobre el cambio.",
    ["Desglosa entregables y dependencias del caso ficticio.", "Compara dos planes con efectos en fecha, recursos y riesgo.", "Escribe la decisión requerida y cómo comunicarás el avance."],
    "No hay presupuesto para más recursos. Prepara una alternativa de alcance y define qué aceptación necesita el cliente.",
  ),
  administrative_assistant: guide(
    "La precisión operativa combina orden y trazabilidad. Dos registros parecidos pueden representar personas o transacciones distintas. Detecta, contrasta con un identificador confiable y documenta antes de consolidar o corregir.",
    "Dos registros tienen el mismo nombre y distinto identificador. ¿Qué haces?",
    "Los marco como posibles duplicados y verifico el origen antes de fusionarlos.",
    "Un nombre coincidente no demuestra identidad; preservar trazabilidad evita perder datos legítimos.",
    "Elimino uno automáticamente por tener el mismo nombre.",
    "Podrían representar entidades distintas y la eliminación no estaría justificada.",
    ["Construye un registro ficticio con tres anomalías.", "Define reglas de detección y una fuente para contrastar cada una.", "Describe qué corregirías, por qué y cómo conservarías el historial."],
    "Dos fuentes discrepan sobre el dato correcto. Deja la corrección pendiente y define quién puede resolver la discrepancia.",
  ),
  executive_assistant: guide(
    "El soporte ejecutivo anticipa dependencias y protege información confidencial. Resolver un conflicto de agenda requiere conocer prioridad, flexibilidad y participantes. Compartir solo lo necesario permite coordinar sin exponer el contenido de las reuniones.",
    "Dos reuniones confidenciales coinciden. ¿Qué información comparte el asistente para coordinar?",
    "Disponibilidad y necesidad de reprogramar, sin reenviar detalles confidenciales.",
    "La coordinación necesita datos de agenda; el contenido privado no es requisito para resolver el horario.",
    "Reenvía ambos documentos completos a todos los participantes.",
    "Amplía el acceso a información que otras personas no necesitan conocer.",
    ["Crea una agenda ficticia con un conflicto y dos dependencias.", "Propón opciones considerando prioridad y flexibilidad.", "Redacta comunicaciones mínimas y un plan de contingencia."],
    "Una reunión cambia de ciudad el mismo día. Revisa desplazamiento, márgenes de tiempo y participantes antes de confirmar.",
  ),
  manager_team_lead: guide(
    "Coordinar personas requiere objetivos claros, capacidad disponible y seguimiento. Delegar define resultado, autonomía y apoyo; no transfiere únicamente tareas. La carga y el desarrollo del equipo deben revisarse junto con las prioridades.",
    "Una persona está sobrecargada y otra puede apoyar. ¿Qué hace el líder?",
    "Acordar prioridades, redistribución, criterio de resultado y apoyo necesario.",
    "La delegación funciona cuando capacidad, expectativas y seguimiento quedan explícitos.",
    "Asignar más trabajo a la persona más rápida sin revisar su carga.",
    "La velocidad actual no justifica una carga sostenible ni desarrolla la capacidad del resto.",
    ["Lista objetivos ficticios, capacidad y restricciones de tres personas.", "Define qué delegar, a quién y con qué autonomía y apoyo.", "Prepara una conversación de seguimiento y señales de sobrecarga."],
    "Una persona reconoce que aún no sabe resolver la tarea. Ajusta el apoyo y el plazo sin confundir acompañamiento con quitarle toda autonomía.",
  ),
};
