export const COMPANY_HELP={
 eyebrow:"GUÍA PARA EMPRESAS · EDICIÓN ESPAÑOL",
 title:"Cómo formar equipos con Garciloga",
 intro:"Guía ilustrada para responsables, supervisores y equipos. Separa las actividades hoy disponibles de la asignación de rutas completas, aún en borrador de pruebas.",
 current:"Disponible según contrato y permisos: organizaciones, perfiles, asignación de actividades publicadas, refuerzos, revisión humana y reportes.",
 upcoming:"En desarrollo, sin habilitar a clientes: asignación de cursos completos por equipo y énfasis de competencia, nuevos currículos GRC/IA/ventas y aplicaciones Android e iOS.",
 steps:[
  {number:"01",title:"Accede a la organización correcta",screen:"Garciloga → Equipos → Tu compañía",detail:"Inicia sesión con tu cuenta de empresa, abre Equipos y confirma el nombre de la organización que administras. Si perteneces a varias, elige la correcta antes de comenzar. Un manager no puede asignar recursos de otra compañía.",link:"/teams"},
  {number:"02",title:"Abre Personas y selecciona al colaborador",screen:"Equipo → Personas → Ficha de aprendizaje",detail:"Desde la sección Personas localiza al integrante que está bajo tu alcance. Abre su ficha para conocer su puesto, actividades asignadas, competencias con evidencia y errores críticos pendientes. Sin evidencia no equivale a incapacidad.",link:"/teams"},
  {number:"03",title:"Configura el perfil de aprendizaje del puesto",screen:"Ficha → Perfil del puesto → Guardar",detail:"Cuando la formación por puesto esté incluida en tu plan y habilitada para la compañía, selecciona el puesto correcto. El perfil fija el punto de comparación de las competencias; no cambia rol de organización, permiso ni salario.",link:"/role-training"},
  {number:"04",title:"Asigna una actividad publicada",screen:"Equipo → Asignar aprendizaje → Actividad",detail:"Con permiso de líder, entra a Asignar aprendizaje, selecciona persona, una actividad publicada y la competencia que deseas trabajar. Guardar la actividad no desbloquea contenido fuera de los derechos contratados.",link:"/teams"},
  {number:"05",title:"Asigna refuerzos desde la ficha",screen:"Ficha → Competencias → Brechas → Asignar",detail:"Dentro de Competencias por evidencia, cada brecha con actividades recomendadas puede tener un refuerzo de una a tres unidades y fecha de entrega. Comprueba que la unidad sea relevante y accesible antes de registrarla.",link:"/role-training/reinforcements"},
  {number:"06",title:"Revisa entregas y proyectos",screen:"Formación por puesto → Revisar",detail:"Un supervisor autorizado debe verificar datos, razonamiento, compromiso, colaboración observable y errores críticos. Una entrega o selección correcta no acredita competencia por sí sola. Registra comentario y siguiente oportunidad de práctica.",link:"/role-training/review"},
  {number:"07",title:"Mide resultados sin confundirlos con personalidad",screen:"Equipo → Avance / Competencias → Reporte",detail:"Compara evidencia inicial y final, fecha, nivel demostrado y criterio de rúbrica. La actitud interna, la personalidad o la disposición no se infieren de clics, tiempo conectado ni puntuaciones aisladas. Los líderes solo ven datos autorizados.",link:"/teams"},
 ],
 draftSteps:[
  {title:"Curso completo",value:"GRC, ventas, soporte, IA o ruta por puesto",explain:"Elegir únicamente cursos publicados cuando el motor completo esté habilitado."},
  {title:"Alcance",value:"Un colaborador o integrantes de un equipo",explain:"El permiso se valida en el servidor frente a organización, membresía, jerarquía y grants del equipo."},
  {title:"Competencia principal",value:"Comunicación · Diagnóstico · Datos · Planeación",explain:"El foco expresa qué evidencia se desea practicar; nunca oculta materias esenciales."},
  {title:"Intensidad",value:"Base · Enfoque · Intensivo",explain:"Configura tiempo, ejercicios y revisión adicional; no reemplaza requisitos del plan ni la aprobación."},
  {title:"Fecha y seguimiento",value:"Entrega, evidencias, revisión y refuerzo",explain:"Solo se registra progreso cuando el motor y la revisión humana estén integrados y verificados."}
 ],
 faqs:[
  {q:"¿Puede un manager asignar cursos a toda la compañía?",a:"No automáticamente. El dueño y los administradores gestionan el alcance autorizado. Managers y supervisores solo pueden trabajar con sus reportes directos o equipos para los que tengan un permiso expreso. El backend volverá a verificarlo incluso si se modifica el formulario."},
  {q:"¿Cómo asigno algo desde el perfil del empleado?",a:"Entra a la empresa, abre Personas y selecciona la Ficha de aprendizaje. Usa Competencias por evidencia → Asigna de una a tres unidades; cuando esté habilitado el nuevo planificador de cursos completos, aparecerá en esa misma ficha. Hoy la asignación de rutas completas está solo en borrador."},
  {q:"¿Cómo se asigna una capacitación a un equipo?",a:"La asignación grupal de cursos completos está en diseño y sandbox. La vista prevista permite escoger equipo autorizado, curso, competencia prioritaria, intensidad y fecha. No aplica en clientes ni desbloquea exámenes hasta verificar RLS, límites y plan contratado."},
  {q:"¿Qué es un refuerzo de una competencia?",a:"Es práctica adicional enfocada en una brecha con evidencia suficiente, un objetivo observable y una nueva evaluación. Una calificación sin evidencia no demuestra una debilidad personal."},
  {q:"¿Qué significan los niveles de competencia 0 a 4?",a:"0 = sin evidencia suficiente; 1 = reconoce; 2 = aplica con apoyo; 3 = aplica autónomamente con evidencia revisada; 4 = sostiene la competencia en diferentes momentos y en un proyecto. No son rasgos psicológicos."},
  {q:"¿Qué evalúa Garciloga en la toma de decisiones?",a:"La interpretación de hechos, calidad del dato, alternativas, impacto, límites de autoridad, comunicación, colaboración, ética y revisión de hipótesis cuando aparece información nueva. La evaluación humana examina lo observable en casos ficticios."},
  {q:"¿Cómo se evitan calificaciones fáciles?",a:"Los cursos en desarrollo requieren defender decisiones escritas, comparar alternativas, calcular indicadores y entregar artefactos. Un simple «terminé» no da la aprobación. Para los nuevos borradores falta integrar el bloqueo transaccional real de progreso."},
  {q:"¿Qué cursos están disponibles hoy y cuáles son próximos?",a:"Consulta Programas para las rutas publicadas y el Roadmap para las funciones en preparación. Los doce currículos nuevos (incluido GRC avanzado) están en borrador académico y no figuran como acreditaciones o compras disponibles."},
  {q:"¿Los cursos de GRC otorgan certificación ISO?",a:"No. Garciloga proporciona formación aplicada y proyectos sintéticos. La certificación ISO oficial requiere evaluaciones de conformidad según las reglas del organismo pertinente. La ruta GRC avanzada todavía está en elaboración."},
  {q:"¿Qué datos puede ver un supervisor?",a:"Solo los de personas y equipos dentro de sus permisos; el acceso se controla por organización y función. No debe poder consultar información de otras compañías o resultados no autorizados."},
  {q:"¿Puedo personalizar la formación sin reducir requisitos mínimos?",a:"El planificador en desarrollo permitirá seleccionar énfasis por competencia y fecha, pero no saltarse controles de seguridad, proyectos obligatorios ni la revisión humana. Los planes contratados conservan sus derechos."},
  {q:"¿Puedo asignar pruebas de selección para candidatos?",a:"El módulo de evaluación de candidatos es borrador y estará sujeto a consentimiento, acceso limitado, accesibilidad y revisión humana. Una nota no autorizará contratar, descartar o sancionar automáticamente."},
  {q:"¿Qué pasa si un empleado pertenece a varias empresas?",a:"Cada asignación, proyecto y evidencia corporativa se delimita por organización. La persona conserva su identidad, pero los managers de una empresa no reciben acceso a otras por compartir al colaborador."},
  {q:"¿Qué pasa si una actividad sale mal?",a:"El responsable recibe retroalimentación sobre el caso y ofrece una nueva práctica o proyecto. Errores críticos se conservan como antecedentes de revisión hasta su remediación; no se presentan como rasgo de personalidad."},
  {q:"¿Cuándo habrá aplicaciones Android e iOS?",a:"Ambas están registradas como Coming soon. No existe fecha de lanzamiento ni aplicación publicada en tiendas. La web puede utilizarse desde navegadores móviles compatibles."},
  {q:"¿Cómo justifico el valor a mi empresa?",a:"Documenta el punto de partida, unidades asignadas y completadas con evidencia, mejoras de competencia demostrada y seguimiento. No confundas resultados de simulación con productividad real o promesas de retorno financiero."},
  {q:"¿Cómo gestiono dudas o incidencias?",a:"Usa el Centro de ayuda, abre un ticket con contexto y pasos para reproducir el problema, y evita adjuntar credenciales, documentos de clientes o datos sensibles."}
 ]
} as const;
