import type {CompetencyKey} from './competency-matrix';
/** Original synthetic curriculum. Sources are guidance, not a legal certification. */
export const GRC_SOURCES=['https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20','https://www.theiia.org/en/resources/statements-of-position'];
export const GRC_FOCUS:{title:string;concept:string;task:string;accept:string;unsafe:string;competencies:CompetencyKey[]}[]=[
 {title:'Gobierno y responsabilidad',concept:'Gobernar exige definir objetivos, autoridad y supervisión. Quien opera un proceso conserva su responsabilidad; una revisión independiente no sustituye la decisión del responsable. Separa operación, supervisión del riesgo y aseguramiento.',task:'Para Faro, construye una matriz de quién prepara, autoriza y revisa la exportación. Registra un conflicto de interés y cómo preservar una revisión independiente.',accept:'Responsables, autoridad y separación de funciones documentados',unsafe:'Permitir que quien ejecuta apruebe su propia excepción',competencies:['planning','collaboration','documentation']},
 {title:'Registro y evaluación de riesgos',concept:'Un riesgo relaciona una causa, un evento incierto y su efecto sobre un objetivo. Distingue riesgo inherente de riesgo residual después de controles. La escala de probabilidad e impacto necesita criterios; su producto es una ayuda de priorización, no una certeza estadística.',task:'Crea tres riesgos sintéticos de Faro: acceso indebido, reporte duplicado y retraso. Define escala de uno a tres, justifica impacto y probabilidad, identifica dueño y conserva incertidumbre.',accept:'Matriz con criterios, causa, efecto, dueño y riesgo residual',unsafe:'Presentar un puntaje de riesgo como probabilidad medida',competencies:['diagnosis','data','prioritization']},
 {title:'Diseño y prueba de controles',concept:'Un control necesita objetivo, responsable, frecuencia y evidencia. Distingue prevenir, detectar y corregir. La existencia de una política no demuestra que el control operó; comprueba diseño y ejecución por separado.',task:'Diseña un control de permisos para el CSV de Faro. Prueba un usuario autorizado y otro denegado con datos ficticios. Documenta una excepción y qué evidencia demostraría su resolución.',accept:'Control con prueba positiva, negativa y evidencia de ejecución',unsafe:'Dar por efectivo un control porque existe un documento',competencies:['technical','documentation','diagnosis']},
 {title:'Políticas y obligaciones',concept:'Relaciona cada requisito aplicable con su fuente, responsable, control y evidencia. Distingue ley, contrato y política interna. Una lista de comprobación no determina por sí sola el cumplimiento legal; los requisitos específicos requieren validación competente.',task:'Usa una política ficticia de Faro: exportar solo datos mínimos autorizados y registrar excepciones. Crea un registro de obligaciones con fuente, vigencia y responsable; marca lo que necesita consulta especializada.',accept:'Obligaciones trazables sin inventar requisitos legales',unsafe:'Afirmar cumplimiento legal sin validar alcance y requisitos',competencies:['documentation','communication','planning']},
 {title:'Auditoría y evidencias',concept:'Una revisión define alcance, criterio, muestra y limitaciones. La evidencia debe permitir reconstruir lo ocurrido; conserva origen y fecha. Un hallazgo conecta condición, criterio, causa y efecto. Una muestra sin fallos no prueba que toda la población está libre de errores.',task:'Revisa tres exportaciones sintéticas de Faro, una sin aprobación. Prepara un hallazgo con evidencia redactada, límite de la muestra, recomendación y respuesta del responsable.',accept:'Hallazgo sustentado con criterio, muestra y limitaciones',unsafe:'Generalizar ausencia de fallos a toda la población',competencies:['data','diagnosis','communication']},
 {title:'Seguimiento y cierre de hallazgos',concept:'Una acción correctiva conserva dueño, plazo, criterio de cierre y verificación. Aceptar riesgo residual exige autoridad explícita. La fecha prometida o la declaración del responsable no sustituyen evidencia de corrección.',task:'Prioriza los hallazgos de Faro, crea un plan de tratamiento y prueba el control corregido. Presenta al comité ficticio decisiones pendientes, retrasos y riesgos aceptados con su autoridad.',accept:'Tratamiento y cierre comprobados con dueño y autoridad',unsafe:'Cerrar un hallazgo únicamente por promesa de corrección',competencies:['negotiation','deescalation','collaboration']},
];
