/** Original introductory curriculum, informed by O*NET occupational tasks.
 * Role in this learning path never grants organization permissions.
 */
export const LEADERSHIP_LEARNING = [
  { role: 'Colaborador', focus: 'Cumplir un proceso con criterio', lesson: 'Antes de actuar, identifica el objetivo, las entradas, el responsable y qué evidencia demuestra que terminaste. Escala un bloqueo con hechos y una petición concreta.', scenario: 'Tu entrega depende de un dato que no ha llegado y el plazo vence hoy.', decision: 'Comunica el impacto, registra lo que falta y propone una alternativa con un momento de revisión. No marques la tarea como terminada.', exercise: 'Escribe un handoff con objetivo, evidencia, bloqueo, responsable y siguiente actualización.', rubric: ['Objetivo verificable', 'Evidencia sin datos sensibles', 'Responsable y siguiente paso'] },
  { role: 'Supervisor', focus: 'Dar seguimiento a reportes directos', lesson: 'Acordar una tarea incluye resultado, plazo, autonomía y puntos de revisión. El seguimiento ayuda a resolver obstáculos; una baja calificación no sustituye una conversación de coaching.', scenario: 'Un reporte directo acumula pendientes mientras otro ya completó su trabajo.', decision: 'Revisa carga y bloqueos, acuerda apoyo y seguimiento. Redistribuye con capacidad y prioridades conocidas, sin exponer resultados individuales fuera de su alcance.', exercise: 'Prepara una conversación de coaching: observación, pregunta abierta, acuerdo y comprobación.', rubric: ['Hechos y preguntas sin etiquetas personales', 'Acuerdo con responsable', 'Seguimiento medible'] },
  { role: 'Gerente', focus: 'Coordinar una rama y sus procesos', lesson: 'Gestionar una rama exige distinguir resultados, capacidad y riesgos entre equipos. Compara indicadores con la misma definición y revisa la causa antes de cambiar un proceso.', scenario: 'Dos supervisores reportan avance distinto porque cuentan actividades diferentes.', decision: 'Alinea el denominador, revisa evidencia y acuerda una definición común. No compares porcentajes incompatibles ni infieras competencia a partir de afinidad.', exercise: 'Define un indicador con objetivo, fórmula, fuente, frecuencia y responsable; decide qué harías si baja.', rubric: ['Métrica comparable y fuente explícita', 'Hipótesis separada de hechos', 'Decisión reversible y revisión'] },
  { role: 'Directivo', focus: 'Priorizar, gobernar y desarrollar líderes', lesson: 'Una decisión de dirección conecta objetivos, recursos, riesgos y responsabilidad. Evalúa alternativas, fija señales para revisar la decisión y delega con límites claros.', scenario: 'Solo puedes financiar una de dos iniciativas: automatización o formación de supervisores.', decision: 'Contrasta impacto esperado, costo, riesgos y evidencia disponible. Define un piloto y un criterio de continuidad antes de comprometer todos los recursos.', exercise: 'Redacta una decisión de una página con dos alternativas, supuestos, riesgos, responsable y criterio de revisión.', rubric: ['Alternativas y tradeoffs explícitos', 'Supuestos y riesgos identificados', 'Responsable y criterio de continuidad'] },
] as const;
export const LEADERSHIP_SOURCE = 'https://www.onetonline.org/link/summary/11-1021.00';
