import {competencyProfile,type CompetencyEvidence,type JobProfile,COMPETENCIES} from './competency-matrix.ts';
import {csvCell} from './team-report.ts';
export function monthlyBounds(month:string){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw Error('INVALID_MONTH');const [y,m]=month.split('-').map(Number);if(y<2020||y>2100)throw Error('INVALID_MONTH');return {start:new Date(Date.UTC(y,m-1,1)),end:new Date(Date.UTC(y,m,1)),previous:new Date(Date.UTC(y,m-2,1))};}
export function monthlyReport(month:string,people:{user_id:string;display_name:string;profile:JobProfile|null}[],history:CompetencyEvidence[],assignments:{user_id:string;activity_key:string;due_at:string|null}[]){
 const {start,end}=monthlyBounds(month);const cutoff=new Date(Math.min(Date.now(),end.getTime()-1));
 const rows=people.map(p=>{const h=history.filter(e=>e.user_id===p.user_id&&Date.parse(e.observed_at)<=cutoff.getTime());const current=competencyProfile(h,p.profile,cutoff),previous=competencyProfile(h.filter(e=>Date.parse(e.observed_at)<start.getTime()),p.profile,new Date(start.getTime()-1));return {...p,current,previous,completed:new Set(h.filter(e=>['manager','admin'].includes(e.review_source)&&!e.critical_errors.length&&Date.parse(e.observed_at)>=start.getTime()).map(e=>e.activity_key)).size,overdue:assignments.filter(a=>a.user_id===p.user_id&&a.due_at&&Date.parse(a.due_at)<cutoff.getTime()&&!h.some(e=>e.activity_key===a.activity_key||a.activity_key==='route_unit:'+e.activity_key)).length};});
 const competencies=Object.keys(COMPETENCIES).map(key=>{const eligible=rows.flatMap(r=>r.current.competencies.filter(c=>c.key===key&&c.count>=3));const old=rows.flatMap(r=>r.previous.competencies.filter(c=>c.key===key&&c.count>=3));const average=(a:typeof eligible)=>a.length?Math.round(a.reduce((s,c)=>s+c.level,0)/a.length*100)/100:null;const now=average(eligible),before=average(old);return {key:key as keyof typeof COMPETENCIES,name:COMPETENCIES[key as keyof typeof COMPETENCIES],average:now,change:now!==null&&before!==null?Math.round((now-before)*100)/100:null};});
 const rated=competencies.filter(c=>c.average!==null).sort((a,b)=>b.average!-a.average!);return {month,rows,competencies,strengths:rated.slice(0,3),gaps:[...rated].reverse().slice(0,3),completed:rows.reduce((s,r)=>s+r.completed,0),overdue:rows.reduce((s,r)=>s+r.overdue,0)};
}
export function monthlyCsv(report:ReturnType<typeof monthlyReport>,t:(s:string)=>string){const data:unknown[][]=[[t('Persona'),t('Competencias'),t('Nivel actual'),t('Cambio mensual'),t('Actividades completadas'),t('Asignaciones vencidas')]];for(const r of report.rows)for(const c of r.current.competencies){const old=r.previous.competencies.find(o=>o.key===c.key);data.push([r.display_name,t(c.name),c.count>=3?c.level:t('Sin evidencia suficiente'),c.count>=3&&old&&old.count>=3?c.level-old.level:'',r.completed,r.overdue]);}return '\ufeff'+data.map(row=>row.map(csvCell).join(',')).join('\r\n')+'\r\n';}

/** One latest completion per activity, canonicalizing legacy numeric assignment keys. */
export function monthlyCompletions(userId:string,history:CompetencyEvidence[],legacy:{user_id:string;activity_key:string;completed:boolean;observed_at:string}[],assignments:{user_id:string;activity_key:string;due_at:string|null}[],catalog:{id:number;content_key:string}[],start:number,cutoff:number){
 const canonical=(key:string)=>key.startsWith('route_unit:')?(catalog.find(a=>String(a.id)===key.slice(11))?.content_key??key):key;
 const latest=new Map<string,{at:number;completed:boolean}>();
 const add=(key:string,observed:string,completed:boolean)=>{const at=Date.parse(observed),k=canonical(key);if(at<=cutoff&&at>=(latest.get(k)?.at??-Infinity))latest.set(k,{at,completed});};
 for(const e of history.filter(e=>e.user_id===userId&&['manager','admin'].includes(e.review_source))){const scores=Object.values(e.competency_scores);add(e.activity_key,e.observed_at,!e.critical_errors.length&&scores.length>0&&scores.every(score=>score>=3));}
 for(const e of legacy.filter(e=>e.user_id===userId))add(e.activity_key,e.observed_at,e.completed);
 return {completed:[...latest.values()].filter(e=>e.completed&&e.at>=start).length,overdue:assignments.filter(a=>a.user_id===userId&&a.due_at&&Date.parse(a.due_at)<cutoff&&!latest.get(canonical(a.activity_key))?.completed).length};
}
