import {enrichTrainingActivity} from './workplace-practice-content.ts';
import type {TrainingActivity,Decision} from './role-training-content.ts';
import type {CompetencyKey} from './competency-matrix.ts';
import type {CareerPositionKey} from './career-guidance.ts';
import {ROLE_WORKFLOWS} from './career-role-workflows.ts';
import {LEARNING_GUIDES} from './career-learning-content.ts';
import {CS_CASE_STAGES} from './customer-success-practical-case.ts';

type Focus={title:string;concept:string;task:string;accept:string;unsafe:string;competencies:CompetencyKey[]};
type Route={key:string;title:string;family:CareerPositionKey;focus:Focus[]};
const focus=(title:string,concept:string,task:string,accept:string,unsafe:string,competencies:CompetencyKey[]):Focus=>({title,concept,task,accept,unsafe,competencies});
/** New curricula reuse the sixteen position profiles and the canonical Faro account. */
export const PROFESSIONAL_ROUTES:Route[]=[
 {key:'operations',title:'Operaciones',family:'project_manager',focus:[
  focus('Proceso y trabajo en curso','Un proceso conecta entrada, responsable, decisión y salida. El volumen entrante no equivale a capacidad disponible; cuenta tareas abiertas y sus dependencias antes de aceptar otro compromiso.','Traza la preparación del reporte de Faro desde la solicitud hasta su verificación; identifica dos esperas y una decisión sin responsable.','Mapa con entradas, salidas, esperas y responsables verificables','Aumentar compromisos sin revisar trabajo abierto',['documentation','prioritization']),
  focus('Capacidad y compromisos','Estima esfuerzo con rangos y explicita variabilidad. Una cola sin límite oculta retrasos. Negocia alcance o fecha cuando demanda y capacidad no coinciden.','Propón una semana de trabajo usando tareas de Faro. Declara estimaciones como supuestos y muestra qué se desplaza ante el bloqueo de exportación.','Capacidad y demanda comparables, con decisiones sobre alcance y fecha','Presentar toda la demanda como compromiso confirmado',['prioritization','planning']),
  focus('Métricas del flujo','Tiempo total, tiempo trabajando y espera son medidas distintas. Define inicio, fin, población y ventana antes de calcular. Un promedio puede ocultar casos extremos.','Usa las semanas canónicas de Faro para calcular cambio del tiempo de preparación; señala qué datos faltan para atribuir la causa a tu proceso.','Fórmula reproducible y limitaciones del dato','Atribuir causalidad a una sola observación',['data','diagnosis']),
  focus('Controles y escalaciones','Un control requiere evidencia de ejecución y un responsable capaz de detener o corregir el proceso. Una excepción aprobada no elimina el registro de su riesgo.','Diseña un control para entregar un CSV permitido: acceso, contenido mínimo, aceptación y condición de escalación.','Control verificable, excepción explícita y autoridad identificada','Considerar autorización implícita cualquier petición urgente',['technical','documentation','collaboration']),
  focus('Mejora y continuidad','Propón una mejora acotada y reversible. Define línea base, resultado esperado y señal para abandonar el cambio. La continuidad incluye sustitución del responsable y recuperación.','Prepara un experimento de reducción de espera y un traspaso para ausencia del coordinador; separa los resultados simulados de los hechos de Faro.','Experimento con línea base, verificación y reversión','Aplicar un cambio global sin verificar ni preparar continuidad',['planning','collaboration','data']),
 ]},
 {key:'quality',title:'QA y calidad',family:'developer',focus:[
  focus('Criterios y riesgo de prueba','Un criterio describe comportamiento observable. Prioriza pruebas por impacto y probabilidad; una lista extensa de pruebas no demuestra cobertura de los riesgos principales.','Escribe criterios de aceptación para la exportación de Faro: usuario permitido, acceso denegado y datos incompletos.','Resultado esperado observable por escenario','Aceptar criterios que solo dicen funciona bien',['diagnosis','documentation','technical']),
  focus('Casos y datos de prueba','Distingue particiones válidas e inválidas y prueba límites. Usa datos sintéticos; no necesitas copiar registros reales para probar una regla.','Diseña casos de exportación con cero filas, duplicados, permiso insuficiente y un caso correcto; incluye preparación y limpieza.','Entradas, precondiciones y resultados reproducibles','Probar únicamente el ejemplo exitoso',['technical','data','documentation']),
  focus('Defectos reproducibles','Un reporte de defecto contiene pasos, ambiente, resultado esperado y observado, alcance y evidencia redactada. Severidad y prioridad requieren argumentos diferentes.','Redacta el defecto 401 de Faro sin tokens, compara un usuario exitoso y explica impacto frente a prioridad comercial.','Reproducción mínima con evidencia y alcance','Asignar prioridad por el tono de quien reporta',['diagnosis','communication']),
  focus('Automatización y regresión','Una prueba automática debe fallar ante la regresión que pretende detectar. Evita depender de esperas arbitrarias y datos compartidos entre pruebas. Conserva pruebas manuales cuando la evaluación requiere juicio.','Escribe pseudocódigo de una prueba de exportación que compruebe acceso, resultado y limpieza; agrega el fallo deliberado que confirma que la prueba detecta el defecto.','Aserciones observables, aislamiento y prueba de sensibilidad','Considerar aprobada una prueba que nunca puede fallar',['technical','documentation']),
  focus('Calidad de entrega','La decisión de liberar relaciona defectos abiertos, riesgos aceptados, evidencia de pruebas y reversión. La ausencia de defectos reportados no garantiza ausencia de fallos.','Prepara una recomendación de liberación con riesgos residuales y criterio de rollback para la exportación de Faro.','Riesgos explícitos y aprobación de la autoridad correspondiente','Afirmar que cero reportes garantiza cero defectos',['planning','collaboration','communication']),
 ]},
 {key:'data_bi',title:'Datos y Business Intelligence',family:'developer',focus:[
  focus('Pregunta y definición de métricas','Antes de construir un gráfico, define la decisión que debe apoyar. Una métrica especifica numerador, denominador, unidad, población y ventana.','Formula la pregunta de valor de Faro y un diccionario de adopción y tiempo de preparación con límites de interpretación.','Definiciones que otra persona puede reproducir','Elegir un gráfico antes de definir la pregunta',['data','diagnosis']),
  focus('Calidad y preparación','Comprueba faltantes, duplicados, tipos y claves antes de agregar. Documenta reglas de limpieza y conserva su efecto sobre el resultado. Un faltante no equivale automáticamente a cero.','Prepara una tabla sintética complementaria, rotulada como simulación, con un duplicado y un faltante; muestra los resultados antes y después de cada regla.','Reglas trazables y diferencias cuantificadas','Sustituir faltantes por cero sin explicar su significado',['data','documentation','technical']),
  focus('Consultas y granularidad','Define qué representa cada fila. Una unión puede multiplicar registros y alterar el denominador. Agrega por la unidad de análisis correcta y comprueba el resultado con un caso calculado a mano.','Escribe SQL de solo lectura sobre las semanas canónicas de Faro y verifica manualmente la reducción de 5 a 3 días; explica cómo evitarías duplicar semanas al unir datos.','Granularidad definida y resultado comprobado','Confiar en la consulta solo porque ejecuta sin error',['technical','data','diagnosis']),
  focus('Visualización y comunicación','Elige escalas y etiquetas que permitan comparar sin inducir una conclusión falsa. Separa observación, explicación hipotética y recomendación. Conserva el dato y fórmula detrás del gráfico.','Prepara un gráfico del tiempo de preparación y una nota ejecutiva que declare muestra y meta pendiente.','Gráfico con unidades, fuente y límites de inferencia','Presentar correlación como explicación causal',['data','communication']),
  focus('Decisión y mantenimiento','Un tablero necesita responsable, frecuencia, validación y proceso para cambiar definiciones. Evalúa si la información modifica una decisión, no solo si genera visitas.','Diseña el contrato de actualización del tablero de Faro: fuentes, responsable, señal de dato obsoleto, criterio de aceptación y decisión que facilita.','Actualización verificable y decisión vinculada al dato','Medir valor del tablero únicamente por visitas',['planning','documentation','collaboration']),
 ]},
 {key:'product',title:'Producto',family:'project_manager',focus:[
  focus('Problema y descubrimiento','La función solicitada es una propuesta de solución. Investiga tarea, contexto y resultado buscado. Una entrevista aporta señales; no constituye por sí sola validación de toda la población.','Convierte la solicitud de exportación de Faro en una hipótesis de problema, preguntas y una prueba que pueda refutarla.','Problema delimitado y evidencia que puede cambiar la hipótesis','Tomar la primera solución sugerida como requisito validado',['diagnosis','communication']),
  focus('Priorización y alcance','Compara valor esperado, esfuerzo, riesgo y dependencias usando supuestos explícitos. Una puntuación organiza discusión; no reemplaza criterio ni autoridad.','Compara corregir exportación, capacitar y cambiar reporte. Declara supuestos y qué evidencia cambiaría tu prioridad.','Prioridad explicable y supuestos revisables','Presentar un puntaje como certeza de valor',['prioritization','data','planning']),
  focus('Experimentos y aprendizaje','Define hipótesis, resultado medible, población, ventana y regla de decisión antes de observar resultados. Controla el daño y conserva una opción de reversión.','Diseña un experimento hipotético de onboarding de Faro; no modifiques sus hechos canónicos ni presentes el resultado esperado como observado.','Hipótesis refutable y regla previa de decisión','Cambiar la meta después de conocer el resultado',['data','diagnosis','planning']),
  focus('Entrega y aceptación','La entrega requiere una definición compartida de terminado y pruebas de comportamiento. Distingue lanzamiento de adopción; una función disponible puede no resolver el problema.','Prepara criterios de aceptación y un handoff a soporte y CS para una mejora hipotética de exportación.','Criterios observables y coordinación del seguimiento','Cerrar el problema por publicar una función',['technical','documentation','collaboration']),
  focus('Resultados y ciclo de feedback','Mide el resultado que motivó la inversión y los efectos no deseados. Cierra el ciclo de feedback sin prometer fechas o funcionalidades no aprobadas.','Escribe una evaluación de valor del reporte de Faro con resultado observado, brecha, incertidumbre y siguiente decisión.','Resultado verificado y respuesta al feedback','Confundir uso de una función con valor demostrado',['data','communication','collaboration']),
 ]},
 {key:'solutions',title:'Soluciones e integraciones',family:'pre_sales',focus:[
  focus('Descubrimiento técnico y alcance','Identifica flujo, restricciones, datos, responsables y criterios de éxito antes de proponer arquitectura. Diferencia capacidad actual y propuesta pendiente de validación.','Delimita integración y alternativa CSV de Faro; registra qué debe comprobar ingeniería antes de prometer la solución.','Alcance confirmado y capacidades por validar','Prometer una integración sin verificar el encaje',['diagnosis','technical','communication']),
  focus('Contrato de datos y acceso','Un contrato define campos, tipos, unidades, versiones y errores. Aplica acceso mínimo; una identidad autenticada no está autorizada para todos los recursos.','Diseña un contrato ficticio de lectura del reporte de Faro con permisos mínimos y errores esperados; usa identificadores sintéticos, nunca credenciales.','Contrato verificable y autorización por recurso','Compartir un token de administrador para acelerar la prueba',['technical','documentation']),
  focus('Fiabilidad y reintentos','Un reintento puede duplicar efectos. Define identidad de solicitud, límites, observabilidad y comportamiento ante respuesta incierta. No reintentes de forma ilimitada.','Especifica un envío ficticio de reporte con solicitud idempotente, tiempo límite, error transitorio y conciliación después de una respuesta incierta.','Efectos controlados y conciliación explícita','Repetir todas las solicitudes sin límite ni identidad',['technical','planning','diagnosis']),
  focus('Validación y despliegue','Valida casos normales, denegados y fallidos en un entorno separado. Documenta aceptación, restricciones y reversión; una demostración no equivale a una integración lista para operar.','Prepara la matriz de validación y el plan de despliegue de una integración hipotética para Faro sin ejecutar cambios en un cliente real.','Pruebas y aceptación separadas de la demostración','Usar el éxito de una demo como garantía operativa',['technical','collaboration','documentation']),
  focus('Operación y traspaso','Una integración necesita señales de fallo, dueño de respuesta y límites de soporte. Entrega información suficiente para investigar sin exponer secretos ni duplicar la fuente canónica.','Escribe un runbook del fallo de exportación y handoff a soporte, con señales, límites de autoridad y criterio de recuperación.','Runbook ejecutable y recuperación comprobable','Dar por cerrado el caso solo porque bajan los errores',['planning','documentation','collaboration']),
 ]},
 {key:'enablement',title:'Enablement y capacitación',family:'onboarding',focus:[
  focus('Necesidad y objetivo de aprendizaje','Un objetivo describe qué podrá hacer la persona y con qué criterio. Distingue una falta de conocimiento de falta de acceso, herramienta o capacidad.','Diagnostica la barrera de reporte de Faro y escribe un objetivo observable que no confunda capacitación con reparación técnica.','Conducta observable y diagnóstico de la barrera','Prescribir capacitación para cualquier fallo de acceso',['diagnosis','communication']),
  focus('Diseño de práctica','Relaciona explicación, decisión, práctica y criterio de evaluación. Ajusta apoyo según evidencia y retíralo progresivamente. Completar un video no demuestra aplicación.','Diseña una lección breve, tres decisiones y un entregable para preparar el reporte permitido de Faro.','Práctica alineada al objetivo y evidencia de aplicación','Usar asistencia al curso como única evidencia',['planning','documentation','technical']),
  focus('Facilitación y feedback','El feedback señala conducta observada, criterio, efecto y siguiente intento. Comprueba comprensión mediante ejecución y preguntas; evita corregir solo estilo sin atender el objetivo.','Escribe un diálogo de capacitación con dos errores simulados y feedback que permita corregirlos sin hacer el trabajo por la persona.','Feedback específico y nuevo intento verificable','Resolver toda la práctica en lugar del aprendiz',['communication','collaboration']),
  focus('Evaluación y transferencia','Una evaluación compara evidencia con rúbrica compartida. Separa satisfacción de competencia y recoge nueva evidencia después de retirar apoyo. Una nota alta aislada no demuestra sostenimiento.','Diseña una evaluación del reporte de Faro y una reevaluación a 30 días con nueva restricción, sin convertir NPS en dominio.','Rúbrica, autonomía y reevaluación diferenciadas','Convertir satisfacción con el curso en nivel de competencia',['data','diagnosis','documentation']),
  focus('Operación del programa','Mantén dueño, versión y revisión del material. Mide cobertura, aplicación y barreras; documenta qué cambia y por qué. Localizar exige conservar intención, reglas y ejemplos.','Prepara un plan de mantenimiento del material de Faro y una comprobación de equivalencia de una decisión en dos idiomas.','Versiones y equivalencia de significado verificables','Traducir palabras sin revisar reglas ni ejemplos',['planning','collaboration','documentation']),
 ]},
 {key:'leadership',title:'Liderazgo',family:'manager_team_lead',focus:[
  focus('Dirección y prioridades','Define resultado, restricciones y autoridad para decidir. Explica el coste de cambiar prioridades y protege capacidad. La responsabilidad del líder incluye reconocer incertidumbre.','Propón prioridades para el equipo que atiende Faro; explica qué se aplaza y quién puede aceptar el riesgo.','Objetivo y decisiones con responsables y límites','Comprometer todas las tareas sin revisar capacidad',['planning','prioritization','communication']),
  focus('Delegación y desarrollo','Delegar exige resultado, margen de decisión, recursos y comprobación. La práctica simulada permite desarrollar habilidades; no reemplaza evidencia del desempeño laboral ni autoriza rankings.','Diseña una delegación del QBR de Faro con apoyo gradual, rúbrica y revisión; distingue aprendizaje de evaluación laboral.','Autonomía acordada y revisión con evidencia','Delegar responsabilidad sin autoridad ni recursos',['collaboration','planning','communication']),
  focus('Coaching y conversaciones','Pregunta por evidencia, alternativas y aprendizaje antes de prescribir. Una conversación difícil describe conducta y efecto sin atribuir motivos. Acuerda siguiente paso y verifica comprensión.','Escribe un 1:1 de ocho turnos sobre un compromiso incumplido en la simulación de Faro; termina con un intento verificable.','Preguntas sustentadas y compromiso de aprendizaje','Atribuir mala intención sin investigar lo ocurrido',['communication','deescalation','diagnosis']),
  focus('Decisiones y conflicto','Explicita opciones, intereses, límites y autoridad. Busca el desacuerdo sobre supuestos y documenta la decisión, incluida la alternativa descartada. No resuelvas presión ampliando tu autorización.','Facilita una decisión entre ventas, soporte y CS sobre renovación de Faro; no concedas condiciones comerciales reales.','Intereses, alternativas y aprobación correspondiente','Conceder excepciones no autorizadas para cerrar el conflicto',['negotiation','collaboration','planning']),
  focus('Sistema de seguimiento','Revisa resultados, riesgos y capacidad sin convertir indicadores en fines. Da continuidad a decisiones, documenta correcciones y verifica el efecto de una intervención sobre el equipo.','Prepara una revisión de gestión de Faro con tres preguntas de aprendizaje, riesgos pendientes y criterios de seguimiento a 30 días.','Seguimiento verificable y límites de la medición','Usar una nota de simulación para clasificar desempeño laboral',['data','planning','documentation']),
 ]},
];
const progression=[
 {name:'Fundamentos',constraint:'Trabaja con el ejemplo y marca las afirmaciones que son hechos, supuestos o decisiones pendientes.',hours:4},
 {name:'Operación',constraint:'Prepara una entrega operable por otra persona, con responsable, fecha, evidencia y condición de aceptación.',hours:6},
 {name:'Dominio',constraint:'Resuelve una variante hipotética donde se reduce a la mitad el tiempo disponible; compara dos alternativas y sus riesgos.',hours:7},
 {name:'Especialista',constraint:'Diseña una revisión independiente del trabajo y responde a una nueva restricción: cambia el sponsor y falta una fuente de datos.',hours:7},
];
const rubric=[
 '1 · Reconoce el concepto y señala qué evidencia falta.',
 '2 · Aplica con apoyo y corrige omisiones indicadas.',
 '3 · Aplica sin ayuda: entrega trazable, decisión justificada y verificación comprobable.',
 '4 · Contrasta alternativas y responde a otra restricción; sostener competencia exige reevaluación y capstone.',
];
const template='Objetivo:\nDatos canónicos utilizados:\nSupuestos de la variante simulada:\nAlternativas y decisión:\nEntregable:\nResponsable y fecha:\nCriterio de aceptación:\nRiesgos y datos pendientes:';
function decisions(f:Focus,level:number):Decision[]{
 return [
  {prompt:`En ${f.title.toLowerCase()}, ¿qué criterio debe cumplir tu entrega?`,options:[f.unsafe,f.accept],correct:1,feedback:f.concept},
  {prompt:`Tu entrega de ${f.title.toLowerCase()} incluye un resultado que no aparece en Faro. ¿Cómo lo registras?`,options:['Como supuesto explícito de la variante y propuesta de medición','Como resultado observado de la cuenta'],correct:0,feedback:'La simulación permite crear variantes, pero sus supuestos no modifican los hechos canónicos de Cuenta Faro.'},
  {prompt:`Para ${f.title.toLowerCase()} ${level>1?'la nueva restricción cambia':'aún falta'} una condición de aceptación. ¿Qué haces?`,options:['Confirmo éxito para conservar el compromiso','Registro el límite, reviso la decisión y acuerdo cómo verificar'],correct:1,feedback:'La verificación debe responder al criterio de aceptación. Una fecha o una opinión no sustituyen evidencia.'},
 ];
}
export const PROFESSIONAL_UNITS:TrainingActivity[]=PROFESSIONAL_ROUTES.flatMap(route=>progression.flatMap((p,level)=>route.focus.map((f,index)=>({
 key:`${route.key}-unit-${level+1}-${index+1}`,route:route.key,title:`${p.name} · ${f.title}`,level:level+1,kind:'deliverable' as const,hours:p.hours,
 competencies:f.competencies,lesson:`${f.concept} ${LEARNING_GUIDES[route.family].concept} ${p.constraint}`,
 task:`${f.task} ${p.constraint} Reutiliza Cuenta Faro; etiqueta cualquier dato adicional como supuesto de esta práctica.`,
 template,example:`Criterio de calidad: ${f.accept}. Flujo de referencia: ${ROLE_WORKFLOWS[route.family].process}. Conserva la fuente canónica y declara lo que aún no puedes verificar.`,
 decisions:decisions(f,level+1),rubric,sourceUrls:[ROLE_WORKFLOWS[route.family].source],optionalPractice:[LEARNING_GUIDES[route.family].twist],
}))));
export const PROFESSIONAL_EXTRAS:TrainingActivity[]=PROFESSIONAL_ROUTES.flatMap(route=>{
 const base=(key:string,title:string,level:number,kind:TrainingActivity['kind'],hours:number,task:string,competencies:CompetencyKey[]=route.focus[0].competencies):TrainingActivity=>({
  key:`${route.key}-${key}`,route:route.key,title,level,kind,hours,task,competencies,lesson:'Integra las decisiones y entregables revisados del nivel. Conserva evidencia y riesgos, y distingue propuesta de resultado verificado.',template,example:ROLE_WORKFLOWS[route.family].quality,decisions:[],rubric,sourceUrls:[ROLE_WORKFLOWS[route.family].source],optionalPractice:[],
 });
 return [
  ...CS_CASE_STAGES.map((stage,i)=>({...base(`episode-${stage.key}`,`Cuenta Faro · ${stage.title}`,Math.floor(i/2)+1,'deliverable',2,`Reutiliza el episodio canónico y aplica el enfoque de ${route.title.toLowerCase()}: ${route.focus[i%5].task}`,route.focus[i%5].competencies),sourceStage:stage.key,example:stage.example})),
  ...progression.map((p,i)=>base(`roleplay-${i+1}`,`Role-play · ${p.name}`,i+1,'deliverable',2,`Escribe ocho turnos con quien recibe tu entrega de ${route.focus[i].title.toLowerCase()}. Incluye una objeción y una pregunta sobre evidencia. ${p.constraint}`,['communication','collaboration'])),
  ...[1,2,3].map((level,i)=>base(`project-${i+1}`,`Proyecto · ${progression[level].name}`,level+1,'project',6,`Integra las cinco entregas del nivel ${level+1} de ${route.title}. Presenta decisiones, fuentes, alternativas, riesgos y handoff. La revisión humana usa la misma rúbrica; tu autoevaluación no aprueba el proyecto.`,['documentation','planning','collaboration'])),
  base('capstone',`Capstone · ${route.title} y Cuenta Faro`,4,'capstone',10,`Presenta un expediente de los ocho episodios de Faro desde ${route.title.toLowerCase()}, integrando decisiones y entregas de los cuatro niveles. Defiende dos alternativas, un riesgo no resuelto y tu propuesta de verificación. Enlaza evidencia revisada de las competencias de peso Alto de tu perfil del puesto.`,['diagnosis','planning','communication']),
  ...progression.map((p,i)=>({...base(`exam-${i+1}`,`Examen · ${p.name}`,i+1,'exercise',2,'Resuelve cinco decisiones del nivel. Cuatro respuestas correctas acreditan reconocimiento formativo, no autonomía.'),decisions:PROFESSIONAL_UNITS.filter(u=>u.route===route.key&&u.level===i+1).map(u=>u.decisions[0])})),
  ...progression.map((p,i)=>({...base(`reevaluation-${i+1}`,`Reevaluación a 30 días · ${p.name}`,i+1,'deliverable',2,`Retoma tu entrega revisada de ${route.focus[i].title.toLowerCase()} a los 30 días. Cambia una restricción hipotética y muestra qué decisión mantienes, qué cambia y cómo la verificas.`,route.focus[i].competencies),reevaluationOf:`${route.key}-unit-${i+1}-${i+1}`})),
 ];
});
export const PROFESSIONAL_ACTIVITIES=[...PROFESSIONAL_UNITS,...PROFESSIONAL_EXTRAS].map(enrichTrainingActivity);

