import {enrichTrainingActivity} from './workplace-practice-content.ts';
import {PROFESSIONAL_ACTIVITIES} from './professional-route-content.ts';
import {CS_CASE_STAGES,CS_CASE_METRICS} from './customer-success-practical-case.ts';
import {CS_LESSONS,CS_CAPSTONE_RUBRIC} from './customer-success-course.ts';
import type {CompetencyKey,EvidenceKind} from './competency-matrix.ts';

export const ROLE_TRAINING_VERSION='role-practice-v1';
export const TRAINING_NOTICE='Esto mide práctica simulada, no desempeño laboral real. No hay ranking de personas.';
export type Decision={prompt:string;options:readonly string[];correct:number;feedback:string};
export type TrainingActivity={key:string;title:string;route:string;level:number;kind:EvidenceKind;
 hours:number;competencies:CompetencyKey[];lesson:string;task:string;template:string;example:string;decisions:Decision[];
 sourceStage?:string;sourceRubric?:readonly string[];sourceUrls:string[];reevaluationOf?:string;rubric:string[];optionalPractice:string[]};
type Seed=[string,string,CompetencyKey[],number,string,string,string,[string,string,string,string][]];
const CS_SOURCE='https://handbook.gitlab.com/handbook/customer-experience/csm/';
const RUBRIC=['1 · Identifica el concepto, pero faltan datos o un siguiente paso verificable.',
 '2 · Aplica con guía; necesita corregir una omisión o justificar una decisión.',
 '3 · Aplica sin ayuda: evidencia trazable, decisión justificada, entrega clara y seguimiento comprobable.',
 '4 · Transferencia: además contrasta alternativas y responde a una nueva restricción. No acredita por sí sola nivel 4 de competencia.'];
const seeds:Seed[]=[
 ['common-communication','Comunicación clara y compromisos',['communication','documentation'],5,
 'Una comunicación útil permite actuar: describe el impacto observado, qué se sabe, qué falta y cuándo habrá actualización. Separa fecha de seguimiento de fecha de solución. Adapta el detalle al receptor: el usuario necesita un siguiente paso; soporte necesita reproducción; el sponsor necesita impacto y decisiones. Antes de enviar, comprueba que cada afirmación tenga una fuente y cada compromiso un responsable. Evita ocultar incertidumbre detrás de lenguaje técnico. Una buena respuesta también verifica comprensión: pide al receptor confirmar la acción y sus límites. Mantén el registro de acuerdos en el sistema compartido; un mensaje privado no basta para coordinar al equipo.',
 'Redacta una respuesta al cliente y un resumen interno del mismo problema, con distinto nivel de detalle.',
 'La exportación falla para dos usuarios. Se investiga; actualizaré mañana a las 10. No hay plazo de solución confirmado.',
 [['No existe plazo técnico confirmado. ¿Qué comunicas?','La fecha de próxima actualización y la incertidumbre','Que quedará resuelto mañana','Una actualización es un compromiso controlable; inventar resolución rompe confianza.'],['El sponsor pide resumen. ¿Qué priorizas?','Impacto, alternativa y decisión solicitada','Todos los registros técnicos','El resumen ejecutivo debe permitir decidir; conserva registros redactados en el ticket.'],['El cliente interpreta una alternativa como solución final. ¿Qué haces?','Aclaro límites y solicito confirmación','Doy el acuerdo por cerrado','Verifica comprensión antes de cerrar el compromiso.']]],
 ['common-diagnosis','Descubrimiento y diagnóstico',['diagnosis','communication'],5,
 'Empieza por la tarea y el resultado que la persona busca, no por la función que solicita. Registra observación, hipótesis y prueba como campos distintos. Una pregunta abierta descubre contexto; una pregunta concreta delimita alcance. Compara una ejecución exitosa con una fallida sin pedir contraseñas. Cada prueba debe poder descartar una hipótesis y tener un límite. Si la evidencia contradice tu idea inicial, actualiza el diagnóstico. Documenta la incertidumbre y explica qué dato falta para decidir. No hagas cambios globales para investigar un fallo localizado. El diagnóstico termina con una conclusión sustentada o una escalación que haga explícito lo que aún no se sabe.',
 'Construye un árbol con tres hipótesis, una prueba por hipótesis y una condición de escalación.',
 'Dos usuarios reciben 401 y otro puede exportar. Comparar permisos y hora del fallo antes de cambiar configuración.',
 [['Una función falla para algunos usuarios. ¿Qué comparas?','Pasos, permisos y contexto de éxito y fallo','Solo opiniones del equipo','La comparación reduce hipótesis sin tocar datos ajenos.'],['Una prueba contradice la hipótesis. ¿Qué sigue?','Actualizar el diagnóstico y registrar la evidencia','Repetir hasta obtener el resultado deseado','La evidencia debe poder cambiar la conclusión.'],['El cliente pide una función. ¿Qué preguntas?','Qué tarea quiere completar y qué le impide hacerlo','Cuándo quiere el botón','La necesidad precede a la solución propuesta.']]],
 ['common-data','Métricas, denominadores y calidad',['data','diagnosis'],5,
 'Una métrica necesita definición, población, ventana y fuente. Cuenta personas únicas cuando buscas adopción, y eventos cuando buscas frecuencia: no mezcles los denominadores. Distingue valor observado, línea base, meta e hipótesis. Antes de comparar periodos, revisa cambios de población, duplicados, datos faltantes y unidades. Un gráfico puede mostrar una diferencia sin explicar su causa. Conserva la fórmula y un ejemplo calculado para que otra persona pueda reproducirlo. Si falta información, informa el límite y diseña una medición; no rellenes con supuestos presentados como hechos. Los datos de este curso son ficticios y sirven para practicar, no para afirmar resultados de clientes reales.',
 'Calcula el cambio del tiempo de preparación en Faro; documenta fórmula, fuente, ventana y límites.',
 'De 5 a 3 días: reducción observada de 2 días, 40%. Una observación no demuestra mejora sostenida ni meta de 2 días.',
 [['Pasar de 5 a 3 días representa…','40% de reducción observada','60% de reducción garantizada','(5−3)/5 = 0.40; conserva la limitación de la muestra.'],['Suben logins pero no mejora el reporte. ¿Qué concluyes?','Hay más actividad; el valor sigue sin demostrarse','El cliente ya obtuvo el resultado','Actividad y resultado son medidas distintas.'],['Faltan filas en un periodo. ¿Qué haces?','Declaro faltantes y reviso comparabilidad','Los convierto a cero sin avisar','Un faltante no necesariamente significa cero.']]],
 ['common-priority','Priorización y capacidad sostenible',['prioritization','planning'],5,
 'Prioriza por impacto, urgencia, dependencias y reversibilidad. Separa el plazo de negocio de la presión del remitente. Estima capacidad disponible y reconoce trabajo en curso antes de aceptar más compromisos. Explica qué tarea desplazas y qué riesgo introduces cuando cambias el orden. Usa una cola visible con responsable y siguiente revisión; no una lista infinita de pendientes sin criterio. Ante una urgencia, delimita alcance y alternativa temporal. El trabajo sostenible incluye margen para fallos y aprendizaje. Si la demanda supera la capacidad, presenta opciones de alcance, fecha o recursos a quien puede decidir; no prometas que todo se hará al mismo tiempo.',
 'Ordena cinco tareas, estima capacidad y escribe qué cambia ante un bloqueo de exportación.',
 'Primero comprobar alcance del bloqueo; después acordar qué entrega se mueve y actualizar a sus responsables.',
 [['Dos plazos compiten con un bloqueo. ¿Qué haces primero?','Compruebo impacto y dependencias','Atiendo al remitente con mayor insistencia','Prioridad depende del contexto, no del volumen del mensaje.'],['No alcanza la capacidad. ¿Qué propones?','Alternativas de alcance y fecha con riesgos','Horas extra indefinidas','La sobrecarga no elimina dependencias ni protege calidad.'],['Cambia la prioridad. ¿Qué registras?','Tarea desplazada, impacto y nueva revisión','Solo el nuevo primer lugar','El cambio debe ser visible para quienes dependen de la entrega.']]],
 ['common-documentation','Documentación y sistemas de trabajo',['documentation','collaboration'],5,
 'Un registro útil permite continuar el trabajo sin depender de la memoria de su autor. Incluye objetivo, contexto, evidencia, decisión, responsable y siguiente paso. Mantén una fuente canónica y enlaza los documentos auxiliares, evitando versiones contradictorias. Una plantilla organiza información, pero completar campos no garantiza calidad. Diferencia hechos confirmados de borradores y deja trazabilidad de correcciones. Redacta credenciales y datos personales; comparte solo lo necesario. Comprueba el documento con una persona que no participó: si no puede reconstruir la decisión o ejecutar la acción, falta contexto. Al cerrar, registra qué se verificó y qué continúa pendiente.',
 'Completa un ticket y un handoff enlazados, sin copiar información sensible ni duplicar decisiones.',
 'Ticket: dos usuarios, exportar, 401, hora, pasos y resultado esperado. Handoff enlaza el ticket y asigna coordinación a CS.',
 [['Hay dos versiones de un acuerdo. ¿Qué haces?','Identifico la canónica y registro la corrección','Elijo la que favorece mi plan','La decisión necesita trazabilidad.'],['El registro incluye un token. ¿Qué procede?','Redactarlo y tratar la exposición con el responsable','Compartirlo para acelerar diagnóstico','Nunca se solicitan ni publican credenciales en la práctica.'],['Todos los campos están completos. ¿Está bien el documento?','Verifico claridad y posibilidad de reconstruir la decisión','Sí, por tener todos los campos','La calidad se demuestra mediante contenido y uso, no casillas.']]],
 ['common-deescalation','Objeciones y desescalamiento',['deescalation','communication'],5,
 'Reconoce el impacto sin confirmar una causa que aún no conoces. Resume lo que entendiste y verifica la prioridad del cliente. Una objeción puede reflejar precio, confianza, esfuerzo, alcance o valor: preguntar evita responder a un problema distinto. Presenta alternativas permitidas con sus límites y acuerda el siguiente contacto. No uses frases que responsabilicen al cliente sin evidencia ni prometas excepciones que no puedes aprobar. Si la conversación amenaza la seguridad o supera tu autoridad, escala con contexto y responsable. La desescalación no consiste en lograr que la persona deje de reclamar; busca un acuerdo claro sobre acciones y expectativas.',
 'Escribe un diálogo de seis turnos ante una exportación fallida y una exigencia de solución inmediata.',
 'Entiendo que el reporte vence hoy. Confirmemos a quién afecta y si el CSV permitido permite avanzar; daré actualización acordada.',
 [['El cliente está molesto. ¿Cómo empiezas?','Reconozco impacto y confirmo la necesidad','Le explico que está usando mal el producto','No atribuyas culpa sin evidencia.'],['Solicita una excepción comercial. ¿Qué haces?','Registro la solicitud y la llevo al autorizado','La concedo para terminar la discusión','La presión no amplía tu autoridad.'],['Acepta una alternativa. ¿Qué confirmas?','Límites, responsable y siguiente contacto','Que el incidente ya está resuelto','Una alternativa temporal no equivale a recuperación verificada.']]],
 ['common-commercial','Negociación y criterio comercial',['negotiation','diagnosis'],5,
 'Distingue posición declarada de necesidad subyacente. Una petición de descuento puede surgir de falta de valor, restricción de presupuesto o cambio de alcance. Prepara opciones con condiciones, límites y aprobación requerida. Separa renovación de expansión para evitar vender más antes de resolver el uso actual. No registres una oportunidad como ganada por entusiasmo ni confirmes funciones futuras. Define tu autoridad y qué responsable comercial debe intervenir. Un acuerdo debe precisar alcance, contraprestación y siguiente paso verificable. La práctica usa condiciones hipotéticas; no modifica precios ni suscripciones reales.',
 'Prepara dos alternativas para una objeción de precio, con contrapartidas y aprobación necesaria.',
 'Mantener alcance con plan de valor; o revisar alcance menor con comercial. Ninguna condición se presenta como aprobada.',
 [['El cliente pide descuento. ¿Qué investigas?','La causa, el alcance y quién decide','Solo cuánto reducir','La alternativa debe responder a la necesidad.'],['Hay interés verbal. ¿Cómo registras el forecast?','Como señal pendiente de pasos confirmados','Como renovación ganada','Interés no equivale a aceptación contractual.'],['Una expansión resolvería una limitación no validada. ¿Qué haces?','Compruebo encaje y capacidad antes de ofertar','La incluyo para acelerar renovación','No vendas una capacidad sin evidencia.']]],
 ['common-planning','Planeación, riesgos y seguimiento',['planning','prioritization'],5,
 'Un plan conecta resultado, entregables, dependencias y verificación. Asigna responsables por acción y por aprobación, que pueden ser distintos. Describe cada riesgo como causa posible, evento e impacto; después define señal temprana y respuesta. La probabilidad es una estimación explícita, no un hecho. Mantén un registro de decisiones y revisa el plan cuando cambian supuestos. Un hito se cierra con aceptación verificable, no porque llegó su fecha. Los planes útiles tienen una próxima revisión concreta y explican qué evidencia cambiaría su estado. Cuando falla una dependencia, presenta alternativas y solicita la decisión al responsable adecuado.',
 'Elabora un plan con cinco hitos, tres riesgos, responsables y criterios de aceptación.',
 'Primer reporte: datos conciliados, analista ejecuta, responsable del cliente acepta; integración automática sigue como dependencia pendiente.',
 [['Llegó la fecha del hito sin aceptación. ¿Qué estado tiene?','Pendiente de verificar con causa y nueva acción','Completado por calendario','Un plazo no es evidencia de cumplimiento.'],['Cambia el sponsor. ¿Qué revisas?','Objetivo, autoridad y prioridades','Solo su correo en CRM','El cambio puede invalidar supuestos del plan.'],['Aparece una dependencia bloqueada. ¿Qué presentas?','Alternativas, impacto y decisión requerida','Una nueva fecha sin explicación','Las personas deben poder valorar el riesgo y el alcance.']]],
 ['common-technical','Producto, datos, APIs y traspasos',['technical','collaboration','documentation'],5,
 'Para colaborar con un equipo técnico necesitas explicar la tarea, entrada, resultado esperado y resultado observado. Distingue autenticación, autorización, formato de datos y lógica del producto. Conoce las capacidades confirmadas y sus límites; una demo pequeña no prueba operación a escala. Un 401 orienta la investigación, pero no prueba por sí solo la causa. Registra pasos mínimos y usa datos ficticios. Reutiliza las lecciones existentes de SQL y APIs como apoyo opcional: no necesitas desarrollar una API para preparar una escalación útil. Un buen traspaso identifica al receptor, lo ya probado y cómo confirmará la recepción.',
 'Prepara una escalación del 401 de Faro y explica una consulta de adopción sin ejecutarla sobre clientes reales.',
 'Soporte recibe pasos, hora y alcance del 401, sin tokens. CS mantiene el plan de cuenta; la propiedad técnica queda explícita.',
 [['Un 401 significa…','Una señal para investigar autenticación y permisos','Que el producto está caído para todos','El código orienta; el alcance y la causa requieren evidencia.'],['Necesitas apoyo técnico. ¿Qué entregas?','Pasos, esperado, observado, pruebas y receptor','Una captura sin contexto','La reproducción mínima evita repetir preguntas.'],['Una demo funciona con diez filas. ¿Qué afirmas?','Funcionó en esa muestra; escala pendiente','Capacidad ilimitada confirmada','La muestra no demuestra rendimiento general.']]],
 ['cs-portfolio','Cartera y ciclo de vida',['prioritization','planning'],2.5,
 'Una cartera combina necesidades, etapa y capacidad. Distingue cuenta nueva, adopción, riesgo y renovación sin asumir que todas requieren la misma cadencia. El tamaño comercial es una señal para asignar recursos, pero no reemplaza impacto ni complejidad. Diseña cobertura con tareas mínimas y señales de excepción. Mantén objetivos por cuenta y una vista del trabajo comprometido. Revisa carga antes de prometer reuniones adicionales. Para Faro, la renovación cercana obliga a comprobar decisor y valor, sin abandonar el bloqueo operativo. Una priorización debe explicar quién recibe atención, por qué y cuándo se revisará.',
 'Diseña una ficha de cartera para Faro y una política de atención con capacidad limitada.',
 'Faro: renovación próxima, objetivo pendiente de confirmar y bloqueo localizado; investigar en paralelo con responsables distintos.',
 [['La cuenta más grande solicita reunión sin objetivo. ¿Qué haces?','Confirmo necesidad y reviso capacidad','Cancelo todas las tareas de las demás cuentas','Tamaño no elimina impacto de otras prioridades.'],['La cartera supera capacidad. ¿Qué propones?','Cadencias y excepciones justificadas','Mismo servicio intensivo para todas','La cobertura debe ser viable.'],['¿Qué hace accionable una ficha?','Objetivo, etapa, riesgo y siguiente revisión','Solo ingreso contratado','Ingresos no explican la acción necesaria.']]],
 ['cs-stakeholders','Stakeholders y autoridad',['communication','collaboration'],2.5,
 'Distingue usuarios, champion, sponsor, decisor económico y responsable técnico. Una persona puede cumplir varias funciones, pero no lo supongas por su título. Documenta influencia, interés y autoridad con evidencia. Si cambia el sponsor, pregunta si sigue vigente el resultado acordado. Diseña una estrategia de contacto que respete al champion y valide decisiones con quien puede tomarlas. Un mapa no es un ranking de personas: sirve para coordinar información y aprobación. Incluye ausencias y dependencia de una sola relación. Actualízalo cuando cambie la estructura o el proceso de compra.',
 'Construye el mapa de actores de Faro con preguntas pendientes y un plan de contacto.',
 'Champion satisfecho no confirma presupuesto; sponsor nuevo debe validar objetivo y proceso de decisión.',
 [['El champion está satisfecho. ¿Qué falta?','Confirmar decisor y valor de negocio','Dar renovación por segura','Satisfacción de un actor no prueba decisión económica.'],['Cambia el sponsor. ¿Qué haces?','Valido objetivos y autoridad con el nuevo contacto','Mantengo todos los supuestos anteriores','La continuidad debe confirmarse.'],['El título dice director. ¿Tiene autoridad?','Debe verificarse para esa decisión','Siempre','Título y autoridad concreta no son equivalentes.']]],
 ['cs-handoff','Handoff y alcance confirmado',['documentation','collaboration','diagnosis'],2.5,CS_LESSONS[0],
 'Extiende el checklist canónico de handoff: clasifica cada promesa como confirmada, pendiente o fuera de alcance.',
 CS_CASE_STAGES[0].example,
 [['No está documentada automatización. ¿Qué registras?','Pendiente con dueño de validación','Disponible porque se mencionó en ventas','La capacidad exige respaldo.'],['El kickoff puede avanzar. ¿Con qué condición?','Vacíos explícitos y responsables','Ocultando los riesgos','Avanzar no implica aceptar dependencias.'],['¿Quién recibe el traspaso?','Un responsable que confirma recepción','Todo el equipo sin dueño','Distribuir información no garantiza continuidad.']]],
 ['cs-success-plan','Plan de éxito y primer valor',['diagnosis','data','planning'],2.5,CS_LESSONS[1],
 'Completa el plan de éxito existente y separa métrica de resultado, adopción y primer valor.',
 CS_CASE_STAGES[1].example,
 [['¿Qué valida éxito?','Un resultado acordado con evidencia','Más accesos solamente','Adopción y resultado deben distinguirse.'],['La meta de dos días no fue confirmada. ¿Cómo aparece?','Como propuesta pendiente del sponsor','Como compromiso aceptado','La meta necesita acuerdo.'],['¿Qué incluye una métrica?','Fórmula, fuente, población y ventana','Un número atractivo','La definición permite reproducir el cálculo.']]],
 ['cs-kickoff','Kickoff y gobierno de cuenta',['communication','planning','collaboration'],2,
 'El kickoff alinea propósito, roles y forma de decidir. Prepara una agenda que cierre vacíos de handoff y deje claro qué se puede iniciar. Acuerda quién ejecuta, quién acepta y cómo se registran cambios. La cadencia de seguimiento depende del riesgo y la etapa; no impongas reuniones sin objetivo. Resume decisiones al terminar y solicita confirmación de diferencias. Si un actor indispensable no participa, registra lo pendiente en lugar de asumir su aprobación. El gobierno de cuenta debe facilitar decisiones y escalación, no multiplicar ceremonias.',
 'Redacta agenda, acta y procedimiento de cambio para el kickoff de Faro.',
 'Agenda: objetivo, fuente de datos, primer reporte y roles; acta deja automatización pendiente de validación.',
 [['No asiste quien acepta resultados. ¿Qué haces?','Dejo aprobación pendiente con siguiente paso','Doy por aceptado el plan','La ausencia no concede autorización.'],['Una reunión no tiene decisión ni objetivo. ¿Qué revisas?','Su utilidad y alternativa asíncrona','Solo su duración','La cadencia debe servir al trabajo.'],['Cambia el alcance durante kickoff. ¿Qué registras?','Impacto y aprobación requerida','Cambio inmediato sin consultar','Gobierno implica control de cambios.']]],
 ['cs-adoption','Adopción y barreras',['data','diagnosis'],4,CS_LESSONS[3],
 'Usa el dataset canónico de Faro para identificar barreras y diseñar una prueba de adopción.',
 CS_CASE_STAGES[3].example,
 [['Suben usuarios activos. ¿Qué investigas?','Si completan el flujo con resultado correcto','Solo si hay más logins','Actividad no garantiza valor.'],['La adopción se estanca. ¿Qué haces?','Investigo el punto de bloqueo','Programo capacitación sin diagnóstico','La barrera puede estar en datos o proceso.'],['¿Cómo compruebas una intervención?','Con ventana, población y resultado definido','Con una opinión posterior','La verificación necesita una comparación explícita.']]],
 ['cs-health','Health score explicable',['data','diagnosis','planning'],4,
 'Un health score sintetiza señales para orientar investigación; no predice con certeza ni sustituye contexto. Define dimensiones, fuente, frescura y tratamiento de faltantes. Separa uso, resultado, relación y riesgo comercial para evitar que una señal positiva oculte un problema grave. Documenta pesos como hipótesis configurables y revisa sensibilidad. Una señal sin datos no debe aparecer verde por defecto. Valida el indicador contra casos conocidos y revisa falsos positivos. En Faro, más uso convive con brecha de resultado y sponsor nuevo: el resumen debe conservar esas diferencias.',
 'Diseña un health score de cuatro dimensiones y explica cómo cambia si falta dato del sponsor.',
 'Uso estable; resultado aún incompleto; relación pendiente; riesgo de renovación por investigar. No presentar certeza de churn.',
 [['No hay datos de una dimensión. ¿Qué estado tiene?','Desconocido con acción de verificación','Saludable por defecto','Ausencia de datos no demuestra salud.'],['Uso alto y valor bajo. ¿Qué haces?','Conservo ambos indicadores y analizo la brecha','Promedio y declaro la cuenta sana','El agregado no debe ocultar una señal crítica.'],['¿Cómo validas pesos?','Con hipótesis, casos y revisión de sensibilidad','Por apariencia del dashboard','Los pesos son decisiones editoriales revisables.']]],
 ['cs-training','Capacitación y transferencia',['communication','technical','data'],4,
 'Diseña capacitación desde una tarea observable: qué debe poder hacer el usuario al terminar. Identifica conocimientos previos y limita el contenido a lo necesario para esa tarea. Muestra un ejemplo, permite practicar y entrega feedback. Evalúa ejecución con datos ficticios y criterio de aceptación. Asistencia y satisfacción ayudan a mejorar la experiencia, pero no prueban aprendizaje ni transferencia. Documenta barreras del sistema que no se resuelven con formación. Revisa la tarea después de un intervalo para comprobar retención y uso. Si el usuario no puede ejecutar por permisos, resuelve la dependencia antes de atribuir falta de habilidad.',
 'Prepara una microcapacitación de reporte para Faro con demostración, práctica y verificación posterior.',
 'Analista importa CSV ficticio, concilia totales y produce reporte; responsable valida exactitud. Asistencia queda como dato separado.',
 [['Todos asistieron. ¿Qué falta?','Demostrar la tarea y aceptar el resultado','Nada','Participación no prueba ejecución.'],['El ejercicio falla por permisos. ¿Qué haces?','Atiendo la dependencia y separo el diagnóstico','Declaro al usuario no competente','Una barrera del sistema no es evidencia de habilidad.'],['¿Qué comprueba transferencia?','Ejecutar luego en un caso nuevo con evidencia','Recordar diapositivas','La transferencia se observa al aplicar.']]],
 ['cs-qbr','QBR y decisiones trimestrales',['communication','data','planning'],4,CS_LESSONS[5],
 'Construye un QBR de Faro que distinga avance observado, meta pendiente y decisiones solicitadas.',
 CS_CASE_STAGES[5].example,
 [['¿Qué abre un QBR?','Resultado buscado y evidencia del periodo','Una lista de funcionalidades','La revisión debe conectar trabajo y valor.'],['Solo hay una observación favorable. ¿Cómo la presentas?','Como avance parcial con limitación','Como resultado sostenido','El tamaño de muestra limita la conclusión.'],['¿Qué cierra la revisión?','Decisiones, dueños y próxima comprobación','Más diapositivas','El QBR debe generar acción.']]],
 ['cs-integration','Colaboración técnica y primer valor',['technical','collaboration','documentation'],4,CS_LESSONS[2],
 'Reutiliza onboarding y escalación de Faro; prepara una alternativa CSV y un paquete técnico sin credenciales.',
 CS_CASE_STAGES[2].example,
 [['CSV es una alternativa permitida. ¿Qué documentas?','Esfuerzo, controles y límites','Que sustituye toda integración','La alternativa requiere aceptación explícita.'],['La capacitación terminó. ¿Se cierra onboarding?','Solo cuando se verifica primer valor','Sí','El hito requiere evidencia de ejecución.'],['¿Qué comparte CS con soporte?','Contexto y reproducción redactada','Tokens y datos completos','Comparte el mínimo necesario.']]],
 ['cs-churn','Churn y rescate de cuenta',['diagnosis','deescalation','planning'],5,CS_LESSONS[4],
 'Extiende el plan de riesgo de Faro con hipótesis, impacto, responsables y criterio de recuperación.',
 CS_CASE_STAGES[4].example,
 [['Un sponsor salió. ¿Qué concluyes?','Hay riesgo que debe investigarse','Cancelación segura','Una señal aislada no determina churn.'],['Hay incidente y riesgo comercial. ¿Qué haces?','Coordino frentes paralelos con dueños distintos','Espero cierre técnico para todo','Los dos riesgos pueden avanzar en paralelo.'],['¿Qué cierra rescate?','Evidencia de recuperación y acuerdo actualizado','Silencio del cliente','La falta de respuesta no confirma recuperación.']]],
 ['cs-renewal','Renovación y proceso de compra',['negotiation','planning','communication'],5,CS_LESSONS[6],
 'Prepara el briefing canónico de renovación con decisor, valor, objeción y pasos confirmados.',
 CS_CASE_STAGES[6].example,
 [['¿Qué confirma renovación?','Aceptación por el proceso autorizado','Entusiasmo del champion','La compra requiere pasos verificables.'],['No hay valor demostrado. ¿Qué haces?','Investigo la brecha antes de negociar','Ofrezco descuento inmediato','Precio no sustituye diagnóstico.'],['¿Qué registra un plan de compra?','Decisor, requisitos, fechas y dependencias','Solo fecha esperada','El plan debe explicar cómo ocurre la decisión.']]],
 ['cs-expansion','Expansión por necesidad y encaje',['negotiation','diagnosis','technical'],5,
 'Una expansión debe resolver una necesidad verificada y ser operable para el cliente. Comprueba resultado esperado, capacidad del producto y recursos de adopción. Separa demanda exploratoria de oportunidad calificada. Pregunta quién decide y qué alternativas existen. Coordina con comercial y preventa sin prometer alcance no aprobado. Evalúa si el cliente debería estabilizar el uso actual antes de ampliar. Registra riesgos y criterios para detener la propuesta. La oportunidad debe explicar valor incremental y esfuerzo, no solo ingreso potencial.',
 'Diseña una hipótesis de expansión para Faro con señales para avanzar o detenerla.',
 'No ampliar por presión de renovación: validar uso del reporte actual, necesidad incremental y capacidad antes de presentar condiciones.',
 [['El cliente tiene adopción bloqueada. ¿Qué haces?','Evalúo resolver la barrera antes de ampliar','Vendo más para compensar','La expansión puede agravar una brecha de uso.'],['Pide una capacidad no validada. ¿Qué haces?','Coordino validación con técnico y comercial','La incluyo en propuesta','La promesa necesita evidencia.'],['¿Qué califica una expansión?','Necesidad, valor incremental, decisor y viabilidad','Cantidad de solicitudes','Interés no demuestra encaje.']]],
 ['cs-roi','ROI y valor verificable',['data','diagnosis','communication'],5,
 'Expresa valor como cambio observado frente a una línea base comparable. Separa ahorro de tiempo, costo evitado y resultado comercial: no sumes dos veces el mismo beneficio. Explicita supuestos de monetización y distingue valor potencial de realizado. ROI requiere beneficio atribuible y costo comparable; si faltan costos o atribución, presenta un modelo condicionado. En Faro sabemos tiempo de preparación, pero no costo de hora ni ahorro sostenido. Usa sensibilidad para mostrar cómo cambia el resultado según supuestos. No conviertas una calculadora en promesa contractual.',
 'Construye un modelo de valor de Faro con fórmula, supuestos y análisis de sensibilidad, sin inventar costos reales.',
 'Ahorro de tiempo observado: 2 días en una medición. Monetización pendiente de horas efectivas y costo validado; no afirmar ROI realizado.',
 [['Falta costo por hora. ¿Qué presentas?','Modelo condicionado y dato pendiente','Un ROI realizado usando un costo inventado','Los supuestos deben estar visibles.'],['El mismo ahorro aparece en dos categorías. ¿Qué haces?','Evito doble conteo','Sumo ambos beneficios','La conciliación protege la credibilidad.'],['La mejora ocurrió tras varios cambios. ¿Qué aclaras?','Atribución incierta y comparación necesaria','Todo fue causado por el producto','Correlación no prueba causalidad.']]],
 ['cs-forecast','Forecast y escenarios de continuidad',['planning','data','negotiation'],4,
 'Un forecast registra hipótesis y evidencia sobre fecha y resultado comercial. Distingue probabilidad de certeza y define qué paso mueve una oportunidad de etapa. Mantén escenarios base, favorable y adverso con dependencias explícitas. Una fecha debe corresponder a un proceso de compra confirmado; no al cierre que deseas. Revisa cambios de sponsor, aprobación y contrato. Compara previsión con resultado para aprender de errores sin castigar honestidad. CS aporta contexto de valor y riesgo; el responsable comercial conserva su autoridad sobre condiciones y cierre.',
 'Prepara tres escenarios de renovación de Faro y señales que cambian cada previsión.',
 'Base: valor y decisor pendientes. Favorable: dos ciclos comparables y pasos de compra confirmados. Adverso: prioridad cambia o aprobación no llega.',
 [['¿Qué cambia etapa de forecast?','Un paso confirmado con evidencia','Optimismo del equipo','Las etapas requieren criterios.'],['Compras retrasa aprobación. ¿Qué haces?','Actualizo fecha, dependencia y escenario','Mantengo fecha para cumplir objetivo','La previsión debe reflejar el proceso.'],['¿Qué aporta CS?','Valor observado y riesgos de cuenta','Aprobación de descuentos sin facultad','La colaboración respeta autoridad.']]],
 ['cs-voc','Voz del cliente y cierre del ciclo',['documentation','collaboration','diagnosis'],2.5,CS_LESSONS[7],
 'Extiende la plantilla canónica de voz del cliente distinguiendo problema, solicitud y evidencia.',
 CS_CASE_STAGES[7].example,
 [['Tres cuentas piden lo mismo. ¿Qué concluyes?','Hay una hipótesis que requiere contexto','Todo el mercado lo necesita','La muestra no es demanda universal.'],['Producto no ha decidido. ¿Qué comunicas?','Evaluación pendiente y alternativa disponible','Fecha de entrega inventada','No prometas roadmap no aprobado.'],['¿Cómo cierras feedback?','Comunico la decisión aunque sea no construir','Solo si se aprueba','El cierre del ciclo también incluye una negativa explicada.']]],
 ['cs-surveys','NPS, CSAT y escucha responsable',['data','communication','diagnosis'],2.5,
 'NPS y CSAT describen respuestas de poblaciones y momentos específicos; no sustituyen resultado, retención ni adopción. Para NPS, documenta escala, promotores, detractores y denominador de respuestas; los no respondientes no equivalen a pasivos. Para CSAT define pregunta, escala y criterio positivo. Revisa tasa de respuesta y sesgo antes de comparar segmentos. Complementa números con comentarios y entrevistas. No contactes personas reales en esta práctica. Una encuesta sirve para orientar preguntas y cerrar acciones; no para afirmar causalidad ni clasificar el desempeño de un colaborador.',
 'Diseña una encuesta ficticia y calcula NPS de 10 respuestas: 5 promotores, 2 pasivos, 3 detractores.',
 'NPS=(5/10−3/10)×100=20. El resultado describe esas diez respuestas; faltan población invitada y tasa de respuesta.',
 [['¿Cuál es el NPS del ejemplo?','20','50','Se resta proporción de detractores a promotores.'],['No respondieron varias personas. ¿Qué haces?','Reporto tasa y posible sesgo','Las cuento como pasivas','No respuesta no es una calificación.'],['¿Qué sigue a la encuesta?','Investigar contexto y cerrar acciones','Celebrar el número sin seguimiento','Escuchar requiere respuesta y acción.']]],
 ['cs-segmentation','Segmentación y diseño de cobertura',['data','prioritization','planning'],2.5,
 'Segmenta para tomar una decisión concreta de cobertura, no para producir etiquetas permanentes. Usa variables observables: etapa, complejidad, necesidades, riesgo y capacidad disponible. Distingue tamaño de contrato de esfuerzo operativo. Define reglas de cambio y excepciones; una cuenta puede necesitar atención intensiva temporalmente. Comprueba que el segmento no oculte falta de datos ni excluya acciones esenciales. Evalúa costo de servicio y resultados por población comparable. El diseño debe ser transparente y revisable, sin inferir habilidades personales a partir del plan contratado.',
 'Diseña segmentos de cobertura y explica el tratamiento temporal de Faro ante cambio de sponsor.',
 'Cobertura temporal por riesgo y renovación próxima; revisar después de recuperar objetivo y flujo, sin etiqueta permanente.',
 [['¿Qué justifica un segmento?','Una decisión de cobertura con criterios','Una etiqueta por intuición','Los segmentos deben ser accionables.'],['Una cuenta pequeña tiene bloqueo grave. ¿Qué haces?','Aplico excepción por impacto','La ignoro por ingresos bajos','Tamaño no elimina necesidades esenciales.'],['¿Cuándo revisas el segmento?','Cuando cambia etapa, riesgo o necesidad','Nunca','La cobertura debe adaptarse.']]],
 ['cs-case-study','Casos de éxito con evidencia y permiso',['communication','documentation','data'],2.5,
 'Un caso de éxito cuenta una transformación verificable: situación inicial, intervención, resultado y límites. Conserva fuente de cada cifra y aprobación para usar nombres o testimonios. Distingue contribución del producto de otros cambios. No selecciones solo la mejor observación y la presentes como típica. Incluye periodo, población y qué no se midió. En esta práctica todos los nombres y cifras son ficticios; no se publica ni solicita testimonio real. El documento debe ser útil para entender el mecanismo, no solo una pieza promocional.',
 'Redacta un caso ficticio de Faro que distinga avance parcial, meta pendiente y permisos necesarios antes de publicar.',
 'Un ciclo pasó de 5 a 3 días. No afirmar meta 2 lograda ni mejora sostenida; el caso es educativo y no es testimonio de un cliente real.',
 [['¿Qué exige una cifra pública?','Fuente, periodo y autorización correspondiente','Que sea atractiva','La credibilidad requiere trazabilidad y permiso.'],['Solo el mejor ciclo mejoró. ¿Qué dices?','Avance observado con límites','Resultado típico garantizado','No generalices una observación seleccionada.'],['¿Puede publicarse el ejercicio como cliente real?','No; es ficción educativa','Sí, cambiando el nombre','No inventes testimonios ni resultados reales.']]],
 ['cs-ebr','EBR y criterio ejecutivo',['communication','planning','negotiation'],2,
 'Una EBR conecta objetivos estratégicos, evidencia de valor y decisiones de continuidad. Prioriza información que cambie una decisión del sponsor. Explica lo logrado, lo pendiente y alternativas con consecuencias. Lleva una recomendación sustentada y una pregunta concreta de aprobación; evita presentar una venta adicional como resultado obligatorio. Un cierre útil asigna responsables y criterios para la próxima revisión. La comunicación ejecutiva exige reconocer incertidumbre con claridad. Practicarla desarrolla preparación para liderazgo, pero no acredita experiencia gerencial ni desempeño real.',
 'Prepara una EBR de Cuenta Faro con una recomendación, alternativa y decisión solicitada.',
 'Recomendación: validar dos ciclos comparables y objetivo con sponsor; alternativa temporal CSV con límites. Renovación sigue proceso comercial.',
 [['¿Qué debe permitir una EBR?','Decidir con evidencia, alternativas y riesgos','Ver todas las funciones del producto','La revisión ejecutiva se orienta a decisiones.'],['El sponsor pide certeza que no tienes. ¿Qué haces?','Declaro incertidumbre y cómo reducirla','Invento una garantía','El criterio ejecutivo incluye reconocer límites.'],['¿Qué cierra el acuerdo?','Dueños, criterios y próxima revisión','Solo un agradecimiento','La decisión requiere seguimiento.']]],
];
export const TRAINING_UNITS:TrainingActivity[]=seeds.map((s,i):TrainingActivity=>({
 key:s[0],title:s[1],competencies:s[2],hours:s[3],route:i<9?'common':'customer_success',level:i<9?0:Math.floor((i-9)/5)+1,
 kind:'deliverable',lesson:s[4],task:s[5],example:s[6],template:'Objetivo y contexto:\nHechos y fuentes:\nSupuestos y datos pendientes:\nAlternativas y decisión justificada:\nEntregable:\nRiesgos y límites:\nResponsable, fecha y criterio de verificación:',
 decisions:s[7].map(([prompt,a,b,feedback],n)=>({prompt,options:n%2?[b,a]:[a,b],correct:n%2?1:0,feedback})),
 rubric:RUBRIC,sourceUrls:[CS_SOURCE],optionalPractice:[
  `Transferencia: repite “${s[1]}” con una restricción nueva de tiempo y justifica qué decisión cambias.`,
  `Contraste: compara tu entrega con el ejemplo; identifica una afirmación sin evidencia y corrígela.`,
 ],
})).map(enrichTrainingActivity);
export const TECHNICAL_BORROWING=[
 {topic:'SQL',level:6,purpose:'Comprender extracción y agregación de adopción; apoyo opcional, sin duplicar lecciones ni conceder acceso nuevo.'},
 {topic:'APIs',level:8,purpose:'Interpretar contratos, errores y escalaciones; no exigir desarrollar una API para Customer Success.'},
 {topic:'Integraciones',level:11,purpose:'Entender dependencias y traspasos; conservar derechos y contenidos de la ruta técnica.'},
];
const extra=(key:string,title:string,level:number,kind:EvidenceKind,hours:number,competencies:CompetencyKey[],task:string,stage?:number):TrainingActivity=>({
 key,title,route:'customer_success',level,kind,hours,competencies,task,
 lesson:stage===undefined?'Integra las unidades de este nivel. Diferencia evidencia, hipótesis y decisión; verifica cada conclusión antes de presentar el resultado.':CS_LESSONS[stage],
 template:stage===undefined?'Diagnóstico:\nFuentes y cálculos:\nAlternativas:\nDecisión:\nEntregable:\nRiesgos:\nResponsables:\nPróxima verificación:':CS_CASE_STAGES[stage].template,
 example:stage===undefined?'El resultado observado de Faro no cumple aún la meta; la propuesta debe conservar esa brecha y definir cómo verificarla.':CS_CASE_STAGES[stage].example,
 decisions:[],rubric:RUBRIC,sourceUrls:[CS_SOURCE],optionalPractice:[],sourceStage:stage===undefined?undefined:CS_CASE_STAGES[stage].key,
});
export const TRAINING_EXTRAS:TrainingActivity[]=[
 ...CS_CASE_STAGES.map((stage,i)=>extra(`cs-episode-${stage.key}`,`Cuenta Faro · ${stage.title}`,Math.floor(i/2)+1,'deliverable',2,
  (['diagnosis','planning','communication'] as CompetencyKey[]),stage.task,i)),
 ...['Sponsor nuevo y objetivo por confirmar','Usuario bloqueado y capacitación','Objeción de valor en renovación','Decisión ejecutiva y límites de evidencia'].map((title,i)=>extra(`cs-roleplay-${i+1}`,`Role-play escrito · ${title}`,i+1,'deliverable',1,
  ['communication','deescalation'],`Escribe ocho turnos de conversación sobre “${title}”, con dos objeciones. Usa Faro y etiqueta hechos, preguntas y compromisos. Termina con acuerdo verificable; no inventes información de la cuenta.`)),
 extra('cs-project-adoption','Proyecto · plan de adopción y health score',2,'project',4,['data','diagnosis','planning'],'Integra diagnóstico de flujo, score explicable, capacitación y QBR. Presenta hipótesis, prueba, cálculos reproducibles y criterio de aceptación.'),
 extra('cs-project-continuity','Proyecto · continuidad, renovación y valor',3,'project',4,['negotiation','planning','data'],'Integra rescate, renovación, expansión, modelo condicionado de ROI y escenarios de forecast. Declara qué datos faltan; no concedas condiciones comerciales.'),
 extra('cs-project-voice','Proyecto · voz del cliente y cobertura',4,'project',4,['collaboration','documentation','data'],'Integra síntesis de feedback, encuesta ficticia, segmentos y caso de éxito. Separa resultados educativos de testimonios reales y cierra el ciclo con receptor y revisión.'),
 {...extra('cs-capstone-faro','Capstone · Cuenta Faro completa y EBR',4,'capstone',8,['communication','diagnosis','planning'],'Integra las ocho etapas canónicas de Faro y las veinte unidades. Entrega expediente de cuenta, fuentes y fórmulas, plan de éxito, adopción, riesgos, renovación y EBR. Anexa evidencias ya revisadas de datos y colaboración; el diploma exige nivel 3 en todas las competencias de peso Alto, no solo las tres de este capstone.'),sourceRubric:CS_CAPSTONE_RUBRIC},
 ...Array.from({length:4},(_,i)=>{
  const units=TRAINING_UNITS.filter(u=>u.route==='customer_success'&&u.level===i+1);
  const a=extra(`cs-exam-${i+1}`,`Examen · ${['Fundamentos','Operación','Dominio','Especialista'][i]}`,i+1,'exercise',1.5,units[0].competencies,'Resuelve cinco decisiones del nivel. Aprobación formativa: cuatro respuestas correctas. La calificación automática acredita reconocimiento, no autonomía.');
  a.decisions=units.map(u=>u.decisions[2]);return a;
 }),
 ...Array.from({length:4},(_,i)=>{
  const unit=TRAINING_UNITS.find(u=>u.key===['cs-kickoff','cs-health','cs-renewal','cs-voc'][i])!;
  return {...extra(`cs-reevaluation-${i+1}`,`Reevaluación a 30 días · nivel ${i+1}`,i+1,'deliverable',1.5,unit.competencies,
   `A los 30 días de una evidencia independiente revisada, aplica ${unit.title.toLowerCase()} ante una restricción hipotética nueva: el sponsor cambia la prioridad y se reduce el tiempo disponible. Distingue esa variante de los hechos originales de Faro. Justifica decisiones y verificación.`),reevaluationOf:unit.key};
 }),
];
export const TRAINING_ACTIVITIES=[...TRAINING_UNITS,...TRAINING_EXTRAS];
export const FARO_DATA=CS_CASE_METRICS;
export const TRAINING_LEVEL_HOURS=[20,32,36,32];
export function suggestedUnits(key:CompetencyKey){return TRAINING_UNITS.filter(u=>u.competencies.includes(key)).slice(0,3);}
export function findTrainingActivity(key:string){return [...TRAINING_ACTIVITIES,...PROFESSIONAL_ACTIVITIES].find(a=>a.key===key);}
export function gradeTrainingDecisions(activity:TrainingActivity,answers:number[]){
 if(answers.length!==activity.decisions.length||!answers.length||answers.some((v,i)=>!Number.isInteger(v)||v<0||v>=activity.decisions[i].options.length))throw Error('INVALID_ANSWERS');
 return {score:Math.round(answers.filter((v,i)=>v===activity.decisions[i].correct).length/answers.length*100),feedback:activity.decisions.map(q=>q.feedback)};
}

