import { ROLE_WORKFLOWS, ROLE_DELIVERY_TEMPLATES } from './career-role-workflows.ts';
import type { CareerPositionKey } from './career-guidance.ts';
import { API_LABS, PRACTICE_ACTIVITIES, TARGET_ROLES } from './practice-learning.ts';

/** Original cases, with fictional data. No course unlock, grade or entitlement. */
export const CASE_RUBRIC = [
 {key:'diagnosis',label:'Diagnóstico',missing:'Solo hay una conclusión.',developing:'Distingue síntoma e hipótesis.',ready:'Contrasta evidencia, descarta una alternativa y declara incertidumbre.'},
 {key:'action',label:'Acción',missing:'No hay un siguiente paso.',developing:'Propone una acción con responsable.',ready:'Acción proporcional, responsable, fecha y criterio de aceptación.'},
 {key:'verification',label:'Verificación',missing:'No se comprueba el resultado.',developing:'Incluye una prueba exitosa.',ready:'Prueba éxito, fallo y recuperación con resultados esperados.'},
 {key:'communication',label:'Comunicación y seguridad',missing:'Promesas o datos sensibles sin justificación.',developing:'Explica límites y seguimiento.',ready:'Mensaje claro, secretos redactados y escalación con contexto mínimo.'},
] as const;
export const ROLE_CASES = [
 {id:'cs-first-value',role:'technical_cs',stage:'Primer valor',title:'El kickoff no es el resultado',facts:'Faro contrató 20 asientos. Solo 4 personas completan el flujo clave; el objetivo acordado es bajar la preparación de reportes de 2 horas a 30 minutos. Aún no hay medición después de la capacitación.',options:['Dar el onboarding por terminado porque asistieron todos','Probar el flujo con un responsable y medir tiempo y adopción'],recommended:1,feedback:'Define baseline, ventana de medición y aceptación del cliente. La asistencia es una actividad; todavía falta demostrar el resultado.',deliverables:['Plan de éxito con objetivo, baseline y responsable','Prueba del flujo con datos ficticios','Acta de aceptación o pendiente explícito'],failure:'El flujo funciona, pero el responsable no puede repetirlo sin ayuda.'},
 {id:'cs-risk',role:'technical_cs',stage:'Adopción y riesgo',title:'Uso alto, valor incierto',facts:'Puente registra 140 accesos semanales, pero exporta los reportes y vuelve a Excel. Hay dos tickets abiertos y cambió el patrocinador.',options:['Proponer más asientos por el volumen de accesos','Validar el resultado y alinear al nuevo patrocinador'],recommended:1,feedback:'Combina señales de adopción, tickets y objetivos. Un indicador agregado no prueba que el cliente obtiene valor.',deliverables:['Mapa de señales confirmadas y pendientes','Plan de recuperación con responsable y fecha','Mensaje al nuevo patrocinador sin prometer resultados no medidos'],failure:'El patrocinador no contesta; define escalación y un contacto alterno autorizado.'},
 {id:'cs-renewal',role:'technical_cs',stage:'Valor y renovación',title:'Renovación con evidencia',facts:'La renovación de Nube es en 30 días. Preparar reportes bajó de 120 a 45 minutos, pero el objetivo era 30. El cliente pide un descuento y no ha confirmado presupuesto.',options:['Prometer el descuento para asegurar renovación','Presentar resultado, brecha y opciones sujetas a aprobación'],recommended:1,feedback:'Reconoce el avance y la brecha. Separa el plan de valor de las condiciones comerciales y confirma el proceso de decisión.',deliverables:['Revisión ejecutiva con comparación equivalente','Opciones de alcance y condiciones pendientes de aprobación','Plan de cierre y traspaso comercial'],failure:'El decisor cambia; registra qué acuerdo sigue vigente y qué debe reconfirmarse.'},
 {id:'support-triage',role:'support',stage:'Recepción y prioridad',title:'Un ticket urgente con alternativa',facts:'Faro no puede exportar un reporte. Afecta a 3 de 20 usuarios y existe una exportación manual aprobada. El cliente dice urgente, sin indicar su fecha límite.',options:['Copiar la palabra urgente como prioridad sin contexto','Confirmar impacto, plazo y alternativa antes de clasificar'],recommended:1,feedback:'Prioriza con impacto y urgencia verificables. Registra la alternativa y cuándo dejaría de ser suficiente.',deliverables:['Ticket con síntoma, alcance y preguntas','Prioridad justificada y próxima actualización','Paquete de escalación sin datos sensibles'],failure:'La alternativa deja de funcionar y aumenta el alcance; reevalúa la prioridad.'},
 {id:'support-hypothesis',role:'support',stage:'Diagnóstico y escalación',title:'401 no siempre significa caída',facts:'Una integración responde 401 tras cambiar credenciales; otra cuenta funciona. Los registros ficticios muestran unauthorized, sin detalle de causa.',options:['Pedir al cliente que pegue el token completo','Comprobar vigencia y alcance usando evidencia redactada'],recommended:1,feedback:'Separa observaciones e hipótesis. Diseña pruebas reversibles; no necesitas la contraseña ni un token completo para describir el problema.',deliverables:['Tres hipótesis y una prueba por hipótesis','Comparación entre caso exitoso y fallido','Escalación con cambios, timestamps y resultados'],failure:'Las pruebas de vigencia y alcance pasan; no declares causa, escala con la evidencia.'},
 {id:'support-close',role:'support',stage:'Cierre y prevención',title:'Bajó el error, falta confirmar',facts:'La mitigación redujo errores de 30 a 2 por hora. El cliente aún ve un reporte incompleto; ingeniería investiga la causa.',options:['Cerrar todos los tickets porque bajó el indicador','Confirmar el flujo del cliente y conservar pendientes vinculados'],recommended:1,feedback:'Distingue mitigación, recuperación y causa. Un problema puede tener incidentes relacionados; el cierre requiere comprobar el resultado que importa al cliente.',deliverables:['Cronología y estado de mitigación','Confirmación del cliente o pendiente','Artículo de ayuda y acción preventiva con responsable'],failure:'El problema reaparece; conserva la cronología y reabre con el nuevo alcance.'},
 {id:'integration-contract',role:'integrations',stage:'Contrato y mapeo',title:'Pesos y centavos',facts:'El CRM envía external_id crm_42 y amount 149. Facturación espera customer_id y amount_cents. No existe una correspondencia confirmada.',options:['Elegir una cuenta por parecido de nombre','Validar mapeo, moneda y unidades antes de escribir'],recommended:1,feedback:'Una coincidencia de nombres no es identidad. Acordar contrato y pruebas evita afectar la cuenta equivocada.',deliverables:['Contrato con campos obligatorios y unidades','Mapeo único confirmado','Pruebas de ID desconocido, moneda incorrecta y campos ausentes'],failure:'Hay dos IDs de destino para crm_42; bloquea el efecto y solicita resolución.'},
 {id:'integration-delivery',role:'integrations',stage:'Entrega y efectos',title:'Dos entregas, un efecto',facts:'El evento evt_demo_99 se entregó dos veces; un proceso paralelo aplicó dos cambios. La firma era válida.',options:['Usar solo la firma como protección contra duplicados','Deduplicar atómicamente y diseñar recuperación'],recommended:1,feedback:'La autenticidad y la unicidad son controles diferentes. Registra el evento y su efecto con una estrategia atómica y recuperable.',deliverables:['Secuencia de validación, deduplicación y persistencia','Prueba de entregas concurrentes y repetidas','Plan ante fallo entre registrar y aplicar el efecto'],failure:'El proceso cae después de registrar el evento; prueba que el trabajo pendiente se recupera.'},
 {id:'integration-operate',role:'integrations',stage:'Operación y aceptación',title:'La cola crece con 429',facts:'La API indica Retry-After 30. Hay 120 eventos pendientes y un límite de 5 reintentos; el cliente necesita saber si se perderán datos.',options:['Vaciar la cola y marcar éxito','Conservar eventos, respetar espera y escalar al agotar intentos'],recommended:1,feedback:'La aceptación incluye comportamiento ante fallos. Acuerda señales, recuperación, responsables y cómo confirmar integridad después de reintentar.',deliverables:['Runbook con backoff y límite de intentos','Alerta y responsable para eventos no resueltos','Pruebas de reconciliación y acta de aceptación'],failure:'Se agotan reintentos; conserva el evento para revisión, sin declararlo completado.'},
] as const;

/** Coverage of the existing position catalog: checklists + common review criteria. */
export function roleReviewGuide(key:CareerPositionKey){
 const workflow=ROLE_WORKFLOWS[key];
 return {title:workflow.title,process:workflow.process,activities:workflow.activities,checklist:ROLE_DELIVERY_TEMPLATES[key],deliverable:workflow.deliverable,decision:workflow.decision,acceptance:workflow.quality,rubric:CASE_RUBRIC,source:workflow.source};
}
export type PracticeApproach='process'|'code'|'customer';
/** Transparent suggestions based on explicit choice and sample coverage, not aptitude. */
export function nextPracticeChoices(roleId:string,passedIds:readonly string[],approach:PracticeApproach){
 const role=TARGET_ROLES.find(x=>x.id===roleId);if(!role||!['process','code','customer'].includes(approach))return [];
 const passed=new Set(passedIds);
 const preferred=approach==='code'?['python','sql']:approach==='customer'?['communication']:['logic','security','apis'];
 const candidates=[...PRACTICE_ACTIVITIES.map(x=>({id:x.id,title:x.title,skill:x.skill,level:x.level})),...API_LABS.map(x=>({id:x.id,title:x.title,skill:'apis' as const,level:x.level}))];
 return candidates.filter(x=>(role.skills as readonly string[]).includes(x.skill)&&!passed.has(x.id))
  .sort((a,b)=>Number(preferred.includes(b.skill))-Number(preferred.includes(a.skill))||a.level-b.level)
  .slice(0,3).map(x=>({...x,reason:`Apoya tu objetivo de ${role.label}; todavía no marcaste esta muestra como resuelta. ${preferred.includes(x.skill)?'Coincide con el enfoque que elegiste.':'Puedes usarla para ampliar tu práctica.'}`}));
}
