/** Separate from persisted samples-v1. Training only; no official counters. */
export const RUNTIME_CHALLENGES = [
 {id:'python-list',language:'python',title:'Lista cuentas activas',task:'Filtra el dataset y muestra sus nombres en orden.',starter:'cuentas = [{"nombre":"Faro","estado":"activo","asientos":3},{"nombre":"Nube","estado":"inactivo","asientos":2},{"nombre":"Puente","estado":"activo","asientos":5}]\nfor cuenta in cuentas:\n    if cuenta["estado"] == "activo":\n        print(cuenta["nombre"])',expected:'Faro\nPuente',explain:'Explica el filtro y prueba una cuenta inactiva adicional.'},
 {id:'python-total',language:'python',title:'Suma asientos activos',task:'Calcula los asientos activos del dataset, sin contar Nube.',starter:'cuentas = [{"nombre":"Faro","estado":"activo","asientos":3},{"nombre":"Nube","estado":"inactivo","asientos":2},{"nombre":"Puente","estado":"activo","asientos":5}]\n# Recorre las cuentas y acumula asientos activos\n',expected:'8',explain:'Explica por qué el total es 8; comprueba el resultado si ninguna cuenta está activa.'},
 {id:'python-input',language:'python',title:'Valida una entrada',task:'Convierte asientos a entero. Muestra 5 para "5" y entrada inválida para "cinco", sin detener el programa.',starter:'entradas = ["5", "cinco"]\nfor valor in entradas:\n    # Valida y convierte cada valor\n    pass',expected:'5\nentrada inválida',explain:'Distingue datos inválidos de fallos del programa y añade el caso vacío.'},
 {id:'sql-list',language:'sql',title:'Consulta cuentas activas',task:'Obtén nombre y asientos de cuentas activas por id ascendente.',starter:"SELECT nombre, asientos FROM cuentas WHERE estado = 'activo' ORDER BY id;",expected:'{"nombre":"Faro","asientos":3}\n{"nombre":"Puente","asientos":5}',explain:'Describe WHERE y ORDER BY; verifica qué sucede con una cuenta inactiva.'},
 {id:'sql-total',language:'sql',title:'Agrega sin perder el filtro',task:'Obtén una sola fila con el alias total y suma los asientos activos.',starter:'-- Usa SUM y filtra el estado\n',expected:'{"total":8}',explain:'Explica la diferencia entre filtrar filas y agregar; usa COALESCE si no hay coincidencias.'},
 {id:'sql-groups',language:'sql',title:'Agrupa por estado',task:'Devuelve estado y COUNT(*) con alias cuentas, por estado ascendente.',starter:'-- Agrupa y ordena por estado\n',expected:'{"estado":"activo","cuentas":2}\n{"estado":"inactivo","cuentas":1}',explain:'Explica GROUP BY y por qué COUNT(*) mide filas, no asientos.'},
] as const;
