import type {TrainingActivity} from './role-training-content';
export const WEEKLY_CASE_SEEDS=[
 ['2026-10-08','customer_success','Faro · primer valor comprobable','El reporte tarda cinco días. El sponsor propone dos días, pero no hay una línea base comparable. Define población, fórmula y una prueba de valor.',['data','diagnosis']],
 ['2026-10-15','customer_support','Faro · incidente y comunicación','Dos usuarios reciben 401 al exportar; el resto trabaja. Aísla permisos y pasos sin pedir contraseñas ni cambiar acceso global.',['technical','communication']],
 ['2026-10-22','account_manager','Faro · renovación con evidencia','La renovación está a treinta días. El champion está satisfecho, pero cambió el decisor económico. Separa hipótesis comercial de aprobación confirmada.',['negotiation','planning']],
 ['2026-10-29','manager_team_lead','Faro · capacidad y prioridades','Tu equipo tiene cuatro horas disponibles y seis de trabajo comprometido. Un incidente afecta a dos cuentas. Explica qué desplazas y cómo verificas el impacto.',['prioritization','collaboration']],
 ['2026-11-05','customer_success','Faro · adopción y calidad de datos','Las sesiones crecen 30%, pero el reporte sigue con duplicados. Concilia personas únicas y eventos antes de afirmar que hay adopción útil.',['data','documentation']],
 ['2026-11-12','customer_support','Faro · traspaso reproducible','El caso vuelve de segundo nivel sin pasos de reproducción. Prepara un ejemplo mínimo, resultados esperados y observados, y condición de escalación.',['diagnosis','documentation']],
 ['2026-11-19','account_manager','Faro · expansión responsable','Ventas propone ampliar asientos. Hay uso alto y resultados pendientes. Presenta dos opciones y evita convertir una intención en compromiso de compra.',['negotiation','data']],
 ['2026-11-26','manager_team_lead','Faro · autonomía y seguimiento','Una persona reconoce conceptos, pero sus entregas requieren apoyo. Diseña un refuerzo con plazo, revisión y evidencia para comprobar transferencia.',['planning','collaboration']],
] as const;
export const WEEKLY_CASES:TrainingActivity[]=WEEKLY_CASE_SEEDS.map(([date,position,title,situation,competencies],i)=>({key:'weekly-faro-'+(i+1),title,route:'common',level:1,kind:'project',hours:1/3,competencies:[...competencies],lesson:situation,task:'Caso sintético de Cuenta Faro. Resuelve tres decisiones encadenadas y entrega un resumen con evidencia, alternativa, responsable y siguiente comprobación.',template:'Observación | Fuente ficticia | Decisiones | Alternativa | Riesgo | Responsable | Próxima comprobación',example:'Declara los datos faltantes; propone una prueba acotada y una actualización con responsable. Una propuesta no demuestra un resultado.',decisions:[
 {prompt:'Antes de actuar, ¿qué necesitas?',options:['Separar observación, hipótesis y dato faltante','Prometer el resultado sin comprobarlo'],correct:0,feedback:'La decisión parte de evidencia y límites explícitos.'},
 {prompt:'Aparece una restricción de capacidad. ¿Qué haces?',options:['Comparar dos alternativas y explicitar su riesgo','Mantener todas las promesas sin revisar'],correct:0,feedback:'Una restricción cambia la decisión y debe quedar registrada.'},
 {prompt:'¿Qué permite cerrar el caso?',options:['Una comprobación con criterio, responsable y fecha','La intención de que salga bien'],correct:0,feedback:'El cierre necesita evidencia verificable.'}],rubric:['1 · Reconoce el problema, pero no justifica la decisión.','2 · Justifica con guía y declara datos faltantes.','3 · Contrasta alternativas con evidencia y seguimiento verificable.','4 · Transfiere el criterio ante una restricción nueva; requiere revisión humana.'],optionalPractice:[],sourceUrls:[]}));
export function publishedWeeklyCases(now=new Date()){return WEEKLY_CASES.filter((_,i)=>Date.parse(WEEKLY_CASE_SEEDS[i][0]+'T00:00:00-06:00')<=now.getTime());}
export function weeklyCaseForPosition(position:string|null,now=new Date()){return publishedWeeklyCases(now).filter(c=>{const i=WEEKLY_CASES.indexOf(c);return !position||WEEKLY_CASE_SEEDS[i][1]===position||(position.startsWith('tech_support')&&WEEKLY_CASE_SEEDS[i][1]==='customer_support');}).at(-1)??null;}
