-- Schema-only bootstrap; NEVER apply to production.
begin;
set local search_path=public,extensions;
set local check_function_bodies=off;
create type "public"."user_role" as enum ('user','admin','owner');
create type "public"."account_status" as enum ('active','suspended','cancelled');
create table public."account_addons" (
"user_id" uuid not null,
"addon_key" text not null,
"status" text default 'inactive'::text not null,
"stripe_customer_id" text,
"stripe_subscription_id" text,
"stripe_schedule_id" text,
"current_price_id" text,
"cancel_at_period_end" boolean default false not null,
"started_at" timestamp with time zone,
"updated_at" timestamp with time zone default now() not null
);
create table public."admin_audit_log" (
"id" bigint generated by default as identity not null,
"actor_user_id" uuid,
"action" text not null,
"target_type" text not null,
"target_id" text,
"metadata" jsonb default '{}'::jsonb not null,
"created_at" timestamp with time zone default now() not null
);
create table public."api_rate_limits" (
"bucket_key" text not null,
"bucket_start" timestamp with time zone not null,
"request_count" integer default 0 not null
);
create table public."certificates" (
"id" uuid default gen_random_uuid() not null,
"user_id" uuid not null,
"certificate_type" text default 'codezero-complete'::text not null,
"title" text not null,
"issued_at" timestamp with time zone default now() not null,
"metadata" jsonb default '{}'::jsonb not null
);
create table public."courses" (
"id" bigint generated by default as identity not null,
"slug" text not null,
"title" text not null,
"description" text,
"status" text default 'published'::text not null,
"created_at" timestamp with time zone default now() not null
);
create table public."exam_attempts" (
"id" bigint generated by default as identity not null,
"user_id" uuid not null,
"exam_id" bigint not null,
"score" integer not null,
"passed" boolean not null,
"answers" jsonb default '{}'::jsonb not null,
"created_at" timestamp with time zone default now() not null
);
create table public."exam_questions" (
"id" bigint generated by default as identity not null,
"exam_id" bigint not null,
"slug" text not null,
"prompt" text not null,
"options" jsonb default '[]'::jsonb not null,
"sort_order" integer not null,
"created_at" timestamp with time zone default now() not null
);
create table public."exam_solutions" (
"question_id" bigint not null,
"correct_answer" text not null
);
create table public."exercise_attempts" (
"id" bigint generated by default as identity not null,
"user_id" uuid not null,
"exercise_id" bigint not null,
"answer" text not null,
"is_correct" boolean not null,
"created_at" timestamp with time zone default now() not null
);
create table public."exercise_solutions" (
"exercise_id" bigint not null,
"correct_answer" text not null
);
create table public."exercises" (
"id" bigint generated by default as identity not null,
"lesson_id" bigint not null,
"slug" text not null,
"prompt" text not null,
"kind" text default 'multiple_choice'::text not null,
"options" jsonb default '[]'::jsonb not null,
"explanation" text,
"sort_order" integer default 1 not null,
"status" text default 'published'::text not null,
"created_at" timestamp with time zone default now() not null
);
create table public."lesson_progress" (
"id" bigint generated by default as identity not null,
"user_id" uuid not null,
"lesson_id" bigint not null,
"status" text default 'not_started'::text not null,
"progress_percent" integer default 0 not null,
"started_at" timestamp with time zone,
"completed_at" timestamp with time zone,
"updated_at" timestamp with time zone default now() not null
);
create table public."lessons" (
"id" bigint generated by default as identity not null,
"level_id" bigint not null,
"slug" text not null,
"title" text not null,
"description" text,
"content" text,
"estimated_minutes" integer default 15 not null,
"sort_order" integer not null,
"status" text default 'published'::text not null,
"created_at" timestamp with time zone default now() not null
);
create table public."level_exams" (
"id" bigint generated by default as identity not null,
"level_id" bigint not null,
"slug" text not null,
"title" text not null,
"description" text,
"passing_score" integer default 70 not null,
"question_count" integer default 3 not null,
"status" text default 'published'::text not null,
"created_at" timestamp with time zone default now() not null
);
create table public."level_projects" (
"id" bigint generated by default as identity not null,
"level_id" bigint not null,
"slug" text not null,
"title" text not null,
"brief" text not null,
"requirements" jsonb default '[]'::jsonb not null,
"status" text default 'published'::text not null,
"created_at" timestamp with time zone default now() not null
);
create table public."levels" (
"id" bigint generated by default as identity not null,
"course_id" bigint not null,
"level_number" integer not null,
"slug" text not null,
"title" text not null,
"description" text,
"estimated_hours" integer default 0 not null,
"sort_order" integer not null,
"status" text default 'published'::text not null,
"created_at" timestamp with time zone default now() not null
);
create table public."plans" (
"id" uuid default gen_random_uuid() not null,
"name" text not null,
"price_monthly_cents" integer default 0 not null,
"exercise_limit" integer not null,
"exam_limit" integer not null,
"ai_query_limit" integer not null,
"project_limit" integer not null,
"sort_order" integer default 0 not null,
"stripe_price_id" text,
"active" boolean default true not null
);
create table public."profiles" (
"id" uuid not null,
"email" text not null,
"full_name" text,
"role" user_role default 'user'::user_role not null,
"status" account_status default 'active'::account_status not null,
"plan_name" text default 'free'::text not null,
"stripe_customer_id" text,
"stripe_subscription_id" text,
"created_at" timestamp with time zone default now() not null,
"updated_at" timestamp with time zone default now() not null,
"billing_status" text,
"stripe_cancel_at_period_end" boolean default false not null
);
create table public."progress" (
"user_id" uuid not null,
"level" integer not null,
"mastery" numeric(5,2) default 0 not null,
"xp" integer default 0 not null,
"updated_at" timestamp with time zone default now() not null
);
create table public."project_submissions" (
"id" bigint generated by default as identity not null,
"user_id" uuid not null,
"project_id" bigint not null,
"submission_text" text not null,
"status" text default 'submitted'::text not null,
"score" integer,
"feedback" text,
"created_at" timestamp with time zone default now() not null,
"updated_at" timestamp with time zone default now() not null
);
create table public."stripe_webhook_events" (
"event_id" text not null,
"event_type" text not null,
"processed_at" timestamp with time zone,
"status" text default 'processed'::text not null,
"attempts" integer default 1 not null,
"last_error" text,
"updated_at" timestamp with time zone default now() not null
);
create table public."support_faq_feedback" (
"id" bigint generated by default as identity not null,
"faq_id" bigint not null,
"user_id" uuid not null,
"helpful" boolean not null,
"query_text" text,
"created_at" timestamp with time zone default now() not null
);
create table public."support_faqs" (
"id" bigint generated by default as identity not null,
"slug" text not null,
"question" text not null,
"answer" text not null,
"category" text not null,
"keywords" text[] default '{}'::text[] not null,
"status" text default 'draft'::text not null,
"notion_url" text,
"sort_order" integer default 100 not null,
"search_vector" tsvector generated always as (to_tsvector('spanish'::regconfig, ((((COALESCE(question, ''::text) || ' '::text) || COALESCE(answer, ''::text)) || ' '::text) || COALESCE(category, ''::text)))) stored,
"created_at" timestamp with time zone default now() not null,
"updated_at" timestamp with time zone default now() not null
);
create table public."support_suggestions" (
"id" bigint generated by default as identity not null,
"user_id" uuid not null,
"title" text not null,
"detail" text not null,
"category" text default 'general'::text not null,
"status" text default 'new'::text not null,
"admin_notes" text,
"created_at" timestamp with time zone default now() not null,
"updated_at" timestamp with time zone default now() not null
);
create table public."support_ticket_messages" (
"id" bigint generated by default as identity not null,
"ticket_id" bigint not null,
"sender_user_id" uuid,
"sender_role" text not null,
"body" text not null,
"created_at" timestamp with time zone default now() not null
);
create table public."support_tickets" (
"id" bigint generated by default as identity not null,
"user_id" uuid not null,
"subject" text not null,
"description" text not null,
"category" text default 'general'::text not null,
"priority" text default 'normal'::text not null,
"status" text default 'open'::text not null,
"original_query" text,
"viewed_faq_ids" bigint[] default '{}'::bigint[] not null,
"assigned_to" uuid,
"resolved_at" timestamp with time zone,
"closed_at" timestamp with time zone,
"created_at" timestamp with time zone default now() not null,
"updated_at" timestamp with time zone default now() not null
);
create table public."usage_monthly" (
"user_id" uuid not null,
"period_start" date not null,
"exercises" integer default 0 not null,
"exams" integer default 0 not null,
"ai_queries" integer default 0 not null,
"projects" integer default 0 not null
);
alter table public."account_addons" add constraint "account_addons_key_check" CHECK (addon_key = 'ai_tutor'::text);
alter table public."account_addons" add constraint "account_addons_status_check" CHECK (status = ANY (ARRAY['inactive'::text, 'active'::text, 'past_due'::text, 'canceled'::text, 'incomplete'::text, 'unpaid'::text]));
alter table public."api_rate_limits" add constraint "api_rate_limits_request_count_check" CHECK (request_count >= 0);
alter table public."exam_attempts" add constraint "exam_attempts_score_check" CHECK (score >= 0 AND score <= 100);
alter table public."exam_questions" add constraint "exam_questions_options_four_check" CHECK (jsonb_typeof(options) = 'array'::text AND jsonb_array_length(options) = 4);
alter table public."exam_solutions" add constraint "exam_solutions_answer_check" CHECK (correct_answer = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text]));
alter table public."exercise_solutions" add constraint "exercise_solutions_answer_check" CHECK (correct_answer = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text]));
alter table public."exercises" add constraint "exercises_options_four_check" CHECK (jsonb_typeof(options) = 'array'::text AND jsonb_array_length(options) = 4);
alter table public."lesson_progress" add constraint "lesson_progress_progress_percent_check" CHECK (progress_percent >= 0 AND progress_percent <= 100);
alter table public."lessons" add constraint "lessons_estimated_minutes_check" CHECK (estimated_minutes > 0);
alter table public."level_exams" add constraint "level_exams_passing_score_check" CHECK (passing_score >= 0 AND passing_score <= 100);
alter table public."level_exams" add constraint "level_exams_question_count_check" CHECK (question_count > 0);
alter table public."levels" add constraint "levels_estimated_hours_check" CHECK (estimated_hours >= 0);
alter table public."profiles" add constraint "profiles_billing_status_check" CHECK (billing_status IS NULL OR (billing_status = ANY (ARRAY['active'::text, 'trialing'::text, 'past_due'::text, 'canceled'::text, 'unpaid'::text, 'incomplete'::text, 'incomplete_expired'::text, 'paused'::text])));
alter table public."profiles" add constraint "profiles_plan_name_check" CHECK (plan_name = ANY (ARRAY['free'::text, 'starter'::text, 'pro'::text, 'enterprise'::text]));
alter table public."project_submissions" add constraint "project_submissions_score_check" CHECK (score IS NULL OR score >= 0 AND score <= 100);
alter table public."project_submissions" add constraint "project_submissions_status_check" CHECK (status = ANY (ARRAY['submitted'::text, 'needs_revision'::text, 'approved'::text]));
alter table public."stripe_webhook_events" add constraint "stripe_webhook_events_attempts_check" CHECK (attempts >= 1);
alter table public."stripe_webhook_events" add constraint "stripe_webhook_events_status_check" CHECK (status = ANY (ARRAY['processing'::text, 'processed'::text, 'failed'::text]));
alter table public."support_faqs" add constraint "support_faqs_sort_order_check" CHECK (sort_order >= 0);
alter table public."support_faqs" add constraint "support_faqs_status_check" CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text]));
alter table public."support_suggestions" add constraint "support_suggestions_detail_check" CHECK (char_length(detail) >= 10 AND char_length(detail) <= 5000);
alter table public."support_suggestions" add constraint "support_suggestions_status_check" CHECK (status = ANY (ARRAY['new'::text, 'reviewing'::text, 'planned'::text, 'implemented'::text, 'declined'::text]));
alter table public."support_suggestions" add constraint "support_suggestions_title_check" CHECK (char_length(title) >= 3 AND char_length(title) <= 160);
alter table public."support_ticket_messages" add constraint "support_ticket_messages_body_check" CHECK (char_length(body) >= 1 AND char_length(body) <= 8000);
alter table public."support_ticket_messages" add constraint "support_ticket_messages_sender_role_check" CHECK (sender_role = ANY (ARRAY['user'::text, 'admin'::text, 'system'::text]));
alter table public."support_tickets" add constraint "support_tickets_description_check" CHECK (char_length(description) >= 10 AND char_length(description) <= 8000);
alter table public."support_tickets" add constraint "support_tickets_priority_check" CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text]));
alter table public."support_tickets" add constraint "support_tickets_status_check" CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'waiting_user'::text, 'resolved'::text, 'closed'::text]));
alter table public."support_tickets" add constraint "support_tickets_subject_check" CHECK (char_length(subject) >= 3 AND char_length(subject) <= 180);
alter table public."usage_monthly" add constraint "usage_monthly_nonnegative_check" CHECK (exercises >= 0 AND exams >= 0 AND ai_queries >= 0 AND projects >= 0);
alter table public."account_addons" add constraint "account_addons_pkey" PRIMARY KEY (user_id, addon_key);
alter table public."admin_audit_log" add constraint "admin_audit_log_pkey" PRIMARY KEY (id);
alter table public."api_rate_limits" add constraint "api_rate_limits_pkey" PRIMARY KEY (bucket_key, bucket_start);
alter table public."certificates" add constraint "certificates_pkey" PRIMARY KEY (id);
alter table public."courses" add constraint "courses_pkey" PRIMARY KEY (id);
alter table public."exam_attempts" add constraint "exam_attempts_pkey" PRIMARY KEY (id);
alter table public."exam_questions" add constraint "exam_questions_pkey" PRIMARY KEY (id);
alter table public."exam_solutions" add constraint "exam_solutions_pkey" PRIMARY KEY (question_id);
alter table public."exercise_attempts" add constraint "exercise_attempts_pkey" PRIMARY KEY (id);
alter table public."exercise_solutions" add constraint "exercise_solutions_pkey" PRIMARY KEY (exercise_id);
alter table public."exercises" add constraint "exercises_pkey" PRIMARY KEY (id);
alter table public."lesson_progress" add constraint "lesson_progress_pkey" PRIMARY KEY (id);
alter table public."lessons" add constraint "lessons_pkey" PRIMARY KEY (id);
alter table public."level_exams" add constraint "level_exams_pkey" PRIMARY KEY (id);
alter table public."level_projects" add constraint "level_projects_pkey" PRIMARY KEY (id);
alter table public."levels" add constraint "levels_pkey" PRIMARY KEY (id);
alter table public."plans" add constraint "plans_pkey" PRIMARY KEY (id);
alter table public."profiles" add constraint "profiles_pkey" PRIMARY KEY (id);
alter table public."progress" add constraint "progress_pkey" PRIMARY KEY (user_id, level);
alter table public."project_submissions" add constraint "project_submissions_pkey" PRIMARY KEY (id);
alter table public."stripe_webhook_events" add constraint "stripe_webhook_events_pkey" PRIMARY KEY (event_id);
alter table public."support_faq_feedback" add constraint "support_faq_feedback_pkey" PRIMARY KEY (id);
alter table public."support_faqs" add constraint "support_faqs_pkey" PRIMARY KEY (id);
alter table public."support_suggestions" add constraint "support_suggestions_pkey" PRIMARY KEY (id);
alter table public."support_ticket_messages" add constraint "support_ticket_messages_pkey" PRIMARY KEY (id);
alter table public."support_tickets" add constraint "support_tickets_pkey" PRIMARY KEY (id);
alter table public."usage_monthly" add constraint "usage_monthly_pkey" PRIMARY KEY (user_id, period_start);
alter table public."account_addons" add constraint "account_addons_stripe_subscription_id_key" UNIQUE (stripe_subscription_id);
alter table public."certificates" add constraint "certificates_user_id_certificate_type_key" UNIQUE (user_id, certificate_type);
alter table public."courses" add constraint "courses_slug_key" UNIQUE (slug);
alter table public."exam_questions" add constraint "exam_questions_slug_key" UNIQUE (slug);
alter table public."exercises" add constraint "exercises_slug_key" UNIQUE (slug);
alter table public."lesson_progress" add constraint "lesson_progress_user_id_lesson_id_key" UNIQUE (user_id, lesson_id);
alter table public."lessons" add constraint "lessons_slug_key" UNIQUE (slug);
alter table public."level_exams" add constraint "level_exams_level_id_key" UNIQUE (level_id);
alter table public."level_exams" add constraint "level_exams_slug_key" UNIQUE (slug);
alter table public."level_projects" add constraint "level_projects_slug_key" UNIQUE (slug);
alter table public."levels" add constraint "levels_course_id_level_number_key" UNIQUE (course_id, level_number);
alter table public."levels" add constraint "levels_slug_key" UNIQUE (slug);
alter table public."plans" add constraint "plans_name_key" UNIQUE (name);
alter table public."support_faqs" add constraint "support_faqs_slug_key" UNIQUE (slug);
alter table public."account_addons" add constraint "account_addons_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."admin_audit_log" add constraint "admin_audit_log_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public."certificates" add constraint "certificates_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."exam_attempts" add constraint "exam_attempts_exam_id_fkey" FOREIGN KEY (exam_id) REFERENCES level_exams(id) ON DELETE CASCADE;
alter table public."exam_attempts" add constraint "exam_attempts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."exam_questions" add constraint "exam_questions_exam_id_fkey" FOREIGN KEY (exam_id) REFERENCES level_exams(id) ON DELETE CASCADE;
alter table public."exam_solutions" add constraint "exam_solutions_question_id_fkey" FOREIGN KEY (question_id) REFERENCES exam_questions(id) ON DELETE CASCADE;
alter table public."exercise_attempts" add constraint "exercise_attempts_exercise_id_fkey" FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE;
alter table public."exercise_attempts" add constraint "exercise_attempts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."exercise_solutions" add constraint "exercise_solutions_exercise_id_fkey" FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE;
alter table public."exercises" add constraint "exercises_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE;
alter table public."lesson_progress" add constraint "lesson_progress_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE;
alter table public."lesson_progress" add constraint "lesson_progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."lessons" add constraint "lessons_level_id_fkey" FOREIGN KEY (level_id) REFERENCES levels(id) ON DELETE CASCADE;
alter table public."level_exams" add constraint "level_exams_level_id_fkey" FOREIGN KEY (level_id) REFERENCES levels(id) ON DELETE CASCADE;
alter table public."level_projects" add constraint "level_projects_level_id_fkey" FOREIGN KEY (level_id) REFERENCES levels(id) ON DELETE CASCADE;
alter table public."levels" add constraint "levels_course_id_fkey" FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE;
alter table public."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."progress" add constraint "progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."project_submissions" add constraint "project_submissions_project_id_fkey" FOREIGN KEY (project_id) REFERENCES level_projects(id) ON DELETE CASCADE;
alter table public."project_submissions" add constraint "project_submissions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."support_faq_feedback" add constraint "support_faq_feedback_faq_id_fkey" FOREIGN KEY (faq_id) REFERENCES support_faqs(id) ON DELETE CASCADE;
alter table public."support_faq_feedback" add constraint "support_faq_feedback_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."support_suggestions" add constraint "support_suggestions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."support_ticket_messages" add constraint "support_ticket_messages_sender_user_id_fkey" FOREIGN KEY (sender_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public."support_ticket_messages" add constraint "support_ticket_messages_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
alter table public."support_tickets" add constraint "support_tickets_assigned_to_fkey" FOREIGN KEY (assigned_to) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public."support_tickets" add constraint "support_tickets_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."usage_monthly" add constraint "usage_monthly_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
CREATE INDEX account_addons_subscription_idx ON public.account_addons USING btree (stripe_subscription_id);
CREATE INDEX admin_audit_log_created_at_idx ON public.admin_audit_log USING btree (created_at DESC);
CREATE INDEX admin_audit_log_actor_idx ON public.admin_audit_log USING btree (actor_user_id);
CREATE INDEX certificates_user_id_idx ON public.certificates USING btree (user_id);
CREATE INDEX exam_attempts_user_exam_idx ON public.exam_attempts USING btree (user_id, exam_id);
CREATE INDEX exam_attempts_exam_id_idx ON public.exam_attempts USING btree (exam_id);
CREATE INDEX exam_questions_exam_id_idx ON public.exam_questions USING btree (exam_id);
CREATE INDEX exercise_attempts_user_exercise_idx ON public.exercise_attempts USING btree (user_id, exercise_id);
CREATE INDEX exercise_attempts_exercise_id_idx ON public.exercise_attempts USING btree (exercise_id);
CREATE INDEX exercises_lesson_id_idx ON public.exercises USING btree (lesson_id);
CREATE INDEX lesson_progress_lesson_id_idx ON public.lesson_progress USING btree (lesson_id);
CREATE INDEX lessons_level_id_idx ON public.lessons USING btree (level_id);
CREATE INDEX level_exams_level_id_idx ON public.level_exams USING btree (level_id);
CREATE INDEX level_projects_level_id_idx ON public.level_projects USING btree (level_id);
CREATE INDEX profiles_plan_idx ON public.profiles USING btree (plan_name);
CREATE INDEX profiles_status_idx ON public.profiles USING btree (status);
CREATE INDEX project_submissions_project_id_idx ON public.project_submissions USING btree (project_id);
CREATE INDEX project_submissions_user_id_idx ON public.project_submissions USING btree (user_id);
CREATE INDEX support_faq_feedback_user_idx ON public.support_faq_feedback USING btree (user_id, created_at DESC);
CREATE INDEX support_faq_feedback_faq_idx ON public.support_faq_feedback USING btree (faq_id, created_at DESC);
CREATE INDEX support_faqs_category_idx ON public.support_faqs USING btree (category, status, sort_order);
CREATE INDEX support_faqs_search_idx ON public.support_faqs USING gin (search_vector);
CREATE INDEX support_suggestions_status_idx ON public.support_suggestions USING btree (status, created_at DESC);
CREATE INDEX support_suggestions_user_idx ON public.support_suggestions USING btree (user_id, created_at DESC);
CREATE INDEX support_ticket_messages_ticket_idx ON public.support_ticket_messages USING btree (ticket_id, created_at);
CREATE INDEX support_ticket_messages_sender_idx ON public.support_ticket_messages USING btree (sender_user_id);
CREATE INDEX support_tickets_queue_idx ON public.support_tickets USING btree (status, priority, created_at);
CREATE INDEX support_tickets_user_idx ON public.support_tickets USING btree (user_id, created_at DESC);
CREATE INDEX support_tickets_assigned_to_idx ON public.support_tickets USING btree (assigned_to);
CREATE INDEX usage_period_idx ON public.usage_monthly USING btree (period_start);
CREATE OR REPLACE FUNCTION public.can_read_level(p_level_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.profiles p
    join public.levels lv on lv.id = p_level_id
    where p.id = auth.uid()
      and p.status = 'active'
      and (
        p.role in ('owner','admin')
        or p.plan_name in ('starter','pro','enterprise')
        or lv.level_number = 1
      )
  );
$function$
;
CREATE OR REPLACE FUNCTION public.consume_api_rate_limit(p_bucket_key text, p_limit integer, p_window_seconds integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_bucket_start timestamptz;
  v_count integer;
begin
  if auth.role() <> 'service_role' then
    raise exception 'not authorized';
  end if;

  if p_bucket_key is null or length(p_bucket_key) < 3 or p_limit <= 0 or p_window_seconds <= 0 then
    raise exception 'invalid arguments';
  end if;

  v_bucket_start :=
    to_timestamp(
      floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds
    );

  insert into public.api_rate_limits(bucket_key, bucket_start, request_count)
  values (p_bucket_key, v_bucket_start, 1)
  on conflict (bucket_key, bucket_start)
  do update set request_count = public.api_rate_limits.request_count + 1
  returning request_count into v_count;

  delete from public.api_rate_limits
  where bucket_start < now() - interval '2 days';

  return jsonb_build_object(
    'allowed', v_count <= p_limit,
    'count', v_count,
    'limit', p_limit,
    'retry_after_seconds',
      case
        when v_count <= p_limit then 0
        else greatest(
          1,
          ceil(
            extract(
              epoch from (
                v_bucket_start + make_interval(secs => p_window_seconds) - now()
              )
            )
          )::integer
        )
      end
  );
end;
$function$
;
CREATE OR REPLACE FUNCTION public.consume_quota(p_user_id uuid, p_metric text, p_amount integer DEFAULT 1)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  current_used integer;
  max_allowed integer;
  new_used integer;
begin
  if auth.role() <> 'service_role' then
    raise exception 'not authorized';
  end if;

  if p_user_id is null or p_amount <= 0 then
    raise exception 'invalid arguments';
  end if;

  select case p_metric
    when 'exercises' then exercise_limit
    when 'exams' then exam_limit
    when 'ai_queries' then ai_query_limit
    when 'projects' then project_limit
    else null
  end
  into max_allowed
  from public.account_entitlements
  where user_id = p_user_id;

  if max_allowed is null then
    raise exception 'invalid metric or entitlement';
  end if;

  insert into public.usage_monthly(user_id, period_start)
  values (p_user_id, date_trunc('month', now())::date)
  on conflict do nothing;

  execute format(
    'select %I from public.usage_monthly where user_id=$1 and period_start=date_trunc(''month'',now())::date for update',
    p_metric
  )
  into current_used
  using p_user_id;

  if max_allowed >= 0 and current_used + p_amount > max_allowed then
    return jsonb_build_object(
      'allowed', false,
      'used', current_used,
      'limit', max_allowed,
      'remaining', greatest(0, max_allowed-current_used)
    );
  end if;

  execute format(
    'update public.usage_monthly set %I=%I+$1 where user_id=$2 and period_start=date_trunc(''month'',now())::date',
    p_metric, p_metric
  )
  using p_amount, p_user_id;

  new_used := current_used + p_amount;

  return jsonb_build_object(
    'allowed', true,
    'used', new_used,
    'limit', max_allowed,
    'remaining', case when max_allowed < 0 then -1 else max_allowed-new_used end
  );
end;
$function$
;
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles(id,email) values(new.id,new.email);
  insert into public.usage_monthly(user_id,period_start)
  values(new.id,date_trunc('month',now())::date);
  return new;
end; $function$
;
CREATE OR REPLACE FUNCTION public.release_quota(p_user_id uuid, p_metric text, p_amount integer DEFAULT 1)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if auth.role() <> 'service_role' then
    raise exception 'not authorized';
  end if;

  if p_user_id is null or p_amount <= 0 or p_metric not in ('exercises','exams','ai_queries','projects') then
    raise exception 'invalid arguments';
  end if;

  execute format(
    'update public.usage_monthly
     set %I=greatest(0,%I-$1)
     where user_id=$2 and period_start=date_trunc(''month'',now())::date',
    p_metric, p_metric
  )
  using p_amount, p_user_id;
end;
$function$
;
create view public."account_entitlements" with (security_invoker=true) as  SELECT p.id AS user_id,
    p.plan_name,
    COALESCE(pl.exercise_limit, 20) AS exercise_limit,
    COALESCE(pl.exam_limit, 1) AS exam_limit,
        CASE
            WHEN (EXISTS ( SELECT 1
               FROM account_addons aa
              WHERE aa.user_id = p.id AND aa.addon_key = 'ai_tutor'::text AND aa.status = 'active'::text)) THEN 100
            ELSE 0
        END AS ai_query_limit,
    COALESCE(pl.project_limit, 1) AS project_limit,
    jsonb_build_object('exercises', COALESCE(u.exercises, 0), 'exams', COALESCE(u.exams, 0), 'ai_queries', COALESCE(u.ai_queries, 0), 'projects', COALESCE(u.projects, 0)) AS usage
   FROM profiles p
     LEFT JOIN plans pl ON pl.name = p.plan_name
     LEFT JOIN usage_monthly u ON u.user_id = p.id AND u.period_start = date_trunc('month'::text, now())::date;
alter table public."account_addons" enable row level security;
alter table public."admin_audit_log" enable row level security;
alter table public."api_rate_limits" enable row level security;
alter table public."certificates" enable row level security;
alter table public."courses" enable row level security;
alter table public."exam_attempts" enable row level security;
alter table public."exam_questions" enable row level security;
alter table public."exam_solutions" enable row level security;
alter table public."exercise_attempts" enable row level security;
alter table public."exercise_solutions" enable row level security;
alter table public."exercises" enable row level security;
alter table public."lesson_progress" enable row level security;
alter table public."lessons" enable row level security;
alter table public."level_exams" enable row level security;
alter table public."level_projects" enable row level security;
alter table public."levels" enable row level security;
alter table public."plans" enable row level security;
alter table public."profiles" enable row level security;
alter table public."progress" enable row level security;
alter table public."project_submissions" enable row level security;
alter table public."stripe_webhook_events" enable row level security;
alter table public."support_faq_feedback" enable row level security;
alter table public."support_faqs" enable row level security;
alter table public."support_suggestions" enable row level security;
alter table public."support_ticket_messages" enable row level security;
alter table public."support_tickets" enable row level security;
alter table public."usage_monthly" enable row level security;
create policy "Users can read own addons" on public."account_addons" as PERMISSIVE for SELECT to "authenticated" using ((( SELECT auth.uid() AS uid) = user_id));
create policy "No client access to admin audit log" on public."admin_audit_log" as PERMISSIVE for ALL to "anon","authenticated" using (false) with check (false);
create policy "No client access to api rate limits" on public."api_rate_limits" as PERMISSIVE for ALL to "anon","authenticated" using (false) with check (false);
create policy "Users can read own certificates" on public."certificates" as PERMISSIVE for SELECT to "authenticated" using ((( SELECT auth.uid() AS uid) = user_id));
create policy "Authenticated users can read courses" on public."courses" as PERMISSIVE for SELECT to "authenticated" using ((status = 'published'::text));
create policy "Users can read own exam attempts" on public."exam_attempts" as PERMISSIVE for SELECT to "authenticated" using ((user_id = ( SELECT auth.uid() AS uid)));
create policy "Users can read entitled exam questions" on public."exam_questions" as PERMISSIVE for SELECT to "authenticated" using ((EXISTS ( SELECT 1
   FROM level_exams e
  WHERE (e.id = exam_questions.exam_id))));
create policy "No client access to exam solutions" on public."exam_solutions" as PERMISSIVE for ALL to "anon","authenticated" using (false) with check (false);
create policy "Users can read own exercise attempts" on public."exercise_attempts" as PERMISSIVE for SELECT to "authenticated" using ((user_id = ( SELECT auth.uid() AS uid)));
create policy "No client access to exercise solutions" on public."exercise_solutions" as PERMISSIVE for ALL to "anon","authenticated" using (false) with check (false);
create policy "Users can read entitled exercises" on public."exercises" as PERMISSIVE for SELECT to "authenticated" using (((status = 'published'::text) AND (EXISTS ( SELECT 1
   FROM lessons l
  WHERE (l.id = exercises.lesson_id)))));
create policy "Users can read own lesson progress" on public."lesson_progress" as PERMISSIVE for SELECT to "authenticated" using ((user_id = ( SELECT auth.uid() AS uid)));
create policy "Users can read entitled lessons" on public."lessons" as PERMISSIVE for SELECT to "authenticated" using (((status = 'published'::text) AND (EXISTS ( SELECT 1
   FROM levels lv
  WHERE (lv.id = lessons.level_id)))));
create policy "Users can read entitled exams" on public."level_exams" as PERMISSIVE for SELECT to "authenticated" using (((status = 'published'::text) AND (EXISTS ( SELECT 1
   FROM levels lv
  WHERE (lv.id = level_exams.level_id)))));
create policy "Users can read entitled projects" on public."level_projects" as PERMISSIVE for SELECT to "authenticated" using (((status = 'published'::text) AND (EXISTS ( SELECT 1
   FROM levels lv
  WHERE (lv.id = level_projects.level_id)))));
create policy "Users can read entitled levels" on public."levels" as PERMISSIVE for SELECT to "authenticated" using (((status = 'published'::text) AND (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.status = 'active'::account_status) AND ((p.role = ANY (ARRAY['owner'::user_role, 'admin'::user_role])) OR (p.plan_name = ANY (ARRAY['starter'::text, 'pro'::text, 'enterprise'::text])) OR (levels.level_number = 1)))))));
create policy "plans are readable" on public."plans" as PERMISSIVE for SELECT to "authenticated" using ((active = true));
create policy "users read own profile" on public."profiles" as PERMISSIVE for SELECT to "authenticated" using ((id = ( SELECT auth.uid() AS uid)));
create policy "users read own progress" on public."progress" as PERMISSIVE for SELECT to "authenticated" using ((user_id = ( SELECT auth.uid() AS uid)));
create policy "Users can read own project submissions" on public."project_submissions" as PERMISSIVE for SELECT to "authenticated" using ((user_id = ( SELECT auth.uid() AS uid)));
create policy "No client access to Stripe webhook events" on public."stripe_webhook_events" as PERMISSIVE for ALL to "anon","authenticated" using (false) with check (false);
create policy "Users can submit own FAQ feedback" on public."support_faq_feedback" as PERMISSIVE for INSERT to "authenticated" with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Anyone can read published support FAQs" on public."support_faqs" as PERMISSIVE for SELECT to "anon","authenticated" using ((status = 'published'::text));
create policy "Users can create own suggestions" on public."support_suggestions" as PERMISSIVE for INSERT to "authenticated" with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can read own suggestions" on public."support_suggestions" as PERMISSIVE for SELECT to "authenticated" using ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can read messages on own tickets" on public."support_ticket_messages" as PERMISSIVE for SELECT to "authenticated" using ((EXISTS ( SELECT 1
   FROM support_tickets t
  WHERE ((t.id = support_ticket_messages.ticket_id) AND (t.user_id = ( SELECT auth.uid() AS uid))))));
create policy "Users can reply to own tickets" on public."support_ticket_messages" as PERMISSIVE for INSERT to "authenticated" with check (((sender_role = 'user'::text) AND (sender_user_id = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1
   FROM support_tickets t
  WHERE ((t.id = support_ticket_messages.ticket_id) AND (t.user_id = ( SELECT auth.uid() AS uid)) AND (t.status <> 'closed'::text))))));
create policy "Users can create own tickets" on public."support_tickets" as PERMISSIVE for INSERT to "authenticated" with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can read own tickets" on public."support_tickets" as PERMISSIVE for SELECT to "authenticated" using ((( SELECT auth.uid() AS uid) = user_id));
create policy "users read own usage" on public."usage_monthly" as PERMISSIVE for SELECT to "authenticated" using ((user_id = ( SELECT auth.uid() AS uid)));
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
revoke all on all tables in schema public from public,anon,authenticated,service_role;
revoke all on all sequences in schema public from public,anon,authenticated,service_role;
grant SELECT on table public."account_entitlements" to "authenticated";
grant MAINTAIN on table public."account_entitlements" to "authenticated";
grant INSERT on table public."account_entitlements" to "service_role";
grant SELECT on table public."account_entitlements" to "service_role";
grant UPDATE on table public."account_entitlements" to "service_role";
grant DELETE on table public."account_entitlements" to "service_role";
grant TRUNCATE on table public."account_entitlements" to "service_role";
grant REFERENCES on table public."account_entitlements" to "service_role";
grant TRIGGER on table public."account_entitlements" to "service_role";
grant MAINTAIN on table public."account_entitlements" to "service_role";
grant SELECT on sequence public."lessons_id_seq" to "anon";
grant UPDATE on sequence public."lessons_id_seq" to "anon";
grant USAGE on sequence public."lessons_id_seq" to "anon";
grant SELECT on sequence public."lessons_id_seq" to "authenticated";
grant UPDATE on sequence public."lessons_id_seq" to "authenticated";
grant USAGE on sequence public."lessons_id_seq" to "authenticated";
grant SELECT on sequence public."lessons_id_seq" to "service_role";
grant UPDATE on sequence public."lessons_id_seq" to "service_role";
grant USAGE on sequence public."lessons_id_seq" to "service_role";
grant INSERT on table public."plans" to "authenticated";
grant SELECT on table public."plans" to "authenticated";
grant UPDATE on table public."plans" to "authenticated";
grant DELETE on table public."plans" to "authenticated";
grant TRUNCATE on table public."plans" to "authenticated";
grant REFERENCES on table public."plans" to "authenticated";
grant TRIGGER on table public."plans" to "authenticated";
grant MAINTAIN on table public."plans" to "authenticated";
grant INSERT on table public."plans" to "service_role";
grant SELECT on table public."plans" to "service_role";
grant UPDATE on table public."plans" to "service_role";
grant DELETE on table public."plans" to "service_role";
grant TRUNCATE on table public."plans" to "service_role";
grant REFERENCES on table public."plans" to "service_role";
grant TRIGGER on table public."plans" to "service_role";
grant MAINTAIN on table public."plans" to "service_role";
grant SELECT on sequence public."courses_id_seq" to "anon";
grant UPDATE on sequence public."courses_id_seq" to "anon";
grant USAGE on sequence public."courses_id_seq" to "anon";
grant SELECT on sequence public."courses_id_seq" to "authenticated";
grant UPDATE on sequence public."courses_id_seq" to "authenticated";
grant USAGE on sequence public."courses_id_seq" to "authenticated";
grant SELECT on sequence public."courses_id_seq" to "service_role";
grant UPDATE on sequence public."courses_id_seq" to "service_role";
grant USAGE on sequence public."courses_id_seq" to "service_role";
grant SELECT on sequence public."levels_id_seq" to "anon";
grant UPDATE on sequence public."levels_id_seq" to "anon";
grant USAGE on sequence public."levels_id_seq" to "anon";
grant SELECT on sequence public."levels_id_seq" to "authenticated";
grant UPDATE on sequence public."levels_id_seq" to "authenticated";
grant USAGE on sequence public."levels_id_seq" to "authenticated";
grant SELECT on sequence public."levels_id_seq" to "service_role";
grant UPDATE on sequence public."levels_id_seq" to "service_role";
grant USAGE on sequence public."levels_id_seq" to "service_role";
grant SELECT on table public."progress" to "authenticated";
grant TRUNCATE on table public."progress" to "authenticated";
grant REFERENCES on table public."progress" to "authenticated";
grant TRIGGER on table public."progress" to "authenticated";
grant MAINTAIN on table public."progress" to "authenticated";
grant INSERT on table public."progress" to "service_role";
grant SELECT on table public."progress" to "service_role";
grant UPDATE on table public."progress" to "service_role";
grant DELETE on table public."progress" to "service_role";
grant TRUNCATE on table public."progress" to "service_role";
grant REFERENCES on table public."progress" to "service_role";
grant TRIGGER on table public."progress" to "service_role";
grant MAINTAIN on table public."progress" to "service_role";
grant INSERT on table public."profiles" to "authenticated";
grant SELECT on table public."profiles" to "authenticated";
grant DELETE on table public."profiles" to "authenticated";
grant TRUNCATE on table public."profiles" to "authenticated";
grant REFERENCES on table public."profiles" to "authenticated";
grant TRIGGER on table public."profiles" to "authenticated";
grant MAINTAIN on table public."profiles" to "authenticated";
grant INSERT on table public."profiles" to "service_role";
grant SELECT on table public."profiles" to "service_role";
grant UPDATE on table public."profiles" to "service_role";
grant DELETE on table public."profiles" to "service_role";
grant TRUNCATE on table public."profiles" to "service_role";
grant REFERENCES on table public."profiles" to "service_role";
grant TRIGGER on table public."profiles" to "service_role";
grant MAINTAIN on table public."profiles" to "service_role";
grant SELECT on sequence public."lesson_progress_id_seq" to "anon";
grant UPDATE on sequence public."lesson_progress_id_seq" to "anon";
grant USAGE on sequence public."lesson_progress_id_seq" to "anon";
grant SELECT on sequence public."lesson_progress_id_seq" to "authenticated";
grant UPDATE on sequence public."lesson_progress_id_seq" to "authenticated";
grant USAGE on sequence public."lesson_progress_id_seq" to "authenticated";
grant SELECT on sequence public."lesson_progress_id_seq" to "service_role";
grant UPDATE on sequence public."lesson_progress_id_seq" to "service_role";
grant USAGE on sequence public."lesson_progress_id_seq" to "service_role";
grant INSERT on table public."usage_monthly" to "authenticated";
grant SELECT on table public."usage_monthly" to "authenticated";
grant UPDATE on table public."usage_monthly" to "authenticated";
grant DELETE on table public."usage_monthly" to "authenticated";
grant TRUNCATE on table public."usage_monthly" to "authenticated";
grant REFERENCES on table public."usage_monthly" to "authenticated";
grant TRIGGER on table public."usage_monthly" to "authenticated";
grant MAINTAIN on table public."usage_monthly" to "authenticated";
grant INSERT on table public."usage_monthly" to "service_role";
grant SELECT on table public."usage_monthly" to "service_role";
grant UPDATE on table public."usage_monthly" to "service_role";
grant DELETE on table public."usage_monthly" to "service_role";
grant TRUNCATE on table public."usage_monthly" to "service_role";
grant REFERENCES on table public."usage_monthly" to "service_role";
grant TRIGGER on table public."usage_monthly" to "service_role";
grant MAINTAIN on table public."usage_monthly" to "service_role";
grant INSERT on table public."courses" to "anon";
grant SELECT on table public."courses" to "anon";
grant UPDATE on table public."courses" to "anon";
grant DELETE on table public."courses" to "anon";
grant TRUNCATE on table public."courses" to "anon";
grant REFERENCES on table public."courses" to "anon";
grant TRIGGER on table public."courses" to "anon";
grant MAINTAIN on table public."courses" to "anon";
grant INSERT on table public."courses" to "authenticated";
grant SELECT on table public."courses" to "authenticated";
grant UPDATE on table public."courses" to "authenticated";
grant DELETE on table public."courses" to "authenticated";
grant TRUNCATE on table public."courses" to "authenticated";
grant REFERENCES on table public."courses" to "authenticated";
grant TRIGGER on table public."courses" to "authenticated";
grant MAINTAIN on table public."courses" to "authenticated";
grant INSERT on table public."courses" to "service_role";
grant SELECT on table public."courses" to "service_role";
grant UPDATE on table public."courses" to "service_role";
grant DELETE on table public."courses" to "service_role";
grant TRUNCATE on table public."courses" to "service_role";
grant REFERENCES on table public."courses" to "service_role";
grant TRIGGER on table public."courses" to "service_role";
grant MAINTAIN on table public."courses" to "service_role";
grant INSERT on table public."exercise_solutions" to "service_role";
grant SELECT on table public."exercise_solutions" to "service_role";
grant UPDATE on table public."exercise_solutions" to "service_role";
grant DELETE on table public."exercise_solutions" to "service_role";
grant TRUNCATE on table public."exercise_solutions" to "service_role";
grant REFERENCES on table public."exercise_solutions" to "service_role";
grant TRIGGER on table public."exercise_solutions" to "service_role";
grant MAINTAIN on table public."exercise_solutions" to "service_role";
grant INSERT on table public."lesson_progress" to "anon";
grant SELECT on table public."lesson_progress" to "anon";
grant UPDATE on table public."lesson_progress" to "anon";
grant DELETE on table public."lesson_progress" to "anon";
grant TRUNCATE on table public."lesson_progress" to "anon";
grant REFERENCES on table public."lesson_progress" to "anon";
grant TRIGGER on table public."lesson_progress" to "anon";
grant MAINTAIN on table public."lesson_progress" to "anon";
grant SELECT on table public."lesson_progress" to "authenticated";
grant TRUNCATE on table public."lesson_progress" to "authenticated";
grant REFERENCES on table public."lesson_progress" to "authenticated";
grant TRIGGER on table public."lesson_progress" to "authenticated";
grant MAINTAIN on table public."lesson_progress" to "authenticated";
grant INSERT on table public."lesson_progress" to "service_role";
grant SELECT on table public."lesson_progress" to "service_role";
grant UPDATE on table public."lesson_progress" to "service_role";
grant DELETE on table public."lesson_progress" to "service_role";
grant TRUNCATE on table public."lesson_progress" to "service_role";
grant REFERENCES on table public."lesson_progress" to "service_role";
grant TRIGGER on table public."lesson_progress" to "service_role";
grant MAINTAIN on table public."lesson_progress" to "service_role";
grant INSERT on table public."exercise_attempts" to "anon";
grant SELECT on table public."exercise_attempts" to "anon";
grant UPDATE on table public."exercise_attempts" to "anon";
grant DELETE on table public."exercise_attempts" to "anon";
grant TRUNCATE on table public."exercise_attempts" to "anon";
grant REFERENCES on table public."exercise_attempts" to "anon";
grant TRIGGER on table public."exercise_attempts" to "anon";
grant MAINTAIN on table public."exercise_attempts" to "anon";
grant SELECT on table public."exercise_attempts" to "authenticated";
grant TRUNCATE on table public."exercise_attempts" to "authenticated";
grant REFERENCES on table public."exercise_attempts" to "authenticated";
grant TRIGGER on table public."exercise_attempts" to "authenticated";
grant MAINTAIN on table public."exercise_attempts" to "authenticated";
grant INSERT on table public."exercise_attempts" to "service_role";
grant SELECT on table public."exercise_attempts" to "service_role";
grant UPDATE on table public."exercise_attempts" to "service_role";
grant DELETE on table public."exercise_attempts" to "service_role";
grant TRUNCATE on table public."exercise_attempts" to "service_role";
grant REFERENCES on table public."exercise_attempts" to "service_role";
grant TRIGGER on table public."exercise_attempts" to "service_role";
grant MAINTAIN on table public."exercise_attempts" to "service_role";
grant SELECT on sequence public."exercise_attempts_id_seq" to "anon";
grant UPDATE on sequence public."exercise_attempts_id_seq" to "anon";
grant USAGE on sequence public."exercise_attempts_id_seq" to "anon";
grant SELECT on sequence public."exercise_attempts_id_seq" to "authenticated";
grant UPDATE on sequence public."exercise_attempts_id_seq" to "authenticated";
grant USAGE on sequence public."exercise_attempts_id_seq" to "authenticated";
grant SELECT on sequence public."exercise_attempts_id_seq" to "service_role";
grant UPDATE on sequence public."exercise_attempts_id_seq" to "service_role";
grant USAGE on sequence public."exercise_attempts_id_seq" to "service_role";
grant INSERT on table public."lessons" to "anon";
grant SELECT on table public."lessons" to "anon";
grant UPDATE on table public."lessons" to "anon";
grant DELETE on table public."lessons" to "anon";
grant TRUNCATE on table public."lessons" to "anon";
grant REFERENCES on table public."lessons" to "anon";
grant TRIGGER on table public."lessons" to "anon";
grant MAINTAIN on table public."lessons" to "anon";
grant INSERT on table public."lessons" to "authenticated";
grant SELECT on table public."lessons" to "authenticated";
grant UPDATE on table public."lessons" to "authenticated";
grant DELETE on table public."lessons" to "authenticated";
grant TRUNCATE on table public."lessons" to "authenticated";
grant REFERENCES on table public."lessons" to "authenticated";
grant TRIGGER on table public."lessons" to "authenticated";
grant MAINTAIN on table public."lessons" to "authenticated";
grant INSERT on table public."lessons" to "service_role";
grant SELECT on table public."lessons" to "service_role";
grant UPDATE on table public."lessons" to "service_role";
grant DELETE on table public."lessons" to "service_role";
grant TRUNCATE on table public."lessons" to "service_role";
grant REFERENCES on table public."lessons" to "service_role";
grant TRIGGER on table public."lessons" to "service_role";
grant MAINTAIN on table public."lessons" to "service_role";
grant SELECT on sequence public."exercises_id_seq" to "anon";
grant UPDATE on sequence public."exercises_id_seq" to "anon";
grant USAGE on sequence public."exercises_id_seq" to "anon";
grant SELECT on sequence public."exercises_id_seq" to "authenticated";
grant UPDATE on sequence public."exercises_id_seq" to "authenticated";
grant USAGE on sequence public."exercises_id_seq" to "authenticated";
grant SELECT on sequence public."exercises_id_seq" to "service_role";
grant UPDATE on sequence public."exercises_id_seq" to "service_role";
grant USAGE on sequence public."exercises_id_seq" to "service_role";
grant INSERT on table public."levels" to "anon";
grant SELECT on table public."levels" to "anon";
grant UPDATE on table public."levels" to "anon";
grant DELETE on table public."levels" to "anon";
grant TRUNCATE on table public."levels" to "anon";
grant REFERENCES on table public."levels" to "anon";
grant TRIGGER on table public."levels" to "anon";
grant MAINTAIN on table public."levels" to "anon";
grant INSERT on table public."levels" to "authenticated";
grant SELECT on table public."levels" to "authenticated";
grant UPDATE on table public."levels" to "authenticated";
grant DELETE on table public."levels" to "authenticated";
grant TRUNCATE on table public."levels" to "authenticated";
grant REFERENCES on table public."levels" to "authenticated";
grant TRIGGER on table public."levels" to "authenticated";
grant MAINTAIN on table public."levels" to "authenticated";
grant INSERT on table public."levels" to "service_role";
grant SELECT on table public."levels" to "service_role";
grant UPDATE on table public."levels" to "service_role";
grant DELETE on table public."levels" to "service_role";
grant TRUNCATE on table public."levels" to "service_role";
grant REFERENCES on table public."levels" to "service_role";
grant TRIGGER on table public."levels" to "service_role";
grant MAINTAIN on table public."levels" to "service_role";
grant INSERT on table public."exercises" to "anon";
grant SELECT on table public."exercises" to "anon";
grant UPDATE on table public."exercises" to "anon";
grant DELETE on table public."exercises" to "anon";
grant TRUNCATE on table public."exercises" to "anon";
grant REFERENCES on table public."exercises" to "anon";
grant TRIGGER on table public."exercises" to "anon";
grant MAINTAIN on table public."exercises" to "anon";
grant INSERT on table public."exercises" to "authenticated";
grant SELECT on table public."exercises" to "authenticated";
grant UPDATE on table public."exercises" to "authenticated";
grant DELETE on table public."exercises" to "authenticated";
grant TRUNCATE on table public."exercises" to "authenticated";
grant REFERENCES on table public."exercises" to "authenticated";
grant TRIGGER on table public."exercises" to "authenticated";
grant MAINTAIN on table public."exercises" to "authenticated";
grant INSERT on table public."exercises" to "service_role";
grant SELECT on table public."exercises" to "service_role";
grant UPDATE on table public."exercises" to "service_role";
grant DELETE on table public."exercises" to "service_role";
grant TRUNCATE on table public."exercises" to "service_role";
grant REFERENCES on table public."exercises" to "service_role";
grant TRIGGER on table public."exercises" to "service_role";
grant MAINTAIN on table public."exercises" to "service_role";
grant SELECT on sequence public."level_exams_id_seq" to "anon";
grant UPDATE on sequence public."level_exams_id_seq" to "anon";
grant USAGE on sequence public."level_exams_id_seq" to "anon";
grant SELECT on sequence public."level_exams_id_seq" to "authenticated";
grant UPDATE on sequence public."level_exams_id_seq" to "authenticated";
grant USAGE on sequence public."level_exams_id_seq" to "authenticated";
grant SELECT on sequence public."level_exams_id_seq" to "service_role";
grant UPDATE on sequence public."level_exams_id_seq" to "service_role";
grant USAGE on sequence public."level_exams_id_seq" to "service_role";
grant SELECT on sequence public."level_projects_id_seq" to "anon";
grant UPDATE on sequence public."level_projects_id_seq" to "anon";
grant USAGE on sequence public."level_projects_id_seq" to "anon";
grant SELECT on sequence public."level_projects_id_seq" to "authenticated";
grant UPDATE on sequence public."level_projects_id_seq" to "authenticated";
grant USAGE on sequence public."level_projects_id_seq" to "authenticated";
grant SELECT on sequence public."level_projects_id_seq" to "service_role";
grant UPDATE on sequence public."level_projects_id_seq" to "service_role";
grant USAGE on sequence public."level_projects_id_seq" to "service_role";
grant SELECT on sequence public."exam_questions_id_seq" to "anon";
grant UPDATE on sequence public."exam_questions_id_seq" to "anon";
grant USAGE on sequence public."exam_questions_id_seq" to "anon";
grant SELECT on sequence public."exam_questions_id_seq" to "authenticated";
grant UPDATE on sequence public."exam_questions_id_seq" to "authenticated";
grant USAGE on sequence public."exam_questions_id_seq" to "authenticated";
grant SELECT on sequence public."exam_questions_id_seq" to "service_role";
grant UPDATE on sequence public."exam_questions_id_seq" to "service_role";
grant USAGE on sequence public."exam_questions_id_seq" to "service_role";
grant INSERT on table public."exam_questions" to "anon";
grant SELECT on table public."exam_questions" to "anon";
grant UPDATE on table public."exam_questions" to "anon";
grant DELETE on table public."exam_questions" to "anon";
grant TRUNCATE on table public."exam_questions" to "anon";
grant REFERENCES on table public."exam_questions" to "anon";
grant TRIGGER on table public."exam_questions" to "anon";
grant MAINTAIN on table public."exam_questions" to "anon";
grant INSERT on table public."exam_questions" to "authenticated";
grant SELECT on table public."exam_questions" to "authenticated";
grant UPDATE on table public."exam_questions" to "authenticated";
grant DELETE on table public."exam_questions" to "authenticated";
grant TRUNCATE on table public."exam_questions" to "authenticated";
grant REFERENCES on table public."exam_questions" to "authenticated";
grant TRIGGER on table public."exam_questions" to "authenticated";
grant MAINTAIN on table public."exam_questions" to "authenticated";
grant INSERT on table public."exam_questions" to "service_role";
grant SELECT on table public."exam_questions" to "service_role";
grant UPDATE on table public."exam_questions" to "service_role";
grant DELETE on table public."exam_questions" to "service_role";
grant TRUNCATE on table public."exam_questions" to "service_role";
grant REFERENCES on table public."exam_questions" to "service_role";
grant TRIGGER on table public."exam_questions" to "service_role";
grant MAINTAIN on table public."exam_questions" to "service_role";
grant SELECT on sequence public."exam_attempts_id_seq" to "anon";
grant UPDATE on sequence public."exam_attempts_id_seq" to "anon";
grant USAGE on sequence public."exam_attempts_id_seq" to "anon";
grant SELECT on sequence public."exam_attempts_id_seq" to "authenticated";
grant UPDATE on sequence public."exam_attempts_id_seq" to "authenticated";
grant USAGE on sequence public."exam_attempts_id_seq" to "authenticated";
grant SELECT on sequence public."exam_attempts_id_seq" to "service_role";
grant UPDATE on sequence public."exam_attempts_id_seq" to "service_role";
grant USAGE on sequence public."exam_attempts_id_seq" to "service_role";
grant INSERT on table public."exam_attempts" to "anon";
grant SELECT on table public."exam_attempts" to "anon";
grant UPDATE on table public."exam_attempts" to "anon";
grant DELETE on table public."exam_attempts" to "anon";
grant TRUNCATE on table public."exam_attempts" to "anon";
grant REFERENCES on table public."exam_attempts" to "anon";
grant TRIGGER on table public."exam_attempts" to "anon";
grant MAINTAIN on table public."exam_attempts" to "anon";
grant SELECT on table public."exam_attempts" to "authenticated";
grant TRUNCATE on table public."exam_attempts" to "authenticated";
grant REFERENCES on table public."exam_attempts" to "authenticated";
grant TRIGGER on table public."exam_attempts" to "authenticated";
grant MAINTAIN on table public."exam_attempts" to "authenticated";
grant INSERT on table public."exam_attempts" to "service_role";
grant SELECT on table public."exam_attempts" to "service_role";
grant UPDATE on table public."exam_attempts" to "service_role";
grant DELETE on table public."exam_attempts" to "service_role";
grant TRUNCATE on table public."exam_attempts" to "service_role";
grant REFERENCES on table public."exam_attempts" to "service_role";
grant TRIGGER on table public."exam_attempts" to "service_role";
grant MAINTAIN on table public."exam_attempts" to "service_role";
grant INSERT on table public."exam_solutions" to "service_role";
grant SELECT on table public."exam_solutions" to "service_role";
grant UPDATE on table public."exam_solutions" to "service_role";
grant DELETE on table public."exam_solutions" to "service_role";
grant TRUNCATE on table public."exam_solutions" to "service_role";
grant REFERENCES on table public."exam_solutions" to "service_role";
grant TRIGGER on table public."exam_solutions" to "service_role";
grant MAINTAIN on table public."exam_solutions" to "service_role";
grant INSERT on table public."level_exams" to "anon";
grant SELECT on table public."level_exams" to "anon";
grant UPDATE on table public."level_exams" to "anon";
grant DELETE on table public."level_exams" to "anon";
grant TRUNCATE on table public."level_exams" to "anon";
grant REFERENCES on table public."level_exams" to "anon";
grant TRIGGER on table public."level_exams" to "anon";
grant MAINTAIN on table public."level_exams" to "anon";
grant INSERT on table public."level_exams" to "authenticated";
grant SELECT on table public."level_exams" to "authenticated";
grant UPDATE on table public."level_exams" to "authenticated";
grant DELETE on table public."level_exams" to "authenticated";
grant TRUNCATE on table public."level_exams" to "authenticated";
grant REFERENCES on table public."level_exams" to "authenticated";
grant TRIGGER on table public."level_exams" to "authenticated";
grant MAINTAIN on table public."level_exams" to "authenticated";
grant INSERT on table public."level_exams" to "service_role";
grant SELECT on table public."level_exams" to "service_role";
grant UPDATE on table public."level_exams" to "service_role";
grant DELETE on table public."level_exams" to "service_role";
grant TRUNCATE on table public."level_exams" to "service_role";
grant REFERENCES on table public."level_exams" to "service_role";
grant TRIGGER on table public."level_exams" to "service_role";
grant MAINTAIN on table public."level_exams" to "service_role";
grant SELECT on sequence public."project_submissions_id_seq" to "anon";
grant UPDATE on sequence public."project_submissions_id_seq" to "anon";
grant USAGE on sequence public."project_submissions_id_seq" to "anon";
grant SELECT on sequence public."project_submissions_id_seq" to "authenticated";
grant UPDATE on sequence public."project_submissions_id_seq" to "authenticated";
grant USAGE on sequence public."project_submissions_id_seq" to "authenticated";
grant SELECT on sequence public."project_submissions_id_seq" to "service_role";
grant UPDATE on sequence public."project_submissions_id_seq" to "service_role";
grant USAGE on sequence public."project_submissions_id_seq" to "service_role";
grant SELECT on table public."account_addons" to "anon";
grant MAINTAIN on table public."account_addons" to "anon";
grant SELECT on table public."account_addons" to "authenticated";
grant MAINTAIN on table public."account_addons" to "authenticated";
grant INSERT on table public."account_addons" to "service_role";
grant SELECT on table public."account_addons" to "service_role";
grant UPDATE on table public."account_addons" to "service_role";
grant DELETE on table public."account_addons" to "service_role";
grant TRUNCATE on table public."account_addons" to "service_role";
grant REFERENCES on table public."account_addons" to "service_role";
grant TRIGGER on table public."account_addons" to "service_role";
grant MAINTAIN on table public."account_addons" to "service_role";
grant INSERT on table public."level_projects" to "anon";
grant SELECT on table public."level_projects" to "anon";
grant UPDATE on table public."level_projects" to "anon";
grant DELETE on table public."level_projects" to "anon";
grant TRUNCATE on table public."level_projects" to "anon";
grant REFERENCES on table public."level_projects" to "anon";
grant TRIGGER on table public."level_projects" to "anon";
grant MAINTAIN on table public."level_projects" to "anon";
grant INSERT on table public."level_projects" to "authenticated";
grant SELECT on table public."level_projects" to "authenticated";
grant UPDATE on table public."level_projects" to "authenticated";
grant DELETE on table public."level_projects" to "authenticated";
grant TRUNCATE on table public."level_projects" to "authenticated";
grant REFERENCES on table public."level_projects" to "authenticated";
grant TRIGGER on table public."level_projects" to "authenticated";
grant MAINTAIN on table public."level_projects" to "authenticated";
grant INSERT on table public."level_projects" to "service_role";
grant SELECT on table public."level_projects" to "service_role";
grant UPDATE on table public."level_projects" to "service_role";
grant DELETE on table public."level_projects" to "service_role";
grant TRUNCATE on table public."level_projects" to "service_role";
grant REFERENCES on table public."level_projects" to "service_role";
grant TRIGGER on table public."level_projects" to "service_role";
grant MAINTAIN on table public."level_projects" to "service_role";
grant INSERT on table public."project_submissions" to "anon";
grant SELECT on table public."project_submissions" to "anon";
grant UPDATE on table public."project_submissions" to "anon";
grant DELETE on table public."project_submissions" to "anon";
grant TRUNCATE on table public."project_submissions" to "anon";
grant REFERENCES on table public."project_submissions" to "anon";
grant TRIGGER on table public."project_submissions" to "anon";
grant MAINTAIN on table public."project_submissions" to "anon";
grant SELECT on table public."project_submissions" to "authenticated";
grant TRUNCATE on table public."project_submissions" to "authenticated";
grant REFERENCES on table public."project_submissions" to "authenticated";
grant TRIGGER on table public."project_submissions" to "authenticated";
grant MAINTAIN on table public."project_submissions" to "authenticated";
grant INSERT on table public."project_submissions" to "service_role";
grant SELECT on table public."project_submissions" to "service_role";
grant UPDATE on table public."project_submissions" to "service_role";
grant DELETE on table public."project_submissions" to "service_role";
grant TRUNCATE on table public."project_submissions" to "service_role";
grant REFERENCES on table public."project_submissions" to "service_role";
grant TRIGGER on table public."project_submissions" to "service_role";
grant MAINTAIN on table public."project_submissions" to "service_role";
grant INSERT on table public."certificates" to "anon";
grant SELECT on table public."certificates" to "anon";
grant UPDATE on table public."certificates" to "anon";
grant DELETE on table public."certificates" to "anon";
grant TRUNCATE on table public."certificates" to "anon";
grant REFERENCES on table public."certificates" to "anon";
grant TRIGGER on table public."certificates" to "anon";
grant MAINTAIN on table public."certificates" to "anon";
grant INSERT on table public."certificates" to "authenticated";
grant SELECT on table public."certificates" to "authenticated";
grant UPDATE on table public."certificates" to "authenticated";
grant DELETE on table public."certificates" to "authenticated";
grant TRUNCATE on table public."certificates" to "authenticated";
grant REFERENCES on table public."certificates" to "authenticated";
grant TRIGGER on table public."certificates" to "authenticated";
grant MAINTAIN on table public."certificates" to "authenticated";
grant INSERT on table public."certificates" to "service_role";
grant SELECT on table public."certificates" to "service_role";
grant UPDATE on table public."certificates" to "service_role";
grant DELETE on table public."certificates" to "service_role";
grant TRUNCATE on table public."certificates" to "service_role";
grant REFERENCES on table public."certificates" to "service_role";
grant TRIGGER on table public."certificates" to "service_role";
grant MAINTAIN on table public."certificates" to "service_role";
grant INSERT on table public."stripe_webhook_events" to "service_role";
grant SELECT on table public."stripe_webhook_events" to "service_role";
grant UPDATE on table public."stripe_webhook_events" to "service_role";
grant DELETE on table public."stripe_webhook_events" to "service_role";
grant TRUNCATE on table public."stripe_webhook_events" to "service_role";
grant REFERENCES on table public."stripe_webhook_events" to "service_role";
grant TRIGGER on table public."stripe_webhook_events" to "service_role";
grant MAINTAIN on table public."stripe_webhook_events" to "service_role";
grant SELECT on sequence public."admin_audit_log_id_seq" to "anon";
grant UPDATE on sequence public."admin_audit_log_id_seq" to "anon";
grant USAGE on sequence public."admin_audit_log_id_seq" to "anon";
grant SELECT on sequence public."admin_audit_log_id_seq" to "authenticated";
grant UPDATE on sequence public."admin_audit_log_id_seq" to "authenticated";
grant USAGE on sequence public."admin_audit_log_id_seq" to "authenticated";
grant SELECT on sequence public."admin_audit_log_id_seq" to "service_role";
grant UPDATE on sequence public."admin_audit_log_id_seq" to "service_role";
grant USAGE on sequence public."admin_audit_log_id_seq" to "service_role";
grant INSERT on table public."admin_audit_log" to "service_role";
grant SELECT on table public."admin_audit_log" to "service_role";
grant UPDATE on table public."admin_audit_log" to "service_role";
grant DELETE on table public."admin_audit_log" to "service_role";
grant TRUNCATE on table public."admin_audit_log" to "service_role";
grant REFERENCES on table public."admin_audit_log" to "service_role";
grant TRIGGER on table public."admin_audit_log" to "service_role";
grant MAINTAIN on table public."admin_audit_log" to "service_role";
grant INSERT on table public."api_rate_limits" to "service_role";
grant SELECT on table public."api_rate_limits" to "service_role";
grant UPDATE on table public."api_rate_limits" to "service_role";
grant DELETE on table public."api_rate_limits" to "service_role";
grant TRUNCATE on table public."api_rate_limits" to "service_role";
grant REFERENCES on table public."api_rate_limits" to "service_role";
grant TRIGGER on table public."api_rate_limits" to "service_role";
grant MAINTAIN on table public."api_rate_limits" to "service_role";
grant SELECT on sequence public."support_faqs_id_seq" to "anon";
grant UPDATE on sequence public."support_faqs_id_seq" to "anon";
grant USAGE on sequence public."support_faqs_id_seq" to "anon";
grant SELECT on sequence public."support_faqs_id_seq" to "authenticated";
grant UPDATE on sequence public."support_faqs_id_seq" to "authenticated";
grant USAGE on sequence public."support_faqs_id_seq" to "authenticated";
grant SELECT on sequence public."support_faqs_id_seq" to "service_role";
grant UPDATE on sequence public."support_faqs_id_seq" to "service_role";
grant USAGE on sequence public."support_faqs_id_seq" to "service_role";
grant SELECT on sequence public."support_faq_feedback_id_seq" to "anon";
grant UPDATE on sequence public."support_faq_feedback_id_seq" to "anon";
grant USAGE on sequence public."support_faq_feedback_id_seq" to "anon";
grant SELECT on sequence public."support_faq_feedback_id_seq" to "authenticated";
grant UPDATE on sequence public."support_faq_feedback_id_seq" to "authenticated";
grant USAGE on sequence public."support_faq_feedback_id_seq" to "authenticated";
grant SELECT on sequence public."support_faq_feedback_id_seq" to "service_role";
grant UPDATE on sequence public."support_faq_feedback_id_seq" to "service_role";
grant USAGE on sequence public."support_faq_feedback_id_seq" to "service_role";
grant SELECT on sequence public."support_suggestions_id_seq" to "anon";
grant UPDATE on sequence public."support_suggestions_id_seq" to "anon";
grant USAGE on sequence public."support_suggestions_id_seq" to "anon";
grant SELECT on sequence public."support_suggestions_id_seq" to "authenticated";
grant UPDATE on sequence public."support_suggestions_id_seq" to "authenticated";
grant USAGE on sequence public."support_suggestions_id_seq" to "authenticated";
grant SELECT on sequence public."support_suggestions_id_seq" to "service_role";
grant UPDATE on sequence public."support_suggestions_id_seq" to "service_role";
grant USAGE on sequence public."support_suggestions_id_seq" to "service_role";
grant SELECT on sequence public."support_tickets_id_seq" to "anon";
grant UPDATE on sequence public."support_tickets_id_seq" to "anon";
grant USAGE on sequence public."support_tickets_id_seq" to "anon";
grant SELECT on sequence public."support_tickets_id_seq" to "authenticated";
grant UPDATE on sequence public."support_tickets_id_seq" to "authenticated";
grant USAGE on sequence public."support_tickets_id_seq" to "authenticated";
grant SELECT on sequence public."support_tickets_id_seq" to "service_role";
grant UPDATE on sequence public."support_tickets_id_seq" to "service_role";
grant USAGE on sequence public."support_tickets_id_seq" to "service_role";
grant SELECT on sequence public."support_ticket_messages_id_seq" to "anon";
grant UPDATE on sequence public."support_ticket_messages_id_seq" to "anon";
grant USAGE on sequence public."support_ticket_messages_id_seq" to "anon";
grant SELECT on sequence public."support_ticket_messages_id_seq" to "authenticated";
grant UPDATE on sequence public."support_ticket_messages_id_seq" to "authenticated";
grant USAGE on sequence public."support_ticket_messages_id_seq" to "authenticated";
grant SELECT on sequence public."support_ticket_messages_id_seq" to "service_role";
grant UPDATE on sequence public."support_ticket_messages_id_seq" to "service_role";
grant USAGE on sequence public."support_ticket_messages_id_seq" to "service_role";
grant SELECT on table public."support_faqs" to "anon";
grant TRUNCATE on table public."support_faqs" to "anon";
grant REFERENCES on table public."support_faqs" to "anon";
grant TRIGGER on table public."support_faqs" to "anon";
grant MAINTAIN on table public."support_faqs" to "anon";
grant SELECT on table public."support_faqs" to "authenticated";
grant TRUNCATE on table public."support_faqs" to "authenticated";
grant REFERENCES on table public."support_faqs" to "authenticated";
grant TRIGGER on table public."support_faqs" to "authenticated";
grant MAINTAIN on table public."support_faqs" to "authenticated";
grant INSERT on table public."support_faqs" to "service_role";
grant SELECT on table public."support_faqs" to "service_role";
grant UPDATE on table public."support_faqs" to "service_role";
grant DELETE on table public."support_faqs" to "service_role";
grant TRUNCATE on table public."support_faqs" to "service_role";
grant REFERENCES on table public."support_faqs" to "service_role";
grant TRIGGER on table public."support_faqs" to "service_role";
grant MAINTAIN on table public."support_faqs" to "service_role";
grant INSERT on table public."support_faq_feedback" to "anon";
grant TRUNCATE on table public."support_faq_feedback" to "anon";
grant REFERENCES on table public."support_faq_feedback" to "anon";
grant TRIGGER on table public."support_faq_feedback" to "anon";
grant MAINTAIN on table public."support_faq_feedback" to "anon";
grant INSERT on table public."support_faq_feedback" to "authenticated";
grant TRUNCATE on table public."support_faq_feedback" to "authenticated";
grant REFERENCES on table public."support_faq_feedback" to "authenticated";
grant TRIGGER on table public."support_faq_feedback" to "authenticated";
grant MAINTAIN on table public."support_faq_feedback" to "authenticated";
grant INSERT on table public."support_faq_feedback" to "service_role";
grant SELECT on table public."support_faq_feedback" to "service_role";
grant UPDATE on table public."support_faq_feedback" to "service_role";
grant DELETE on table public."support_faq_feedback" to "service_role";
grant TRUNCATE on table public."support_faq_feedback" to "service_role";
grant REFERENCES on table public."support_faq_feedback" to "service_role";
grant TRIGGER on table public."support_faq_feedback" to "service_role";
grant MAINTAIN on table public."support_faq_feedback" to "service_role";
grant INSERT on table public."support_suggestions" to "anon";
grant SELECT on table public."support_suggestions" to "anon";
grant TRUNCATE on table public."support_suggestions" to "anon";
grant REFERENCES on table public."support_suggestions" to "anon";
grant TRIGGER on table public."support_suggestions" to "anon";
grant MAINTAIN on table public."support_suggestions" to "anon";
grant INSERT on table public."support_suggestions" to "authenticated";
grant SELECT on table public."support_suggestions" to "authenticated";
grant TRUNCATE on table public."support_suggestions" to "authenticated";
grant REFERENCES on table public."support_suggestions" to "authenticated";
grant TRIGGER on table public."support_suggestions" to "authenticated";
grant MAINTAIN on table public."support_suggestions" to "authenticated";
grant INSERT on table public."support_suggestions" to "service_role";
grant SELECT on table public."support_suggestions" to "service_role";
grant UPDATE on table public."support_suggestions" to "service_role";
grant DELETE on table public."support_suggestions" to "service_role";
grant TRUNCATE on table public."support_suggestions" to "service_role";
grant REFERENCES on table public."support_suggestions" to "service_role";
grant TRIGGER on table public."support_suggestions" to "service_role";
grant MAINTAIN on table public."support_suggestions" to "service_role";
grant INSERT on table public."support_tickets" to "anon";
grant SELECT on table public."support_tickets" to "anon";
grant TRUNCATE on table public."support_tickets" to "anon";
grant REFERENCES on table public."support_tickets" to "anon";
grant TRIGGER on table public."support_tickets" to "anon";
grant MAINTAIN on table public."support_tickets" to "anon";
grant INSERT on table public."support_tickets" to "authenticated";
grant SELECT on table public."support_tickets" to "authenticated";
grant TRUNCATE on table public."support_tickets" to "authenticated";
grant REFERENCES on table public."support_tickets" to "authenticated";
grant TRIGGER on table public."support_tickets" to "authenticated";
grant MAINTAIN on table public."support_tickets" to "authenticated";
grant INSERT on table public."support_tickets" to "service_role";
grant SELECT on table public."support_tickets" to "service_role";
grant UPDATE on table public."support_tickets" to "service_role";
grant DELETE on table public."support_tickets" to "service_role";
grant TRUNCATE on table public."support_tickets" to "service_role";
grant REFERENCES on table public."support_tickets" to "service_role";
grant TRIGGER on table public."support_tickets" to "service_role";
grant MAINTAIN on table public."support_tickets" to "service_role";
grant INSERT on table public."support_ticket_messages" to "anon";
grant SELECT on table public."support_ticket_messages" to "anon";
grant TRUNCATE on table public."support_ticket_messages" to "anon";
grant REFERENCES on table public."support_ticket_messages" to "anon";
grant TRIGGER on table public."support_ticket_messages" to "anon";
grant MAINTAIN on table public."support_ticket_messages" to "anon";
grant INSERT on table public."support_ticket_messages" to "authenticated";
grant SELECT on table public."support_ticket_messages" to "authenticated";
grant TRUNCATE on table public."support_ticket_messages" to "authenticated";
grant REFERENCES on table public."support_ticket_messages" to "authenticated";
grant TRIGGER on table public."support_ticket_messages" to "authenticated";
grant MAINTAIN on table public."support_ticket_messages" to "authenticated";
grant INSERT on table public."support_ticket_messages" to "service_role";
grant SELECT on table public."support_ticket_messages" to "service_role";
grant UPDATE on table public."support_ticket_messages" to "service_role";
grant DELETE on table public."support_ticket_messages" to "service_role";
grant TRUNCATE on table public."support_ticket_messages" to "service_role";
grant REFERENCES on table public."support_ticket_messages" to "service_role";
grant TRIGGER on table public."support_ticket_messages" to "service_role";
grant MAINTAIN on table public."support_ticket_messages" to "service_role";
revoke all on function public."can_read_level"(p_level_id bigint) from public,anon,authenticated,service_role;
revoke all on function public."consume_api_rate_limit"(p_bucket_key text, p_limit integer, p_window_seconds integer) from public,anon,authenticated,service_role;
revoke all on function public."consume_quota"(p_user_id uuid, p_metric text, p_amount integer) from public,anon,authenticated,service_role;
revoke all on function public."handle_new_user"() from public,anon,authenticated,service_role;
revoke all on function public."release_quota"(p_user_id uuid, p_metric text, p_amount integer) from public,anon,authenticated,service_role;
grant EXECUTE on function public."release_quota"(p_user_id uuid, p_metric text, p_amount integer) to "service_role";
grant EXECUTE on function public."handle_new_user"() to "service_role";
grant EXECUTE on function public."consume_quota"(p_user_id uuid, p_metric text, p_amount integer) to "service_role";
grant EXECUTE on function public."consume_api_rate_limit"(p_bucket_key text, p_limit integer, p_window_seconds integer) to "service_role";
commit;
