import {translatedMetadata} from '../../../lib/localization/metadata';
import LocalizedContent from '../../components/localization/server';
import {socialSession,workflowMessage} from '../../../lib/social-server';
export async function generateMetadata(){return translatedMetadata({title:'Administración de comunidad y mentorías',robots:{index:false,follow:false}});}
export default async function SocialAdmin({searchParams}:{searchParams:Promise<{result?:string}>}){
 const s=await socialSession(true);const message=workflowMessage((await searchParams).result);
 const [posts,reports,mentors,requests,blocked]=await Promise.all([
 s.admin.from('community_posts').select('id,title,body,status,parent_id').eq('status','pending').order('created_at').limit(50),
 s.admin.from('community_reports').select('id,post_id,reason,community_posts!inner(title,body)').is('resolved_at',null).order('created_at').limit(50),
 s.admin.from('mentoring_profiles').select('user_id,display_name,bio,languages,status').order('created_at',{ascending:false}).limit(50),
 s.admin.from('mentoring_requests').select('id,topic,status,expires_at,price_cents,mentoring_slots!inner(starts_at)').eq('status','pending').gt('expires_at',new Date().toISOString()).order('created_at').limit(50),
 s.admin.from('community_members').select('user_id,alias').eq('blocked',true).limit(50)
 ]);
 function controls(id:string){return <form method="post" action="/api/community"><input type="hidden" name="target" value={id}/><button className="btn" name="action" value="approve">Aprobar publicación</button><button className="btn secondary" name="action" value="hide">Ocultar publicación</button><button className="btn secondary" name="action" value="lock">Cerrar o abrir conversación</button><button className="btn secondary" name="action" value="block">Suspender participación</button><button className="btn secondary" name="action" value="resolve">Resolver reporte</button></form>;}
 return <LocalizedContent><main className="wrap"><h1>Administrar comunidad y mentorías</h1>{message&&<p role="status">{message}</p>}{[posts,reports,mentors,requests,blocked].some(r=>r.error)&&<p role="alert">No pudimos cargar la administración. Intenta nuevamente.</p>}
 <section className="social-stack"><h2>Publicaciones en revisión</h2>{posts.data?.length===0&&<p>No hay publicaciones pendientes.</p>}{posts.data?.map(p=><article className="card" key={p.id}><h3 translate="no">{p.title}</h3><p className="social-body" translate="no">{p.body}</p>{controls(p.id)}</article>)}</section>
 <section className="social-stack"><h2>Reportes abiertos</h2>{reports.data?.length===0&&<p>No hay reportes pendientes.</p>}{reports.data?.map(r=>{const post=r.community_posts as unknown as {title:string;body:string};return <article className="card" key={r.id}><h3 translate="no">{post.title}</h3><p className="social-body" translate="no">{post.body}</p><p className="social-body" translate="no">{r.reason}</p>{controls(r.post_id)}</article>;})}</section>
 <section className="social-stack"><h2>Participación suspendida</h2>{blocked.data?.map(m=><form className="card" key={m.user_id} method="post" action="/api/community"><p translate="no">{m.alias}</p><input type="hidden" name="action" value="unblock"/><input type="hidden" name="target" value={m.user_id}/><button className="btn secondary">Restablecer participación</button></form>)}</section><section className="social-stack"><h2>Perfiles de mentoría</h2>{mentors.data?.length===0&&<p>No hay perfiles pendientes.</p>}{mentors.data?.map(m=><article className="card" key={m.user_id}><h3 translate="no">{m.display_name}</h3><p className="social-body" translate="no">{m.bio}</p><p translate="no">{m.languages.join(' / ')} · {m.status}</p><form method="post" action="/api/mentoring"><input type="hidden" name="target" value={m.user_id}/><button className="btn" name="action" value="approve_mentor">Aprobar mentor</button><button className="btn secondary" name="action" value="pause_mentor">Pausar mentor</button></form></article>)}</section>
 <section className="social-stack"><h2>Solicitudes de mentoría</h2><p>Confirma únicamente pagos verificados. Cancelar una sesión no procesa un reembolso automático.</p>{requests.data?.length===0&&<p>No hay solicitudes pendientes.</p>}{requests.data?.map(r=>{const slot=r.mentoring_slots as unknown as {starts_at:string};return <article className="card" key={r.id}><p translate="no">{slot.starts_at} · $699 MXN</p><p className="social-body" translate="no">{r.topic}</p><form method="post" action="/api/mentoring"><input type="hidden" name="target" value={r.id}/><label>Referencia del pago verificado<input name="payment_reference" minLength={5} maxLength={200} required/></label><label>Enlace HTTPS de la sesión<input type="url" name="meeting_url" maxLength={500} required/></label><button className="btn" name="action" value="confirm">Confirmar sesión</button></form><form method="post" action="/api/mentoring"><input type="hidden" name="target" value={r.id}/><button className="btn secondary" name="action" value="decline">Rechazar solicitud</button></form></article>;})}</section>
 </main></LocalizedContent>;
}
