import json
from pathlib import Path
R=Path('lib/localization')
# Human reviewed navigation and terminology. Order: English, Portuguese, French.
copy={
 'Isaac López García':['Isaac López García','Isaac López García','Isaac López García'],
 'CodeZero':['CodeZero','CodeZero','CodeZero'],
 'Copiar el código tres veces':['Copy the code three times','Copiar o código três vezes','Copier le code trois fois'],
 'OAuth 2.0':['OAuth 2.0','OAuth 2.0','OAuth 2.0'],
 'Tutor IA':['AI tutor','Tutor de IA','Tuteur IA'],
 'Cómo funciona':['How it works','Como funciona','Comment ça marche'],
 'La ruta':['Learning path','Trilha de aprendizagem','Parcours d’apprentissage'],
 'Precios':['Pricing','Preços','Tarifs'],
 'Preguntas':['Questions','Perguntas','Questions'],
 'Ir a mi panel':['Go to my dashboard','Ir para o meu painel','Accéder à mon tableau de bord'],
 'Entrar':['Sign in','Entrar','Se connecter'],
 'Empezar gratis':['Get started for free','Começar gratuitamente','Commencer gratuitement'],
 'Crear cuenta':['Create account','Criar conta','Créer un compte'],
 'Saltar al contenido':['Skip to content','Ir para o conteúdo','Aller au contenu'],
 'Mi cuenta':['My account','Minha conta','Mon compte'],
 'Mi espacio':['My space','Meu espaço','Mon espace'],
 'Mi CodeZero':['My CodeZero','Meu CodeZero','Mon CodeZero'],
 'Diploma de finalización':['Certificate of completion','Diploma de conclusão','Attestation de réussite'],
 'A TU MANERA':['YOUR WAY','DO SEU JEITO','À VOTRE FAÇON'],
 'Guardar actividad':['Save activity','Salvar atividade','Enregistrer l’activité'],
 'Guardar nombre':['Save name','Salvar nome','Enregistrer le nom'],
 'Guardar':['Save','Salvar','Enregistrer'],
 'Contraseña':['Password','Senha','Mot de passe'],
 'Mostrar':['Show','Mostrar','Afficher'],
 'Ocultar':['Hide','Ocultar','Masquer'],
 'Correo':['Email','E-mail','E-mail'],
 'Nombre':['Name','Nome','Nom'],
 'Iniciar sesión':['Sign in','Entrar','Se connecter'],
 'Contacto':['Contact','Contato','Contact'],
 'tu@email.com':['you@email.com','voce@email.com','vous@email.com'],
 'Inicio':['Home','Início','Accueil'],
 'Volver a Mi CodeZero':['Back to My CodeZero','Voltar ao Meu CodeZero','Retour à Mon CodeZero'],
 'Centro de ayuda':['Help center','Central de ajuda','Centre d’aide'],
 'Mis certificados':['My certificates','Meus certificados','Mes attestations'],
 'Mis equipos':['My teams','Minhas equipes','Mes équipes'],
 'Contenido':['Content','Conteúdo','Contenu'],
 'Continuar mi camino':['Continue my learning path','Continuar minha trilha','Continuer mon parcours'],
 'Lección anterior':['Previous lesson','Lição anterior','Leçon précédente'],
 'Siguiente lección':['Next lesson','Próxima lição','Leçon suivante'],
 'Completada':['Completed','Concluída','Terminée'],
 'Pendiente':['Pending','Pendente','En attente'],
 'APROBADO':['PASSED','APROVADO','RÉUSSI'],
 'Guardar actividad':['Save activity','Salvar atividade','Enregistrer l’activité'],
 'De cero a construir y entender soluciones técnicas para SaaS.':['Learn to build and understand technical solutions for SaaS, starting from scratch.','Aprenda a construir e entender soluções técnicas para SaaS, começando do zero.','Apprenez à construire et comprendre des solutions techniques pour le SaaS en partant de zéro.'],
 'Constancia privada de finalización. No equivale a un título oficial ni a acreditación profesional.':['Private record of completion. This is not an official degree or professional accreditation.','Comprovante privado de conclusão. Não equivale a um diploma oficial nem a uma acreditação profissional.','Attestation privée de réussite. Elle ne constitue ni un diplôme officiel ni une accréditation professionnelle.'],
 'de':['of','de','sur'], 'y':['and','e','et'], 'o':['or','ou','ou'], 'en':['in','em','dans'], 'para':['for','para','pour'], 'por':['per','por','par'],
 'active':['Active','Ativo','Actif'],'suspended':['Suspended','Suspenso','Suspendu'],'inactive':['Inactive','Inativo','Inactif'],
 'past_due':['Past due','Pagamento em atraso','Paiement en retard'],'unpaid':['Unpaid','Não pago','Impayé'],
 'open':['Open','Aberto','Ouvert'],'in_progress':['In progress','Em andamento','En cours'],'waiting_user':['Waiting for your reply','Aguardando sua resposta','En attente de votre réponse'],'resolved':['Resolved','Resolvido','Résolu'],'closed':['Closed','Fechado','Fermé'],
 'owner':['Owner','Proprietário','Propriétaire'],'admin':['Administrator','Administrador','Administrateur'],'student':['Student','Estudante','Élève'],'manager':['Manager','Gerente','Responsable'],'supervisor':['Supervisor','Supervisor','Superviseur'],'learner':['Learner','Estudante','Apprenant'],
 'billing':['Billing','Faturamento','Facturation'],'technical':['Technical','Técnico','Technique'],'other':['Other','Outro','Autre'],'payment':['Payment','Pagamento','Paiement'],'access':['Access','Acesso','Accès'],'bug':['Bug','Erro','Erreur'],'suggestion':['Suggestion','Sugestão','Suggestion'],
 'Idioma preferido y edad opcional de registro. La elección de idioma solo personaliza la presentación; no cambia permisos, calificaciones ni precios.':['Preferred language and optional registration age. Your language choice only changes presentation; it does not change permissions, grades or prices.','Idioma preferido e idade opcional no cadastro. A escolha do idioma personaliza apenas a apresentação; não altera permissões, notas nem preços.','Langue préférée et âge facultatif à l’inscription. Le choix de la langue personnalise uniquement la présentation ; il ne modifie ni les autorisations, ni les notes, ni les prix.'],
 'Los certificados y exámenes están incluidos en los planes, dentro de sus límites y requisitos académicos. No cobramos un cargo separado por emitir el certificado.':['Certificates and exams are included in your plan, within its limits and academic requirements. There is no separate certificate issuance fee.','Certificados e exames estão incluídos nos planos, dentro dos limites e requisitos acadêmicos. Não cobramos uma taxa separada pela emissão do certificado.','Les attestations et les examens sont inclus dans les forfaits, dans la limite des quotas et des exigences pédagogiques. Aucun frais distinct n’est facturé pour délivrer l’attestation.'],
 'El Tutor IA no está disponible actualmente.':['The AI tutor is currently unavailable.','O tutor de IA não está disponível no momento.','Le tuteur IA n’est pas disponible actuellement.'],
 'Cómo estudiar esta lección':['How to study this lesson','Como estudar esta lição','Comment étudier cette leçon'],
 'Lee y explica':['Read and explain','Leia e explique','Lisez et expliquez'],
 'Resume la idea con tus propias palabras y escribe un ejemplo distinto al presentado.':['Summarize the idea in your own words and write a different example from the one shown.','Resuma a ideia com suas próprias palavras e escreva um exemplo diferente do apresentado.','Résumez l’idée avec vos propres mots et écrivez un exemple différent de celui présenté.'],
 'Predice antes de ejecutar':['Predict before running','Preveja antes de executar','Prévoyez avant d’exécuter'],
 'Anota la entrada, el resultado esperado y una condición que podría causar un error.':['Write down the input, the expected result and a condition that could cause an error.','Anote a entrada, o resultado esperado e uma condição que poderia causar um erro.','Notez l’entrée, le résultat attendu et une condition susceptible de provoquer une erreur.'],
 'Comprueba y compara':['Check and compare','Verifique e compare','Vérifiez et comparez'],
 'Resuelve los dos ejercicios. Si fallas, compara tu razonamiento con la explicación antes de volver a intentar.':['Complete both exercises. If you make a mistake, compare your reasoning with the explanation before trying again.','Resolva os dois exercícios. Se errar, compare seu raciocínio com a explicação antes de tentar novamente.','Résolvez les deux exercices. En cas d’erreur, comparez votre raisonnement avec l’explication avant de réessayer.'],
 'Reúne evidencia':['Gather evidence','Reúna evidências','Rassemblez des preuves'],
 'Registra qué esperabas, qué observaste y cómo corregiste la diferencia. Usa datos ficticios; nunca incluyas contraseñas ni datos de clientes.':['Record what you expected, what you observed and how you corrected the difference. Use fictional data; never include passwords or customer data.','Registre o que esperava, o que observou e como corrigiu a diferença. Use dados fictícios; nunca inclua senhas nem dados de clientes.','Consignez ce que vous attendiez, ce que vous avez observé et comment vous avez corrigé l’écart. Utilisez des données fictives ; n’incluez jamais de mots de passe ni de données clients.'],
}
es={'active':'Activo','suspended':'Suspendido','inactive':'Inactivo','past_due':'Pago vencido','unpaid':'Sin pagar','open':'Abierto','in_progress':'En proceso','waiting_user':'Esperando tu respuesta','resolved':'Resuelto','closed':'Cerrado','owner':'Propietario','admin':'Administrador','student':'Estudiante','manager':'Gerente','supervisor':'Supervisor','learner':'Estudiante','billing':'Facturación','technical':'Técnico','other':'Otro','payment':'Pago','access':'Acceso','bug':'Error','suggestion':'Sugerencia'}
(R/'es-ui.json').write_text(json.dumps(es,ensure_ascii=False,indent=2)+'\n')
for i,lang in enumerate(['en','pt','fr']):
 for kind in ['ui','server','curriculum']:
  p=R/f'{lang}-{kind}.json';d=json.loads(p.read_text());d.update({s:v[i] for s,v in copy.items() if kind!='curriculum' or s in d});p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
