import fs from 'node:fs';
import levels from '../lib/position-curricula/customer-success.json' with {type:'json'};
import {ROLE_WORKFLOWS} from '../lib/career-role-workflows.ts';
import {DEFAULT_JOB_PROFILES} from '../lib/competency-matrix.ts';
import {translator} from '../lib/localization/shared.ts';
const dict=Object.fromEntries(['en','pt','fr'].map(l=>[l,Object.assign({},...['ui','server','curriculum','extension','social','mixed','suggestions'].map(k=>JSON.parse(fs.readFileSync(`lib/localization/${l}-${k}.json`))))]));
const translate=(v,l)=>l==='es'?v:translator(dict[l])(v);
const roles=[['onboarding','Onboarding Specialist','Plan de implementación de 30-60-90 días','Rescate de una implementación atrasada'],['account_manager','Account Manager','Plan de cuenta con oportunidades','Negociación de renovación con objeciones'],['customer_support','Customer Support','Resolución documentada de una cola de casos','Base de conocimiento para un producto'],['tech_support_l3','Tech Support','Investigación de un incidente con causa raíz','Guía de diagnóstico por síntomas'],['key_account_manager','Key Account Manager','Plan estratégico de una cuenta clave','Propuesta de expansión ante comité'],['product_specialist','Product Specialist','Demo guiada por caso de uso','Documento de requerimientos desde la voz del cliente'],['project_manager','Project Manager','Plan de proyecto completo','Recuperación de un proyecto en riesgo'],['manager_team_lead','Managers y Team Leads','Plan de desarrollo de un equipo usando la matriz','Revisión trimestral con decisiones de capacidad']];
const stages=[['Fundamentos del puesto','Role foundations','Fundamentos do cargo','Fondamentaux du poste'],['Ciclo de trabajo','Work lifecycle','Ciclo de trabalho','Cycle de travail'],['Inicio de un caso','Starting a case','Início de um caso','Démarrage d’un cas'],['Comunicación','Communication','Comunicação','Communication'],['Calidad y resultado','Quality and outcome','Qualidade e resultado','Qualité et résultat'],['Herramientas','Tools','Ferramentas','Outils'],['Priorización','Prioritization','Priorização','Priorités'],['Plan y revisión','Plan and review','Plano e revisão','Plan et revue'],['Riesgos y escalaciones','Risks and escalations','Riscos e escalações','Risques et escalades'],['Negociación','Negotiation','Negociação','Négociation'],['Mejora del servicio','Service improvement','Melhoria do serviço','Amélioration du service'],['Colaboración','Collaboration','Colaboração','Collaboration'],['Supervisión','Supervision','Supervisão','Supervision'],['Gerencia','Management','Gestão','Gestion'],['Dirección','Leadership','Direção','Direction']];
const focus=[['Contexto y alcance','Context and scope','Contexto e escopo','Contexte et périmètre'],['Datos y fuentes','Data and sources','Dados e fontes','Données et sources'],['Alternativas y criterio','Alternatives and judgment','Alternativas e critério','Options et jugement'],['Entregable del puesto','Role deliverable','Entrega do cargo','Livrable du poste'],['Verificación y aceptación','Verification and acceptance','Verificação e aceitação','Vérification et acceptation'],['Restricción nueva y transferencia','New constraint and transfer','Nova restrição e transferência','Nouvelle contrainte et transfert'],['Decisión de capacidad','Capacity decision','Decisão de capacidade','Décision de capacité']];
const languages=['es','en','pt','fr'];
for(const [key,title,p1,p2] of roles){
 const w=ROLE_WORKFLOWS[key]??ROLE_WORKFLOWS.pre_sales,profile=DEFAULT_JOB_PROFILES.find(p=>p.position_key===key)??DEFAULT_JOB_PROFILES.find(p=>p.position_key==='pre_sales');
 const draft={key,title,status:'draft',editorial_review:'pending',calibration:'pending',published:false,
  role:Object.fromEntries(languages.map(l=>[l,{process:translate(w.process,l),deliverable:translate(w.deliverable,l),decision:translate(w.decision,l),quality:translate(w.quality,l)}])),
  competencies:profile.weights,expectedByStage:Object.fromEntries([1,2,3,4,5].map((stage,i)=>[stage,Object.fromEntries(Object.keys(profile.weights).map(k=>[k,Math.min(i+1,profile.weights[k]==='high'?4:3)]))])),
  levels:stages.map((stage,i)=>({number:i+1,title:Object.fromEntries(languages.map((l,j)=>[l,title+' · '+stage[j]])),objective:Object.fromEntries(languages.map(l=>[l,translate(w.process,l)+' · '+translate(w.quality,l)])),lessons:focus.slice(0,i>=13?7:6).map((f,n)=>({key:`position-${key}-l${i+1}-${n+1}`,title:Object.fromEntries(languages.map((l,j)=>[l,title+' · '+stage[j]+' · '+f[j]])),sharedSource:levels[i].source}))})),
  projects:[{level:8,title:p1,rubric:['scope','decision','evidence','verification']},{level:15,title:p2,rubric:['scope','decision','evidence','verification']}],
  diagnostic:{type:'situations',source:w.source,competencies:Object.keys(profile.weights),blocking:false},optionalTechnical:['data','spreadsheets','sql','automation','ai'],references:[w.source],sharedUnits:['common-communication','common-diagnosis','common-data','common-priority','common-documentation','common-deescalation','common-commercial','common-planning','common-technical']};
 if(draft.levels.flatMap(l=>l.lessons).length!==92)throw Error('COUNT');fs.writeFileSync(`docs/position-curricula/${key}.draft.json`,JSON.stringify(draft,null,2)+'\n');
}
console.log('PASS 8 hidden drafts: profile, expectations per stage, 15 levels, 92 titles, 2 projects, diagnostic and shared references');
