-- CodeZero Career Guidance persistence draft v0.1
-- STATUS: DRAFT ONLY. DO NOT APPLY TO PRODUCTION YET.
-- Purpose: define the production data model, consent, model versioning and RLS strategy.

create table public.career_model_versions (
  version text primary key,
  status text not null check (status in ('draft','active','retired')),
  notes text,
  activated_at timestamptz,
  retired_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.career_dimensions (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now()
);

create table public.career_routes (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  family text not null,
  description text,
  requires_experience_gate boolean not null default false,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now()
);

create table public.career_route_dimension_weights (
  model_version text not null references public.career_model_versions(version) on delete restrict,
  route_id bigint not null references public.career_routes(id) on delete cascade,
  dimension_id bigint not null references public.career_dimensions(id) on delete cascade,
  weight numeric(6,5) not null check (weight >= 0 and weight <= 1),
  primary key (model_version, route_id, dimension_id)
);

create table public.career_activities (
  id bigint generated by default as identity primary key,
  key text not null unique,
  title text not null,
  activity_type text not null check (activity_type in ('base','discriminator','learning')),
  content_area text,
  estimated_minutes integer check (estimated_minutes is null or estimated_minutes > 0),
  status text not null default 'draft' check (status in ('draft','active','retired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.career_activity_signals (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.career_activities(id) on delete cascade,
  dimension_id bigint not null references public.career_dimensions(id) on delete cascade,
  signal_key text not null,
  signal_type text not null check (signal_type in ('behavior','performance','preference','self_report')),
  weight numeric(6,5) not null check (weight >= 0 and weight <= 1),
  measurement_rule jsonb not null default '{}'::jsonb,
  unique(activity_id, signal_key)
);

create table public.career_user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  personalization_enabled boolean not null default false,
  consent_version text,
  consented_at timestamptz,
  disabled_at timestamptz,
  updated_at timestamptz not null default now()
);

create table public.career_user_activity_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_id bigint not null references public.career_activities(id) on delete restrict,
  model_version text not null references public.career_model_versions(version) on delete restrict,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  response_json jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb
);

create index on public.career_user_activity_attempts(user_id, started_at desc);

create table public.career_user_signals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_attempt_id bigint references public.career_user_activity_attempts(id) on delete set null,
  dimension_id bigint not null references public.career_dimensions(id) on delete restrict,
  signal_key text not null,
  signal_type text not null check (signal_type in ('behavior','performance','preference','self_report','correction')),
  raw_value jsonb,
  normalized_value numeric(6,5) not null check (normalized_value >= 0 and normalized_value <= 1),
  confidence numeric(6,5) not null default 1 check (confidence >= 0 and confidence <= 1),
  evidence_summary text,
  model_version text not null references public.career_model_versions(version) on delete restrict,
  created_at timestamptz not null default now()
);

create index on public.career_user_signals(user_id, created_at desc);
create index on public.career_user_signals(user_id, dimension_id);

create table public.career_user_dimension_scores (
  user_id uuid not null references auth.users(id) on delete cascade,
  dimension_id bigint not null references public.career_dimensions(id) on delete restrict,
  score numeric(6,5) not null check (score >= 0 and score <= 1),
  confidence numeric(6,5) not null check (confidence >= 0 and confidence <= 1),
  maturity text not null check (maturity in ('preliminary','stable','mixed')),
  evidence_count integer not null default 0 check (evidence_count >= 0),
  model_version text not null references public.career_model_versions(version) on delete restrict,
  recalculated_at timestamptz not null default now(),
  primary key (user_id, dimension_id, model_version)
);

create table public.career_user_route_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  route_id bigint not null references public.career_routes(id) on delete restrict,
  affinity_score numeric(6,5) not null check (affinity_score >= 0 and affinity_score <= 1),
  confidence_score numeric(6,5) not null check (confidence_score >= 0 and confidence_score <= 1),
  experience_gate text not null check (experience_gate in ('ready_now','near_ready','future_progression','insufficient_evidence')),
  explanation jsonb not null default '{}'::jsonb,
  rank integer,
  model_version text not null references public.career_model_versions(version) on delete restrict,
  recalculated_at timestamptz not null default now(),
  unique(user_id, route_id, model_version)
);

create index on public.career_user_route_scores(user_id, model_version, rank);

create table public.career_user_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  route_id bigint references public.career_routes(id) on delete set null,
  feedback_type text not null check (feedback_type in ('represents_me','does_not_represent_me','unsure','explore_anyway')),
  note text,
  model_version text not null references public.career_model_versions(version) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.career_experience_evidence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  technical_years_band text,
  commercial_years_band text,
  complexity_band text,
  autonomy_band text,
  led_people boolean,
  owned_process_or_kpi boolean,
  handled_escalations boolean,
  supported_executives boolean,
  handled_confidential_info boolean,
  advanced_debugging_evidence boolean,
  updated_at timestamptz not null default now()
);

alter table public.career_model_versions enable row level security;
alter table public.career_dimensions enable row level security;
alter table public.career_routes enable row level security;
alter table public.career_route_dimension_weights enable row level security;
alter table public.career_activities enable row level security;
alter table public.career_activity_signals enable row level security;
alter table public.career_user_preferences enable row level security;
alter table public.career_user_activity_attempts enable row level security;
alter table public.career_user_signals enable row level security;
alter table public.career_user_dimension_scores enable row level security;
alter table public.career_user_route_scores enable row level security;
alter table public.career_user_feedback enable row level security;
alter table public.career_experience_evidence enable row level security;

-- Public/authenticated read of active catalog only.
create policy "Read active career dimensions"
on public.career_dimensions for select
to authenticated
using (status = 'active');

create policy "Read active career routes"
on public.career_routes for select
to authenticated
using (status = 'active');

create policy "Read active career activities"
on public.career_activities for select
to authenticated
using (status = 'active');

-- User-owned state.
create policy "Users read own career preferences"
on public.career_user_preferences for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users read own career attempts"
on public.career_user_activity_attempts for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users read own career signals"
on public.career_user_signals for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users read own dimension scores"
on public.career_user_dimension_scores for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users read own route scores"
on public.career_user_route_scores for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users read own career feedback"
on public.career_user_feedback for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users read own experience evidence"
on public.career_experience_evidence for select
to authenticated
using ((select auth.uid()) = user_id);

-- Client writes intentionally omitted in draft.
-- Recommended production pattern:
-- - browser submits to same-origin server routes;
-- - server validates consent, activity, model version and rate limits;
-- - service role performs writes;
-- - admin changes to model/catalog go through audited admin-only routes.

-- Draft grants should be tightened explicitly when migration is approved.
