import Link from 'next/link';
import {redirect} from 'next/navigation';
import {workspaceUser} from '../../lib/workspace-server';
import {createAdminSupabase} from '../../lib/admin';
import {personalPortfolioData} from '../../lib/portfolio-server';
import {COMPETENCIES} from '../../lib/competency-matrix';
import {findTrainingActivity} from '../../lib/role-training-content';
import LocalizedContent from '../components/localization/server';
export default async function Portfolio(){const session=await workspaceUser();if(!session)redirect('/login');const personal=await personalPortfolioData(session.user.id);if(!personal)redirect('/login');const {data:p,error}=await createAdminSupabase().from('public_portfolios').select('*').eq('user_id',session.user.id).maybeSingle();if(error)throw Error('PORTFOLIO_DATA_UNAVAILABLE');return <LocalizedContent><main className="wrap"><h1>Mi portafolio público</h1><p>Apagado por defecto. Tú eliges qué publicar y puedes retirar el enlace en cualquier momento.</p><p>Solo evidencia personal aprobada. No se publican textos de entregas, nombres de otras personas, datos de compañías ni tu foto privada.</p>{p?.published&&<section className="card"><Link prefetch={false} href={'/portfolio/share/'+p.share_token}>Abrir mi portafolio</Link><form action="/api/portfolio" method="post"><input type="hidden" name="action" value="unpublish"/><button className="btn secondary">Despublicar ahora</button></form></section>}
 <form action="/api/portfolio" method="post" className="card"><input type="hidden" name="action" value="publish"/><label>Nombre público<input name="display_name" required minLength={2} maxLength={120} defaultValue={p?.display_name??session.profile.full_name??''}/></label><fieldset><legend>Proyectos personales aprobados</legend>{personal.evidence.map(e=><label key={e.id}><input type="checkbox" name="evidence" value={e.id} defaultChecked={p?.evidence_ids?.includes(e.id)}/>{findTrainingActivity(e.activity_key)?.title??'Proyecto personal'} · {e.observed_at.slice(0,10)}</label>)}{!personal.evidence.length&&<p>Aún no hay proyectos personales aprobados.</p>}</fieldset><fieldset><legend>Competencias con evidencia</legend>{personal.summary.competencies.filter(c=>c.count>=3).map(c=><label key={c.key}><input type="checkbox" name="competencies" value={c.key} defaultChecked={p?.competency_keys?.includes(c.key)}/>{COMPETENCIES[c.key]} · {c.level}/4</label>)}</fieldset><fieldset><legend>Certificados personales</legend>{personal.certificates.map(c=><label key={c.id}><input type="checkbox" name="certificates" value={c.id} defaultChecked={p?.certificate_ids?.includes(c.id)}/>{c.title}</label>)}</fieldset><label><input type="checkbox" name="consent" value="yes" required/>Acepto publicar mi nombre y los elementos seleccionados para cualquier persona que tenga el enlace.</label><button className="btn">Publicar selección</button><Link prefetch={false} href="/privacy">Aviso de privacidad</Link></form></main></LocalizedContent>;}
