import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {roleTrainingEnabled,trainingPerson,roleTrainingSession} from '../../../lib/role-training-server';
import {careerLadder} from '../../../lib/career-ladder';
import {COMPETENCIES} from '../../../lib/competency-matrix';
import {ROLE_WORKFLOWS} from '../../../lib/career-role-workflows';
import LocalizedContent from '../../components/localization/server';
import {isUuid} from '../../../lib/workspace-sandbox';
export default async function CareerMap({searchParams}:{searchParams:Promise<{position?:string;organization_id?:string}>}){
 if(!roleTrainingEnabled())notFound();const s=await roleTrainingSession();if(!s)redirect('/login');const q=await searchParams,org=q.organization_id??null;if(org&&!isUuid(org))notFound();
 const p=await trainingPerson(s.user.id,org);if(!p)notFound();const profile=p.profiles.find(x=>x.position_key===q.position)??p.profile??p.profiles[0];if(!profile)notFound();const ladder=careerLadder(p.summary,profile);
 return <LocalizedContent><main className="wrap"><h1>Mapa de carrera</h1><p>Orientación de aprendizaje basada en la misma evidencia revisada de tu matriz. Los escalones son metas educativas provisionales; no asignan un título, no bloquean contenido ni garantizan una promoción.</p><form method="get"><label>Explorar otro puesto<select name="position" defaultValue={profile.position_key}>{p.profiles.map(x=><option key={x.position_key} value={x.position_key}>{ROLE_WORKFLOWS[x.position_key as keyof typeof ROLE_WORKFLOWS]?.title??x.position_key}</option>)}</select></label>{org&&<input type="hidden" name="organization_id" value={org}/>}<button className="btn">Explorar</button></form><p>{ladder.current<0?'Reúne tus primeras evidencias revisadas.':'Tu evidencia respalda este escalón educativo:'} {ladder.current>=0&&ladder.stages[ladder.current].name}</p><p>Competencias por reforzar: {ladder.gaps.length}</p><ol className="career-ladder">{ladder.stages.map((step,i)=><li className="card" key={step.name} aria-current={i===ladder.next?'step':undefined}><h2>{step.name}</h2>{i===ladder.next&&<span className="pill">Siguiente escalón</span>}<details><summary>Competencias esperadas</summary>{Object.entries(step.expected).map(([k,level])=><p key={k}>{COMPETENCIES[k as keyof typeof COMPETENCIES]} · {level}/4</p>)}</details><Link href={'/role-training'+(org?'?organization_id='+org:'')}>Practicar y reunir evidencia</Link></li>)}</ol><section className="card"><h2>Tu siguiente práctica</h2>{ladder.gaps.map(k=><p key={k}>{COMPETENCIES[k]} · {p.summary.competencies.find(c=>c.key===k)?.level}/4 → {ladder.stages[ladder.next].expected[k]}/4</p>)}<Link href="/role-training/mixed">Explorar rutas mixtas por puesto</Link></section></main></LocalizedContent>;
}
