-- CodeZero learning platform schema
-- Idempotent migration for courses, lessons, exercises, exams, projects and certificates.

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  description text,
  status text not null default 'published',
  created_at timestamptz not null default now()
);

create table if not exists public.levels (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  level_number integer not null,
  slug text unique not null,
  title text not null,
  description text,
  estimated_hours integer not null default 0,
  sort_order integer not null,
  status text not null default 'published',
  created_at timestamptz not null default now(),
  unique(course_id, level_number)
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  level_id bigint not null references public.levels(id) on delete cascade,
  slug text unique not null,
  title text not null,
  description text,
  content text,
  estimated_minutes integer not null default 15,
  sort_order integer not null,
  status text not null default 'published',
  created_at timestamptz not null default now()
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  status text not null default 'not_started',
  progress_percent integer not null default 0 check (progress_percent between 0 and 100),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(user_id, lesson_id)
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  slug text unique not null,
  prompt text not null,
  kind text not null default 'multiple_choice',
  options jsonb not null default '[]'::jsonb,
  explanation text,
  sort_order integer not null default 1,
  status text not null default 'published',
  created_at timestamptz not null default now()
);

create table if not exists public.exercise_solutions (
  exercise_id bigint primary key references public.exercises(id) on delete cascade,
  correct_answer text not null
);

create table if not exists public.exercise_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  answer text not null,
  is_correct boolean not null,
  created_at timestamptz not null default now()
);

create table if not exists public.level_exams (
  id bigint generated by default as identity primary key,
  level_id bigint not null references public.levels(id) on delete cascade,
  slug text unique not null,
  title text not null,
  description text,
  passing_score integer not null default 70,
  question_count integer not null default 3,
  status text not null default 'published',
  created_at timestamptz not null default now()
);

create table if not exists public.exam_questions (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.level_exams(id) on delete cascade,
  slug text unique not null,
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  sort_order integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.exam_solutions (
  question_id bigint primary key references public.exam_questions(id) on delete cascade,
  correct_answer text not null
);

create table if not exists public.exam_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  exam_id bigint not null references public.level_exams(id) on delete cascade,
  score integer not null,
  passed boolean not null,
  answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.level_projects (
  id bigint generated by default as identity primary key,
  level_id bigint not null references public.levels(id) on delete cascade,
  slug text unique not null,
  title text not null,
  brief text not null,
  requirements jsonb not null default '[]'::jsonb,
  status text not null default 'published',
  created_at timestamptz not null default now()
);

create table if not exists public.project_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id bigint not null references public.level_projects(id) on delete cascade,
  submission_text text not null,
  status text not null default 'submitted',
  score integer,
  feedback text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.certificates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  certificate_type text not null default 'codezero-complete',
  title text not null,
  issued_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique(user_id, certificate_type)
);

alter table public.courses enable row level security;
alter table public.levels enable row level security;
alter table public.lessons enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.exercises enable row level security;
alter table public.exercise_solutions enable row level security;
alter table public.exercise_attempts enable row level security;
alter table public.level_exams enable row level security;
alter table public.exam_questions enable row level security;
alter table public.exam_solutions enable row level security;
alter table public.exam_attempts enable row level security;
alter table public.level_projects enable row level security;
alter table public.project_submissions enable row level security;
alter table public.certificates enable row level security;

create index if not exists lessons_level_id_idx on public.lessons(level_id);
create index if not exists lesson_progress_lesson_id_idx on public.lesson_progress(lesson_id);
create index if not exists exercises_lesson_id_idx on public.exercises(lesson_id);
create index if not exists exercise_attempts_user_exercise_idx on public.exercise_attempts(user_id,exercise_id);
create index if not exists exercise_attempts_exercise_id_idx on public.exercise_attempts(exercise_id);
create index if not exists level_exams_level_id_idx on public.level_exams(level_id);
create index if not exists exam_questions_exam_id_idx on public.exam_questions(exam_id);
create index if not exists exam_attempts_user_exam_idx on public.exam_attempts(user_id,exam_id);
create index if not exists exam_attempts_exam_id_idx on public.exam_attempts(exam_id);
create index if not exists level_projects_level_id_idx on public.level_projects(level_id);
create index if not exists project_submissions_project_id_idx on public.project_submissions(project_id);
create index if not exists project_submissions_user_id_idx on public.project_submissions(user_id);
create index if not exists certificates_user_id_idx on public.certificates(user_id);
