create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;

create policy "No client access to admin audit log"
on public.admin_audit_log
for all
to anon, authenticated
using (false)
with check (false);

revoke all on table public.admin_audit_log from anon, authenticated;
grant select, insert on table public.admin_audit_log to service_role;

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log(created_at desc);

create index if not exists admin_audit_log_actor_idx
  on public.admin_audit_log(actor_user_id);
