with bank(slug, addition) as (
values
('n2-variables-y-tipos', E'\n\n=== CASO APLICADO ===\nUna app SaaS recibe el precio mensual como texto desde un formulario. Convierte y valida el dato antes de calcular impuestos: elegir el tipo correcto evita concatenaciones accidentales y comparaciones incorrectas.\n\nRETO EXTRA\nModela nombre, usuarios activos, precio mensual y estado de prueba de una cuenta usando tipos apropiados. Explica por qué elegiste cada tipo.'),
('n2-condiciones', E'\n\n=== CASO APLICADO ===\nUn cliente puede exportar datos si su cuenta está activa y su plan incluye exportaciones. Escribe primero la regla en lenguaje natural y después conviértela en condiciones; prueba también cuenta suspendida, plan Free y datos faltantes.\n\nRETO EXTRA\nDiseña una decisión con al menos tres ramas para clasificar una cuenta por riesgo de renovación.'),
('n2-bucles', E'\n\n=== CASO APLICADO ===\nRecibes una lista de integraciones y debes identificar cuáles están desconectadas. Recorre cada elemento, evalúa su estado y construye una nueva colección con las que requieren atención.\n\nRETO EXTRA\nAñade un contador de éxitos y fallos y define qué ocurrirá si la colección está vacía.'),
('n2-funciones', E'\n\n=== CASO APLICADO ===\nTres flujos necesitan calcular el porcentaje de uso de una cuenta. Encapsular la fórmula en una función evita diferencias entre pantallas y hace más fácil probar casos como límite cero o uso superior al contratado.\n\nRETO EXTRA\nDiseña la firma de una función que reciba uso y límite y devuelva porcentaje más una clasificación de riesgo.'),
('n2-colecciones', E'\n\n=== CASO APLICADO ===\nPara agrupar tickets por categoría, una lista conserva el orden, un diccionario relaciona categoría con datos y un set ayuda a eliminar identificadores repetidos. Elegir la colección correcta simplifica la lógica.\n\nRETO EXTRA\nRepresenta tres clientes con nombre, plan y lista de integraciones usando una combinación de colecciones.'),
('n2-proyecto-python-basico', E'\n\n=== CASO APLICADO ===\nConstruye un pequeño analizador de cuentas SaaS que reciba datos, valide entradas, calcule uso y emita una recomendación. Separa lectura, cálculo y salida para que puedas probar cada parte.\n\nRETO EXTRA\nIncluye al menos cinco casos de prueba manuales y documenta el resultado esperado antes de ejecutar el programa.'),

('n3-modulos-y-paquetes', E'\n\n=== CASO APLICADO ===\nUna herramienta crece y ya tiene validaciones, acceso a archivos y lógica de reportes. Separar esas responsabilidades en módulos reduce dependencias circulares y permite reutilizar funciones sin copiar código.\n\nRETO EXTRA\nPropón una estructura de carpetas para una herramienta CLI con validación, datos, reportes y punto de entrada.'),
('n3-excepciones', E'\n\n=== CASO APLICADO ===\nUn proceso consulta un archivo local y una API externa. FileNotFoundError y timeout requieren respuestas distintas: el primero puede pedir configuración; el segundo quizá admita reintento. Capturar todo con un except genérico oculta contexto útil.\n\nRETO EXTRA\nDiseña tres excepciones esperadas y define para cada una si debes reintentar, informar o abortar.'),
('n3-archivos-y-datos', E'\n\n=== CASO APLICADO ===\nUn CSV de clientes puede traer columnas ausentes, codificación inesperada o fechas inválidas. Antes de procesarlo, valida encabezados y tipos y separa filas rechazadas para revisión.\n\nRETO EXTRA\nDefine un esquema mínimo para importar clientes y una estrategia para conservar evidencia de errores sin perder filas válidas.'),
('n3-programacion-orientada-a-objetos', E'\n\n=== CASO APLICADO ===\nUna CuentaSaaS puede agrupar plan, estado y uso junto con comportamientos como puede_exportar() o porcentaje_uso(). La clase tiene sentido si mantiene reglas coherentes de una entidad, no solo para envolver datos sin comportamiento.\n\nRETO EXTRA\nDiseña dos clases relacionadas y explica qué responsabilidad pertenece a cada una.'),
('n3-codigo-limpio-y-pruebas', E'\n\n=== CASO APLICADO ===\nUna función de 80 líneas valida datos, calcula métricas y genera texto. Divide responsabilidades, usa nombres que expresen intención y escribe pruebas sobre entradas normales y límites.\n\nRETO EXTRA\nToma una función imaginaria demasiado grande y propón tres funciones pequeñas con nombres, entradas y salidas claras.'),
('n3-proyecto-python-intermedio', E'\n\n=== CASO APLICADO ===\nEntrega una herramienta que lea datos, los valide, aplique reglas de negocio y genere un reporte. Incluye módulos separados, excepciones específicas y pruebas sobre las reglas críticas.\n\nRETO EXTRA\nEscribe un README con instalación, ejecución, formato de entrada, ejemplo de salida y limitaciones conocidas.'),

('n4-complejidad-y-eficiencia', E'\n\n=== CASO APLICADO ===\nBuscar cada email recorriendo una lista completa puede ser suficiente con 20 elementos, pero costoso con millones. La eficiencia importa cuando relacionas tamaño de entrada, frecuencia de operación y costo real.\n\nRETO EXTRA\nCompara búsqueda lineal y pertenencia en set para un proceso repetido miles de veces y explica cuándo vale la pena cambiar la estructura.'),
('n4-listas-pilas-y-colas', E'\n\n=== CASO APLICADO ===\nUna cola modela trabajos en orden de llegada; una pila modela deshacer operaciones recientes. Elegir la estructura por su comportamiento esperado evita lógica adicional innecesaria.\n\nRETO EXTRA\nDiseña una cola de tareas con prioridad conceptual y explica qué cambia si debes respetar estrictamente FIFO.'),
('n4-diccionarios-y-conjuntos', E'\n\n=== CASO APLICADO ===\nUn diccionario user_id→plan permite recuperar el plan sin recorrer toda una lista; un set de event_id ayuda a detectar eventos ya vistos. Ambas estructuras expresan intenciones distintas.\n\nRETO EXTRA\nDiseña una estructura para contar eventos por tipo y otra para detectar duplicados.'),
('n4-busqueda-y-ordenamiento', E'\n\n=== CASO APLICADO ===\nOrdenar una lista antes de buscar puede acelerar búsquedas repetidas, pero tiene un costo inicial. La decisión depende de cuántas veces buscarás y si los datos cambian con frecuencia.\n\nRETO EXTRA\nDescribe un escenario donde ordenar una vez y buscar muchas veces sea mejor que hacer búsquedas lineales siempre.'),
('n4-recursion-y-arboles', E'\n\n=== CASO APLICADO ===\nUn árbol de carpetas se presta a recorrer nodos y subnodos de forma recursiva. Cada llamada necesita un caso base y debe avanzar hacia él para evitar recursión infinita.\n\nRETO EXTRA\nEscribe en pseudocódigo cómo contar archivos dentro de una estructura de carpetas anidadas.'),
('n4-proyecto-de-algoritmos', E'\n\n=== CASO APLICADO ===\nConstruye un proceso que reciba eventos, elimine duplicados, clasifique prioridades y permita búsquedas frecuentes. Justifica cada estructura de datos con el patrón de acceso esperado.\n\nRETO EXTRA\nIncluye una tabla de decisiones con alternativa, complejidad aproximada y razón para elegir o descartar cada opción.'),

('n5-terminal-y-sistema-de-archivos', E'\n\n=== CASO APLICADO ===\nAntes de automatizar con terminal, confirma ruta, archivos objetivo y efecto del comando. Una operación correcta en el directorio equivocado sigue siendo un incidente.\n\nRETO EXTRA\nEscribe una secuencia segura para crear una carpeta de proyecto, mover un archivo y verificar el resultado sin usar privilegios elevados.'),
('n5-git-basico', E'\n\n=== CASO APLICADO ===\nUn buen ciclo local es revisar status, inspeccionar diff, seleccionar cambios relacionados y crear un commit con intención clara. Esto reduce commits accidentales y facilita revertir.\n\nRETO EXTRA\nPropón tres mensajes de commit útiles para una corrección, una mejora y una refactorización.'),
('n5-ramas-y-merges', E'\n\n=== CASO APLICADO ===\nUna rama permite aislar trabajo, pero integrar requiere comprender diferencias. Un conflicto no es un error de Git: es una decisión que la herramienta no puede resolver por ti.\n\nRETO EXTRA\nDescribe cómo verificarías que una resolución de conflicto conserva el comportamiento de ambas ramas.'),
('n5-pull-requests', E'\n\n=== CASO APLICADO ===\nUna PR pequeña explica problema, solución, pruebas y riesgos. El revisor debe entender qué cambió y por qué sin reconstruir toda la historia del proyecto.\n\nRETO EXTRA\nEscribe la plantilla de una PR para corregir un bug de autenticación, incluyendo pasos de prueba y plan de rollback.'),
('n5-flujo-colaborativo', E'\n\n=== CASO APLICADO ===\nEn equipo, sincronizar ramas, revisar cambios y evitar force push innecesario protege el trabajo compartido. La coordinación técnica también es parte de la calidad del software.\n\nRETO EXTRA\nDiseña un flujo simple desde issue hasta merge e identifica en qué pasos debe existir revisión humana.'),
('n5-proyecto-con-git', E'\n\n=== CASO APLICADO ===\nEntrega un proyecto con historial legible: commits pequeños, ramas con propósito y README que explique cómo reproducir el resultado. El repositorio debe contar la historia técnica del trabajo.\n\nRETO EXTRA\nDefine una secuencia de al menos cinco commits lógicos para construir una funcionalidad desde cero.')
)
update public.lessons l
set content = coalesce(l.content,'') || b.addition
from bank b
where l.slug=b.slug
  and coalesce(l.content,'') not like '%=== CASO APLICADO ===%';
