with bank(slug, addition) as (
values
('n6-modelo-relacional', E'\n\n=== CASO APLICADO ===\nModela clientes, suscripciones y facturas como entidades separadas enlazadas por claves. Esto permite que una cuenta tenga varias facturas sin repetir todos sus datos en cada fila.\n\nRETO EXTRA\nDibuja un esquema simple con tres tablas, claves primarias y foráneas y explica la cardinalidad entre ellas.'),
('n6-select-y-filtros', E'\n\n=== CASO APLICADO ===\nUn equipo necesita encontrar cuentas activas creadas en los últimos 30 días y ordenarlas por fecha. Combinar filtros claros con columnas específicas evita traer datos innecesarios.\n\nRETO EXTRA\nEscribe una consulta que filtre por dos condiciones y ordene por una tercera columna.'),
('n6-joins', E'\n\n=== CASO APLICADO ===\nQuieres listar todos los clientes y, cuando exista, su suscripción. Un LEFT JOIN conserva clientes sin suscripción; un INNER JOIN los eliminaría del resultado.\n\nRETO EXTRA\nExplica con un ejemplo cuándo usarías INNER JOIN y cuándo LEFT JOIN sobre las mismas dos tablas.'),
('n6-agregaciones', E'\n\n=== CASO APLICADO ===\nPara medir clientes por plan puedes agrupar por plan y contar filas, pero antes debes asegurarte de que los JOIN no dupliquen clientes.\n\nRETO EXTRA\nDiseña una consulta para obtener ingresos mensuales por plan y menciona un riesgo de duplicación.'),
('n6-diseno-y-normalizacion', E'\n\n=== CASO APLICADO ===\nGuardar varios teléfonos en columnas telefono1, telefono2 y telefono3 funciona al principio pero complica crecimiento y consultas. Una tabla relacionada modela mejor una cantidad variable de teléfonos.\n\nRETO EXTRA\nDetecta un grupo repetido en un esquema imaginario y propón cómo normalizarlo.'),
('n6-proyecto-sql', E'\n\n=== CASO APLICADO ===\nConstruye un pequeño modelo de datos SaaS y responde preguntas reales con SQL: cuentas sin suscripción, uso por plan e ingresos por periodo. Valida resultados con muestras conocidas.\n\nRETO EXTRA\nEntrega cinco consultas de negocio y para cada una explica qué decisión podría apoyar.'),

('n7-html-semantico', E'\n\n=== CASO APLICADO ===\nUn formulario accesible usa label asociado a input, button para acciones y encabezados en orden lógico. La semántica mejora teclado, lectores de pantalla y mantenimiento.\n\nRETO EXTRA\nReescribe una interfaz hecha solo con divs usando elementos semánticos apropiados.'),
('n7-css-y-layout', E'\n\n=== CASO APLICADO ===\nUna tarjeta que se ve bien en desktop puede romperse en móvil si depende de anchos fijos. Flexbox o Grid permiten que el layout se adapte al espacio disponible.\n\nRETO EXTRA\nDiseña una cuadrícula que use cuatro columnas en escritorio y una en móvil sin duplicar contenido.'),
('n7-javascript-basico', E'\n\n=== CASO APLICADO ===\nUn resumen de cuenta calcula uso, transforma datos y decide qué mensaje mostrar. Mantener variables con nombres claros y evitar mutaciones innecesarias hace la lógica más predecible.\n\nRETO EXTRA\nEscribe pseudocódigo JS que transforme una lista de cuentas en una lista de nombres de cuentas activas.'),
('n7-dom-y-eventos', E'\n\n=== CASO APLICADO ===\nUn formulario escucha submit, valida datos y actualiza un mensaje de estado. El evento debe manejarse en el elemento correcto en lugar de repartir listeners arbitrarios.\n\nRETO EXTRA\nDiseña el flujo de eventos para un botón que abre un modal y un formulario dentro del modal.'),
('n7-fetch-y-estado', E'\n\n=== CASO APLICADO ===\nUna vista que consume API necesita estados explícitos: inicial, cargando, éxito vacío, éxito con datos y error. Esto evita dejar al usuario sin saber qué ocurre.\n\nRETO EXTRA\nDefine qué mensaje o componente mostrarías en cada uno de esos cinco estados.'),
('n7-proyecto-web', E'\n\n=== CASO APLICADO ===\nEntrega una interfaz que consuma datos, permita una acción y responda bien en móvil y teclado. Incluye manejo de carga, error y estado vacío, no solo el happy path.\n\nRETO EXTRA\nPrepara una lista de revisión manual con accesibilidad, responsividad y fallos de red.'),

('n8-http-y-rest', E'\n\n=== CASO APLICADO ===\nUna API recibe GET para consultar, POST para crear y PATCH para actualizar parcialmente. Los códigos de estado deben comunicar el resultado sin obligar al cliente a interpretar mensajes ambiguos.\n\nRETO EXTRA\nAsigna método y código de éxito a cinco operaciones comunes de una API de clientes.'),
('n8-diseno-de-apis', E'\n\n=== CASO APLICADO ===\nAntes de programar, define recurso, ruta, cuerpo, respuesta y errores. Un contrato consistente reduce sorpresas para frontend e integraciones externas.\n\nRETO EXTRA\nDiseña el contrato de una ruta para crear una integración, incluyendo dos errores posibles.'),
('n8-backend-con-rutas', E'\n\n=== CASO APLICADO ===\nUna ruta debe separar parseo, validación, autorización, lógica y persistencia. Cuando todo vive en un bloque enorme, probar errores específicos se vuelve más difícil.\n\nRETO EXTRA\nEscribe el orden de validaciones de una ruta que elimina un recurso propiedad del usuario.'),
('n8-validacion-y-errores', E'\n\n=== CASO APLICADO ===\nAunque el navegador limite un campo a 100 caracteres, un cliente puede llamar directamente a la API. Por eso el backend valida tipo, longitud y reglas de negocio.\n\nRETO EXTRA\nDefine un formato de error consistente con código, mensaje seguro y detalles de campo cuando corresponda.'),
('n8-autenticacion', E'\n\n=== CASO APLICADO ===\nTener sesión válida no autoriza a editar cualquier recurso. El backend debe comprobar además que el recurso pertenece a la cuenta o que el rol tiene permiso explícito.\n\nRETO EXTRA\nDescribe cuatro pruebas negativas para una ruta protegida.'),
('n8-proyecto-api', E'\n\n=== CASO APLICADO ===\nConstruye una API pequeña con autenticación, autorización, validación y respuestas consistentes. Documenta ejemplos de petición y respuesta para éxito y error.\n\nRETO EXTRA\nAñade una matriz de pruebas que cubra 200/201, 400, 401, 403 y 404.'),

('n9-arquitectura-de-software', E'\n\n=== CASO APLICADO ===\nSeparar interfaz, dominio y acceso a datos permite cambiar una dependencia sin reescribir toda la aplicación. La arquitectura debe reducir acoplamiento, no multiplicar capas por moda.\n\nRETO EXTRA\nDibuja tres componentes y explica qué dependencia permitirías y cuál evitarías.'),
('n9-testing', E'\n\n=== CASO APLICADO ===\nUna regla de cálculo puede probarse unitariamente, mientras que registro→dashboard requiere integración o E2E. Elegir el nivel correcto de prueba evita tanto sobreprobar como dejar huecos.\n\nRETO EXTRA\nClasifica cinco escenarios como unitarios, integración o end-to-end y justifica.'),
('n9-patrones-de-diseno', E'\n\n=== CASO APLICADO ===\nSi varias partes necesitan enviar notificaciones por distintos proveedores, una interfaz común puede desacoplar el dominio del proveedor concreto. El patrón aparece por una necesidad, no al revés.\n\nRETO EXTRA\nPropón una interfaz simple para email y SMS y explica qué parte del sistema debería conocerla.'),
('n9-observabilidad', E'\n\n=== CASO APLICADO ===\nUna petición lenta requiere saber cuánto tarda, dónde falla y con qué contexto. Métricas muestran tendencia, logs explican eventos y trazas conectan pasos distribuidos.\n\nRETO EXTRA\nDefine tres métricas y tres campos de log útiles para una API de checkout sin incluir datos sensibles.'),
('n9-ci-cd', E'\n\n=== CASO APLICADO ===\nUn pipeline instala dependencias, compila y ejecuta controles antes de permitir despliegue. El objetivo es detectar defectos temprano y hacer el proceso reproducible.\n\nRETO EXTRA\nDiseña un pipeline mínimo con etapas, condición de fallo y qué artefacto o evidencia produce cada etapa.'),
('n9-proyecto-de-ingenieria', E'\n\n=== CASO APLICADO ===\nEntrega una funcionalidad con diseño, pruebas, observabilidad y procedimiento de despliegue. La calidad incluye cómo operar y recuperar, no solo que funcione en tu máquina.\n\nRETO EXTRA\nEscribe un plan de despliegue con verificación inmediata, métrica de éxito y criterio de rollback.')
)
update public.lessons l
set content=coalesce(l.content,'') || b.addition
from bank b
where l.slug=b.slug and coalesce(l.content,'') not like '%=== CASO APLICADO ===%';
