with bank(slug, addition) as (
values
('n10-definicion-del-producto', E'\n\n=== CASO APLICADO ===\nUn capstone sólido empieza con una necesidad verificable, no con una tecnología favorita. Define usuario, problema, alcance, restricciones y una métrica de éxito antes de diseñar.\n\nRETO EXTRA\nRedacta un problema en formato “persona + necesidad + resultado esperado” y añade dos cosas que explícitamente quedan fuera de alcance.'),
('n10-diseno-tecnico', E'\n\n=== CASO APLICADO ===\nTransforma requisitos en componentes, datos, interfaces y riesgos. Un diagrama simple acompañado de decisiones suele ser más útil que una arquitectura compleja sin justificación.\n\nRETO EXTRA\nDocumenta tres decisiones técnicas con alternativa considerada, ventaja, costo y riesgo.'),
('n10-implementacion', E'\n\n=== CASO APLICADO ===\nDivide el proyecto en incrementos verticales: primero un flujo mínimo completo, después validación, seguridad y mejoras. Cada incremento debe poder ejecutarse y demostrarse.\n\nRETO EXTRA\nPlanifica cuatro incrementos y define la evidencia de que cada uno está terminado.'),
('n10-pruebas-y-calidad', E'\n\n=== CASO APLICADO ===\nPrioriza pruebas según riesgo: reglas críticas unitarias, integración en límites entre componentes y E2E para el flujo principal. Añade casos de error y datos inválidos.\n\nRETO EXTRA\nCrea una matriz de riesgo con cinco fallos posibles y el tipo de prueba que mejor los detecta.'),
('n10-documentacion', E'\n\n=== CASO APLICADO ===\nOtra persona debe poder clonar, configurar, ejecutar y diagnosticar el proyecto sin depender del autor. Documenta prerequisitos, variables, comandos, arquitectura y problemas conocidos.\n\nRETO EXTRA\nEscribe el índice de un README profesional y añade una sección de troubleshooting con tres fallos comunes.'),
('n10-entrega-capstone', E'\n\n=== CASO APLICADO ===\nLa entrega final debe conectar problema, solución, evidencia y limitaciones. Incluye una demo reproducible, decisiones importantes, pruebas y próximos pasos razonables.\n\nRETO EXTRA\nPrepara una defensa de cinco minutos: contexto, arquitectura, decisión difícil, evidencia de calidad y límite conocido.'),

('n11-consumo-de-apis', E'\n\n=== CASO APLICADO ===\nAl consumir una API externa debes tratar timeouts, 429, 5xx y respuestas inesperadas como parte normal del diseño. Configura límites y registra contexto sin exponer secretos.\n\nRETO EXTRA\nDiseña una política de reintento distinta para 400, 401, 429 y 503 y explica por qué.'),
('n11-diseno-de-webhooks', E'\n\n=== CASO APLICADO ===\nUn receptor de webhooks valida autenticidad, persiste identidad del evento y responde rápido. El trabajo pesado puede procesarse después para reducir timeouts del proveedor.\n\nRETO EXTRA\nDibuja el flujo desde recepción hasta procesamiento y marca dónde ocurre validación, deduplicación y respuesta HTTP.'),
('n11-firmas-y-reintentos', E'\n\n=== CASO APLICADO ===\nVerificar la firma debe usar el cuerpo original y el secreto correcto. Los reintentos del emisor significan que tu endpoint debe soportar recibir el mismo evento otra vez.\n\nRETO EXTRA\nEnumera qué datos guardarías para investigar un fallo de firma sin registrar el secreto.'),
('n11-idempotencia', E'\n\n=== CASO APLICADO ===\nSi payment_succeeded llega dos veces, crear dos accesos sería un incidente. Guarda un identificador estable del evento y haz que el segundo procesamiento produzca el mismo estado final sin repetir efectos.\n\nRETO EXTRA\nDiseña una tabla mínima para registrar eventos procesados y el estado de cada intento.'),
('n11-manejo-de-errores', E'\n\n=== CASO APLICADO ===\nDistingue errores permanentes de transitorios. Un payload inválido no mejora al reintentarlo; un timeout sí podría recuperarse con backoff y límite de intentos.\n\nRETO EXTRA\nClasifica seis errores de integración en reintentable/no reintentable y define la acción operativa.'),
('n11-proyecto-de-integracion', E'\n\n=== CASO APLICADO ===\nConstruye una integración con trazabilidad: correlación de solicitudes, estados, deduplicación y recuperación ante fallos. La demo debe incluir al menos un reintento controlado.\n\nRETO EXTRA\nEscribe un runbook corto para investigar por qué un registro no llegó al sistema destino.'),

('n12-oauth-2-0', E'\n\n=== CASO APLICADO ===\nUna app conecta con un proveedor sin almacenar la contraseña del usuario. El flujo OAuth delega autorización y entrega tokens con alcance y vida limitada.\n\nRETO EXTRA\nDibuja actores y pasos de Authorization Code y marca qué valores nunca deben exponerse al navegador cuando son confidenciales.'),
('n12-scopes-y-tokens', E'\n\n=== CASO APLICADO ===\nSolicitar scopes de lectura y escritura cuando solo necesitas lectura aumenta el impacto de una filtración. El mínimo privilegio también aplica a duración, almacenamiento y rotación de tokens.\n\nRETO EXTRA\nDefine scopes mínimos para una integración que solo lee contactos y crea tareas.'),
('n12-automatizacion-saas', E'\n\n=== CASO APLICADO ===\nUna automatización puede encadenar alta de cliente, creación de proyecto y notificación. Debe conservar estado para saber qué pasos terminaron y cuáles requieren reintento.\n\nRETO EXTRA\nDiseña una máquina de estados simple con pendiente, procesando, completado y fallido.'),
('n12-jobs-y-colas', E'\n\n=== CASO APLICADO ===\nProcesar una sincronización larga dentro de una petición HTTP aumenta riesgo de timeout. Encolarla permite responder rápido y procesar con concurrencia y reintentos controlados.\n\nRETO EXTRA\nDefine payload mínimo de un job, número máximo de intentos y estrategia ante fallo definitivo.'),
('n12-sincronizacion-de-datos', E'\n\n=== CASO APLICADO ===\nCuando dos sistemas editan el mismo cliente necesitas fuente de verdad, marcas de versión o reglas de conflicto. Sin ellas, una sincronización puede sobrescribir cambios válidos.\n\nRETO EXTRA\nCompara last-write-wins con una política de campo por campo y explica sus riesgos.'),
('n12-proyecto-saas', E'\n\n=== CASO APLICADO ===\nEntrega una integración OAuth que renueve credenciales, procese trabajo asíncrono y sincronice datos con una política de conflicto explícita.\n\nRETO EXTRA\nIncluye en la demo expiración de token, reautorización y un job reintentado con éxito.')
)
update public.lessons l
set content=coalesce(l.content,'') || b.addition
from bank b
where l.slug=b.slug and coalesce(l.content,'') not like '%=== CASO APLICADO ===%';
