with bank(slug, addition) as (
values
('n13-erp-y-crm', E'\n\n=== CASO APLICADO ===\nUn CRM y un ERP pueden llamar “cuenta” a conceptos distintos. Antes de sincronizar, define entidades, identificadores estables y qué sistema manda sobre cada dato.\n\nRETO EXTRA\nCrea una tabla de mapeo entre cliente CRM y cliente ERP y explica cómo manejarías duplicados y fusiones.'),
('n13-sistemas-de-identidad', E'\n\n=== CASO APLICADO ===\nEl ciclo de vida de identidad incluye alta, cambios de rol y baja. Una integración madura aprovisiona y desaprovisiona acceso con trazabilidad y mínimo privilegio.\n\nRETO EXTRA\nDiseña el flujo de baja de un empleado y marca qué sistemas deben confirmar revocación.'),
('n13-integraciones-batch', E'\n\n=== CASO APLICADO ===\nUn lote grande debe poder reanudarse sin repetir todo. Divide en unidades, guarda checkpoints y registra errores por registro para separar fallos parciales de fallos globales.\n\nRETO EXTRA\nDefine una estrategia para procesar 100,000 registros en lotes y reanudar desde el último checkpoint válido.'),
('n13-etl-y-mapeo', E'\n\n=== CASO APLICADO ===\nExtraer, transformar y cargar datos exige reglas explícitas de conversión. Si un proveedor usa códigos distintos a tu modelo, documenta el mapeo y qué hacer con valores desconocidos.\n\nRETO EXTRA\nDiseña una tabla de transformación para país, moneda y estado de cliente e incluye una política para valores no reconocidos.'),
('n13-mensajeria-empresarial', E'\n\n=== CASO APLICADO ===\nEn mensajería distribuida, duplicados y desorden pueden ocurrir. El consumidor debe identificar mensajes, manejar reintentos y decidir qué garantías necesita realmente.\n\nRETO EXTRA\nExplica cómo procesarías un mensaje duplicado y uno fuera de orden sin perder consistencia.'),
('n13-proyecto-enterprise', E'\n\n=== CASO APLICADO ===\nEntrega una integración empresarial que reconcilie entidades, procese lotes y deje evidencia de cada transferencia. La operación debe poder explicar qué pasó con un registro específico.\n\nRETO EXTRA\nPrepara un reporte de reconciliación con totales enviados, aceptados, rechazados y pendientes.'),

('n14-threat-modeling', E'\n\n=== CASO APLICADO ===\nModela una integración preguntando qué activos existen, quién puede interactuar, dónde cambia la confianza y cómo podría abusarse el flujo. Después prioriza amenazas por impacto y probabilidad.\n\nRETO EXTRA\nHaz un threat model sencillo de un webhook público y propone una mitigación para spoofing, replay y abuso de volumen.'),
('n14-gestion-de-secretos', E'\n\n=== CASO APLICADO ===\nLos secretos deben vivir fuera del código, rotarse cuando se exponen y limitarse por entorno y privilegio. Borrar un commit no invalida una credencial ya filtrada.\n\nRETO EXTRA\nDiseña un procedimiento de rotación para una API key usada por producción y staging sin interrumpir el servicio.'),
('n14-seguridad-de-apis', E'\n\n=== CASO APLICADO ===\nUna API sensible combina autenticación, autorización por recurso, validación, límites de tasa y logs seguros. Ninguna capa sustituye completamente a las demás.\n\nRETO EXTRA\nConstruye una checklist de seguridad para una ruta que modifica datos de facturación.'),
('n14-escalabilidad', E'\n\n=== CASO APLICADO ===\nAntes de escalar infraestructura, identifica el cuello de botella: CPU, base de datos, red o dependencia externa. Medir evita optimizar la parte equivocada.\n\nRETO EXTRA\nDefine tres métricas para decidir si un endpoint necesita cache, más concurrencia o una consulta SQL mejor.'),
('n14-resiliencia', E'\n\n=== CASO APLICADO ===\nLos fallos externos deben quedar contenidos. Timeouts, backoff, límites de concurrencia y circuit breakers evitan que una dependencia degradada arrastre todo el sistema.\n\nRETO EXTRA\nDiseña la respuesta del sistema cuando un proveedor crítico falla durante 15 minutos y luego se recupera.'),
('n14-arquitectura-final', E'\n\n=== CASO APLICADO ===\nUna arquitectura defendible conecta requisitos con decisiones y documenta límites. Debe explicar seguridad, escalabilidad, resiliencia y operación con trade-offs explícitos.\n\nRETO EXTRA\nEscribe un ADR breve para elegir entre procesamiento síncrono y asíncrono en una integración de alto volumen.'),

('n15-descubrimiento-del-caso', E'\n\n=== CASO APLICADO ===\nEl capstone final comienza entendiendo proceso actual, actores, sistemas, datos, volúmenes, errores y criterio de éxito. Las preguntas correctas reducen retrabajo técnico.\n\nRETO EXTRA\nPrepara diez preguntas de discovery para una empresa que quiere sincronizar su CRM con una plataforma de soporte.'),
('n15-diseno-de-solucion', E'\n\n=== CASO APLICADO ===\nDiseña contratos, flujo de datos, seguridad, estados de error y operación antes de implementar. Incluye qué ocurre cuando cada dependencia no está disponible.\n\nRETO EXTRA\nEntrega un diagrama de secuencia con happy path y un flujo alternativo por fallo de proveedor.'),
('n15-implementacion-integral', E'\n\n=== CASO APLICADO ===\nConstruye por cortes verticales que atraviesen entrada, lógica, persistencia e integración. Cada corte debe ser observable y probabile antes de añadir complejidad.\n\nRETO EXTRA\nDivide la solución en cuatro incrementos demostrables y define dependencias entre ellos.'),
('n15-pruebas-end-to-end', E'\n\n=== CASO APLICADO ===\nUna prueba E2E final debe cubrir negocio real, no solo botones: autorización, intercambio de datos, persistencia y resultado en el sistema destino. Añade al menos un fallo recuperable.\n\nRETO EXTRA\nEscribe seis escenarios E2E incluyendo duplicado, timeout, permiso insuficiente y recuperación.'),
('n15-observabilidad-y-runbook', E'\n\n=== CASO APLICADO ===\nUn sistema listo para operar necesita métricas, logs correlacionados y un runbook que indique cómo diagnosticar y recuperar. La observabilidad sin acción operativa se queda incompleta.\n\nRETO EXTRA\nDefine una alerta con umbral, señal, impacto esperado y los primeros cinco pasos de diagnóstico.'),
('n15-capstone-de-integraciones', E'\n\n=== CASO APLICADO ===\nLa defensa final debe demostrar que puedes construir, explicar y operar la integración. Presenta decisiones, evidencia de pruebas, riesgos, límites y cómo responderías ante incidentes.\n\nRETO EXTRA\nPrepara una revisión post-lanzamiento con métricas de éxito, incidentes posibles, deuda técnica y próximos pasos priorizados.')
)
update public.lessons l
set content=coalesce(l.content,'') || b.addition
from bank b
where l.slug=b.slug and coalesce(l.content,'') not like '%=== CASO APLICADO ===%';
