-- CodeZero Support S1: FAQ, suggestions and tickets.

create table if not exists public.support_faqs (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  question text not null,
  answer text not null,
  category text not null,
  keywords text[] not null default '{}',
  status text not null default 'draft'
    check (status in ('draft','published','archived')),
  notion_url text,
  sort_order integer not null default 100 check (sort_order >= 0),
  search_vector tsvector generated always as (
    to_tsvector(
      'spanish',
      coalesce(question,'') || ' ' ||
      coalesce(answer,'') || ' ' ||
      coalesce(category,'')
    )
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_faqs_search_idx
  on public.support_faqs using gin(search_vector);
create index if not exists support_faqs_category_idx
  on public.support_faqs(category, status, sort_order);

create table if not exists public.support_faq_feedback (
  id bigint generated by default as identity primary key,
  faq_id bigint not null references public.support_faqs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  helpful boolean not null,
  query_text text,
  created_at timestamptz not null default now()
);

create index if not exists support_faq_feedback_faq_idx
  on public.support_faq_feedback(faq_id, created_at desc);
create index if not exists support_faq_feedback_user_idx
  on public.support_faq_feedback(user_id, created_at desc);

create table if not exists public.support_suggestions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 3 and 160),
  detail text not null check (char_length(detail) between 10 and 5000),
  category text not null default 'general',
  status text not null default 'new'
    check (status in ('new','reviewing','planned','implemented','declined')),
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_suggestions_user_idx
  on public.support_suggestions(user_id, created_at desc);
create index if not exists support_suggestions_status_idx
  on public.support_suggestions(status, created_at desc);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null check (char_length(subject) between 3 and 180),
  description text not null check (char_length(description) between 10 and 8000),
  category text not null default 'general',
  priority text not null default 'normal'
    check (priority in ('low','normal','high','urgent')),
  status text not null default 'open'
    check (status in ('open','in_progress','waiting_user','resolved','closed')),
  original_query text,
  viewed_faq_ids bigint[] not null default '{}',
  assigned_to uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_user_idx
  on public.support_tickets(user_id, created_at desc);
create index if not exists support_tickets_queue_idx
  on public.support_tickets(status, priority, created_at);

create table if not exists public.support_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  sender_user_id uuid references auth.users(id) on delete set null,
  sender_role text not null check (sender_role in ('user','admin','system')),
  body text not null check (char_length(body) between 1 and 8000),
  created_at timestamptz not null default now()
);

create index if not exists support_ticket_messages_ticket_idx
  on public.support_ticket_messages(ticket_id, created_at);

alter table public.support_faqs enable row level security;
alter table public.support_faq_feedback enable row level security;
alter table public.support_suggestions enable row level security;
alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;

create policy "Anyone can read published support FAQs"
on public.support_faqs for select
to anon, authenticated
using (status = 'published');

create policy "Users can submit own FAQ feedback"
on public.support_faq_feedback for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can read own suggestions"
on public.support_suggestions for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create own suggestions"
on public.support_suggestions for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can read own tickets"
on public.support_tickets for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create own tickets"
on public.support_tickets for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can read messages on own tickets"
on public.support_ticket_messages for select
to authenticated
using (
  exists (
    select 1
    from public.support_tickets t
    where t.id = support_ticket_messages.ticket_id
      and t.user_id = (select auth.uid())
  )
);

create policy "Users can reply to own tickets"
on public.support_ticket_messages for insert
to authenticated
with check (
  sender_role = 'user'
  and sender_user_id = (select auth.uid())
  and exists (
    select 1
    from public.support_tickets t
    where t.id = support_ticket_messages.ticket_id
      and t.user_id = (select auth.uid())
      and t.status not in ('closed')
  )
);

revoke insert, update, delete on table public.support_faqs from anon, authenticated;
revoke select, update, delete on table public.support_faq_feedback from anon, authenticated;
revoke update, delete on table public.support_suggestions from anon, authenticated;
revoke update, delete on table public.support_tickets from anon, authenticated;
revoke update, delete on table public.support_ticket_messages from anon, authenticated;

grant select on table public.support_faqs to anon, authenticated;
grant insert on table public.support_faq_feedback to authenticated;
grant select, insert on table public.support_suggestions to authenticated;
grant select, insert on table public.support_tickets to authenticated;
grant select, insert on table public.support_ticket_messages to authenticated;

grant select, insert, update, delete on
  public.support_faqs,
  public.support_faq_feedback,
  public.support_suggestions,
  public.support_tickets,
  public.support_ticket_messages
to service_role;

insert into public.support_faqs(slug,question,answer,category,keywords,status,sort_order,notion_url)
values
('necesito-experiencia-previa','¿Necesito experiencia previa?','No. CodeZero comienza con pensamiento computacional y avanza de forma progresiva hacia programación, web, backend e integraciones SaaS.','Aprendizaje y progreso',array['principiante','experiencia','empezar'],'published',10,'https://app.notion.com/p/3f152732bf9481a48801c71e79dd352a'),
('que-incluye-free','¿Qué incluye el plan Free?','El plan Free permite acceder al Nivel 1 y a sus actividades dentro de los límites del plan. Los niveles posteriores requieren un plan compatible.','Planes y facturación',array['free','gratis','nivel 1'],'published',20,'https://app.notion.com/p/3f152732bf94817ea19ade4cb378c7a1'),
('horas-programa','¿Las 316 horas son horas de video?','No. Son una estimación de ruta que incluye lectura, práctica, ejercicios, evaluaciones, proyectos y trabajo independiente.','Aprendizaje y progreso',array['316','horas','duración'],'published',30,'https://app.notion.com/p/3f152732bf9481a48801c71e79dd352a'),
('desbloqueo-niveles','¿Cómo se desbloquean los niveles?','El avance es secuencial. Debes completar las lecciones y aprobar la evaluación correspondiente. En niveles con Capstone, el proyecto también debe estar aprobado.','Aprendizaje y progreso',array['nivel','desbloqueo','progreso'],'published',40,'https://app.notion.com/p/3f152732bf9481a48801c71e79dd352a'),
('ejercicios-por-leccion','¿Cuántos ejercicios hay por lección?','Actualmente cada una de las 92 lecciones tiene 2 ejercicios formativos, para un total de 184 ejercicios.','Ejercicios y exámenes',array['ejercicios','184','lección'],'published',50,'https://app.notion.com/p/3f152732bf9481a48801c71e79dd352a'),
('preguntas-examen','¿Cuántas preguntas tiene cada examen?','Cada nivel tiene una evaluación de 5 preguntas. Se requiere un mínimo de 70 % para aprobar.','Ejercicios y exámenes',array['examen','preguntas','70'],'published',60,'https://app.notion.com/p/3f152732bf9481a48801c71e79dd352a'),
('capstones','¿Qué son los proyectos Capstone?','Son proyectos profesionales en los niveles 10 y 15. Se entregan para revisión y deben ser aprobados antes de presentar el examen final de esos niveles.','Aprendizaje y progreso',array['capstone','proyecto','nivel 10','nivel 15'],'published',70,'https://app.notion.com/p/3f152732bf9481a48801c71e79dd352a'),
('certificado','¿Obtengo un certificado?','Al completar satisfactoriamente los 15 niveles se genera un certificado dentro de tu cuenta. No equivale a un título oficial ni garantiza resultados laborales.','Certificados',array['certificado','finalizar','15 niveles'],'published',80,'https://app.notion.com/p/3f152732bf9481a48801c71e79dd352a'),
('menores','¿Pueden usar CodeZero personas menores de edad?','Sí. Cuando corresponda deben contar con autorización y supervisión de su madre, padre o tutor legal. Las compras deben realizarse con autorización del adulto responsable y del titular del método de pago.','Cuenta y acceso',array['menor','edad','tutor'],'published',90,'https://app.notion.com/p/3f152732bf9481a1ab51e54de2d55513'),
('suscripciones','¿Cómo funcionan las suscripciones?','Los planes de pago se gestionan con Stripe y se cobran de forma recurrente según el precio mostrado antes de contratar. Una suscripción activa puede administrarse desde el portal de facturación.','Planes y facturación',array['stripe','suscripción','pago'],'published',100,'https://app.notion.com/p/3f152732bf94817ea19ade4cb378c7a1'),
('reembolsos','¿Hay reembolsos?','No hay reembolsos automáticos. Se revisan errores de cobro, cargos duplicados y los casos en que la legislación aplicable exija una devolución.','Planes y facturación',array['reembolso','duplicado','cobro'],'published',110,'https://app.notion.com/p/3f152732bf94817ea19ade4cb378c7a1'),
('tutor-ia','¿Cómo funciona Tutor IA?','Tutor IA es un add-on separado de los planes base. Está diseñado para ofrecer 100 consultas por mes cuando se encuentre activo. Su compra permanece bloqueada mientras el servicio de OpenAI no esté configurado.','Tutor IA',array['ia','tutor','addon','openai'],'published',120,'https://app.notion.com/p/3f152732bf94817ea19ade4cb378c7a1'),
('precio-tutor-ia','¿Cuánto cuesta Tutor IA?','El esquema definido es $50 MXN el primer mes, $75 MXN el segundo mes y $100 MXN al mes desde el tercer mes.','Tutor IA',array['precio','50','75','100'],'published',130,'https://app.notion.com/p/3f152732bf94817ea19ade4cb378c7a1'),
('descargar-datos','¿Puedo descargar mis datos?','Sí. Desde tu perfil puedes descargar una copia en JSON de tus datos de cuenta y aprendizaje.','Privacidad y datos',array['privacidad','datos','exportar'],'published',140,'https://app.notion.com/p/3f152732bf94819e9dfbd6922e47dab8'),
('contacto-soporte','¿Cómo contacto a soporte?','Puedes usar este Centro de ayuda y, si una FAQ no resuelve tu caso, abrir un ticket dentro de CodeZero. Para asuntos de privacidad también está disponible el correo de contacto publicado en la plataforma.','Problemas técnicos',array['soporte','contacto','ticket'],'published',150,'https://app.notion.com/p/3f252732bf94819ea6d8ce7c839e034a'),
('smtp-email','No recibo un correo de confirmación o recuperación, ¿qué hago?','El correo transaccional propio todavía está pendiente de dominio y SMTP. Mientras esa configuración no esté finalizada pueden existir limitaciones de entrega. Si el problema persiste, abre un ticket.','Cuenta y acceso',array['email','confirmación','recuperación','smtp'],'published',160,'https://app.notion.com/p/3f152732bf9481fab66ad7ab575c6b3b')
on conflict (slug) do nothing;
