-- Additive release requested by Isaac; no changes to existing grants, Auth, quotas or evidence.
set local lock_timeout='5s';
create table public.learning_development_plans(
 id uuid primary key,organization_id uuid not null,user_id uuid not null,proposed_by uuid not null,
 goals jsonb not null check(jsonb_typeof(goals)='array' and jsonb_array_length(goals) between 1 and 3),
 due_at timestamptz not null,state text not null default 'proposed' check(state in ('proposed','accepted','commented')),
 revision integer not null default 1,history jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 foreign key(organization_id,user_id) references public.organization_memberships(organization_id,user_id),
 foreign key(organization_id,proposed_by) references public.organization_memberships(organization_id,user_id)
);
create index development_plan_person_idx on public.learning_development_plans(organization_id,user_id,created_at desc);
create index development_plan_actor_idx on public.learning_development_plans(organization_id,proposed_by);
alter table public.learning_development_plans enable row level security;
revoke all on public.learning_development_plans from public,anon,authenticated;
grant select on public.learning_development_plans to authenticated;grant all on public.learning_development_plans to service_role;
create policy development_plan_read on public.learning_development_plans for select to authenticated using(
 exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.status='active') and
 exists(select 1 from codezero_private.organization_access a where a.organization_id=learning_development_plans.organization_id and a.viewer_id=(select auth.uid()) and a.target_id=learning_development_plans.user_id)
);
create function public.propose_learning_development_plan(p_actor uuid,p_org uuid,p_user uuid,p_id uuid,p_goals jsonb,p_due timestamptz,p_before jsonb) returns void language plpgsql security invoker set search_path='' as $$
declare g jsonb;ids bigint[]='{}';aid bigint;keys text[]='{}';
begin
 if current_setting('role',true)<>'service_role' or not exists(select 1 from public.profiles where id=p_actor and status='active') or
 not exists(select 1 from public.organization_memberships m join public.organizations o on o.id=m.organization_id join codezero_private.organization_access a on a.organization_id=m.organization_id and a.viewer_id=p_actor and a.target_id=p_user where m.organization_id=p_org and m.user_id=p_actor and m.active and o.active and m.role in ('owner','admin','manager','supervisor')) then raise exception 'FORBIDDEN';end if;
 if p_actor=p_user or p_due is null or p_due<=now() or jsonb_typeof(p_goals)<>'array' or jsonb_array_length(p_goals) not between 1 and 3 then raise exception 'INVALID_PLAN';end if;
 for g in select value from jsonb_array_elements(p_goals) loop
  if g->>'key'=any(keys) or not (g->>'key'=any(array['communication','diagnosis','data','prioritization','documentation','deescalation','negotiation','planning','technical','collaboration'])) or (g->>'target') !~ '^[1-4]$' or (g->>'baseline') !~ '^[0-4]$' then raise exception 'INVALID_GOAL';end if;
  select id into aid from public.learning_activity_catalog where content_key=g->>'activity' and active and g->>'key'=any(competencies) and kind='deliverable';
  if aid is null then raise exception 'INVALID_ACTIVITY';end if;ids=array_append(ids,aid);keys=array_append(keys,g->>'key');
 end loop;
 if exists(select 1 from public.learning_development_plans where id=p_id) then raise exception 'PLAN_CONFLICT';end if;
 perform public.assign_training_reinforcement(p_org,p_actor,p_user,array(select distinct unnest(ids)),p_due,p_before);
 insert into public.learning_development_plans(id,organization_id,user_id,proposed_by,goals,due_at,history) values(p_id,p_org,p_user,p_actor,p_goals,p_due,jsonb_build_array(jsonb_build_object('action','proposed','actor',p_actor,'at',now())));
end $$;
create function public.respond_learning_development_plan(p_actor uuid,p_id uuid,p_revision integer,p_action text,p_comment text) returns void language plpgsql security invoker set search_path='' as $$
declare plan public.learning_development_plans;
begin
 if current_setting('role',true)<>'service_role' or not exists(select 1 from public.profiles where id=p_actor and status='active') then raise exception 'FORBIDDEN';end if;
 select * into plan from public.learning_development_plans where id=p_id for update;
 if plan.user_id is distinct from p_actor or not exists(select 1 from public.organization_memberships m join public.organizations o on o.id=m.organization_id where m.organization_id=plan.organization_id and m.user_id=p_actor and m.active and o.active) then raise exception 'FORBIDDEN';end if;
 if p_revision<>plan.revision or p_action not in ('accept','comment') or length(p_comment)>2000 or (p_action='comment' and length(trim(p_comment))<1) or jsonb_array_length(plan.history)>=50 then raise exception 'PLAN_CONFLICT';end if;
 update public.learning_development_plans set state=case when p_action='accept' then 'accepted' else 'commented' end,revision=revision+1,updated_at=now(),history=history||jsonb_build_array(jsonb_build_object('action',p_action,'actor',p_actor,'at',now(),'comment',p_comment)) where id=p_id;
end $$;
revoke all on function public.propose_learning_development_plan(uuid,uuid,uuid,uuid,jsonb,timestamptz,jsonb),public.respond_learning_development_plan(uuid,uuid,integer,text,text) from public,anon,authenticated;
grant execute on function public.propose_learning_development_plan(uuid,uuid,uuid,uuid,jsonb,timestamptz,jsonb),public.respond_learning_development_plan(uuid,uuid,integer,text,text) to service_role;
create table public.notice_read_states(user_id uuid not null references public.profiles(id) on delete cascade,event_key text not null check(length(event_key)<=240),read_at timestamptz not null default now(),primary key(user_id,event_key));
create table public.notice_preferences(user_id uuid primary key references public.profiles(id) on delete cascade,disabled_types text[] not null default '{}',updated_at timestamptz not null default now(),check(disabled_types<@array['assignment','review','weekly','invitation','ticket','message','mentoring','news']));
alter table public.notice_read_states enable row level security;alter table public.notice_preferences enable row level security;
revoke all on public.notice_read_states,public.notice_preferences from public,anon,authenticated;
grant select on public.notice_read_states,public.notice_preferences to authenticated;grant all on public.notice_read_states,public.notice_preferences to service_role;
create policy own_notice_states on public.notice_read_states for select to authenticated using(user_id=(select auth.uid()) and read_at>now()-interval '90 days');
create policy own_notice_preferences on public.notice_preferences for select to authenticated using(user_id=(select auth.uid()));
create index notice_retention_idx on public.notice_read_states(read_at);
-- Read-state retention is physical, not only a UI filter. Existing Supabase Cron is reused.
select cron.schedule('learning-notices-retention','17 * * * *',$$delete from public.notice_read_states where read_at<=now()-interval '90 days'$$);

insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('necesito-experiencia-previa','Aprendizaje y progreso','¿Necesito experiencia previa?','Puedes empezar desde cero. Garciloga combina programación, práctica y decisiones por puesto; las rutas completas dependen de tu plan.',array['Aprendizaje y progreso','necesito-experiencia-previa'],'published',150) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('precio-tutor-ia','Tutor IA','¿Cuánto cuesta Tutor IA?','Tutor IA no está disponible para contratar. Su compra sigue bloqueada; no es necesario para usar las funciones de aprendizaje publicadas.',array['Tutor IA','precio-tutor-ia'],'published',151) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('curso-customer-success','Aprendizaje y progreso','¿Qué incluye el curso Customer Success?','Pro incluye ocho unidades de Cuenta Faro, examen y proyecto con revisión humana, además del kit de empleabilidad. Las compañías conservan el acceso de su contrato. Exámenes y entregas usan las cuotas vigentes.',array['Aprendizaje y progreso','curso-customer-success'],'published',152) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('equipo-checkout','Equipos y compañías','¿Cómo contrato un equipo?','Elige Starter o Pro por persona en Contratar por seats, con un mínimo de cinco usuarios. Stripe confirma el pago y crea la organización. El contacto se utiliza para propuestas Enterprise a la medida.',array['Equipos y compañías','equipo-checkout'],'published',153) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('equipo-visibilidad','Equipos y compañías','¿Qué puede ver un manager?','Un supervisor ve sus reportes directos; un manager ve su rama. Dueño y administrador de compañía ven su organización. Los equipos y permisos adicionales limitan la visibilidad; no se muestran datos de otras compañías.',array['Equipos y compañías','equipo-visibilidad'],'published',154) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('equipo-refuerzo','Equipos y compañías','¿Cómo asigno un refuerzo y descargo el reporte?','Abre la ficha de aprendizaje, elige una actividad y una fecha. El reporte mensual permite filtrar equipo y mes y descargar CSV o PDF. Los resultados son de práctica revisada, no desempeño laboral real.',array['Equipos y compañías','equipo-refuerzo'],'published',155) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('rutas-acceso','Rutas por puesto y casos','¿Cómo encuentro mi ruta por puesto?','En Formación por puesto encontrarás tronco común y rutas de práctica. Pro y los contratos compatibles dan acceso a rutas completas. El mapa de carrera orienta con evidencia; no asigna títulos ni garantiza una promoción.',array['Rutas por puesto y casos','rutas-acceso'],'published',156) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('caso-semana','Rutas por puesto y casos','¿Cómo funciona el caso semanal?','Cada semana se publica un caso con datos ficticios de Cuenta Faro. Resuelve decisiones y envía tu entrega. La revisión humana usa la misma matriz de competencias.',array['Rutas por puesto y casos','caso-semana'],'published',157) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('proyecto-evidencia','Rutas por puesto y casos','¿Un proyecto aprobado cambia mis competencias?','La evidencia revisada actualiza la matriz según su rúbrica, autonomía y requisitos. Una autoevaluación o un objetivo del plan no cambia por sí solo el nivel validado.',array['Rutas por puesto y casos','proyecto-evidencia'],'published',158) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('comunidad-alias','Comunidad y mentoría','¿Cómo participo en la comunidad?','Elige un alias y publica dudas o avances sin datos confidenciales. Las publicaciones se moderan; puedes retirarlas o reportar contenido.',array['Comunidad y mentoría','comunidad-alias'],'published',159) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('mentoria-isaac','Comunidad y mentoría','¿Quién imparte las mentorías?','Isaac López García imparte las sesiones. Consulta disponibilidad y envía una solicitud; necesita confirmación. No se cobra por abrir la solicitud ni se solicita que los alumnos trabajen como mentores.',array['Comunidad y mentoría','mentoria-isaac'],'published',160) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('avisos-sin-correo','Comunidad y mentoría','¿Cómo me entero de revisiones o respuestas?','La campana de Avisos muestra actividad dentro de tu alcance. Puedes marcar avisos como leídos y silenciar tipos desde Mi cuenta. El correo saliente propio sigue pendiente de dominio y configuración.',array['Comunidad y mentoría','avisos-sin-correo'],'published',161) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('practica-lenguajes','Práctica ejecutable','¿Qué puedo ejecutar en la práctica?','Puedes ejecutar Python y SQL en un entorno aislado y usar datos ficticios. Los resultados ayudan a comprobar tu trabajo; no conectan con sistemas reales de tu empresa.',array['Práctica ejecutable','practica-lenguajes'],'published',162) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('practica-seguridad','Práctica ejecutable','¿Puedo pegar credenciales o datos de clientes?','Usa únicamente datos ficticios. No introduzcas contraseñas, tokens, datos personales de terceros ni información confidencial.',array['Práctica ejecutable','practica-seguridad'],'published',163) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('practica-recuperacion','Práctica ejecutable','¿Qué hago si una ejecución falla?','Revisa el mensaje, reduce el ejemplo y compara lo esperado con lo obtenido. Si persiste, abre un ticket con pasos y el error, sin credenciales.',array['Práctica ejecutable','practica-recuperacion'],'published',164) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('portfolio-voluntario','Portafolio y privacidad','¿Mi portafolio es público automáticamente?','No. Está desactivado por defecto. Elige evidencia personal aprobada y da consentimiento para publicar un enlace. No se incluyen entregas de compañías, textos privados ni la foto de perfil.',array['Portafolio y privacidad','portfolio-voluntario'],'published',165) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('portfolio-retirar','Portafolio y privacidad','¿Cómo retiro mi portafolio?','Desde Portafolio puedes despublicarlo. El enlace anterior deja de funcionar. Una persona que ya lo haya visto puede conservar una copia fuera de Garciloga.',array['Portafolio y privacidad','portfolio-retirar'],'published',166) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
insert into public.support_faqs(slug,category,question,answer,keywords,status,sort_order) values('soporte-vista','Portafolio y privacidad','¿Qué permite la vista de alumno del propietario?','Es una sesión registrada de solo lectura, de máximo 20 minutos, para revisar progreso y errores. Caduca y bloquea escrituras; no revela tu contraseña.',array['Portafolio y privacidad','soporte-vista'],'published',167) on conflict(slug) do update set category=excluded.category,question=excluded.question,answer=excluded.answer,keywords=excluded.keywords,status=excluded.status;
