set local lock_timeout='5s';
create table public.learning_mixed_release(id boolean primary key default true check(id), enabled boolean not null default false);
insert into public.learning_mixed_release values(true,false);
create table public.learning_mixed_steps(
 step_key text primary key,unit_key text not null,ordinal integer not null check(ordinal between 1 and 8),
 activity_id bigint not null references public.learning_activity_catalog(id),
 work_type text not null check(work_type in ('tecnica','comercial','procesos','herramientas')),
 primary_competency text not null,format text not null check(format in ('decision','deliverable','python','sql','simulation')),
 version text not null default 'mixed-v1',unique(unit_key,ordinal));
create index learning_mixed_steps_activity_idx on public.learning_mixed_steps(activity_id);
create table public.learning_mixed_submission_steps(
 submission_id uuid primary key references public.learning_practice_submissions(id) on delete cascade,
 step_key text not null references public.learning_mixed_steps(step_key),payload jsonb not null check(jsonb_typeof(payload)='object' and octet_length(payload::text)<=24000));
create index learning_mixed_submission_step_idx on public.learning_mixed_submission_steps(step_key);
alter table public.learning_mixed_release enable row level security;
alter table public.learning_mixed_steps enable row level security;
alter table public.learning_mixed_submission_steps enable row level security;
revoke all on public.learning_mixed_release,public.learning_mixed_steps,public.learning_mixed_submission_steps from public,anon,authenticated;
grant all on public.learning_mixed_release,public.learning_mixed_steps,public.learning_mixed_submission_steps to service_role;
grant select on public.learning_mixed_submission_steps to authenticated;
create policy mixed_submission_read on public.learning_mixed_submission_steps for select to authenticated using(exists(select 1 from public.learning_practice_submissions s where s.id=submission_id));
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'account-manager-renewal:1','account-manager-renewal',1,id,'comercial','communication','decision' from public.learning_activity_catalog where content_key='cs-qbr' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'account-manager-renewal:2','account-manager-renewal',2,id,'tecnica','technical','sql' from public.learning_activity_catalog where content_key='data_bi-unit-1-3' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'account-manager-renewal:3','account-manager-renewal',3,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'account-manager-renewal:4','account-manager-renewal',4,id,'procesos','planning','decision' from public.learning_activity_catalog where content_key='cs-renewal' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'account-manager-renewal:5','account-manager-renewal',5,id,'tecnica','data','python' from public.learning_activity_catalog where content_key='cs-forecast' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'account-manager-renewal:6','account-manager-renewal',6,id,'comercial','negotiation','decision' from public.learning_activity_catalog where content_key='cs-expansion' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'account-manager-renewal:7','account-manager-renewal',7,id,'procesos','planning','deliverable' from public.learning_activity_catalog where content_key='cs-renewal' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'account-manager-renewal:8','account-manager-renewal',8,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'onboarding-implementation:1','onboarding-implementation',1,id,'comercial','communication','decision' from public.learning_activity_catalog where content_key='cs-kickoff' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'onboarding-implementation:2','onboarding-implementation',2,id,'procesos','planning','deliverable' from public.learning_activity_catalog where content_key='cs-success-plan' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'onboarding-implementation:3','onboarding-implementation',3,id,'tecnica','data','python' from public.learning_activity_catalog where content_key='data_bi-unit-1-2' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'onboarding-implementation:4','onboarding-implementation',4,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'onboarding-implementation:5','onboarding-implementation',5,id,'tecnica','technical','python' from public.learning_activity_catalog where content_key='cs-integration' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'onboarding-implementation:6','onboarding-implementation',6,id,'procesos','planning','decision' from public.learning_activity_catalog where content_key='cs-success-plan' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'onboarding-implementation:7','onboarding-implementation',7,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'onboarding-implementation:8','onboarding-implementation',8,id,'comercial','communication','decision' from public.learning_activity_catalog where content_key='cs-kickoff' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'support-sync-incident:1','support-sync-incident',1,id,'procesos','prioritization','decision' from public.learning_activity_catalog where content_key='common-priority' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'support-sync-incident:2','support-sync-incident',2,id,'tecnica','technical','python' from public.learning_activity_catalog where content_key='solutions-unit-1-2' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'support-sync-incident:3','support-sync-incident',3,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'support-sync-incident:4','support-sync-incident',4,id,'comercial','deescalation','decision' from public.learning_activity_catalog where content_key='common-deescalation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'support-sync-incident:5','support-sync-incident',5,id,'tecnica','technical','python' from public.learning_activity_catalog where content_key='solutions-unit-1-3' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'support-sync-incident:6','support-sync-incident',6,id,'procesos','collaboration','deliverable' from public.learning_activity_catalog where content_key='solutions-unit-1-5' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'support-sync-incident:7','support-sync-incident',7,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'support-sync-incident:8','support-sync-incident',8,id,'comercial','communication','decision' from public.learning_activity_catalog where content_key='common-deescalation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'product-low-adoption:1','product-low-adoption',1,id,'comercial','communication','decision' from public.learning_activity_catalog where content_key='product-unit-1-1' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'product-low-adoption:2','product-low-adoption',2,id,'tecnica','technical','sql' from public.learning_activity_catalog where content_key='data_bi-unit-1-3' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'product-low-adoption:3','product-low-adoption',3,id,'procesos','prioritization','decision' from public.learning_activity_catalog where content_key='product-unit-1-2' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'product-low-adoption:4','product-low-adoption',4,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'product-low-adoption:5','product-low-adoption',5,id,'tecnica','data','sql' from public.learning_activity_catalog where content_key='product-unit-1-3' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'product-low-adoption:6','product-low-adoption',6,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'product-low-adoption:7','product-low-adoption',7,id,'procesos','collaboration','deliverable' from public.learning_activity_catalog where content_key='product-unit-1-4' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'product-low-adoption:8','product-low-adoption',8,id,'comercial','communication','decision' from public.learning_activity_catalog where content_key='product-unit-1-5' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'customer-success-risk:1','customer-success-risk',1,id,'comercial','communication','decision' from public.learning_activity_catalog where content_key='cs-roleplay-1' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'customer-success-risk:2','customer-success-risk',2,id,'tecnica','technical','sql' from public.learning_activity_catalog where content_key='data_bi-unit-1-3' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'customer-success-risk:3','customer-success-risk',3,id,'procesos','planning','decision' from public.learning_activity_catalog where content_key='cs-churn' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'customer-success-risk:4','customer-success-risk',4,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'customer-success-risk:5','customer-success-risk',5,id,'tecnica','data','python' from public.learning_activity_catalog where content_key='cs-health' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'customer-success-risk:6','customer-success-risk',6,id,'comercial','communication','decision' from public.learning_activity_catalog where content_key='cs-roleplay-3' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'customer-success-risk:7','customer-success-risk',7,id,'procesos','planning','deliverable' from public.learning_activity_catalog where content_key='cs-success-plan' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'customer-success-risk:8','customer-success-risk',8,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'manager-rising-churn:1','manager-rising-churn',1,id,'comercial','negotiation','decision' from public.learning_activity_catalog where content_key='cs-ebr' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'manager-rising-churn:2','manager-rising-churn',2,id,'tecnica','technical','sql' from public.learning_activity_catalog where content_key='data_bi-unit-1-3' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'manager-rising-churn:3','manager-rising-churn',3,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'manager-rising-churn:4','manager-rising-churn',4,id,'procesos','planning','deliverable' from public.learning_activity_catalog where content_key='leadership-unit-1-1' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'manager-rising-churn:5','manager-rising-churn',5,id,'tecnica','technical','sql' from public.learning_activity_catalog where content_key='data_bi-unit-1-3' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'manager-rising-churn:6','manager-rising-churn',6,id,'procesos','collaboration','decision' from public.learning_activity_catalog where content_key='leadership-unit-1-2' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'manager-rising-churn:7','manager-rising-churn',7,id,'herramientas','documentation','simulation' from public.learning_activity_catalog where content_key='common-documentation' and active;
insert into public.learning_mixed_steps(step_key,unit_key,ordinal,activity_id,work_type,primary_competency,format) select 'manager-rising-churn:8','manager-rising-churn',8,id,'comercial','communication','decision' from public.learning_activity_catalog where content_key='cs-ebr' and active;
do $$begin if (select count(*) from public.learning_mixed_steps)<>48 then raise exception 'MIXED_CATALOG_MISMATCH';end if;end$$;
insert into public.learning_job_profiles(position_key,version,weights,expected)
select 'product_specialist',1,weights,expected from public.learning_job_profiles where position_key='project_manager' order by version desc limit 1;
create function public.submit_mixed_training(p_actor uuid,p_step text,p_request uuid,p_org uuid,p_payload jsonb,p_draft text,p_scores jsonb,p_assistance text,p_auto_results jsonb) returns uuid language plpgsql security invoker set search_path='' as $$
declare step public.learning_mixed_steps; result uuid; old public.learning_mixed_submission_steps;
begin
 if not exists(select 1 from public.learning_mixed_release where id and enabled) then raise exception 'MIXED_DISABLED';end if;
 select * into step from public.learning_mixed_steps where step_key=p_step;
 if not found or p_payload is null or jsonb_typeof(p_payload)<>'object' or octet_length(p_payload::text)>24000 then raise exception 'INVALID_MIXED_SUBMISSION';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_request::text,0));
 select * into old from public.learning_mixed_submission_steps where submission_id=p_request;
 if found and (old.step_key<>p_step or old.payload<>p_payload) then raise exception 'REQUEST_CONFLICT';end if;
 result=public.submit_training_practice(p_actor,step.activity_id,p_request,p_org,p_draft,p_scores,p_assistance,'[]'::jsonb,p_auto_results,null);
 insert into public.learning_mixed_submission_steps(submission_id,step_key,payload) values(result,p_step,p_payload) on conflict(submission_id) do nothing;
 return result;
end$$;
revoke all on function public.submit_mixed_training(uuid,text,uuid,uuid,jsonb,text,jsonb,text,jsonb) from public,anon,authenticated;
grant execute on function public.submit_mixed_training(uuid,text,uuid,uuid,jsonb,text,jsonb,text,jsonb) to service_role;
create function public.reject_mixed_self_review() returns trigger language plpgsql security invoker set search_path='' as $$begin
 if new.review_source in ('manager','admin') and new.reviewed_by=new.user_id and exists(select 1 from public.learning_mixed_submission_steps where submission_id=new.submission_id) then raise exception 'SELF_REVIEW_FORBIDDEN';end if;
 return new;end$$;
revoke all on function public.reject_mixed_self_review() from public,anon,authenticated;
grant execute on function public.reject_mixed_self_review() to service_role;
create trigger mixed_self_review_guard before insert on public.learning_evidence_history for each row execute function public.reject_mixed_self_review();
