begin;
-- New company data stays hidden after company deactivation, including direct Storage reads.
drop policy contract_read on public.organization_contracts;
create policy contract_read on public.organization_contracts for select to authenticated using(exists(select 1 from public.organizations o where o.id=organization_id and o.active) and exists(select 1 from public.organization_memberships m where m.organization_id=organization_contracts.organization_id and m.user_id=(select auth.uid()) and m.active and m.role in ('owner','admin')));
drop policy teams_read on public.organization_teams;
create policy teams_read on public.organization_teams for select to authenticated using(exists(select 1 from public.organizations o where o.id=organization_id and o.active) and (exists(select 1 from codezero_private.organization_access a where a.organization_id=organization_teams.organization_id and a.viewer_id=(select auth.uid()) and a.can_manage) or exists(select 1 from public.organization_team_members m where m.organization_id=organization_teams.organization_id and m.team_id=id and m.user_id=(select auth.uid())) or exists(select 1 from public.organization_team_grants g where g.organization_id=organization_teams.organization_id and g.team_id=id and g.user_id=(select auth.uid()) and (g.can_view or g.can_invite))));
drop policy team_members_read on public.organization_team_members;
create policy team_members_read on public.organization_team_members for select to authenticated using(exists(select 1 from public.organizations o where o.id=organization_id and o.active) and exists(select 1 from codezero_private.organization_access a where a.organization_id=organization_team_members.organization_id and a.viewer_id=(select auth.uid()) and a.target_id=user_id));
drop policy team_grants_read on public.organization_team_grants;
create policy team_grants_read on public.organization_team_grants for select to authenticated using(exists(select 1 from public.organizations o where o.id=organization_id and o.active) and exists(select 1 from codezero_private.organization_access a where a.organization_id=organization_team_grants.organization_id and a.viewer_id=(select auth.uid()) and (a.can_manage or user_id=(select auth.uid()))));
drop policy company_brand_read on storage.objects;
create policy company_brand_read on storage.objects for select to authenticated using(bucket_id='company-brand' and exists(select 1 from public.organization_memberships m join public.organizations o on o.id=m.organization_id where m.organization_id::text=split_part(storage.objects.name,'/',1) and m.user_id=(select auth.uid()) and m.active and o.active) and split_part(storage.objects.name,'/',2) ~ '^(logo|cover)-[0-9a-f-]{36}[.]webp$');
drop policy invitation_read on public.organization_invitations;
create policy invitation_read on public.organization_invitations for select to authenticated using(exists(select 1 from public.organizations o where o.id=organization_id and o.active) and exists(select 1 from codezero_private.organization_access a where a.organization_id=organization_invitations.organization_id and a.viewer_id=(select auth.uid()) and (a.can_manage or created_by=(select auth.uid()))));
commit;
