-- GRC uses existing Pro/Enterprise access, evidence and human review.
set local lock_timeout='5s';
alter table public.learning_activity_catalog drop constraint learning_activity_catalog_route_key_check;
alter table public.learning_activity_catalog add constraint learning_activity_catalog_route_key_check check(route_key in ('common','customer_success','operations','quality','data_bi','product','solutions','enablement','leadership','grc'));
create or replace function public.issue_professional_route_diploma(p_user uuid,p_org uuid,p_route text)
returns uuid language plpgsql security invoker set search_path='' as $$
declare profile public.learning_job_profiles; competency text; recognized integer; independent boolean; cap uuid; result uuid; position text;
begin
 if p_route not in ('operations','quality','data_bi','product','solutions','enablement','leadership','grc') then raise exception 'INVALID_ROUTE';end if;
 if not exists(select 1 from public.profiles where id=p_user and status='active' and (role in ('owner','admin') or codezero_private.effective_learning_plan(p_user) in ('pro','enterprise'))) then raise exception 'FORBIDDEN';end if;
 if p_org is not null and not exists(select 1 from public.organization_memberships m join public.organizations o on o.id=m.organization_id where m.organization_id=p_org and m.user_id=p_user and m.active and o.active) then raise exception 'FORBIDDEN';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_user::text||':professional:'||p_route,0));
 if p_org is null then select learning_position_key into position from public.profiles where id=p_user;
 else select learning_position_key into position from public.organization_memberships where organization_id=p_org and user_id=p_user and active;end if;
 select * into profile from public.learning_job_profiles where position_key=position order by version desc limit 1;
 if not found then raise exception 'MISSING_PROFILE';end if;
 select h.id into cap from public.learning_evidence_history h where h.user_id=p_user and h.organization_id is not distinct from p_org and h.activity_key=p_route||'-capstone' and h.review_source='admin' order by h.observed_at desc,h.id desc limit 1;
 if cap is null or not exists(select 1 from public.learning_evidence_history h where h.id=cap and h.assistance='independent' and cardinality(h.critical_errors)=0 and not exists(select 1 from jsonb_each(h.competency_scores) x where (x.value::text)::integer<3)) then raise exception 'CAPSTONE_REQUIRED';end if;
 for competency in select key from jsonb_each_text(profile.weights) where value='high' loop
  with latest as (
   select distinct on(h.independent_key) h.* from public.learning_evidence_history h
   where h.user_id=p_user and h.organization_id is not distinct from p_org and h.competency_scores?competency
   order by h.independent_key,(h.review_source in ('manager','admin')) desc,h.observed_at desc,h.id desc
  ) select count(*) filter(where cardinality(critical_errors)=0 and (competency_scores->>competency)::integer>=1),
   coalesce(bool_or(cardinality(critical_errors)=0 and review_source in ('manager','admin') and assistance='independent' and kind<>'exercise' and (competency_scores->>competency)::integer>=3),false)
   into recognized,independent from latest;
  if recognized<3 or not independent then raise exception 'COMPETENCY_NOT_DEMONSTRATED';end if;
 end loop;
 insert into public.certificates(user_id,certificate_type,title,metadata) values(p_user,'professional-'||p_route||'-v1','Garciloga · '||p_route||': práctica simulada',jsonb_build_object('route_version','professional-practice-v1','estimated_hours',case when p_route='grc' then 257 else 233 end,'profile_position',position,'profile_version',profile.version,'capstone_evidence_id',cap,'scope','simulated_practice','included_in_plan',true)) on conflict(user_id,certificate_type) do nothing;
 select id into result from public.certificates where user_id=p_user and certificate_type='professional-'||p_route||'-v1';return result;
end $$;
revoke all on function public.issue_professional_route_diploma(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.issue_professional_route_diploma(uuid,uuid,text) to service_role;

insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-1-1','grc','Fundamentos · Gobierno y responsabilidad','deliverable',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-1-2','grc','Fundamentos · Registro y evaluación de riesgos','deliverable',array['diagnosis','data','prioritization']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-1-3','grc','Fundamentos · Diseño y prueba de controles','deliverable',array['technical','documentation','diagnosis']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-1-4','grc','Fundamentos · Políticas y obligaciones','deliverable',array['documentation','communication','planning']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-1-5','grc','Fundamentos · Auditoría y evidencias','deliverable',array['data','diagnosis','communication']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-1-6','grc','Fundamentos · Seguimiento y cierre de hallazgos','deliverable',array['negotiation','deescalation','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-2-1','grc','Operación · Gobierno y responsabilidad','deliverable',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-2-2','grc','Operación · Registro y evaluación de riesgos','deliverable',array['diagnosis','data','prioritization']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-2-3','grc','Operación · Diseño y prueba de controles','deliverable',array['technical','documentation','diagnosis']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-2-4','grc','Operación · Políticas y obligaciones','deliverable',array['documentation','communication','planning']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-2-5','grc','Operación · Auditoría y evidencias','deliverable',array['data','diagnosis','communication']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-2-6','grc','Operación · Seguimiento y cierre de hallazgos','deliverable',array['negotiation','deescalation','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-3-1','grc','Dominio · Gobierno y responsabilidad','deliverable',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-3-2','grc','Dominio · Registro y evaluación de riesgos','deliverable',array['diagnosis','data','prioritization']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-3-3','grc','Dominio · Diseño y prueba de controles','deliverable',array['technical','documentation','diagnosis']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-3-4','grc','Dominio · Políticas y obligaciones','deliverable',array['documentation','communication','planning']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-3-5','grc','Dominio · Auditoría y evidencias','deliverable',array['data','diagnosis','communication']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-3-6','grc','Dominio · Seguimiento y cierre de hallazgos','deliverable',array['negotiation','deescalation','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-4-1','grc','Especialista · Gobierno y responsabilidad','deliverable',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-4-2','grc','Especialista · Registro y evaluación de riesgos','deliverable',array['diagnosis','data','prioritization']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-4-3','grc','Especialista · Diseño y prueba de controles','deliverable',array['technical','documentation','diagnosis']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-4-4','grc','Especialista · Políticas y obligaciones','deliverable',array['documentation','communication','planning']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-4-5','grc','Especialista · Auditoría y evidencias','deliverable',array['data','diagnosis','communication']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-unit-4-6','grc','Especialista · Seguimiento y cierre de hallazgos','deliverable',array['negotiation','deescalation','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-episode-handoff','grc','Cuenta Faro · 1 · Traspaso comercial','deliverable',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-episode-success_plan','grc','Cuenta Faro · 2 · Plan de éxito','deliverable',array['diagnosis','data','prioritization']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-episode-onboarding','grc','Cuenta Faro · 3 · Onboarding y primer valor','deliverable',array['technical','documentation','diagnosis']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-episode-adoption','grc','Cuenta Faro · 4 · Adopción y resultados','deliverable',array['documentation','communication','planning']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-episode-risk','grc','Cuenta Faro · 5 · Riesgo y escalación','deliverable',array['data','diagnosis','communication']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-episode-business_review','grc','Cuenta Faro · 6 · Revisión de resultados','deliverable',array['negotiation','deescalation','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-episode-renewal','grc','Cuenta Faro · 7 · Renovación y expansión','deliverable',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-episode-voice_customer','grc','Cuenta Faro · 8 · Voz del cliente y cierre del ciclo','deliverable',array['diagnosis','data','prioritization']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-roleplay-1','grc','Role-play · Fundamentos','deliverable',array['communication','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-roleplay-2','grc','Role-play · Operación','deliverable',array['communication','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-roleplay-3','grc','Role-play · Dominio','deliverable',array['communication','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-roleplay-4','grc','Role-play · Especialista','deliverable',array['communication','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-project-1','grc','Proyecto · Operación','project',array['documentation','planning','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-project-2','grc','Proyecto · Dominio','project',array['documentation','planning','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-project-3','grc','Proyecto · Especialista','project',array['documentation','planning','collaboration']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-capstone','grc','Capstone · GRC · Gobierno, Riesgo y Cumplimiento y Cuenta Faro','capstone',array['diagnosis','planning','communication']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-exam-1','grc','Examen · Fundamentos','exercise',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-exam-2','grc','Examen · Operación','exercise',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-exam-3','grc','Examen · Dominio','exercise',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-exam-4','grc','Examen · Especialista','exercise',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-reevaluation-1','grc','Reevaluación a 30 días · Fundamentos','deliverable',array['planning','collaboration','documentation']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-reevaluation-2','grc','Reevaluación a 30 días · Operación','deliverable',array['diagnosis','data','prioritization']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-reevaluation-3','grc','Reevaluación a 30 días · Dominio','deliverable',array['technical','documentation','diagnosis']) on conflict(content_key) do nothing;
insert into public.learning_activity_catalog(content_key,route_key,title,kind,competencies) values('grc-reevaluation-4','grc','Reevaluación a 30 días · Especialista','deliverable',array['documentation','communication','planning']) on conflict(content_key) do nothing;
