-- Varied, server-graded lesson activities: ordering, fill-in with word bank and find-the-error.
-- Source: docs/curriculum/varied-activities.json. Additive; on conflict do nothing.
-- For order_steps the answer is exercise_solutions.correct_sequence; correct_answer keeps its
-- A-D check and stores the first step. Requires 20261010110000 (correct_sequence column).
create temp table _v(lesson text,slug text,kind text,prompt text,options jsonb,explanation text,answer text,seq text) on commit drop;
insert into _v values
('algoritmos-paso-a-paso','n1-orden-resolver-problema','order_steps','Ordena los pasos para diseñar un algoritmo antes de programarlo.','["Probar con casos normales y casos límite", "Definir el objetivo, las entradas y la salida", "Escribir los pasos en orden", "Dividir el problema en partes pequeñas"]'::jsonb,'Primero se entiende el problema, luego se divide, se escriben los pasos y al final se comprueban con casos.','B','BDCA'),
('depuracion-y-casos-limite','n1-error-promedio-vacio','find_error','Un algoritmo calcula un promedio dividiendo la suma entre la cantidad de elementos. ¿Qué caso lo rompe?','["Una lista con números negativos", "Una lista con un solo elemento", "Una lista vacía, porque divide entre cero", "Una lista con números repetidos"]'::jsonb,'Con cero elementos la división no está definida; ese caso límite debe decidirse antes de programar.','C',null),
('n2-funciones','n2-orden-crear-funcion','order_steps','Ordena los pasos para crear y comprobar una función en Python.','["Escribir el cuerpo y devolver el resultado con return", "Comprobar que el resultado es el esperado", "Definir la función con def y sus parámetros", "Llamar a la función con un valor de prueba"]'::jsonb,'Se define, se escribe el cuerpo, se llama con un valor conocido y se compara el resultado.','C','CADB'),
('n2-bucles','n2-completa-range','fill_blank','for i in ___(3): print(i) imprime 0, 1 y 2. ¿Qué palabra falta?','["len", "range", "list", "input"]'::jsonb,'range(3) genera 0, 1 y 2; el bucle recorre esos valores.','B',null),
('n3-excepciones','n3-orden-manejar-excepcion','order_steps','Ordena los pasos para manejar un error previsible en Python.','["Envolver esa operación en un bloque try", "Informar el error con un mensaje claro", "Capturar solo la excepción esperada con except", "Identificar la operación que puede fallar"]'::jsonb,'Se localiza el riesgo, se protege con try, se captura la excepción concreta y se informa con claridad.','D','DACB'),
('n3-codigo-limpio-y-pruebas','n3-error-prueba-sin-assert','find_error','Una prueba llama a la función pero no contiene ningún assert. ¿Cuál es el problema?','["Nunca falla, así que no verifica nada", "Tarda demasiado en ejecutarse", "Usa demasiada memoria", "No puede importarse"]'::jsonb,'Sin una comprobación, la prueba pasa aunque el resultado sea incorrecto.','A',null),
('n4-busqueda-y-ordenamiento','n4-orden-busqueda-binaria','order_steps','Ordena los pasos de una búsqueda binaria.','["Comparar el elemento central con el valor buscado", "Comprobar que la lista está ordenada", "Repetir hasta encontrarlo o quedarse sin elementos", "Descartar la mitad donde no puede estar"]'::jsonb,'La búsqueda binaria exige una lista ordenada; en cada vuelta compara el centro y descarta una mitad.','B','BADC'),
('n4-listas-pilas-y-colas','n4-completa-lifo','fill_blank','Una pila entrega primero el último elemento que entró. Ese orden se llama ___.','["FIFO", "aleatorio", "alfabético", "LIFO"]'::jsonb,'LIFO significa «último en entrar, primero en salir»; una cola, en cambio, es FIFO.','D',null),
('n5-git-basico','n5-orden-guardar-cambio','order_steps','Ordena los comandos para guardar y publicar un cambio con Git.','["git add archivo", "git commit -m \"mensaje\"", "git status", "git push"]'::jsonb,'Primero se revisa el estado, se prepara el archivo, se confirma con un mensaje y se publica.','C','CABD'),
('n5-ramas-y-merges','n5-error-conflicto','find_error','Al fusionar dos ramas aparece un conflicto en un archivo. ¿Cuál de estas acciones es un error?','["Leer ambas versiones y decidir qué conservar", "Borrar los cambios de la otra persona sin revisarlos", "Probar el resultado después de resolverlo", "Pedir contexto al autor si algo no está claro"]'::jsonb,'Un conflicto se resuelve entendiendo ambas versiones; descartar a ciegas pierde trabajo y puede romper el código.','B',null),
('n6-select-y-filtros','n6-orden-clausulas','order_steps','Ordena las cláusulas tal como se escriben en una consulta SQL.','["WHERE", "FROM", "ORDER BY", "SELECT"]'::jsonb,'Una consulta se escribe SELECT, FROM, WHERE y ORDER BY: qué columnas, de qué tabla, qué filas y en qué orden.','D','DBAC'),
('n6-joins','n6-completa-join','fill_blank','SELECT c.nombre, p.total FROM clientes c ___ pedidos p ON p.cliente_id = c.id; ¿Qué palabra une ambas tablas?','["JOIN", "WHERE", "GROUP BY", "UNION"]'::jsonb,'JOIN combina filas de dos tablas según la condición indicada en ON.','A',null),
('n7-fetch-y-estado','n7-orden-cargar-datos','order_steps','Ordena lo que debe hacer una página al cargar datos de una API.','["Comprobar si la respuesta fue correcta", "Indicar al usuario que la carga está en curso", "Mostrar los datos o un mensaje de error", "Enviar la solicitud con fetch"]'::jsonb,'Se avisa de la carga, se envía la solicitud, se comprueba la respuesta y se muestra el resultado o el error.','B','BDAC'),
('n7-html-semantico','n7-error-div-boton','find_error','Una página usa un elemento div con un evento de clic como si fuera un botón. ¿Cuál es el problema principal?','["Se ve más pequeño", "Carga más lento", "No admite colores", "No se alcanza con teclado ni se anuncia como botón"]'::jsonb,'Un div no recibe foco ni tiene rol de botón; el elemento button ofrece teclado y accesibilidad sin trabajo extra.','D',null),
('n8-validacion-y-errores','n8-orden-validar-solicitud','order_steps','Ordena cómo debe tratar una API una solicitud entrante.','["Validar tipos, campos obligatorios y límites", "Ejecutar la operación y responder", "Recibir la solicitud", "Devolver un error 400 con un mensaje claro si no cumple"]'::jsonb,'Se valida antes de ejecutar; lo que no cumple se rechaza con un error claro y solo lo válido llega a la operación.','C','CADB'),
('n8-http-y-rest','n8-completa-post','fill_blank','Para crear un recurso nuevo en una API REST se usa normalmente el método ___.','["GET", "DELETE", "POST", "HEAD"]'::jsonb,'POST crea recursos; GET los lee y DELETE los elimina.','C',null),
('n9-ci-cd','n9-orden-entrega-continua','order_steps','Ordena el recorrido de un cambio hasta producción.','["Abrir un pull request", "Desplegar a producción", "Integrar el cambio en la rama principal", "Ejecutar las pruebas automáticas"]'::jsonb,'El cambio se propone, se prueba automáticamente, se integra y solo entonces se despliega.','A','ADCB'),
('n9-testing','n9-error-prueba-inestable','find_error','Una prueba usa la hora actual del sistema y falla solo algunos días. ¿Cuál es el defecto?','["Depende de un estado externo que no controla", "Tiene demasiadas comprobaciones", "Está escrita en otro idioma", "Se ejecuta demasiado rápido"]'::jsonb,'Una prueba fiable controla sus entradas; la hora debe recibirse como dato para poder fijarla.','A',null),
('n10-definicion-del-producto','n10-orden-definir-producto','order_steps','Ordena los pasos para definir un producto antes de construirlo.','["Construir el alcance mínimo", "Describir el problema y para quién es", "Validar con usuarios y medir", "Definir el resultado esperado y cómo medirlo"]'::jsonb,'Se parte del problema y de su medida; después se construye lo mínimo y se valida con usuarios.','B','BDAC'),
('n10-documentacion','n10-completa-readme','fill_blank','El archivo que explica qué hace un proyecto y cómo ejecutarlo suele llamarse ___.','["LICENSE", "README", "CHANGELOG", ".gitignore"]'::jsonb,'El README es la puerta de entrada: propósito, requisitos y pasos para ejecutar el proyecto.','B',null),
('n11-firmas-y-reintentos','n11-orden-procesar-webhook','order_steps','Ordena cómo debe procesarse un webhook entrante.','["Comprobar si el evento ya fue procesado", "Responder con éxito al emisor", "Verificar la firma sobre el cuerpo original", "Aplicar el cambio una sola vez"]'::jsonb,'Primero autenticidad, luego duplicados; solo entonces se aplica el cambio y se confirma al emisor.','C','CADB'),
('n11-idempotencia','n11-error-cobro-duplicado','find_error','Un servicio reintenta un cobro tras un tiempo de espera agotado, sin clave de idempotencia. ¿Qué puede ocurrir?','["El cobro se cancela solo", "La solicitud se vuelve más rápida", "El cliente recibe dos cobros", "El token caduca"]'::jsonb,'Sin una clave que identifique la operación, el receptor no distingue un reintento de un cobro nuevo.','C',null),
('n12-oauth-2-0','n12-orden-flujo-oauth','order_steps','Ordena el flujo de código de autorización de OAuth 2.0.','["La aplicación intercambia el código por un token", "El proveedor devuelve un código de autorización", "La aplicación llama a la API con el token", "El usuario da su consentimiento en el proveedor"]'::jsonb,'El usuario consiente, el proveedor entrega un código, la aplicación lo cambia por un token y con él llama a la API.','D','DBAC'),
('n12-scopes-y-tokens','n12-completa-minimo-privilegio','fill_blank','Pedir solo los permisos necesarios para la tarea se conoce como principio de ___ privilegio.','["mínimo", "máximo", "doble", "libre"]'::jsonb,'Con el mínimo privilegio, un token filtrado expone solo lo imprescindible.','A',null),
('n13-etl-y-mapeo','n13-orden-etl','order_steps','Ordena las etapas de un proceso ETL.','["Cargar los datos en el destino", "Extraer los datos del origen", "Verificar conteos y registros rechazados", "Transformar y mapear los campos"]'::jsonb,'Extraer, transformar y cargar; la verificación final confirma que no se perdieron ni duplicaron registros.','B','BDAC'),
('n13-integraciones-batch','n13-error-reinicio-batch','find_error','Un proceso nocturno falla en el registro 500 de 2000 y, al reiniciarlo, vuelve a insertar los primeros 499. ¿Qué le falta?','["Más memoria", "Un horario distinto", "Un archivo más pequeño", "Un punto de control y cargas idempotentes"]'::jsonb,'Guardar el avance y poder repetir sin duplicar permite reanudar desde el fallo.','D',null),
('n14-threat-modeling','n14-orden-modelar-amenazas','order_steps','Ordena los pasos de un modelado de amenazas.','["Identificar amenazas en cada flujo", "Verificar que las mitigaciones funcionan", "Dibujar el sistema y sus flujos de datos", "Priorizar y definir mitigaciones"]'::jsonb,'Sin el mapa del sistema no se ven las amenazas; después se priorizan, se mitigan y se comprueba.','C','CADB'),
('n14-gestion-de-secretos','n14-completa-variable-entorno','fill_blank','Una clave de API no debe guardarse en el repositorio; debe leerse de una variable de ___.','["clase", "sesión", "entorno", "plantilla"]'::jsonb,'Las variables de entorno mantienen los secretos fuera del código y permiten rotarlos sin cambiarlo.','C',null),
('n15-pruebas-end-to-end','n15-orden-prueba-e2e','order_steps','Ordena una prueba de extremo a extremo de una integración.','["Ejecutar el flujo completo como lo haría un usuario", "Limpiar los datos de prueba", "Comprobar el resultado en cada sistema integrado", "Preparar datos de prueba ficticios"]'::jsonb,'Se preparan datos ficticios, se recorre el flujo, se comprueba cada sistema y se limpia al terminar.','D','DACB'),
('n15-observabilidad-y-runbook','n15-error-runbook-vago','find_error','Un runbook dice: «Si falla la sincronización, revisar y arreglar». ¿Qué le falta?','["Un título más largo", "Pasos concretos, cómo verificar y a quién escalar", "Más capturas de pantalla", "El nombre de quien lo escribió"]'::jsonb,'Un runbook sirve cuando otra persona puede seguirlo bajo presión: qué mirar, qué hacer, cómo confirmar y cuándo escalar.','B',null);
do $$begin if (select count(*) from _v v join public.lessons l on l.slug=v.lesson)<>30 then raise exception 'lesson missing'; end if; end$$;
insert into public.exercises(lesson_id,slug,prompt,kind,options,explanation,sort_order,status)
 select l.id,v.slug,v.prompt,v.kind,v.options,v.explanation,(select coalesce(max(e.sort_order),0)+1 from public.exercises e where e.lesson_id=l.id),'published'
 from _v v join public.lessons l on l.slug=v.lesson on conflict(slug) do nothing;
insert into public.exercise_solutions(exercise_id,correct_answer,correct_sequence)
 select e.id,v.answer,v.seq from _v v join public.exercises e on e.slug=v.slug on conflict(exercise_id) do nothing;
