import { translatedMetadata } from '../../lib/localization/metadata';
import LocalizedDate from '../components/localization/date';
import LocalizedContent from "../components/localization/server";
import Link from 'next/link';
import { redirect,notFound } from 'next/navigation';
import { workspaceEnabled } from '../../lib/workspace-sandbox';
import { workspaceUser } from '../../lib/workspace-server';
import {CS_COURSE_UNITS,CS_COURSE_DATA,CS_LESSONS,CS_CAPSTONE_RUBRIC,hasCustomerSuccessCourse} from '../../lib/customer-success-course';
import {CS_EXAM} from '../../lib/customer-success-exam';
import AssessmentProtection from '../components/assessment-protection';
import {randomUUID} from 'node:crypto';
import CertificateSharing from '../components/certificate-sharing';
export const dynamic='force-dynamic';
export async function generateMetadata() { return translatedMetadata({title:'Customer Success · Cuenta Faro',robots:{index:false,follow:false}}); }
export default async function CustomerSuccess({searchParams}:{searchParams:Promise<{result?:string}>}){
 if(!workspaceEnabled())notFound();const session=await workspaceUser();if(!session)redirect('/login');
 if(!hasCustomerSuccessCourse(session.profile))return <LocalizedContent><main className="wrap"><h1>Customer Success</h1><p>Este curso práctico está incluido en Pro y Enterprise, con examen y certificado sin cargo adicional al aprobar.</p><Link className="btn" href="/pricing">Ver planes</Link></main></LocalizedContent>;
 const [{data:units,error:unitError},{data:attempts,error:examError},{data:projects,error:projectError},{data:certificate,error:certError}]=await Promise.all([
 session.supabase.from('cs_course_units').select('unit_index,draft,choice').eq('user_id',session.user.id).order('unit_index'),
 session.supabase.from('cs_course_attempts').select('score,passed,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(10),
 session.supabase.from('cs_course_projects').select('id,status,feedback,score,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(10),
 session.supabase.from('certificates').select('id,title').eq('user_id',session.user.id).eq('certificate_type','customer-success-v1').maybeSingle(),
 ]);
 if(unitError||examError||projectError||certError)throw Error('COURSE_UNAVAILABLE');
 const publication=certificate?(await session.supabase.from('certificate_publications').select('public_id,status').eq('certificate_id',certificate.id).eq('user_id',session.user.id).maybeSingle()).data:null;
 const result=(await searchParams).result;const completed=units?.length??0;
 return <LocalizedContent><main className="wrap"><span className="pill">CURSO PRÁCTICO · INCLUIDO EN PRO Y ENTERPRISE</span><h1>Customer Success: de handoff a renovación</h1><p>Ocho unidades sobre una cuenta ficticia. Lee la explicación, toma una decisión y entrega un borrador. El examen y el proyecto final comprueban aprendizajes distintos.</p>
 <p>Examen incluido dentro de tu cuota mensual; proyecto incluido dentro de tu cuota de entregas. Certificado sin pago adicional al aprobar ambos y completar las ocho unidades.</p>
 {result&&<p role="status" className="card">{({saved:'Actividad guardada.',passed:'Examen aprobado.',failed:'Examen no aprobado. Repasa las unidades antes de volver a intentarlo.',submitted:'Proyecto enviado para revisión humana.',limit:'Alcanzaste la cuota mensual. Puedes esperar al siguiente periodo o cambiar de plan.'} as Record<string,string>)[result]??'Revisa el estado de tu curso.'}</p>}
 <p>{completed} de 8 unidades entregadas</p><progress max={8} value={completed} aria-label="Unidades entregadas"/>
 <section className="card"><h2>Dataset ficticio</h2><table><caption>Cuenta Faro: meta de preparación de reporte, 2 días</caption><thead><tr><th>Semana</th><th>Usuarios activos</th><th>Reportes</th><th>Días de preparación</th></tr></thead><tbody>{CS_COURSE_DATA.map(x=><tr key={x.week}><td>{x.week}</td><td>{x.activeUsers}</td><td>{x.reportsDelivered}</td><td>{x.preparationDays}</td></tr>)}</tbody></table></section>
 {CS_COURSE_UNITS.map((unit,i)=>{const saved=units?.find(x=>x.unit_index===i);return <section className="card" key={unit.key} style={{marginTop:20}}><h2>{unit.title}</h2><p><b>Objetivo:</b> {unit.goal}</p><p>{CS_LESSONS[i]}</p><h3>Aplica lo aprendido</h3><p>{unit.context}</p><p>{unit.task}</p><form action="/api/customer-success" method="post"><input type="hidden" name="action" value="unit"/><input type="hidden" name="unit" value={i}/><fieldset><legend>Decisión del caso</legend>{unit.choices.map((choice,n)=><label key={choice.key} style={{display:'block'}}><input type="radio" name="choice" value={n} defaultChecked={saved?.choice===n} required/>{choice.label}</label>)}</fieldset><label htmlFor={'draft-'+i}>Borrador del entregable, solo datos ficticios</label><textarea id={'draft-'+i} name="draft" minLength={80} maxLength={4000} rows={7} placeholder={unit.template} defaultValue={saved?.draft??''} required/><p className="muted">Guardado privado. Entregar una unidad no acredita dominio por sí solo.</p><button className="btn">Guardar actividad</button></form>{saved&&<p><b>Feedback de tu decisión:</b> {unit.choices[saved.choice]?.feedback}</p>}<details><summary>Ejemplo y criterios para revisar tu borrador</summary><p style={{whiteSpace:'pre-wrap'}}>{unit.example}</p><ul>{unit.review.map(x=><li key={x}>{x}</li>)}</ul></details></section>})}
 <section className="card" style={{marginTop:20}}><h2>Examen final</h2><p>Ocho preguntas; aprobación con 75%. Cada envío válido consume un intento de la cuota de exámenes de tu plan. Reenviar la misma solicitud no consume otro.</p>{completed===8?<AssessmentProtection><form action="/api/customer-success" method="post"><input type="hidden" name="action" value="exam"/><input type="hidden" name="request_id" value={randomUUID()}/>{CS_EXAM.map((q,i)=><fieldset key={i}><legend>{q.prompt}</legend>{q.options.map((option,j)=><label key={option} style={{display:'block'}}><input type="radio" name={'q_'+i} value={j} required/>{option}</label>)}</fieldset>)}<button className="btn">Enviar examen incluido</button></form></AssessmentProtection>:<p>Entrega las ocho actividades para habilitar el examen.</p>}<ul>{attempts?.map((a,i)=><li key={i}>{a.passed?'Aprobado':'Pendiente de aprobar'} · {a.score}% · <LocalizedDate value={a.created_at} /></li>)}</ul></section>
 <section className="card" style={{marginTop:20}}><h2>Proyecto final: plan de continuidad de Cuenta Faro</h2><p>Integra las ocho actividades en un documento: alcance, plan de éxito, onboarding, adopción, riesgo, resultados, renovación y voz del cliente. Incluye fórmulas del dataset, responsables y decisiones pendientes. Usa solo datos ficticios.</p><ul>{CS_CAPSTONE_RUBRIC.map(x=><li key={x}>{x}</li>)}</ul><p>La revisión humana exige 70/100 y evidencia para cada criterio; no hay aprobación automática.</p>{completed===8&&<form action="/api/customer-success" method="post"><input type="hidden" name="action" value="project"/><input type="hidden" name="request_id" value={randomUUID()}/><label htmlFor="cs-project">Entregable final</label><textarea id="cs-project" name="draft" rows={12} minLength={300} maxLength={16000} required/><button className="btn">Enviar proyecto incluido</button></form>}<ul>{projects?.map(p=><li key={p.id}>{({submitted:'En revisión',needs_revision:'Requiere cambios',approved:'Aprobado'} as Record<string,string>)[p.status]}{p.score!=null?' · '+p.score+'/100':''}{p.feedback&&<p><span translate="no">{p.feedback}</span></p>}</li>)}</ul></section>
 {certificate&&<section className="card"><h2>{certificate.title}</h2><p>Certificado incluido, emitido por Garciloga al cumplir los requisitos. Es una constancia de formación; no acredita un título oficial ni garantiza empleo.</p><CertificateSharing certificateId={certificate.id} initialPath={publication?.status==='verified'?'/verify/'+publication.public_id:null} displayName={session.profile.full_name||'Estudiante Garciloga'}/></section>}
 <Link className="btn secondary" href="/dashboard">Volver a Mi Garciloga</Link></main></LocalizedContent>;
}

